---
title: "check type"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = '/workspace')
```


```{r message=FALSE}

library("data.table")
library("dplyr")
library("tidyverse")

```

```{r }
df = read.csv(here::here("output","measures","input_ab_type_OS_2021_2021-01-01.csv.gz"))
#df=read.csv("/Users/yayang/Documents/GitHub/amr-uom-brit/output/measures/input_ab_type_OS_2021_2021-01-01.csv.gz")


names(df)
```

# row number
```{r}
nrow(df)
```

# patient number
```{r}
length(unique(as.factor(df$patient_id)))
```

# ab date ==""

```{r }
for (i in 6:17){
print(sum(df[,i]==""))
}


table(as.Date(df[,6],origin="1960-01-01"))
table(as.Date(df[,17],origin="1960-01-01"))

sum(df[,6]==""&df[,7]!="")

```

# is.na (ab date)
```{r}
for (i in 6:17){
print(sum(is.na(df[,i])))}


```

# AB_date_indication ==""
```{r }

for (i in 18:29){
print(sum(df[,i]==""))
}


table(df[,18])
table(df[,29])
```

# is.na (AB_date_indication)
```{r }
for (i in  18:29){
print(sum(is.na(df[,i])))}


```


# AB_date_type=="
```{r }
for (i in 30:41){
print(sum(df[,i]==""))
}


table(df[,30])
table(df[,41])
```

# is.na (AB_date_type)
```{r }
for (i in  30:41){
print(sum(is.na(df[,i])))}


```

