

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = '/workspace')
```


```{r}
library("data.table")
library("dplyr")
library("tidyverse")
df = read.csv(here::here("output","measures","input_infection_type_test_2021_2021-01-01.csv.gz"))
df$Infect_1_date[df$Infect_1_date == ""] <- NA
df$Infect_1[df$Infect_1 == ""] <- NA
df$Infect_2_date[df$Infect_2_date == ""] <- NA
df$Infect_2[df$Infect_2 == ""] <- NA
df$Infect_3_date[df$Infect_3_date == ""] <- NA
df$Infect_3[df$Infect_3 == ""] <- NA
df$Infect_4_date[df$Infect_4_date == ""] <- NA
df$Infect_4[df$Infect_4 == ""] <- NA
```

### infection patient number
```{r}
length(df$patient_id)
```
### date 1 infection
```{r}
sum(!is.na(df$Infect_1_date))
```

### date 2 infection
```{r}
sum(!is.na(df$Infect_2_date))
```

### date 3 infection
```{r}
sum(!is.na(df$Infect_3_date))
```

### date 4 infection
```{r}
sum(!is.na(df$Infect_4_date))
```

```{r}
ab_date_12=paste0("Infect_",rep(1:4),"_date")
infection_type=paste0("Infect_",rep(1:4))

df1=df%>%select(patient_id,age,sex,all_of(ab_date_12))
colnames(df1)[4:7]=paste0("time",rep(1:4))
df1.1=df1%>%gather(times,date,paste0("time",rep(1:4)))
rm(df1)

df2=df%>%select(patient_id,age,sex,all_of(infection_type))
colnames(df2)[4:7]=paste0("time",rep(1:4))
df2.1=df2%>%gather(times,type,paste0("time",rep(1:4)))
rm(df2)

DF=merge(df1.1,df2.1,by=c("patient_id","age","sex","times"))
DF=DF%>%select(patient_id,date,type)
```

```{r}
df = read.csv(here::here("output","measures","input_ab_type_OS_2021_keep_2021-01-01.csv.gz"))
ab_date_12=paste0("AB_",rep(1:4),"_date")
ab_type=paste0("AB_",rep(1:4))

df1=df%>%select(patient_id,age,sex,all_of(ab_date_12))
colnames(df1)[4:7]=paste0("time",rep(1:4))
df1.1=df1%>%gather(times,date,paste0("time",rep(1:4)))
rm(df1)

df2=df%>%select(patient_id,age,sex,all_of(ab_type))
colnames(df2)[4:7]=paste0("time",rep(1:4))
df2.1=df2%>%gather(times,ab_type,paste0("time",rep(1:4)))
rm(df2)
DF2=merge(df1.1,df2.1,by=c("patient_id","age","sex","times"))


```

```{r}
DF_all <- left_join(DF2,DF,by=c("patient_id","date"))
```

```{r}
DF_all$date[df$date == ""] <- NA
DF_all=DF_all%>%filter(!is.na(date))
```

### same day infection
```{r}
sum(!is.na(DF_all$type))
```

### record number
```{r}
length(DF_all$date)
```


```{r}
head(DF_all,20)
```