---
title: "2021_overall_check"
author: "Billy"
date: "31/08/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = '/workspace')
```


```{r}
library("data.table")
library("dplyr")
library("tidyverse")
library("finalfit")
```


```{r}
setwd(here::here("output", "measures"))
# file list
csvFiles = list.files(pattern="input_ab_type_2021_new_extraction", full.names = FALSE)

# variables
ab_date_12=paste0("AB_",rep(1:12),"_date")
ab_type=paste0("AB_",rep(1:12))


temp <- vector("list", length(csvFiles))
for (i in seq_along(csvFiles)){
  # read in one-month data
  df <- read_csv((csvFiles[i]),
                 col_types = cols_only(
                   AB_1_date = col_date(format = ""),
                   AB_2_date = col_date(format = ""),
                   AB_3_date = col_date(format = ""),
                   AB_4_date = col_date(format = ""),
                   AB_5_date = col_date(format = ""),
                   AB_6_date = col_date(format = ""),
                   AB_7_date = col_date(format = ""),
                   AB_8_date = col_date(format = ""),
                   AB_9_date = col_date(format = ""),
                   AB_10_date = col_date(format = ""),
                   AB_11_date = col_date(format = ""),
                   AB_12_date = col_date(format = ""),
                   age = col_integer(),
                   sex = col_character(),
                   practice = col_integer(),
                   AB_1 = col_character(),
                   AB_2 = col_character(),
                   AB_3 = col_character(),
                   AB_4 = col_character(),
                   AB_5 = col_character(),
                   AB_6 = col_character(),
                   AB_7 = col_character(),
                   AB_8 = col_character(),
                   AB_9 = col_character(),
                   AB_10 = col_character(),
                   AB_11 = col_character(),
                   AB_12 = col_character(),
                   patient_id = col_integer()
                 ),
                 na = character())

  df1=df%>%select(patient_id,age,sex,all_of(ab_date_12))
  colnames(df1)[4:15]=paste0("time",rep(1:12))
  df1.1=df1%>%gather(times,date,paste0("time",rep(1:12)))
  rm(df1)
  
  df2=df%>%select(patient_id,age,sex,all_of(ab_type))
  colnames(df2)[4:15]=paste0("time",rep(1:12))
  df2.1=df2%>%gather(times,ab_type,paste0("time",rep(1:12)))
  rm(df2)
  DF=merge(df1.1,df2.1,by=c("patient_id","age","sex","times"))
  
  DF$date[DF$date == ""] <- NA
  DF=DF%>%filter(!is.na(date))
  
  temp[[i]] <- DF
  rm(DF,df1,df2,df1.1,df2.1)
  
}
DF_type <- bind_rows(temp)
```


## 2021 ab prescription count
```{r}
length(DF_type$patient_id)
```


```{r}
# file list
csvFiles = list.files(pattern="input_ab_infection_2021_new_extraction", full.names = FALSE)

# variables
ab_date_12=paste0("Infect_",rep(1:8),"_date")
infection_type=paste0("Infect_",rep(1:8))


temp <- vector("list", length(csvFiles))
for (i in seq_along(csvFiles)){
  # read in one-month data
  df <- read_csv((csvFiles[i]),
                 col_types = cols_only(
                   Infect_1_date = col_date(format = ""),
                   Infect_2_date = col_date(format = ""),
                   Infect_3_date = col_date(format = ""),
                   Infect_4_date = col_date(format = ""),
                   Infect_5_date = col_date(format = ""),
                   Infect_6_date = col_date(format = ""),
                   Infect_7_date = col_date(format = ""),
                   Infect_8_date = col_date(format = ""),
                   age = col_integer(),
                   sex = col_character(),
                   practice = col_integer(),
                   Infect_1 = col_character(),
                   Infect_2 = col_character(),
                   Infect_3 = col_character(),
                   Infect_4 = col_character(),
                   Infect_5 = col_character(),
                   Infect_6 = col_character(),
                   Infect_7 = col_character(),
                   Infect_8 = col_character(),
                   patient_id = col_integer()
                 ),
                 na = character())

  df1=df%>%select(patient_id,age,sex,all_of(ab_date_12))
  colnames(df1)[4:11]=paste0("time",rep(1:8))
  df1.1=df1%>%gather(times,date,paste0("time",rep(1:8)))
  rm(df1)
  
  df2=df%>%select(patient_id,age,sex,all_of(infection_type))
  colnames(df2)[4:11]=paste0("time",rep(1:8))
  df2.1=df2%>%gather(times,type,paste0("time",rep(1:8)))
  rm(df2)
  
  DF=merge(df1.1,df2.1,by=c("patient_id","age","sex","times"))
  DF=DF%>%select(patient_id,times,date,type)
  
  DF$date[DF$date == ""] <- NA
  DF=DF%>%filter(!is.na(date))
  
  temp[[i]] <- DF
  rm(DF,df1,df2,df1.1,df2.1)
  
}


DF_infect <- bind_rows(temp)

dttable <- select(DF_infect,times,type)

colsfortab <- colnames(dttable)
dttable %>% summary_factorlist(explanatory = colsfortab)

```

```{r}
DF_infect <- select(DF_infect,patient_id,date,type)
DF_all <- left_join(DF_type,DF_infect,by=c("patient_id","date"))
dttable <- select(DF_all,ab_type,type)

colsfortab <- colnames(dttable)
dttable %>% summary_factorlist(explanatory = colsfortab)
```


