version: '3.0'

expectations:
  population_size: 10000

actions:

  # generate_study_population:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2021-08-01 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/measures/input_*.csv.gz

  generate_study_population_hospitalisation:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation --index-date-range "2019-01-01 to today by month" --skip-existing --output-dir=output/hospitalisation_data --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_*.csv.gz

  # generate_study_population_elderly:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition_elderly 
  #     --output-format=csv.gz
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input_elderly.csv.gz

  # generate_measures:
  #   run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
  #   needs: [generate_study_population]
  #   outputs:
  #     moderately_sensitive:
  #       measure_csv: output/measures/measure_*.csv
        
  # describe_elderly_agedis:
  #   run: r:latest analysis/tables/gen_csv_age_check.R
  #   needs: [generate_study_population_elderly]
  #   outputs:
  #     moderately_sensitive:
  #       agetable: output/age_quant.csv

  # describe:
  #   run: r:latest analysis/plot/overall_ab_prescribing.R
  #   needs: [generate_measures]
  #   outputs:
  #     moderately_sensitive:
  #       cohort: output/overall.png
  #       boxplot: output/overallbox.png

  # describe_percentile:
  #   run: r:latest analysis/plot/overall_ab_prescribing_2575percentile.R
  #   needs: [generate_measures]
  #   outputs:
  #     moderately_sensitive:
  #       percentile: output/overall_25th_75th_percentile.png

  # describe_starpu:
  #   run: r:latest analysis/plot/starpu_ab_prescribing.R
  #   needs: [generate_measures]
  #   outputs:
  #     moderately_sensitive:
  #       cohort: output/starpuline.png
  #       boxplot: output/starpubox.png
  
  #generate_notebook_starpu:
  #  run: jupyter:latest jupyter nbconvert /workspace/analysis/starpu.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_risk --ExecutePreprocessor.timeout=86400
  #  needs: [generate_measures]
  #  outputs:
  #    moderately_sensitive:
  #      notebook: output/hospitalisation_risk/starpu.html 
  #      figures: output/hospitalisation_risk/*
        #tables: output/tables/*
        #csvs: output/*/* # two possible subfolders
        #text: output/text/*

  # generate_notebook_hospitalisation_analysis:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_analysis.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_risk --ExecutePreprocessor.timeout=86400
  #   needs: [generate_study_population_hospitalisation]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/hospitalisation_risk/hospitalisation_analysis.html 
  #       figures: output/hospitalisation_risk/*

  generate_notebook_hospitalisation_prediction_uti:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_uti.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_uti --ExecutePreprocessor.timeout=86400
    needs: [generate_study_population_hospitalisation]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_uti/hospitalisation_prediction_uti.html 
        figures: output/hospitalisation_prediction_uti/*
  
  # generate_notebook_hospitalisation_prediction:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction --ExecutePreprocessor.timeout=86400
  #   needs: [generate_study_population_hospitalisation]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/hospitalisation_prediction/hospitalisation_prediction.html 
  #       figures: output/hospitalisation_prediction/*

  # describe_infection_ab_UTI:
  #   run: r:latest analysis/plot/infection_ab_UTI.R
  #   needs: [generate_study_population, generate_measures]
  #   outputs:
  #      moderately_sensitive:
  #       plot: output/UTI.png
    
