version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to today by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

  generate_study_population_elderly:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_elderly 
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_elderly.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv
        
  describe_elderly_agedis:
    run: r:latest analysis/tables/gen_csv_age_check.R
    needs: [generate_study_population_elderly]
    outputs:
      moderately_sensitive:
        agetable: output/age_quant.csv

  describe:
    run: r:latest analysis/plot/overall_ab_prescribing.R
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        cohort: output/overall.png
        boxplot: output/overallbox.png

  describe_percentile:
    run: r:latest analysis/plot/overall_ab_prescribing_2575percentile.R
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        percentile: output/overall_25th_75th_percentile.png

  describe_starpu:
    run: r:latest analysis/plot/starpu_ab_prescribing.R
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        cohort: output/starpuline.png
        boxplot: output/starpubox.png
  
  generate_notebook_starpu:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/starpu.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        notebook: output/starpu.html 
        figures: output/*
        #tables: output/tables/*
        #csvs: output/*/* # two possible subfolders
        #text: output/text/*
  
  describe_infection_ab_UTI:
    run: r:latest analysis/plot/infection_ab_UTI.R
    needs: [generate_study_population, generate_measures]
    outputs:
       moderately_sensitive:
        plot: output/UTI.png
    
  describe_prior_ab_12mb4:
    run: r:latest analysis/plot/ab_1yb4_stackedbar_2.R
    needs: [generate_study_population]
    outputs:
       moderately_sensitive:
        plot: output/AB_1yb4_line.jpeg
        plot_sex: output/AB_1yb4_SEX.jpeg
        count_table: output/prior_ab_by_month.csv