version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to today by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz


  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv
        

  describe:
    run: r:latest analysis/plot/overall_ab_prescribing.R
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        cohort: output/overall.png
        boxplot: output/overallbox.png

  describe_percentile:
    run: r:latest analysis/plot/overall_ab_prescribing_2575percentile.R
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        percentile: output/overall_25th_75th_percentile.png

  describe_starpu:
    run: r:latest analysis/plot/starpu_ab_prescribing.R
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        cohort: output/starpuline.png
        boxplot: output/starpubox.png

  #describe_infection_event:
  #  run: r:latest analysis/plot/infection_event_2575percentile.R
  #  needs: [generate_measures]
  #  outputs:
  #     moderately_sensitive:
  #      percentile1: output/uti_event_25th_75th_percentile.png
  #      percentile2: output/lrti_event_25th_75th_percentile.png


  #describe_infection_ab:
  #  run: r:latest analysis/plot/infection_ab_boxplot.R
  #  needs: [generate_study_population]
  #  outputs:
  #     moderately_sensitive:
  #      boxplot1: output/uti_prescribing_rate_box.png
  #      boxplot2: output/lrti_prescribing_rate_box.png

  describe_infection_ab_UTI:
    run: r:latest analysis/plot/infection_ab_UTI.R
    needs: [generate_study_population, generate_measures]
    outputs:
       moderately_sensitive:
        plot: output/UTI.png
    

