version: '3.0'

expectations:
  population_size: 30000

actions:

### study cohort ###
  generate_study_population_case:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case
    outputs:
      highly_sensitive:
        cohort: output/input_case.csv

  generate_study_population_control:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control
    outputs:
      highly_sensitive:
        cohort: output/input_control.csv

  generate_study_population_sepsis_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_sepsis_2019
    outputs:
      highly_sensitive:
        cohort: output/input_sepsis_2019.csv

  generate_study_population_sepsis_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_sepsis_2020
    outputs:
      highly_sensitive:
        cohort: output/input_sepsis_2020.csv

  generate_study_population_sepsis_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_sepsis_2021
    outputs:
      highly_sensitive:
        cohort: output/input_sepsis_2021.csv

  generate_study_population_sepsis_2022:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_sepsis_2022
    outputs:
      highly_sensitive:
        cohort: output/input_sepsis_2022.csv
### extract patient_id & index_date in case ###

  process_1:  
    run: r:latest analysis/process_1.R
    needs: [generate_study_population_case,generate_study_population_control]
    outputs:
      moderately_sensitive:
        table1: output/table_case_0.csv
        table2: output/table_case_1.csv
        table3: output/table_control_0.csv
        table4: output/table_control_1.csv
      highly_sensitive: 
        case_csv: output/case_csv.csv
        match_csv: output/match_csv.csv


  matching_1:
    run: python:latest python analysis/matching.py
    needs: [process_1]
    outputs:
      highly_sensitive: 
        table1: output/matched_cases.csv
        table2: output/matched_matches.csv
        table3: output/matched_combined.csv
      moderately_sensitive: 
        report1: output/matching_report.txt

  process_sepsis_2019:  
    run: r:latest analysis/process_sepsis_2019.R
    needs: [generate_study_population_sepsis_2019]
    outputs:
      moderately_sensitive:
        table1: output/table_sepsis_2019_0.csv
        table2: output/table_sepsis_2019_1.csv

  process_sepsis_2020:  
    run: r:latest analysis/process_sepsis_2020.R
    needs: [generate_study_population_sepsis_2020]
    outputs:
      moderately_sensitive:
        table1: output/table_sepsis_2020_0.csv
        table2: output/table_sepsis_2020_1.csv

  process_sepsis_2021:  
    run: r:latest analysis/process_sepsis_2021.R
    needs: [generate_study_population_sepsis_2021]
    outputs:
      moderately_sensitive:
        table1: output/table_sepsis_2021_0.csv
        table2: output/table_sepsis_2021_1.csv

  process_sepsis_2022:  
    run: r:latest analysis/process_sepsis_2022.R
    needs: [generate_study_population_sepsis_2022]
    outputs:
      moderately_sensitive:
        table1: output/table_sepsis_2022_0.csv
        table2: output/table_sepsis_2022_1.csv