version: '3.0'

expectations:
  population_size: 1000

actions:

# general population

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to today by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz 

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

# # AB prescribing rate 

  describe_percentile:
    run: r:latest analysis/plot/overall_ab_prescribing_2575percentile.R
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        percentile: output/overall_25th_75th_percentile.jpeg
        table_total: output/total_number_antibacterial_prescriptions.csv

  describe_percentile_starpu:
    run: r:latest analysis/plot/starpu_ab_percentile.R
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        percentile_STARPU: output/overall_25th_75th_percentile_STARPU.jpeg
        percentile_csv_STARPU: output/monthly_quantile_ab_STARPU.csv
  
# merge monthly datasets and split by years
  describe_basic_record_process:
    run: r:latest analysis/process/baseline_variables_transform.R
    needs: [generate_study_population]
    outputs:
       highly_sensitive:
        rds1: output/measures/basic_record_2019.rds
        rds2: output/measures/basic_record_2020.rds
        rds3: output/measures/basic_record_2021.rds
        rds4: output/measures/basic_record_2022.rds


# baseline table

  describe_baseline_table_split_2019:
    run: r:latest analysis/tables/baseline_table_2019.R
    needs: [describe_basic_record_process]
    outputs:
      moderately_sensitive:
        baseline_overall_2019: output/overall_counts_blt_2019.csv
        baseline_table_2019: output/blt_one_random_obs_perpat_2019.csv
      highly_sensitive:
        cohort: output/measures/id_2019.csv

  describe_baseline_table_split_2020:
    run: r:latest analysis/tables/baseline_table_2020.R
    needs: [describe_basic_record_process]
    outputs:
      moderately_sensitive:
        baseline_overall_2020: output/overall_counts_blt_2020.csv
        baseline_table_2020: output/blt_one_random_obs_perpat_2020.csv
      highly_sensitive:
        cohort: output/measures/id_2020.csv
  
  describe_baseline_table_split_2021:
    run: r:latest analysis/tables/baseline_table_2021.R
    needs: [describe_basic_record_process]
    outputs:
      moderately_sensitive:
        baseline_overall_2021: output/overall_counts_blt_2021.csv
        baseline_table_2021: output/blt_one_random_obs_perpat_2021.csv
      highly_sensitive:
        cohort: output/measures/id_2021.csv
  
  describe_baseline_table_split_2022:
    run: r:latest analysis/tables/baseline_table_2022.R
    needs: [describe_basic_record_process]
    outputs:
      moderately_sensitive:
        baseline_overall_2022: output/overall_counts_blt_2022.csv
        baseline_table_2022: output/blt_one_random_obs_perpat_2022.csv
      highly_sensitive:
        cohort: output/measures/id_2022.csv

#  additional: baseline table - covid infetion patients

  generate_study_population_covidnum_2020:
      run: cohortextractor:latest generate_cohort 
        --with-end-date-fix
        --study-definition study_definition_covidnum_2020
        --output-format=csv.gz
      outputs:
        highly_sensitive:
          cohort: output/input_covidnum_2020.csv.gz

  generate_study_population_covidnum_2021:
      run: cohortextractor:latest generate_cohort 
        --with-end-date-fix
        --study-definition study_definition_covidnum_2021
        --output-format=csv.gz
      outputs:
        highly_sensitive:
          cohort: output/input_covidnum_2021.csv.gz

  generate_study_population_covidnum_2022:
      run: cohortextractor:latest generate_cohort 
        --with-end-date-fix
        --study-definition study_definition_covidnum_2022
        --output-format=csv.gz
      outputs:
        highly_sensitive:
          cohort: output/input_covidnum_2022.csv.gz

  describe_covid_count: 
    run: r:latest analysis/tables/covidcount.R
    needs: [generate_study_population_covidnum_2020,generate_study_population_covidnum_2021,generate_study_population_covidnum_2022]
    outputs:
      moderately_sensitive:
        table1: output/covid_count.csv

  describe_covid_count_patone: 
    run: r:latest analysis/tables/covidcount_patone.R
    needs: [generate_study_population_samedayab]
    outputs:
      moderately_sensitive:
        table1: output/covid_count_patone.csv
  

  #  additional: baseline table - covid vaccination %

  extract_covrx_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covrx_2019
    needs: [describe_baseline_table_split_2019]
    outputs:
      highly_sensitive:
        cohort: output/measures/input_covrx_2019.csv 
  
  describe_covrx_2019:
    run: r:latest analysis/tables/covrx_2019.R
    needs: [extract_covrx_2019]
    outputs:
      moderately_sensitive:
        number: output/covrx_2019.txt
  
  extract_covrx_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covrx_2020
    needs: [describe_baseline_table_split_2020]
    outputs:
      highly_sensitive:
        cohort: output/measures/input_covrx_2020.csv 

  describe_covrx_2020:
    run: r:latest analysis/tables/covrx_2020.R
    needs: [extract_covrx_2020]
    outputs:
      moderately_sensitive:
        number: output/covrx_2020.txt
  
  extract_covrx_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covrx_2021
    needs: [describe_baseline_table_split_2021]
    outputs:
      highly_sensitive:
        cohort: output/measures/input_covrx_2021.csv 
  
  describe_covrx_2021:
    run: r:latest analysis/tables/covrx_2021.R
    needs: [extract_covrx_2021]
    outputs:
      moderately_sensitive:
        number: output/covrx_2021.txt
  
  extract_covrx_2022:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covrx_2022
    needs: [describe_baseline_table_split_2022]
    outputs:
      highly_sensitive:
        cohort: output/measures/input_covrx_2022.csv 
  
  describe_covrx_2022:
    run: r:latest analysis/tables/covrx_2022.R
    needs: [extract_covrx_2022]
    outputs:
      moderately_sensitive:
        number: output/covrx_2022.txt



#  12 extractions for antibiotics /per month

  generate_study_population_ab: #  Antibiotics_recorded_01
    run: cohortextractor:latest generate_cohort  --with-end-date-fix --study-definition study_definition_ab --index-date-range "2019-01-01 to today" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_ab_*.csv.gz
  
  describe_ab_recoded_indication_process: #  Antibiotics_recorded_02: generate prescription-level dataset 
    run: r:latest analysis/process/ab_recorded_indication_transform.R
    needs: [generate_study_population_ab]
    outputs:
       highly_sensitive:
        rds1: output/measures/recorded_ab_2019.rds
        rds2: output/measures/recorded_ab_2020.rds
        rds3: output/measures/recorded_ab_2021.rds
        rds4: output/measures/recorded_ab_2022.rds
        
  describe_ab_recoded_indication_plot_incident: #  Antibiotics_recorded_03
    run: r:latest analysis/plot/ab_recorded_indication_plot_incident.R
    needs: [describe_ab_recoded_indication_process] # transfrom & define all variables
    outputs:
       moderately_sensitive:
        plot1: output/ab_recorded_incident_bar.jpeg
        plot2: output/ab_recorded_incident_line.jpeg
        plot3: output/ab_recorded_incident_bar_2.jpeg
        csv: output/ab_recorded_incident.csv

  describe_ab_recoded_indication_plot_prevalent: #  Antibiotics_recorded_03
    run: r:latest analysis/plot/ab_recorded_indication_plot_prevalent.R
    needs: [describe_ab_recoded_indication_process]
    outputs:
       moderately_sensitive:
        plot1: output/ab_recorded_prevalent_bar.jpeg
        plot2: output/ab_recorded_prevalent_line.jpeg
        plot3: output/ab_recorded_prevalent_bar_2.jpeg
        csv: output/ab_recorded_prevalent.csv

  ab_recoded_indication_ITS2_plot: # overall, incident, prevalent
    run: r:latest -e 'rmarkdown::render("analysis/model/ab_recoded_indication_ITS2_plot.rmd", output_dir = "output/report")'
    needs: [describe_ab_recoded_indication_plot_prevalent,describe_ab_recoded_indication_plot_incident]
    outputs:
      moderately_sensitive:
        html: output/report/ab_recoded_indication_ITS2_plot.html



#  4 extractions for infection consultations /per month  (with same-day AB prescribing)
  generate_study_population_infection_abtype: # for ab types plot
    run: cohortextractor:latest generate_cohort --with-end-date-fix --study-definition study_definition_infection_abtype --index-date-range "2019-01-01 to today by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_infection_abtype_*.csv.gz
  
  describe_infection_abtype_process: #  infection/row
    run: r:latest analysis/process/infection_abtype_transform.R
    needs: [generate_study_population_infection_abtype]
    outputs:
       highly_sensitive:
        rds1: output/measures/abtype_uti.rds
        rds2: output/measures/abtype_lrti.rds
        rds3: output/measures/abtype_urti.rds
        rds4: output/measures/abtype_sinusitis.rds
        rds5: output/measures/abtype_ot_externa.rds
        rds6: output/measures/abtype_otmedia.rds

  describe_infection_noAB_plot: #  percentage
    run: r:latest analysis/redaction/infection_v2_noAB.R
    needs: [describe_infection_abtype_process]
    outputs:
       moderately_sensitive:
        plot1: output/redacted_v2/noAB_uti.jpeg
        plot2: output/redacted_v2/noAB_lrti.jpeg
        plot3: output/redacted_v2/noAB_urti.jpeg
        plot4: output/redacted_v2/noAB_sinusitis.jpeg
        plot5: output/redacted_v2/noAB_ot_externa.jpeg
        plot6: output/redacted_v2/noAB_otmedia.jpeg
        csv1: output/redacted_v2/noAB_uti_check.csv
        csv2: output/redacted_v2/noAB_lrti_check.csv
        csv3: output/redacted_v2/noAB_urti_check.csv
        csv4: output/redacted_v2/noAB_sinusitis_check.csv
        csv5: output/redacted_v2/noAB_ot_externa_check.csv
        csv6: output/redacted_v2/noAB_otmedia_check.csv
        csv7: output/redacted_v2/noAB.csv

  describe_infection_AB_plot: #  percentage
    run: r:latest analysis/redaction/infection_v2_AB.R
    needs: [describe_infection_abtype_process]
    outputs:
       moderately_sensitive:
        plot1: output/redacted_v2/AB_uti.jpeg
        plot2: output/redacted_v2/AB_lrti.jpeg
        plot3: output/redacted_v2/AB_urti.jpeg
        plot4: output/redacted_v2/AB_sinusitis.jpeg
        plot5: output/redacted_v2/AB_ot_externa.jpeg
        plot6: output/redacted_v2/AB_otmedia.jpeg
        csv1: output/redacted_v2/AB_uti_check.csv
        csv2: output/redacted_v2/AB_lrti_check.csv
        csv3: output/redacted_v2/AB_urti_check.csv
        csv4: output/redacted_v2/AB_sinusitis_check.csv
        csv5: output/redacted_v2/AB_ot_externa_check.csv
        csv6: output/redacted_v2/AB_otmedia_check.csv
        csv7: output/redacted_v2/AB.csv

  infection_ab_ITS2_plot: 
    run: r:latest -e 'rmarkdown::render("analysis/model/infection_ab_ITS2_plot.rmd", output_dir = "output/report")'
    needs: [describe_infection_noAB_plot]
    outputs:
      moderately_sensitive:
        html: output/report/infection_ab_ITS2_plot.html

  describe_infection_AB_plot_top5: #  percentage
    run: r:latest analysis/redaction/infection_v2_AB_top5.R
    needs: [describe_infection_abtype_process]
    outputs:
       moderately_sensitive:
        csv1: output/redacted_v2/AB_uti_check_top5.csv
        csv2: output/redacted_v2/AB_lrti_check_top5.csv
        csv3: output/redacted_v2/AB_urti_check_top5.csv
        csv4: output/redacted_v2/AB_sinusitis_check_top5.csv
        csv5: output/redacted_v2/AB_ot_externa_check_top5.csv
        csv6: output/redacted_v2/AB_otmedia_check_top5.csv
        csv7: output/redacted_v2/AB_top5.csv
        plot1: output/redacted_v2/prevalent_AB_top5.jpeg # combined 6 infections
        plot2: output/redacted_v2/incident_AB_top5.jpeg

  describe_top5_ab: 
    run: r:latest -e 'rmarkdown::render("analysis/redaction/top5_ab.rmd", output_dir = "output/redacted_v2")'
    needs: [describe_infection_AB_plot_top5]
    outputs:
      moderately_sensitive:
        html: output/redacted_v2/top5_ab.html

  
  
  
  # 4 extractions for infection consultations /per month  (with 14-day AB prescribing)

  generate_study_population_infection_abtype_wk : # for ab types plot
    run: cohortextractor:latest generate_cohort --with-end-date-fix --study-definition study_definition_infection_abtype_wk --index-date-range "2019-01-01 to 2022-07-01 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_infection_abtype_wk_*.csv.gz




# same-day COVID-19 diagnosis with an antibiotic prescription (+/- 2 days)

  generate_study_population_samedayab:
    run: cohortextractor:latest generate_cohort --with-end-date-fix --study-definition study_definition_sameday_ab --index-date-range "2019-01-01 to 2022-06-01" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_sameday_ab_*.csv.gz

  generate_measures_samedayab:
    run: cohortextractor:latest generate_measures --study-definition study_definition_sameday_ab --skip-existing --output-dir=output/measures
    needs: [generate_study_population_samedayab]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_samedayab_*.csv

  describe_same_day_ab:
    run: r:latest analysis/plot/same_day_covid_ab.R
    needs: [generate_measures_samedayab]
    outputs:
       moderately_sensitive:
        plot1: output/same_day_ab_prop_line_sgss.jpeg
        plot2: output/same_day_ab_prop_line_gp.jpeg

