version: '3.0'

expectations:
  population_size: 30000

actions:

  generate_study_population_patient_characteristics_2019:
      run: cohortextractor:latest generate_cohort 
        --with-end-date-fix
        --study-definition study_definition_patient_characteristics_2019
        --output-format=csv.gz
      outputs:
        highly_sensitive:
          cohort: output/input_patient_characteristics_2019.csv.gz

  generate_study_population_patient_characteristics_2020:
      run: cohortextractor:latest generate_cohort 
        --with-end-date-fix
        --study-definition study_definition_patient_characteristics_2020
        --output-format=csv.gz
      outputs:
        highly_sensitive:
          cohort: output/input_patient_characteristics_2020.csv.gz

  generate_study_population_patient_characteristics_2021:
      run: cohortextractor:latest generate_cohort 
        --with-end-date-fix
        --study-definition study_definition_patient_characteristics_2021
        --output-format=csv.gz
      outputs:
        highly_sensitive:
          cohort: output/input_patient_characteristics_2021.csv.gz

  table_1: 
    run: r:latest analysis/table_1.R
    needs: [generate_study_population_patient_characteristics_2019]
    outputs:
       moderately_sensitive:
        table1: output/table1_2019_overallcount.csv
        table2: output/table1_2019.csv

  table_1_2020: 
    run: r:latest analysis/table_1_2020.R
    needs: [generate_study_population_patient_characteristics_2020]
    outputs:
       moderately_sensitive:
        table1: output/table1_2020_overallcount.csv
        table2: output/table1_2020.csv

  table_1_2021: 
    run: r:latest analysis/table_1_2021.R
    needs: [generate_study_population_patient_characteristics_2021]
    outputs:
       moderately_sensitive:
        table1: output/table1_2021_overallcount.csv
        table2: output/table1_2021.csv

  generate_study_population:
    run: cohortextractor:latest generate_cohort
      --with-end-date-fix
      --study-definition study_definition 
      --index-date-range "2019-01-01 to 2021-12-31 by month" 
      --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition 
      --skip-existing 
      --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  generate_study_population_covid:
    run: cohortextractor:latest generate_cohort
      --with-end-date-fix
      --study-definition study_definition_covid 
      --index-date-range "2019-01-01 to 2021-12-31 by month" 
      --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_covid_*.csv.gz

  generate_measures_covid:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition_covid 
      --skip-existing 
      --output-dir=output/measures
    needs: [generate_study_population_covid]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_allpopulation_*.csv

  figure_1A: 
    run: r:latest analysis/figure_1A.R
    needs: [generate_measures]
    outputs:
       moderately_sensitive:
        plot1: output/figure_1A.jpeg

  figure_1B: 
    run: r:latest analysis/figure_1B.R
    needs: [generate_measures,generate_measures_covid]
    outputs:
       moderately_sensitive:
        plot1: output/figure_1B.jpeg
        table1: output/figure_1B_table.csv

  figure_2: 
    run: r:latest analysis/figure_2.R
    needs: [generate_measures]
    outputs:
       moderately_sensitive:
        plot1: output/figure_2.1.jpeg
        plot2: output/figure_2.2.jpeg
        plot3: output/figure_2.3.jpeg
        table1: output/figure_2.1_table.csv

  generate_study_population_weekly:
    run: cohortextractor:latest generate_cohort
      --with-end-date-fix
      --study-definition study_definition_weekly 
      --index-date-range "2019-01-01 to 2021-12-31 by week" 
      --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_weekly_*.csv.gz

  generate_measures_weekly:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition_weekly 
      --skip-existing 
      --output-dir=output/measures
    needs: [generate_study_population_weekly]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_weekly_*.csv

  figure_1A_weekly: 
    run: r:latest analysis/figure_1A_weekly.R
    needs: [generate_measures_weekly]
    outputs:
       moderately_sensitive:
        plot1: output/figure_1A_weekly.jpeg

### generate study cohort with the date of each prescriptions
  generate_study_population_ab_type_2019: 
    run: cohortextractor:latest generate_cohort
      --with-end-date-fix
      --study-definition study_definition_ab_type_2019
      --index-date-range "2019-01-01 to 2019-12-31"
      --skip-existing
      --output-dir=output/measures
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_ab_type_2019_*.csv.gz

  generate_study_population_ab_type_2020: 
    run: cohortextractor:latest generate_cohort 
      --with-end-date-fix
      --study-definition study_definition_ab_type_2020 
      --index-date-range "2020-01-01 to 2020-12-31" 
      --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_ab_type_2020_*.csv.gz

  generate_study_population_ab_type_2021: 
    run: cohortextractor:latest generate_cohort 
      --with-end-date-fix
      --study-definition study_definition_ab_type_2021 
      --index-date-range "2021-01-01 to 2021-12-31" 
      --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_ab_type_2021_*.csv.gz

  conversion_abtype_2019: 
    run: r:latest analysis/conversion_abtype_2019.R
    needs: [generate_study_population_ab_type_2019]
    outputs:
       highly_sensitive:
        rds1: output/measures/abtype_2019.rds

  conversion_abtype_2020: 
    run: r:latest analysis/conversion_abtype_2020.R
    needs: [generate_study_population_ab_type_2020]
    outputs:
       highly_sensitive:
        rds1: output/measures/abtype_2020.rds

  conversion_abtype_2021: 
    run: r:latest analysis/conversion_abtype_2021.R
    needs: [generate_study_population_ab_type_2021]
    outputs:
       highly_sensitive:
        rds1: output/measures/abtype_2021.rds

  figure_2B: 
    run: r:latest analysis/figure_2B.R
    needs: [conversion_abtype_2019,conversion_abtype_2020,conversion_abtype_2021]
    outputs:
       moderately_sensitive:
        plot1: output/figure_2B.jpeg
        table1: output/figure_2B_table.csv

  ITS_var: 
    run: r:latest analysis/ITS_var.R
    needs: [conversion_abtype_2019,conversion_abtype_2020,conversion_abtype_2021,generate_measures]
    outputs:
       moderately_sensitive:
        table1: output/mon_uti.csv
        table2: output/mon_cold.csv
        table3: output/mon_cough.csv
        table4: output/mon_copd.csv
        table5: output/mon_throat.csv
        table6: output/mon_lrti.csv
        table7: output/mon_urti.csv
        table8: output/mon_sinusitis.csv
        table9: output/mon_ot_media.csv
        table10: output/mon_ot_externa.csv
        table11: output/mon_all.csv
        table12: output/mon_all_coded.csv
        table13: output/mon_all_uncoded.csv

  describe_ITS_model_broad_mon_overall:
    run: r:latest analysis/itsmodel/ITS_model_monthly.R
    needs: [ITS_var]
    outputs:
        moderately_sensitive:
          plot1: output/mon_overall_predicted_plot.jpeg
          plot2: output/mon_overall_forest_C.jpeg
          plot3: output/mon_overall_forest_B.jpeg
          plot4: output/mon_overall_combined.jpeg
          table1: output/mon_overall_predicted_table.csv
          table2: output/mon_overall_forest_B_table.csv
          table3: output/mon_overall_forest_C_table.csv

  ITS_var_weekly: 
    run: r:latest analysis/ITS_var_weekly.R
    needs: [conversion_abtype_2019,conversion_abtype_2020,conversion_abtype_2021,generate_measures_weekly]
    outputs:
       moderately_sensitive:
        table1: output/week_uti.csv
        table2: output/week_cold.csv
        table3: output/week_cough.csv
        table4: output/week_copd.csv
        table5: output/week_throat.csv
        table6: output/week_lrti.csv
        table7: output/week_urti.csv
        table8: output/week_sinusitis.csv
        table9: output/week_ot_media.csv
        table10: output/week_ot_externa.csv
        table11: output/week_all.csv

  describe_ITS_model_broad_week_overall:
    run: r:latest analysis/itsmodel/ITS_model_weekly.R
    needs: [ITS_var_weekly]
    outputs:
        moderately_sensitive:
          plot1: output/week_overall_predicted_plot.jpeg
          plot2: output/week_overall_forest_C.jpeg
          plot3: output/week_overall_forest_B.jpeg
          plot4: output/week_overall_combined.jpeg
          table1: output/week_overall_predicted_table.csv
          table2: output/week_overall_forest_B_table.csv
          table3: output/week_overall_forest_C_table.csv

  ITS_overall_uti_plot:
    run: r:latest analysis/itsmodel/ITS_model_predict.R
    needs: [describe_ITS_model_broad_mon_overall]
    outputs:
        moderately_sensitive:
          plot1: output/overall_predicted.jpeg
          plot2: output/UTI_predicted.jpeg

  ITS_model_monthly_rest:
    run: r:latest analysis/itsmodel/ITS_model_monthly_rest.R
    needs: [ITS_var]
    outputs:
        moderately_sensitive:
          plot1: output/mon_overall_predicted_rest.jpeg

  Poisson_model_table:
    run: r:latest analysis/itsmodel/Poisson_model_table.R
    needs: [ITS_var]
    outputs:
        moderately_sensitive:
          plot1: output/table2.csv

  generate_study_population_2020_covid_window:
    run: cohortextractor:latest generate_cohort
      --with-end-date-fix
      --study-definition study_definition_2020_covid_window 
      --index-date-range "2020-01-01 to 2020-12-31 by month" 
      --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_2020_covid_window_*.csv.gz

  generate_measures_2020_covid_window:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition_2020_covid_window 
      --skip-existing 
      --output-dir=output/measures
    needs: [generate_study_population_2020_covid_window]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_covid_window_*.csv

  generate_study_population_2021_covid_window:
    run: cohortextractor:latest generate_cohort
      --with-end-date-fix
      --study-definition study_definition_2021_covid_window 
      --index-date-range "2021-01-01 to 2021-12-31 by month" 
      --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_2021_covid_window_*.csv.gz

  generate_measures_2021_covid_window:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition_2021_covid_window 
      --skip-existing 
      --output-dir=output/measures
    needs: [generate_study_population_2021_covid_window]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_21_covid_window_*.csv

  figure_3: 
    run: r:latest analysis/figure_3.R
    needs: [generate_measures_2020_covid_window,generate_measures_2021_covid_window]
    outputs:
       moderately_sensitive:
        plot1: output/figure_3.jpeg
        table1: output/figure_3_table.csv

  figure_3_bar: 
    run: r:latest analysis/figure_3_bar.R
    needs: [generate_measures_2020_covid_window,generate_measures_2021_covid_window]
    outputs:
       moderately_sensitive:
        plot1: output/figure_3_bar.jpeg
        table1: output/figure_3_bar_table.csv

  figure_3_2D: 
    run: r:latest analysis/figure_3_2D.R
    needs: [generate_measures_2020_covid_window,generate_measures_2021_covid_window]
    outputs:
       moderately_sensitive:
        plot1: output/figure_3_2D.jpeg
        table1: output/figure_3_2D_table.csv

  ab_type_table: 
    run: r:latest analysis/ab_type_table.R
    needs: [generate_measures_2020_covid_window,generate_measures_2021_covid_window]
    outputs:
       moderately_sensitive:
        table1: output/ab_type_table.csv
        table2: output/ab_type_table_2D.csv

  figure_Stype: 
    run: r:latest analysis/figure_Stype.R
    needs: [generate_measures]
    outputs:
       moderately_sensitive:
        plot1: output/figure_Stype.jpeg
        table1: output/figure_Stype_table.csv

  ITS_var_sen_2month: 
    run: r:latest analysis/ITS_var_sen_2month.R
    needs: [conversion_abtype_2019,conversion_abtype_2020,conversion_abtype_2021,generate_measures]
    outputs:
       moderately_sensitive:
        table1: output/sen_2mon_uti.csv
        table2: output/sen_2mon_cold.csv
        table3: output/sen_2mon_cough.csv
        table4: output/sen_2mon_copd.csv
        table5: output/sen_2mon_throat.csv
        table6: output/sen_2mon_lrti.csv
        table7: output/sen_2mon_urti.csv
        table8: output/sen_2mon_sinusitis.csv
        table9: output/sen_2mon_ot_media.csv
        table10: output/sen_2mon_ot_externa.csv
        table11: output/sen_2mon_all.csv
        table12: output/sen_2mon_all_coded.csv
        table13: output/sen_2mon_all_uncoded.csv

  ITS_var_sen_3month: 
    run: r:latest analysis/ITS_var_sen_3month.R
    needs: [conversion_abtype_2019,conversion_abtype_2020,conversion_abtype_2021,generate_measures]
    outputs:
       moderately_sensitive:
        table1: output/sen_3mon_uti.csv
        table2: output/sen_3mon_cold.csv
        table3: output/sen_3mon_cough.csv
        table4: output/sen_3mon_copd.csv
        table5: output/sen_3mon_throat.csv
        table6: output/sen_3mon_lrti.csv
        table7: output/sen_3mon_urti.csv
        table8: output/sen_3mon_sinusitis.csv
        table9: output/sen_3mon_ot_media.csv
        table10: output/sen_3mon_ot_externa.csv
        table11: output/sen_3mon_all.csv
        table12: output/sen_3mon_all_coded.csv
        table13: output/sen_3mon_all_uncoded.csv

  describe_ITS_model_broad_sen2mon:
    run: r:latest analysis/itsmodel/ITS_model_monthly_sen2mon.R
    needs: [ITS_var_sen_2month]
    outputs:
        moderately_sensitive:
          plot1: output/sen_2mon_overall_predicted_plot.jpeg
          plot2: output/sen_2mon_overall_forest_C.jpeg
          plot3: output/sen_2mon_overall_forest_B.jpeg
          plot4: output/sen_2mon_overall_combined.jpeg
          table1: output/sen_2mon_overall_predicted_table.csv
          table2: output/sen_2mon_overall_forest_B_table.csv
          table3: output/sen_2mon_overall_forest_C_table.csv

  describe_ITS_model_broad_sen3mon:
    run: r:latest analysis/itsmodel/ITS_model_monthly_sen3mon.R
    needs: [ITS_var_sen_3month]
    outputs:
        moderately_sensitive:
          plot1: output/sen_3mon_overall_predicted_plot.jpeg
          plot2: output/sen_3mon_overall_forest_C.jpeg
          plot3: output/sen_3mon_overall_forest_B.jpeg
          plot4: output/sen_3mon_overall_combined.jpeg
          table1: output/sen_3mon_overall_predicted_table.csv
          table2: output/sen_3mon_overall_forest_B_table.csv
          table3: output/sen_3mon_overall_forest_C_table.csv

  generate_study_population_2020_coinfection:
    run: cohortextractor:latest generate_cohort
      --with-end-date-fix
      --study-definition study_definition_2020_coinfection 
      --index-date-range "2020-01-01 to 2020-12-31 by month" 
      --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_2020_coinfection_*.csv.gz

  generate_measures_2020_coinfection:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition_2020_coinfection 
      --skip-existing 
      --output-dir=output/measures
    needs: [generate_study_population_2020_coinfection]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_infection_coded_*.csv

  generate_study_population_2021_coinfection:
    run: cohortextractor:latest generate_cohort
      --with-end-date-fix
      --study-definition study_definition_2021_coinfection 
      --index-date-range "2021-01-01 to 2021-12-31 by month" 
      --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_2021_coinfection_*.csv.gz

  generate_measures_2021_coinfection:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition_2021_coinfection 
      --skip-existing 
      --output-dir=output/measures
    needs: [generate_study_population_2021_coinfection]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_21_infection_coded_*.csv