version: '3.0'

expectations:
  population_size: 200000

actions:

  generate_study_population_hospitalisation_urti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_urti --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_urti.csv.gz

  generate_study_population_hospitalisation_lrti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_lrti --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_lrti.csv.gz

  generate_study_population_hospitalisation_uti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_uti --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_uti.csv.gz

  generate_study_population_hospitalisation_sinusitis:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_sinusitis --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_sinusitis.csv.gz

  generate_study_population_hospitalisation_ot_externa:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_ot_externa --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_ot_externa.csv.gz

  generate_study_population_hospitalisation_otmedia:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_otmedia --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_otmedia.csv.gz

  generate_notebook_hospitalisation_prediction_urti:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_urti.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_urti --ExecutePreprocessor.timeout=86400
    # needs: [generate_study_population_hospitalisation_urti,generate_study_population_bmi]
    needs: [generate_study_population_hospitalisation_urti]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_urti/hospitalisation_prediction_urti.html 
        figures: output/hospitalisation_prediction_urti/*

  generate_notebook_hospitalisation_prediction_lrti:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_lrti.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_lrti --ExecutePreprocessor.timeout=86400
    # needs: [generate_study_population_hospitalisation_lrti,generate_study_population_bmi]
    needs: [generate_study_population_hospitalisation_lrti]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_lrti/hospitalisation_prediction_lrti.html 
        figures: output/hospitalisation_prediction_lrti/*

  generate_notebook_hospitalisation_prediction_sinusitis:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_sinusitis.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_sinusitis --ExecutePreprocessor.timeout=86400
    # needs: [generate_study_population_hospitalisation_sinusitis,generate_study_population_bmi]
    needs: [generate_study_population_hospitalisation_sinusitis]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_sinusitis/hospitalisation_prediction_sinusitis.html 
        figures: output/hospitalisation_prediction_sinusitis/*