version: '3.0'

expectations:
  population_size: 1000

actions:
  
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_general_population
    outputs:
      highly_sensitive:
        cohort: output/input_general_population.csv

  generate_study_population_covid_primarycare:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_primarycare
    outputs:
      highly_sensitive:
        cohort: output/input_covid_primarycare.csv
  
  generate_study_population_covid_SGSS:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_SGSS
    outputs:
      highly_sensitive:
        cohort: output/input_covid_SGSS.csv
  
  generate_study_population_covid_admission:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_admission
    outputs:
      highly_sensitive:
        cohort: output/input_covid_admission.csv
  
  # generate_study_population_covid_icu:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_icu
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input_covid_icu.csv

  generate_study_population_covid_death_ons:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_death_ons
    outputs:
      highly_sensitive:
        cohort: output/input_covid_death_ons.csv
  
  generate_study_population_covid_death_cpns:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_death_cpns
    outputs:
      highly_sensitive:
        cohort: output/input_covid_death_cpns.csv
  
  process:
    run: r:latest analysis/process.R
    needs: [generate_study_population_covid_primarycare, generate_study_population_covid_SGSS,generate_study_population_covid_admission,generate_study_population_covid_death_ons,generate_study_population_covid_death_cpns]
    outputs:
      highly_sensitive:
        cohort1.1: output/case_covid_infection.csv
        cohort1.2: output/control_covid_infection.csv 
        cohort1.3: output/case_covid_infection_*.csv # for monthly matching
        cohort2: output/case_covid_admission.csv
        cohort3: output/case_covid_icu_death.csv
        

  matching:
    run: python:latest python analysis/matching_case_control.py
    needs: [generate_study_population, process]
    outputs:
      moderately_sensitive: 
        matching_report1: output/matching_report_general_population_infection.txt
        matching_report2: output/matching_report_infection_hosp.txt
        matching_report3: output/matching_report_hosp_icu_death.txt 
      highly_sensitive: 
        combined1: output/matched_combined_general_population_infection.csv
        combined2: output/matched_combined_infection_hosp.csv
        combined3: output/matched_combined_hosp_icu_death.csv

  extract_control:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control
    needs: [matching]
    outputs:
      highly_sensitive:
        cohort: output/input_control.csv

 

## monthly matching datasets
  generate_study_population_month:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_general_population --index-date-range "2020-02-01 to 2021-12-31 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz
  
  exclusion:
    run: r:latest analysis/exclusion.R
    needs: [process, generate_study_population_month]
    outputs:
       highly_sensitive:
        cohort4: output/control_general_population_*.csv
    
  
        
        