version: '3.0'

expectations:
  population_size: 1000

actions:
  

  generate_study_population_covid_admission:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_admission
    outputs:
      highly_sensitive:
        cohort: output/input_covid_admission.csv

  process_1:  
    run: r:latest analysis/process_1.R
    needs: [generate_study_population_covid_admission]
    outputs:
      highly_sensitive:
        case: output/case_covid_icu_death.csv
       # case2: output/case_covid_icu_death_2.csv
        control: output/control_covid_hosp.csv
      #  control2: output/control_covid_hosp_2.csv

  matching: # matching with replacement # died covid
    run: r:latest -e 'rmarkdown::render("analysis/matching.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_1]
    outputs:
      moderately_sensitive:
        html: output/matching.html
      highly_sensitive: 
        rds1: output/matched_patients.rds
        rds2: output/unmatched_patients.rds
        csv: output/matched_patients_id.csv

  check_unmatched:
    run: r:latest -e 'rmarkdown::render("analysis/check_unmatched.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [matching]
    outputs:
      moderately_sensitive:
        html: output/check_unmatched.html
  

  extract_variables: 
    run: cohortextractor:latest generate_cohort --with-end-date-fix --study-definition study_definition_outcome
    needs: [matching]
    outputs:
      highly_sensitive:
        cohort: output/input_outcome.csv

  process_Rmatching: # add variables 
    run: r:latest analysis/process_Rmatching.R
    needs: [extract_variables,matching]
    outputs:
      highly_sensitive:
        cohort1: output/matched_outcome.rds
        rds1: output/abtype79.rds
        rds2: output/comor17.rds

  table1: # matching var
    run: r:latest -e 'rmarkdown::render("analysis/table1.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_1,process_Rmatching]
    outputs:
      moderately_sensitive:
        html: output/table1.html

  table1_round: 
    run: r:latest analysis/table1.R
    needs: [process_1,process_Rmatching]
    outputs:
      moderately_sensitive:
        csv1: output/table1_unmatched.csv
        csv2: output/table1_matched.csv
        csv3: output/table1_random.csv
        
  table2: # confounders
    run: r:latest -e 'rmarkdown::render("analysis/table2.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        html: output/table2.html

  table2_round: 
    run: r:latest analysis/table2.R
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        csv1: output/table2_matched.csv
        csv3: output/table2_random.csv

  table2_ab: # ab
    run: r:latest -e 'rmarkdown::render("analysis/table2_ab.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        html: output/table2_ab.html


  table3_round: 
    run: r:latest analysis/table3.R
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        csv1: output/table3.csv
        csv3: output/table3_ab.csv

  model: 
    run: r:latest analysis/model/model.R
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        csv1: output/model_1_crude.csv
        csv2: output/model_1_adjusted.csv


  # model: 
  #   run: r:latest -e 'rmarkdown::render("analysis/model.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/model.html

  # model_subgroup: # by age and sex 
  #   run: r:latest -e 'rmarkdown::render("analysis/model_subgroup.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/model_subgroup.html
  
  #   # abtype modeling
  # model_abtype: 
  #   run: r:latest -e 'rmarkdown::render("analysis/model_abtype.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/model_abtype.html


  model_2: 
    run: r:latest -e 'rmarkdown::render("analysis/model_2.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        html: output/model_2.html

        
  # model_complete_case: 
  #   run: r:latest -e 'rmarkdown::render("analysis/model_complete_case.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/model_complete_case.html
        ################# check ok###########


  ### test 1:3 matching  ###

  matching_3: # matching with replacement # died covid
    run: r:latest -e 'rmarkdown::render("analysis/matching_3.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_1]
    outputs:
      moderately_sensitive:
        html: output/matching_3.html
      highly_sensitive: 
        rds1: output/matched_patients_3.rds
        rds2: output/unmatched_patients_3.rds
        csv: output/matched_patients_id_3.csv

  process_Rmatching_3: # add variables 
    run: r:latest analysis/process_Rmatching_3.R
    needs: [extract_variables,matching]
    outputs:
      highly_sensitive:
        cohort1: output/matched_outcome_3.rds
        rds1: output/abtype79_3.rds
        rds2: output/comor17_3.rds

  model_abtype_3: 
    run: r:latest -e 'rmarkdown::render("analysis/model_abtype_3.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_Rmatching_3]
    outputs:
      moderately_sensitive:
        html: output/model_abtype_3.html

  # model_time: # adjust for last AB time
  #   run: r:latest -e 'rmarkdown::render("analysis/model_time.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/model_time.html
  
  # model_disease: # adjust for disease
  #   run: r:latest -e 'rmarkdown::render("analysis/model_disease.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/model_disease.html

  # model_wave: # separate wave
  #   run: r:latest -e 'rmarkdown::render("analysis/model_wave.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/model_wave.html

        #### addintional check for 6 weeks exclusion
  extract_variables_6w: 
    run: cohortextractor:latest generate_cohort --study-definition study_definition_outcome_6w
    needs: [matching]
    outputs:
      highly_sensitive:
        cohort: output/input_outcome_6w.csv
  
  process_Rmatching_6w: # add variables 
    run: r:latest analysis/process_Rmatching_6w.R
    needs: [extract_variables_6w,matching,process_Rmatching]
    outputs:
      highly_sensitive:
        cohort1: output/matched_outcome_6w.rds
  
  model_6w: # adjust for last AB time
    run: r:latest -e 'rmarkdown::render("analysis/model_6w.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_Rmatching_6w]
    outputs:
      moderately_sensitive:
        html: output/model_6w.html

          #### addintional check for 6 weeks exclusion



  # matching2: # matching with replacement # died any
  #   run: r:latest -e 'rmarkdown::render("analysis/matching2.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_1]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/matching2.html
  #     highly_sensitive: 
  #       rds1: output/matched_patients_2.rds
  #       rds2: output/unmatched_patients_2.rds
  #       csv: output/matched_patients_id_2.csv

  # check_matching:
  #   run: r:latest -e 'rmarkdown::render("analysis/check_matching.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [matching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/check_matching.html
  
  # check_matching2:
  #   run: r:latest -e 'rmarkdown::render("analysis/check_matching2.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [matching2]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/check_matching2.html



  # extract_variables2: 
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition_outcome2
  #   needs: [matching2]
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input_outcome2.csv
  
  # process_Rmatching: # add variables 
  #   run: r:latest analysis/process_Rmatching.R
  #   needs: [extract_variables,matching]
  #   outputs:
  #     highly_sensitive:
  #       cohort1: output/matched_outcome.rds

  # process_Rmatching2: # add variables 
  #   run: r:latest analysis/process_Rmatching2.R
  #   needs: [extract_variables2,matching2]
  #   outputs:
  #     highly_sensitive:
  #       cohort1: output/matched_outcome2.rds


  # check_input: # 
  #   run: r:latest -e 'rmarkdown::render("analysis/check_input.Rmd", knit_root_dir = "/workspace", output_dir = "output")'
  #   needs: [process_Rmatching2,extract_variables2,matching2,process_Rmatching,extract_variables,matching,process_1, generate_study_population_covid_admission]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/check_input.html

  ### for covid icu/ covid death
  # process_Rmatching: # add variables 
  #   run: r:latest analysis/process_Rmatching.R
  #   needs: [extract_variables,matching]
  #   outputs:
  #     highly_sensitive:
  #       cohort1: output/matched_outcome.rds
  #       rds1: output/abtype79.rds
  #       rds2: output/comor17.rds

  # check_exposures_cont: # continuous variables
  #   run: r:latest -e 'rmarkdown::render("analysis/check_exposures_cont.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/check_exposures_cont.html
  
  # check_exposures_cat: # category variables
  #   run: r:latest -e 'rmarkdown::render("analysis/check_exposures_cat.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/check_exposures_cat.html

  # modeling: # ab level
  #   run: r:latest -e 'rmarkdown::render("analysis/modeling.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/modeling.html

  # modeling2: # ab level+ CCI + covid vaccine
  #   run: r:latest -e 'rmarkdown::render("analysis/modeling2.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/modeling2.html

  # modeling3: # all
  #   run: r:latest -e 'rmarkdown::render("analysis/modeling3.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/modeling3.html

  # describe_ab: 
  #   run: r:latest -e 'rmarkdown::render("analysis/describe_ab.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/describe_ab.html
  
  # abtype modeling
  # modeling4: # all
  #   run: r:latest -e 'rmarkdown::render("analysis/modeling4.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/modeling4.html

  
  #   broad ab modeling
  # modeling5: # all
  #   run: r:latest -e 'rmarkdown::render("analysis/modeling5.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
  #   needs: [process_Rmatching]
  #   outputs:
  #     moderately_sensitive:
  #       html: output/modeling5.html




  ### for covid icu/ any death
 ### for covid icu/ covid death
  # process_Rmatching: # add variables 
  #   run: r:latest analysis/process_Rmatching.R
  #   needs: [extract_variables,matching]
  #   outputs:
  #     highly_sensitive:
  #       cohort1: output/matched_outcome.rds
  #       rds1: output/abtype79.rds
  #       rds2: output/comor17.rds

  check_exposures_cont: # continuous variables
    run: r:latest -e 'rmarkdown::render("analysis/check_exposures_cont.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        html: output/check_exposures_cont.html
  
  check_exposures_cat: # category variables
    run: r:latest -e 'rmarkdown::render("analysis/check_exposures_cat.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        html: output/check_exposures_cat.html

  modeling: # ab level
    run: r:latest -e 'rmarkdown::render("analysis/modeling.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        html: output/modeling.html

  modeling2: # ab level+ CCI + covid vaccine
    run: r:latest -e 'rmarkdown::render("analysis/modeling2.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        html: output/modeling2.html

  modeling3: # all
    run: r:latest -e 'rmarkdown::render("analysis/modeling3.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        html: output/modeling3.html

  describe_ab: 
    run: r:latest -e 'rmarkdown::render("analysis/describe_ab.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        html: output/describe_ab.html
  
  # abtype modeling
  modeling4: # all
    run: r:latest -e 'rmarkdown::render("analysis/modeling4.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        html: output/modeling4.html

  
    # broad ab modeling
  modeling5: # all
    run: r:latest -e 'rmarkdown::render("analysis/modeling5.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_Rmatching]
    outputs:
      moderately_sensitive:
        html: output/modeling5.html