version: '3.0'

expectations:
  population_size: 1000

actions:

  # generate_study_population:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to today by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/measures/input_*.csv.gz

  # generate_study_population_elderly:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition_elderly 
  #     --output-format=csv.gz
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input_elderly.csv.gz

  # generate_measures:
  #   run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
  #   needs: [generate_study_population]
  #   outputs:
  #     moderately_sensitive:
  #       measure_csv: output/measures/measure_*.csv
        
  # describe_elderly_agedis:
  #   run: r:latest analysis/tables/gen_csv_age_check.R
  #   needs: [generate_study_population_elderly]
  #   outputs:
  #     moderately_sensitive:
  #       agetable: output/age_quant.csv

  # describe:
  #   run: r:latest analysis/plot/overall_ab_prescribing.R
  #   needs: [generate_measures]
  #   outputs:
  #     moderately_sensitive:
  #       cohort: output/overall.png
  #       boxplot: output/overallbox.png

  # describe_percentile:
  #   run: r:latest analysis/plot/overall_ab_prescribing_2575percentile.R
  #   needs: [generate_measures]
  #   outputs:
  #     moderately_sensitive:
  #       percentile: output/overall_25th_75th_percentile.png

  # describe_starpu:
  #   run: r:latest analysis/plot/starpu_ab_prescribing.R
  #   needs: [generate_measures]
  #   outputs:
  #     moderately_sensitive:
  #       cohort: output/starpuline.png
  #       boxplot: output/starpubox.png
  
  # generate_notebook_starpu:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/starpu.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400
  #   needs: [generate_measures]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/starpu.html 
  #       figures: output/*
  #       tables: output/tables/*
  #       csvs: output/*/* # two possible subfolders
  #       text: output/text/*
  
  # describe_infection_ab_UTI:
  #   run: r:latest analysis/plot/infection_ab_UTI.R
  #   needs: [generate_study_population, generate_measures]
  #   outputs:
  #      moderately_sensitive:
  #       plot: output/UTI.png
  
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_general_population --index-date-range "2020-02-01 to 2021-12-31 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz
  
  # generate_study_population_general_population:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_general_population
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input_covid_general_population.csv

  generate_study_population_covid_primarycare:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_primarycare
    outputs:
      highly_sensitive:
        cohort: output/input_covid_primarycare.csv
  
  generate_study_population_covid_SGSS:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_SGSS
    outputs:
      highly_sensitive:
        cohort: output/input_covid_SGSS.csv
  
  generate_study_population_covid_admission:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_admission
    outputs:
      highly_sensitive:
        cohort: output/input_covid_admission.csv
  
  generate_study_population_covid_icu:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_icu
    outputs:
      highly_sensitive:
        cohort: output/input_covid_icu.csv

  generate_study_population_covid_death_ons:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_death_ons
    outputs:
      highly_sensitive:
        cohort: output/input_covid_death_ons.csv
  
  generate_study_population_covid_death_cpns:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_death_cpns
    outputs:
      highly_sensitive:
        cohort: output/input_covid_death_cpns.csv
  
  exclusion:
    run: r:latest analysis/exclusion.R
    needs: [generate_study_population_covid_primarycare, generate_study_population_covid_SGSS,generate_study_population_covid_admission,generate_study_population_covid_icu,generate_study_population_covid_death_ons,generate_study_population_covid_death_cpns,generate_study_population]
    outputs:
       highly_sensitive:
        cohort1: output/case_covid_infection.csv
        cohort2: output/case_covid_admission.csv
        cohort3: output/case_covid_icu_death.csv
        cohort4: output/control_general_population_*.csv
        cohort5: output/case_covid_infection_*.csv

  matching:
    run: python:latest python analysis/matching.py
    needs: [exclusion]
    outputs:
      moderately_sensitive: 
        matching_report1: output/matching_report_infection_hosp.txt
        matching_report2: output/matching_report_hosp_icu_death.txt   
      highly_sensitive: 
        combined1: output/matched_combined_infection_hosp.csv
        combined2: output/matched_combined_hosp_icu_death.csv