version: '3.0'

expectations:
  population_size: 30000

actions:

### study cohort ###
  generate_study_population_case:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case
    outputs:
      highly_sensitive:
        cohort: output/input_case.csv

  generate_study_population_case_test:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_test
    outputs:
      highly_sensitive:
        cohort: output/input_case_test.csv

  generate_study_population_control_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_1
    outputs:
      highly_sensitive:
        cohort: output/input_control_1.csv

  generate_study_population_control_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_2
    outputs:
      highly_sensitive:
        cohort: output/input_control_2.csv

  generate_study_population_control_3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_3
    outputs:
      highly_sensitive:
        cohort: output/input_control_3.csv

  generate_study_population_control_4:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_4
    outputs:
      highly_sensitive:
        cohort: output/input_control_4.csv

  generate_study_population_control_5:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_5
    outputs:
      highly_sensitive:
        cohort: output/input_control_5.csv

  generate_study_population_control_6:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_6
    outputs:
      highly_sensitive:
        cohort: output/input_control_6.csv

  generate_study_population_control_7:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_7
    outputs:
      highly_sensitive:
        cohort: output/input_control_7.csv

  generate_study_population_control_8:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_8
    outputs:
      highly_sensitive:
        cohort: output/input_control_8.csv

  case_check:  
    run: r:latest analysis/case_check.R
    needs: [generate_study_population_case]
    outputs:
      highly_sensitive:
        cohort: output/case_ch.csv
      moderately_sensitive:
        table1: output/case_check.csv
        table2: output/case_frequency_check.csv

  sepsis_trend:  
    run: r:latest analysis/sepsis_trend.R
    needs: [case_check]
    outputs:
      moderately_sensitive:
        plot1: output/figure_2.1.jpeg
        plot2: output/figure_2.2.jpeg
        plot3: output/figure_2.3.jpeg
        table1: output/figure_2.3_table.csv

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2022-12-31 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  sepsis_trend_rate:  
    run: r:latest analysis/sepsis_trend_rate.R
    needs: [case_check,generate_measures]
    outputs:
      moderately_sensitive:
        plot1: output/figure_rate.jpeg
        table1: output/figure_rate_table.csv

  sepsis_trend_rate_com:  
    run: r:latest analysis/sepsis_trend_rate_com.R
    needs: [case_check,generate_measures]
    outputs:
      moderately_sensitive:
        plot1: output/figure_rate_com.jpeg

  sepsis_trend_rate_hos:  
    run: r:latest analysis/sepsis_trend_rate_hos.R
    needs: [case_check,generate_measures]
    outputs:
      moderately_sensitive:
        plot1: output/figure_rate_hos.jpeg

  process1:  
    run: r:latest analysis/process1.R
    needs: [case_check,generate_study_population_control_1,generate_study_population_control_2,
    generate_study_population_control_3,generate_study_population_control_4,generate_study_population_control_5,
    generate_study_population_control_6,generate_study_population_control_7,generate_study_population_control_8]
    outputs:
      highly_sensitive:
        cohort1: output/case_191.csv
        cohort2: output/case_192.csv
        cohort3: output/case_201.csv
        cohort4: output/case_202.csv
        cohort5: output/case_211.csv
        cohort6: output/case_212.csv
        cohort7: output/case_221.csv
        cohort8: output/case_222.csv
        cohort9: output/control_191.csv
        cohort10: output/control_192.csv
        cohort11: output/control_201.csv
        cohort12: output/control_202.csv
        cohort13: output/control_211.csv
        cohort14: output/control_212.csv
        cohort15: output/control_221.csv
        cohort16: output/control_222.csv

  matching1:
    run: python:latest python analysis/matching1.py
    needs: [process1]
    outputs:
      highly_sensitive: 
        table1: output/matched_cases_191.csv
        table2: output/matched_matches_191.csv
        table3: output/matched_combined_191.csv
        table4: output/matched_cases_192.csv
        table5: output/matched_matches_192.csv
        table6: output/matched_combined_192.csv
      moderately_sensitive: 
        report1: output/matching_report_191.txt
        report2: output/matching_report_192.txt

  matching2:
    run: python:latest python analysis/matching2.py
    needs: [process1]
    outputs:
      highly_sensitive: 
        table1: output/matched_cases_201.csv
        table2: output/matched_matches_201.csv
        table3: output/matched_combined_201.csv
        table4: output/matched_cases_202.csv
        table5: output/matched_matches_202.csv
        table6: output/matched_combined_202.csv
      moderately_sensitive: 
        report1: output/matching_report_201.txt
        report2: output/matching_report_202.txt

  matching3:
    run: python:latest python analysis/matching3.py
    needs: [process1]
    outputs:
      highly_sensitive: 
        table1: output/matched_cases_211.csv
        table2: output/matched_matches_211.csv
        table3: output/matched_combined_211.csv
        table4: output/matched_cases_212.csv
        table5: output/matched_matches_212.csv
        table6: output/matched_combined_212.csv
      moderately_sensitive: 
        report1: output/matching_report_211.txt
        report2: output/matching_report_212.txt

  matching4:
    run: python:latest python analysis/matching4.py
    needs: [process1]
    outputs:
      highly_sensitive: 
        table1: output/matched_cases_221.csv
        table2: output/matched_matches_221.csv
        table3: output/matched_combined_221.csv
      moderately_sensitive: 
        report1: output/matching_report_221.txt


  process_covidinclude:  
    run: r:latest analysis/process_covidinclude.R
    needs: [generate_study_population_case]
    outputs:
      highly_sensitive:
        cohort: output/case_covidinclude.csv
      moderately_sensitive:
        table1: output/case_frequency_check1.csv
        table2: output/case_frequency_check2.csv

  sepsis_trend_rate_covidinclude:  
    run: r:latest analysis/sepsis_trend_rate_covidinclude.R
    needs: [process_covidinclude,generate_measures]
    outputs:
      moderately_sensitive:
        plot1: output/figure_rate_covidinclude.jpeg
        table1: output/figure_rate_covidinclude_table.csv
        plot2: output/figure_rate_covidinclude_com.jpeg
        plot3: output/figure_rate_covidinclude_hos.jpeg

  process_noexclude:  
    run: r:latest analysis/process_noexclude.R
    needs: [generate_study_population_case]
    outputs:
      moderately_sensitive:
        plot1: output/figure_noexclude.jpeg
        table1: output/figure_noexclude_table.csv

  case_check_test:  
    run: r:latest analysis/case_check_test.R
    needs: [generate_study_population_case_test]
    outputs:
      moderately_sensitive:
        table1: output/case_test.csv

  2019_imd_model: 
    run: r:latest analysis/2019_imd_model.R
    needs: [matching1]
    outputs:
      moderately_sensitive:
        table1: output/2019_imd_model.csv

  2019_modelall:   
    run: r:latest -e 'rmarkdown::render("analysis/2019_modelall.Rmd", output_dir = "output")'
    needs: [matching1]
    outputs:
      moderately_sensitive:
        html: output/2019_modelall.html

  1921_modelall:   
    run: r:latest -e 'rmarkdown::render("analysis/1921_modelall.Rmd", output_dir = "output")'
    needs: [matching1,matching2,matching3]
    outputs:
      moderately_sensitive:
        html: output/1921_modelall.html

  covidimd_model:   
    run: r:latest -e 'rmarkdown::render("analysis/covidimd_model.Rmd", output_dir = "output")'
    needs: [matching1,matching2,matching3,matching4]
    outputs:
      moderately_sensitive:
        html: output/covidimd_model.html

  process2_idextraction:  
    run: r:latest analysis/process2_idextraction.R
    needs: [matching1,matching2,matching3,matching4]
    outputs:
      highly_sensitive:
        cohort: output/case_id.csv

  generate_study_population_variables:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_variables
    needs: [process2_idextraction]
    outputs:
      highly_sensitive:
        cohort: output/input_variables.csv

  process3_idextraction:  
    run: r:latest analysis/process3_idextraction.R
    needs: [matching1,matching2,matching3,matching4]
    outputs:
      highly_sensitive:
        cohort1: output/control_id_191.csv
        cohort2: output/control_id_192.csv
        cohort3: output/control_id_201.csv
        cohort4: output/control_id_202.csv
        cohort5: output/control_id_211.csv
        cohort6: output/control_id_212.csv
        cohort7: output/control_id_221.csv

  generate_study_population_control_var_191:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_var_191
    needs: [process3_idextraction]
    outputs:
      highly_sensitive:
        cohort: output/input_control_var_191.csv

  generate_study_population_control_var_192:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_var_192
    needs: [process3_idextraction]
    outputs:
      highly_sensitive:
        cohort: output/input_control_var_192.csv

  generate_study_population_control_var_201:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_var_201
    needs: [process3_idextraction]
    outputs:
      highly_sensitive:
        cohort: output/input_control_var_201.csv

  generate_study_population_control_var_202:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_var_202
    needs: [process3_idextraction]
    outputs:
      highly_sensitive:
        cohort: output/input_control_var_202.csv

  generate_study_population_control_var_211:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_var_211
    needs: [process3_idextraction]
    outputs:
      highly_sensitive:
        cohort: output/input_control_var_211.csv

  generate_study_population_control_var_212:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_var_212
    needs: [process3_idextraction]
    outputs:
      highly_sensitive:
        cohort: output/input_control_var_212.csv

  generate_study_population_control_var_221:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_var_221
    needs: [process3_idextraction]
    outputs:
      highly_sensitive:
        cohort: output/input_control_var_221.csv

  process_data:
    run: r:latest analysis/data_process.R
    needs: [generate_study_population_variables]
    outputs:
      highly_sensitive: 
        rds: output/processed/input_case_data.rds

  process_data_control:
    run: r:latest analysis/data_process_control.R
    needs: [generate_study_population_control_var_191,generate_study_population_control_var_192,
    generate_study_population_control_var_201,generate_study_population_control_var_202,
    generate_study_population_control_var_211,generate_study_population_control_var_212,
    generate_study_population_control_var_221]
    outputs:
      highly_sensitive: 
        rds: output/processed/input_control_data.rds

# Skim data
  skim_data_case:
    run: r:latest analysis/data_skim.R output/processed/input_case_data.rds output/data_properties
    needs: [process_data]
    outputs: 
      moderately_sensitive:
        txt1: output/data_properties/input_case_data_skim.txt
        txt2: output/data_properties/input_case_data_coltypes.txt
        txt3: output/data_properties/input_case_data_tabulate.txt

  skim_data_control:
    run: r:latest analysis/data_skim.R output/processed/input_control_data.rds output/data_properties
    needs: [process_data_control]
    outputs: 
      moderately_sensitive:
        txt1: output/data_properties/input_control_data_skim.txt
        txt2: output/data_properties/input_control_data_coltypes.txt
        txt3: output/data_properties/input_control_data_tabulate.txt

  fully_model:   
    run: r:latest -e 'rmarkdown::render("analysis/fully_model.Rmd", output_dir = "output")'
    needs: [matching1,matching2,matching3,matching4,process_data,process_data_control]
    outputs:
      moderately_sensitive:
        html: output/fully_model.html

  fully_model_community:   
    run: r:latest -e 'rmarkdown::render("analysis/fully_model_community.Rmd", output_dir = "output")'
    needs: [matching1,matching2,matching3,matching4,process_data,process_data_control]
    outputs:
      moderately_sensitive:
        html: output/fully_model_community.html

  fully_model_hospital:   
    run: r:latest -e 'rmarkdown::render("analysis/fully_model_hospital.Rmd", output_dir = "output")'
    needs: [matching1,matching2,matching3,matching4,process_data,process_data_control]
    outputs:
      moderately_sensitive:
        html: output/fully_model_hospital.html

  fully_model_combine:   
    run: r:latest -e 'rmarkdown::render("analysis/fully_model_combine.Rmd", output_dir = "output")'
    needs: [matching1,matching2,matching3,matching4,process_data,process_data_control]
    outputs:
      moderately_sensitive:
        html: output/fully_model_combine.html