version: '3.0'

expectations:
  population_size: 30000

actions:
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
### study cohort ###
