version: '3.0'

expectations:
  population_size: 30000

actions:

### study cohort ###
  generate_study_population_case_uti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_uti
    outputs:
      highly_sensitive:
        cohort: output/input_case_uti.csv

  generate_study_population_control_uti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_uti
    outputs:
      highly_sensitive:
        cohort: output/input_control_uti.csv

  matching_uti:
    run: python:latest python analysis/matching_uti.py
    needs: [generate_study_population_case_uti,generate_study_population_control_uti]
    outputs:
      highly_sensitive: 
        table1: output/matched_cases_uti.csv
        table2: output/matched_matches_uti.csv
        table3: output/matched_combined_uti.csv
      moderately_sensitive: 
        report1: output/matching_report_uti.txt

  generate_study_population_case_uti_abvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_uti_abvar
    needs: [matching_uti]
    outputs:
      highly_sensitive:
        cohort: output/input_case_uti_abvar.csv

  generate_study_population_control_uti_abvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_uti_abvar
    needs: [matching_uti]
    outputs:
      highly_sensitive:
        cohort: output/input_control_uti_abvar.csv

  generate_study_population_case_uti_othvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_uti_othvar
    needs: [matching_uti]
    outputs:
      highly_sensitive:
        cohort: output/input_case_uti_othvar.csv

  generate_study_population_control_uti_othvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_uti_othvar
    needs: [matching_uti]
    outputs:
      highly_sensitive:
        cohort: output/input_control_uti_othvar.csv
