version: '3.0'

expectations:
  population_size: 1000

actions:
  

  generate_study_population_covid_admission:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_admission
    outputs:
      highly_sensitive:
        cohort: output/input_covid_admission.csv

  process_1:  
    run: r:latest analysis/process_1.R
    needs: [generate_study_population_covid_admission]
    outputs:
      highly_sensitive:
        case: output/case_covid_icu_death.csv
        case2: output/case_covid_icu_death_2.csv
        control: output/control_covid_hosp.csv
        control2: output/control_covid_hosp_2.csv
        

# R MatchIt

  matching: # matching with replacement
    run: r:latest -e 'rmarkdown::render("analysis/matching.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_1]
    outputs:
      moderately_sensitive:
        html: output/matching.html
      highly_sensitive: 
        rds1: output/matched_patients.rds
        rds2: output/unmatched_patients.rds
        csv: output/matched_patients_id.csv
  
  matching2: # matching with replacement
    run: r:latest -e 'rmarkdown::render("analysis/matching2.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [process_1]
    outputs:
      moderately_sensitive:
        html: output/matching2.html
      highly_sensitive: 
        rds1: output/matched_patients_2.rds
        rds2: output/unmatched_patients_2.rds
        csv: output/matched_patients_id_2.csv

  check_matching:
    run: r:latest -e 'rmarkdown::render("analysis/check_matching.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [matching]
    outputs:
      moderately_sensitive:
        html: output/check_matching.html
  
  check_matching2:
    run: r:latest -e 'rmarkdown::render("analysis/check_matching2.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [matching2]
    outputs:
      moderately_sensitive:
        html: output/check_matching2.html

  extract_variables: 
    run: cohortextractor:latest generate_cohort --study-definition study_definition_outcome
    needs: [matching]
    outputs:
      highly_sensitive:
        cohort: output/input_outcome.csv

  extract_variables2: 
    run: cohortextractor:latest generate_cohort --study-definition study_definition_outcome2
    needs: [matching2]
    outputs:
      highly_sensitive:
        cohort: output/input_outcome2.csv
  
  process_Rmatching: # add variables 
    run: r:latest analysis/process_Rmatching.R
    needs: [extract_variables,matching]
    outputs:
      highly_sensitive:
        cohort1: output/matched_outcome.rds

  process_Rmatching2: # add variables 
    run: r:latest analysis/process_Rmatching2.R
    needs: [extract_variables2,matching2]
    outputs:
      highly_sensitive:
        cohort1: output/matched_outcome2.rds


  check_input: # 
    run: r:latest -e 'rmarkdown::render("analysis/check_input.Rmd", knit_root_dir = "/workspace", output_dir = "output")'
    needs: [process_Rmatching2,extract_variables2,matching2,process_Rmatching,extract_variables,matching,process_1, generate_study_population_covid_admission]
    outputs:
      moderately_sensitive:
        html: output/check_input.html