version: '3.0'

expectations:
  population_size: 200000

actions:

  # generate_study_population:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to today by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/measures/input_*.csv.gz

  # generate_study_population_hospitalisation_rate:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_rate --output-format=csv.gz
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/hospitalisation_data/input_hospitalisation_rate.csv.gz

  # generate_measures:
    # run: cohortextractor:latest generate_measures --study-definition all --skip-existing --output-dir=output/measures
    # needs: [generate_study_population_hospitalisation_rate]
    # outputs:
    #   moderately_sensitive:
    #     measure_csv: output/measures/measure_hospitalisation_rate.csv

  study_definition_hospitalisation_rate:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_rate --index-date-range "2019-01-01 to today by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_hospitalisation_rate --skip-existing --output-dir=output/measures
    needs: [study_definition_hospitalisation_rate]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  # describe_percentile_starpu:
  #   run: r:latest analysis/plot/starpu_ab_percentile.R
  #   needs: [generate_study_population_hospitalisation_rate]
  #   outputs:
  #     moderately_sensitive:
  #       percentile_STARPU: output/overall_25th_75th_percentile_STARPU.jpeg

  # generate_notebook_hospitalisation_analysis:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_analysis.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_risk --ExecutePreprocessor.timeout=86400
  #   needs: [generate_study_population_hospitalisation]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/hospitalisation_risk/hospitalisation_analysis.html 
  #       figures: output/hospitalisation_risk/*

  # generate_notebook_hospitalisation_rate:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_rate.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_rate --ExecutePreprocessor.timeout=86400
  #   needs: [generate_study_population_hospitalisation_rate]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/hospitalisation_rate/hospitalisation_rate.html 
  #       figures: output/hospitalisation_rate/*