version: '3.0'

expectations:
  population_size: 30000

actions:

### study cohort ###
  generate_study_population_case:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case
    outputs:
      highly_sensitive:
        cohort: output/input_case.csv

  generate_study_population_control_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_1
    outputs:
      highly_sensitive:
        cohort: output/input_control_1.csv

  generate_study_population_control_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_2
    outputs:
      highly_sensitive:
        cohort: output/input_control_2.csv

  case_check:  
    run: r:latest analysis/case_check.R
    needs: [generate_study_population_case]
    outputs:
      highly_sensitive:
        cohort: output/case_ch.csv
      moderately_sensitive:
        table1: output/case_check.csv
        table2: output/case_frequency_check.csv

  sepsis_trend:  
    run: r:latest analysis/sepsis_trend.R
    needs: [case_check]
    outputs:
      moderately_sensitive:
        plot1: output/figure_2.1.jpeg
        plot2: output/figure_2.2.jpeg
        plot3: output/figure_2.3.jpeg

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2022-12-31 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  sepsis_trend_rate:  
    run: r:latest analysis/sepsis_trend_rate.R
    needs: [case_check,generate_measures]
    outputs:
      moderately_sensitive:
        plot1: output/figure_rate.jpeg

  sepsis_trend_rate_com:  
    run: r:latest analysis/sepsis_trend_rate_com.R
    needs: [case_check,generate_measures]
    outputs:
      moderately_sensitive:
        plot1: output/figure_rate_com.jpeg

  process1:  
    run: r:latest analysis/process1.R
    needs: [case_check]
    outputs:
      highly_sensitive:
        cohort1: output/case_191.csv
        cohort2: output/case_192.csv
        cohort3: output/case_201.csv
        cohort4: output/case_202.csv
        cohort5: output/case_211.csv
        cohort6: output/case_212.csv
        cohort7: output/case_221.csv
        cohort8: output/case_222.csv
