version: '3.0'

expectations:
  population_size: 30000

actions:

### study cohort ###
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_study_population_ae:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ae --index-date-range "2019-01-01 to 2023-03-31 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_ae_*.csv.gz

  generate_measures_ae:
    run: cohortextractor:latest generate_measures --study-definition study_definition_ae --skip-existing --output-dir=output/measures
    needs: [generate_study_population_ae]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  ae_rate_table:  
    run: r:latest analysis/figure/ae_rate.R
    needs: [generate_measures_ae]
    outputs:
      moderately_sensitive:
        table1: output/ae_rate_table.csv
        table2: output/ae_rate_forplot.csv