version: '3.0'

expectations:
  population_size: 30000

actions:

  generate_study_population_patient_characteristics_2019:
      run: cohortextractor:latest generate_cohort 
        --with-end-date-fix
        --study-definition study_definition_patient_characteristics_2019
        --output-format=csv.gz
      outputs:
        highly_sensitive:
          cohort: output/input_patient_characteristics_2019.csv.gz

  generate_study_population_patient_characteristics_2020:
      run: cohortextractor:latest generate_cohort 
        --with-end-date-fix
        --study-definition study_definition_patient_characteristics_2020
        --output-format=csv.gz
      outputs:
        highly_sensitive:
          cohort: output/input_patient_characteristics_2020.csv.gz

  generate_study_population_patient_characteristics_2021:
      run: cohortextractor:latest generate_cohort 
        --with-end-date-fix
        --study-definition study_definition_patient_characteristics_2021
        --output-format=csv.gz
      outputs:
        highly_sensitive:
          cohort: output/input_patient_characteristics_2021.csv.gz

  table_1: 
    run: r:latest analysis/table_1.R
    needs: [generate_study_population_patient_characteristics_2019]
    outputs:
       moderately_sensitive:
        table1: output/table1_2019_overallcount.csv
        table2: output/table1_2019.csv

  table_1_2020: 
    run: r:latest analysis/table_1_2020.R
    needs: [generate_study_population_patient_characteristics_2020]
    outputs:
       moderately_sensitive:
        table1: output/table1_2020_overallcount.csv
        table2: output/table1_2020.csv

  table_1_2021: 
    run: r:latest analysis/table_1_2021.R
    needs: [generate_study_population_patient_characteristics_2021]
    outputs:
       moderately_sensitive:
        table1: output/table1_2021_overallcount.csv
        table2: output/table1_2021.csv

  generate_study_population:
    run: cohortextractor:latest generate_cohort
      --with-end-date-fix
      --study-definition study_definition 
      --index-date-range "2019-01-01 to 2021-12-31 by month" 
      --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition 
      --skip-existing 
      --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  figure_1A: 
    run: r:latest analysis/figure_1A.R
    needs: [generate_measures]
    outputs:
       moderately_sensitive:
        plot1: output/figure_1A.jpeg

### generate study cohort with the date of each prescriptions
  generate_study_population_ab_type_2019: 
    run: cohortextractor:latest generate_cohort
      --with-end-date-fix
      --study-definition study_definition_ab_type_2019
      --index-date-range "2019-01-01 to 2019-12-31"
      --skip-existing
      --output-dir=output/measures
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_ab_type_2019_*.csv.gz

  generate_study_population_ab_type_2020: 
    run: cohortextractor:latest generate_cohort 
      --with-end-date-fix
      --study-definition study_definition_ab_type_2020 
      --index-date-range "2020-01-01 to 2020-12-31" 
      --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_ab_type_2020_*.csv.gz

  generate_study_population_ab_type_2021: 
    run: cohortextractor:latest generate_cohort 
      --with-end-date-fix
      --study-definition study_definition_ab_type_2021 
      --index-date-range "2021-01-01 to 2021-12-31" 
      --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_ab_type_2021_*.csv.gz

  conversion_abtype_2019: 
    run: r:latest analysis/conversion_abtype_2019.R
    needs: [generate_study_population_ab_type_2019]
    outputs:
       highly_sensitive:
        rds1: output/measures/abtype_2019.rds
