version: '3.0'

expectations:
  population_size: 30000

actions:
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
### study cohort ###

### UTI ###

  generate_study_population_case_uti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_uti
    outputs:
      highly_sensitive:
        cohort: output/input_case_uti.csv

  generate_study_population_control_uti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_uti
    outputs:
      highly_sensitive:
        cohort: output/input_control_uti.csv

  matching_uti:
    run: python:latest python analysis/matching_uti.py
    needs: [generate_study_population_case_uti,generate_study_population_control_uti]
    outputs:
      highly_sensitive: 
        table1: output/matched_cases_uti.csv
        table2: output/matched_matches_uti.csv
        table3: output/matched_combined_uti.csv
      moderately_sensitive: 
        report1: output/matching_report_uti.txt
### UTI var ###
  generate_study_population_case_uti_abvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_uti_abvar
    needs: [matching_uti]
    outputs:
      highly_sensitive:
        cohort: output/input_case_uti_abvar.csv

  generate_study_population_control_uti_abvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_uti_abvar
    needs: [matching_uti]
    outputs:
      highly_sensitive:
        cohort: output/input_control_uti_abvar.csv

  generate_study_population_case_uti_othvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_uti_othvar
    needs: [matching_uti]
    outputs:
      highly_sensitive:
        cohort: output/input_case_uti_othvar.csv

  generate_study_population_control_uti_othvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_uti_othvar
    needs: [matching_uti]
    outputs:
      highly_sensitive:
        cohort: output/input_control_uti_othvar.csv

  generate_study_population_case_uti_type:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_uti_type
    needs: [matching_uti]
    outputs:
      highly_sensitive:
        cohort: output/input_case_uti_type.csv

### URTI ###

  generate_study_population_case_urti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_urti
    outputs:
      highly_sensitive:
        cohort: output/input_case_urti.csv

  generate_study_population_control_urti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_urti
    outputs:
      highly_sensitive:
        cohort: output/input_control_urti.csv

  matching_urti:
    run: python:latest python analysis/matching_urti.py
    needs: [generate_study_population_case_urti,generate_study_population_control_urti]
    outputs:
      highly_sensitive: 
        table1: output/matched_cases_urti.csv
        table2: output/matched_matches_urti.csv
        table3: output/matched_combined_urti.csv
      moderately_sensitive: 
        report1: output/matching_report_urti.txt

### URTI var ###
  generate_study_population_case_urti_abvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_urti_abvar
    needs: [matching_urti]
    outputs:
      highly_sensitive:
        cohort: output/input_case_urti_abvar.csv

  generate_study_population_control_urti_abvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_urti_abvar
    needs: [matching_urti]
    outputs:
      highly_sensitive:
        cohort: output/input_control_urti_abvar.csv

  generate_study_population_case_urti_othvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_urti_othvar
    needs: [matching_urti]
    outputs:
      highly_sensitive:
        cohort: output/input_case_urti_othvar.csv

  generate_study_population_control_urti_othvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_urti_othvar
    needs: [matching_urti]
    outputs:
      highly_sensitive:
        cohort: output/input_control_urti_othvar.csv

  generate_study_population_case_urti_type:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_urti_type
    needs: [matching_urti]
    outputs:
      highly_sensitive:
        cohort: output/input_case_urti_type.csv

### LRTI ###

  generate_study_population_case_lrti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_lrti
    outputs:
      highly_sensitive:
        cohort: output/input_case_lrti.csv

  generate_study_population_control_lrti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_lrti
    outputs:
      highly_sensitive:
        cohort: output/input_control_lrti.csv

  matching_lrti:
    run: python:latest python analysis/matching_lrti.py
    needs: [generate_study_population_case_lrti,generate_study_population_control_lrti]
    outputs:
      highly_sensitive: 
        table1: output/matched_cases_lrti.csv
        table2: output/matched_matches_lrti.csv
        table3: output/matched_combined_lrti.csv
      moderately_sensitive: 
        report1: output/matching_report_lrti.txt

### LRTI var ###
  generate_study_population_case_lrti_abvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_lrti_abvar
    needs: [matching_lrti]
    outputs:
      highly_sensitive:
        cohort: output/input_case_lrti_abvar.csv

  generate_study_population_control_lrti_abvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_lrti_abvar
    needs: [matching_lrti]
    outputs:
      highly_sensitive:
        cohort: output/input_control_lrti_abvar.csv

  generate_study_population_case_lrti_othvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_lrti_othvar
    needs: [matching_lrti]
    outputs:
      highly_sensitive:
        cohort: output/input_case_lrti_othvar.csv

  generate_study_population_control_lrti_othvar:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_lrti_othvar
    needs: [matching_lrti]
    outputs:
      highly_sensitive:
        cohort: output/input_control_lrti_othvar.csv

  generate_study_population_case_lrti_type:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case_lrti_type
    needs: [matching_lrti]
    outputs:
      highly_sensitive:
        cohort: output/input_case_lrti_type.csv


### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###

  case_othvar_process:
    run: r:latest analysis/casecontrol/case_othvar_process.R
    needs: [generate_study_population_case_uti_othvar,generate_study_population_case_urti_othvar,
    generate_study_population_case_lrti_othvar]
    outputs:
      highly_sensitive: 
        rds1: output/processed/input_case_*_othvar.rds

  control_othvar_process:
    run: r:latest analysis/casecontrol/control_othvar_process.R
    needs: [generate_study_population_control_uti_othvar,generate_study_population_control_urti_othvar,
    generate_study_population_control_lrti_othvar]
    outputs:
      highly_sensitive: 
        rds1: output/processed/input_control_*_othvar.rds

  case_abvar_process:
    run: r:latest analysis/casecontrol/case_abvar_process.R
    needs: [generate_study_population_case_uti_abvar,generate_study_population_case_urti_abvar,
    generate_study_population_case_lrti_abvar]
    outputs:
      highly_sensitive: 
        rds1: output/processed/input_case_*_abvar.rds

  control_abvar_process:
    run: r:latest analysis/casecontrol/control_abvar_process.R
    needs: [generate_study_population_control_uti_abvar,generate_study_population_control_urti_abvar,
    generate_study_population_control_lrti_abvar]
    outputs:
      highly_sensitive: 
        rds1: output/processed/input_control_*_abvar.rds

  model_process:
    run: r:latest analysis/casecontrol/model_process.R
    needs: [matching_uti,matching_urti,matching_lrti,case_othvar_process,control_othvar_process,case_abvar_process,control_abvar_process]
    outputs:
      highly_sensitive: 
        rds1: output/processed/model_*.rds

  model_OR:
    run: r:latest analysis/casecontrol/model_OR.R
    needs: [model_process]
    outputs:
      moderately_sensitive: 
        csv: output/*_model_result.csv

  model_table:
    run: r:latest analysis/casecontrol/model_table.R
    needs: [model_process]
    outputs:
      moderately_sensitive: 
        csv1: output/table_1_*_case.csv
        csv2: output/table_1_*_control.csv

  case_type_process:
    run: r:latest analysis/casecontrol/case_type_process.R
    needs: [generate_study_population_case_uti_type,generate_study_population_case_urti_type,
    generate_study_population_case_lrti_type,matching_uti,matching_urti,matching_lrti]
    outputs:
      highly_sensitive: 
        csv: output/mapping_*.csv

  model_table_sideeffect:
    run: r:latest analysis/casecontrol/model_table_sideeffect.R
    needs: [model_process,case_type_process]
    outputs:
      moderately_sensitive: 
        csv1: output/table_1_*_case_sideeffect.csv
        csv2: output/table_1_*_control_sideeffect.csv

  model_table_disease:
    run: r:latest analysis/casecontrol/model_table_disease.R
    needs: [model_process,case_type_process]
    outputs:
      moderately_sensitive: 
        csv1: output/table_1_*_case_disease.csv
        csv2: output/table_1_*_control_disease.csv

  table_typecheck:
    run: r:latest analysis/casecontrol/table_typecheck.R
    needs: [generate_study_population_case_uti_type,generate_study_population_case_urti_type,generate_study_population_case_lrti_type]
    outputs:
      moderately_sensitive: 
        csv1: output/table_case_*_type.csv

  model_OR_sideeffect:
    run: r:latest analysis/casecontrol/model_OR_sideeffect.R
    needs: [model_process,case_type_process]
    outputs:
      moderately_sensitive: 
        csv: output/*_model_result_sideeffect.csv

  model_OR_disease:
    run: r:latest analysis/casecontrol/model_OR_disease.R
    needs: [model_process,case_type_process]
    outputs:
      moderately_sensitive: 
        csv: output/*_model_result_disease.csv

  case_abvar_freq_process:
    run: r:latest analysis/casecontrol/case_abvar_freq_process.R
    needs: [generate_study_population_case_uti_abvar,generate_study_population_case_urti_abvar,
    generate_study_population_case_lrti_abvar]
    outputs:
      moderately_sensitive: 
        csv: output/processed/input_case_*_abvar_freq_ab.csv
      highly_sensitive: 
        rds: output/processed/input_case_*_ab.rds

  control_abvar_freq_process:
    run: r:latest analysis/casecontrol/control_abvar_freq_process.R
    needs: [generate_study_population_control_uti_abvar,generate_study_population_control_urti_abvar,
    generate_study_population_control_lrti_abvar]
    outputs:
      moderately_sensitive: 
        csv: output/processed/input_control_*_abvar_freq_ab.csv
      highly_sensitive: 
        rds: output/processed/input_control_*_ab.rds

  model_process_ab:
    run: r:latest analysis/casecontrol/model_process_ab.R
    needs: [matching_uti,matching_urti,matching_lrti,case_othvar_process,control_othvar_process,
    case_abvar_process,control_abvar_process]
    outputs:
      highly_sensitive: 
        rds1: output/processed/model_*_ab.rds

  type_uti_OR:
    run: r:latest analysis/casecontrol/type_uti_OR.R
    needs: [model_process_ab]
    outputs:
      moderately_sensitive: 
        csv: output/uti_*_OR.csv

  type_urti_OR:
    run: r:latest analysis/casecontrol/type_urti_OR.R
    needs: [model_process_ab]
    outputs:
      moderately_sensitive: 
        csv: output/urti_*_OR.csv

  type_lrti_OR:
    run: r:latest analysis/casecontrol/type_lrti_OR.R
    needs: [model_process_ab]
    outputs:
      moderately_sensitive: 
        csv: output/lrti_*_OR.csv

  type_uti_OR_disease:
    run: r:latest analysis/casecontrol/type_uti_OR_disease.R
    needs: [model_process_ab,case_type_process]
    outputs:
      moderately_sensitive: 
        csv: output/uti_*_OR_disease.csv

  type_uti_OR_sideeffect:
    run: r:latest analysis/casecontrol/type_uti_OR_sideeffect.R
    needs: [model_process_ab,case_type_process]
    outputs:
      moderately_sensitive: 
        csv: output/uti_*_OR_sideeffect.csv
