version: '3.0'

expectations:
  population_size: 1000

actions:

  study_definition_hospitalisation_rate:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_rate --index-date-range "2019-01-01 to 2022-02-01 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_hospitalisation_rate --skip-existing --output-dir=output/measures
    needs: [study_definition_hospitalisation_rate]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  generate_notebook_hospitalisation_rate:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_rate.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_rate --ExecutePreprocessor.timeout=86400
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_rate/hospitalisation_rate.html 
        figures: output/hospitalisation_rate/*

  
  # study_definition_hospitalisation_rate_hxdx:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_rate_hxdx --index-date-range "2019-01-01 to 2022-02-01 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/measures/input*.csv.gz

  # generate_measures_hxdx:
  #   run: cohortextractor:latest generate_measures --study-definition study_definition_hospitalisation_rate_hxdx --skip-existing --output-dir=output/measures
  #   needs: [study_definition_hospitalisation_rate_hxdx]
  #   outputs:
  #     moderately_sensitive:
  #       measure_csv: output/measures/measur_*.csv

  # generate_notebook_hospitalisation_rate_hxdx:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_rate_hxdx.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_rate_hxdx --ExecutePreprocessor.timeout=86400
  #   needs: [generate_measures_hxdx]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/hospitalisation_rate_hxdx/hospitalisation_rate_hxdx.html 
  #       figures: output/hospitalisation_rate_hxdx/*