version: '3.0'

expectations:
  population_size: 30000

actions:
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
### study cohort ###

  generate_study_population_period_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1
    outputs:
      highly_sensitive:
        cohort: output/input_period_1.csv

  period_1_process:
    run: r:latest analysis/period_1_process.R
    needs: [generate_study_population_period_1]
    outputs:
      highly_sensitive: 
        csv1: output/period_1a.csv
        csv2: output/period_1_*.csv

  generate_study_population_period_1b:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1b
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1b.csv

  period_1b_quickcheck:
    run: r:latest analysis/period_1b_quickcheck.R
    needs: [generate_study_population_period_1b]
    outputs:
      moderately_sensitive: 
        csv1: output/period_1b_quickcheck.csv

  generate_study_population_period_1c:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1c
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1c.csv

  generate_study_population_period_1d:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1d
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1d.csv

  generate_study_population_period_1e:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1e
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1e.csv

  generate_study_population_period_1f:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1f
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1f.csv

  generate_study_population_period_1g:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1g
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1g.csv

  generate_study_population_period_1h:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1h
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1h.csv

  generate_study_population_period_1i:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1i
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1i.csv

  generate_study_population_period_1j:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1j
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1j.csv

  generate_study_population_period_1k:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1k
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1k.csv

  generate_study_population_period_1l:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1l
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1l.csv

  generate_study_population_period_1m:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1m
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1m.csv

  generate_study_population_period_1n:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1n
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1n.csv

  generate_study_population_period_1o:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1o
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1o.csv

  generate_study_population_period_1p:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1p
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1p.csv

  generate_study_population_period_1q:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1q
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1q.csv

  generate_study_population_period_1r:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1r
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1r.csv

  generate_study_population_period_1s:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1s
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1s.csv

  generate_study_population_period_1t:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1t
    needs: [period_1_process]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1t.csv

  period_1a_id:
    run: r:latest analysis/period_1a_id.R
    needs: [generate_study_population_period_1]
    outputs:
      highly_sensitive: 
        csv1: output/period_1a_id.csv

  generate_study_population_period_1a:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_period_1a
    needs: [period_1a_id]
    outputs:
      highly_sensitive:
        cohort: output/input_period_1a.csv

  process_cox_dataset:
    run: r:latest analysis/process_cox_dataset.R
    needs: [generate_study_population_period_1a,generate_study_population_period_1b,generate_study_population_period_1c,generate_study_population_period_1d,
    generate_study_population_period_1e,generate_study_population_period_1f,generate_study_population_period_1g,generate_study_population_period_1h,
    generate_study_population_period_1i,generate_study_population_period_1j,generate_study_population_period_1k,generate_study_population_period_1l,
    generate_study_population_period_1m,generate_study_population_period_1n,generate_study_population_period_1o,generate_study_population_period_1p,
    generate_study_population_period_1q,generate_study_population_period_1r,generate_study_population_period_1s,generate_study_population_period_1t]
    outputs:
      highly_sensitive: 
        rds: output/processed_data.rds

  process_kaplan_meier_plot:
    run: r:latest analysis/prediction/kaplan_meier_plot.R
    needs: [process_cox_dataset]
    outputs:
      moderately_sensitive: 
        plot1: output/KM_overall_with_CI.jpeg
        csv1: output/surv_df.csv

  process_kaplan_meier_plot_by_infection:
    run: r:latest analysis/prediction/kaplan_meier_plot_by_infection.R
    needs: [process_cox_dataset]
    outputs:
      moderately_sensitive: 
        plot1: output/KM_by_*_with_CI.jpeg
