version: '3.0'

expectations:
  population_size: 200000

actions:

  generate_study_population_hospitalisation_urti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_urti --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_urti.csv.gz

  generate_study_population_hospitalisation_lrti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_lrti --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_lrti.csv.gz

  generate_study_population_hospitalisation_uti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_uti --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_uti.csv.gz

  generate_study_population_hospitalisation_sinusitis:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_sinusitis --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_sinusitis.csv.gz

  generate_study_population_hospitalisation_ot_externa:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_ot_externa --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_ot_externa.csv.gz

  generate_study_population_hospitalisation_otmedia:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_otmedia --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_otmedia.csv.gz

  generate_study_population_hospitalisation_cough:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_cough --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_cough.csv.gz

  generate_study_population_hospitalisation_cough_cold:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_cough_cold --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_cough_cold.csv.gz

  generate_study_population_hospitalisation_throat:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_throat --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_throat.csv.gz

  generate_notebook_hospitalisation_prediction_urti:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_urti.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_urti --ExecutePreprocessor.timeout=86400
    needs: [generate_study_population_hospitalisation_urti]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_urti/hospitalisation_prediction_urti.html 
        figures: output/hospitalisation_prediction_urti/*

  generate_notebook_hospitalisation_prediction_lrti:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_lrti.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_lrti --ExecutePreprocessor.timeout=86400
    needs: [generate_study_population_hospitalisation_lrti]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_lrti/hospitalisation_prediction_lrti.html 
        figures: output/hospitalisation_prediction_lrti/*

  generate_notebook_hospitalisation_prediction_uti:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_uti.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_uti --ExecutePreprocessor.timeout=86400
    needs: [generate_study_population_hospitalisation_uti]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_uti/hospitalisation_prediction_uti.html 
        figures: output/hospitalisation_prediction_uti/*

  generate_notebook_hospitalisation_prediction_sinusitis:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_sinusitis.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_sinusitis --ExecutePreprocessor.timeout=86400
    needs: [generate_study_population_hospitalisation_sinusitis]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_sinusitis/hospitalisation_prediction_sinusitis.html 
        figures: output/hospitalisation_prediction_sinusitis/*

  generate_notebook_hospitalisation_prediction_ot_externa:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_ot_externa.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_ot_externa --ExecutePreprocessor.timeout=86400
    needs: [generate_study_population_hospitalisation_ot_externa]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_ot_externa/hospitalisation_prediction_ot_externa.html 
        figures: output/hospitalisation_prediction_ot_externa/*

  generate_notebook_hospitalisation_prediction_otmedia:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_otmedia.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_otmedia --ExecutePreprocessor.timeout=86400
    needs: [generate_study_population_hospitalisation_otmedia]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_otmedia/hospitalisation_prediction_otmedia.html 
        figures: output/hospitalisation_prediction_otmedia/*

  generate_notebook_hospitalisation_prediction_cough:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_cough.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_cough --ExecutePreprocessor.timeout=86400
    needs: [generate_study_population_hospitalisation_cough]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_cough/hospitalisation_prediction_cough.html 
        figures: output/hospitalisation_prediction_cough/*

  generate_notebook_hospitalisation_prediction_cough_cold:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_cough_cold.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_cough_cold --ExecutePreprocessor.timeout=86400
    needs: [generate_study_population_hospitalisation_cough_cold]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_cough_cold/hospitalisation_prediction_cough_cold.html 
        figures: output/hospitalisation_prediction_cough_cold/*

  generate_notebook_hospitalisation_prediction_throat:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_throat.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_throat --ExecutePreprocessor.timeout=86400
    needs: [generate_study_population_hospitalisation_throat]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_throat/hospitalisation_prediction_throat.html 
        figures: output/hospitalisation_prediction_throat/* 

  generate_notebook_hospitalisation_prediction_urti_combined:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_urti_combined.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_urti_combined --ExecutePreprocessor.timeout=86400
    needs: [generate_study_population_hospitalisation_urti, generate_study_population_hospitalisation_cough, generate_study_population_hospitalisation_cough_cold, generate_study_population_hospitalisation_throat]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_urti_combined/hospitalisation_prediction_urti_combined.html 
        figures: output/hospitalisation_prediction_urti_combined/* 

  generate_notebook_hosp_plots:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hosp_plots.ipynb --execute --to html --output-dir=/workspace/output/hosp_plots --ExecutePreprocessor.timeout=86400
    needs: [generate_notebook_hospitalisation_prediction_urti_combined,generate_notebook_hospitalisation_prediction_urti,generate_notebook_hospitalisation_prediction_lrti,generate_notebook_hospitalisation_prediction_uti,generate_notebook_hospitalisation_prediction_sinusitis,generate_notebook_hospitalisation_prediction_otmedia,generate_notebook_hospitalisation_prediction_ot_externa, generate_notebook_hospitalisation_prediction_cough, generate_notebook_hospitalisation_prediction_cough_cold, generate_notebook_hospitalisation_prediction_throat]
    outputs:
      moderately_sensitive:
        notebook: output/hosp_plots/hosp_plots.html 
        figures: output/hosp_plots/*

  generate_notebook_aggregate_table:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/aggregate_baseline_table.ipynb --execute --to html --output-dir=/workspace/output/aggregate_tables --ExecutePreprocessor.timeout=86400
    needs: [generate_notebook_hospitalisation_prediction_urti_combined,generate_notebook_hospitalisation_prediction_urti,generate_notebook_hospitalisation_prediction_lrti,generate_notebook_hospitalisation_prediction_uti,generate_notebook_hospitalisation_prediction_sinusitis,generate_notebook_hospitalisation_prediction_otmedia,generate_notebook_hospitalisation_prediction_ot_externa, generate_notebook_hospitalisation_prediction_cough, generate_notebook_hospitalisation_prediction_cough_cold, generate_notebook_hospitalisation_prediction_throat]    
    outputs:
      moderately_sensitive:
        notebook: output/aggregate_tables/aggregate_baseline_table.html 
        figures: output/aggregate_tables/*

  generate_notebook_aggregate_hosp_table:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/aggregate_hosp_table.ipynb --execute --to html --output-dir=/workspace/output/aggregate_hosp_table --ExecutePreprocessor.timeout=86400
    needs: [generate_notebook_hospitalisation_prediction_urti_combined,generate_notebook_hospitalisation_prediction_urti,generate_notebook_hospitalisation_prediction_lrti,generate_notebook_hospitalisation_prediction_uti,generate_notebook_hospitalisation_prediction_sinusitis,generate_notebook_hospitalisation_prediction_otmedia,generate_notebook_hospitalisation_prediction_ot_externa, generate_notebook_hospitalisation_prediction_cough, generate_notebook_hospitalisation_prediction_cough_cold, generate_notebook_hospitalisation_prediction_throat]
    outputs:
      moderately_sensitive:
        notebook: output/aggregate_hosp_table/aggregate_hosp_table.html 
        figures: output/aggregate_hosp_table/*

  generate_notebook_aggregate_cox_hrs_betas:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/aggregate_cox_hrs_betas.ipynb --execute --to html --output-dir=/workspace/output/aggregate_hrs_betas --ExecutePreprocessor.timeout=86400
    needs: [generate_notebook_hospitalisation_prediction_urti_combined,generate_notebook_hospitalisation_prediction_urti,generate_notebook_hospitalisation_prediction_lrti,generate_notebook_hospitalisation_prediction_uti,generate_notebook_hospitalisation_prediction_sinusitis,generate_notebook_hospitalisation_prediction_otmedia,generate_notebook_hospitalisation_prediction_ot_externa, generate_notebook_hospitalisation_prediction_cough, generate_notebook_hospitalisation_prediction_cough_cold, generate_notebook_hospitalisation_prediction_throat]
    outputs:
      moderately_sensitive:
        notebook: output/aggregate_hrs_betas/aggregate_cox_hrs_betas.html 
        figures: output/aggregate_hrs_betas/*

  generate_notebook_aggregate_cox_hrs_antibiotics:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/aggregate_cox_hrs_antibiotics.ipynb --execute --to html --output-dir=/workspace/output/aggregate_hrs_antibiotics --ExecutePreprocessor.timeout=86400
    needs: [generate_notebook_hospitalisation_prediction_urti_combined,generate_notebook_hospitalisation_prediction_urti,generate_notebook_hospitalisation_prediction_lrti,generate_notebook_hospitalisation_prediction_uti,generate_notebook_hospitalisation_prediction_sinusitis,generate_notebook_hospitalisation_prediction_otmedia,generate_notebook_hospitalisation_prediction_ot_externa, generate_notebook_hospitalisation_prediction_cough, generate_notebook_hospitalisation_prediction_cough_cold, generate_notebook_hospitalisation_prediction_throat]
    outputs:
      moderately_sensitive:
        notebook: output/aggregate_hrs_antibiotics/aggregate_cox_hrs_antibiotics.html 
        figures: output/aggregate_hrs_antibiotics/*

  generate_notebook_aggregate_cox_cis:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/aggregate_cox_cis.ipynb --execute --to html --output-dir=/workspace/output/aggregate_cox_cis --ExecutePreprocessor.timeout=86400
    needs: [generate_notebook_hospitalisation_prediction_urti_combined,generate_notebook_hospitalisation_prediction_urti,generate_notebook_hospitalisation_prediction_lrti,generate_notebook_hospitalisation_prediction_uti,generate_notebook_hospitalisation_prediction_sinusitis,generate_notebook_hospitalisation_prediction_otmedia,generate_notebook_hospitalisation_prediction_ot_externa, generate_notebook_hospitalisation_prediction_cough, generate_notebook_hospitalisation_prediction_cough_cold, generate_notebook_hospitalisation_prediction_throat]
    outputs:
      moderately_sensitive:
        notebook: output/aggregate_cox_cis/aggregate_cox_cis.html 
        figures: output/aggregate_cox_cis/*

  generate_notebook_aggregate_ab_prob:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/aggregate_ab_prob.ipynb --execute --to html --output-dir=/workspace/output/aggregate_ab_prob --ExecutePreprocessor.timeout=86400
    needs: [generate_notebook_hospitalisation_prediction_urti_combined,generate_notebook_hospitalisation_prediction_urti,generate_notebook_hospitalisation_prediction_lrti,generate_notebook_hospitalisation_prediction_uti,generate_notebook_hospitalisation_prediction_sinusitis,generate_notebook_hospitalisation_prediction_otmedia,generate_notebook_hospitalisation_prediction_ot_externa, generate_notebook_hospitalisation_prediction_cough, generate_notebook_hospitalisation_prediction_cough_cold, generate_notebook_hospitalisation_prediction_throat]
    outputs:
      moderately_sensitive:
        notebook: output/aggregate_ab_prob/aggregate_ab_prob_plots.html 
        figures: output/aggregate_ab_prob/*