version: '3.0'

expectations:
  population_size: 1000

actions:

  study_definition_hospitalisation_rate:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_rate --index-date-range "2019-01-01 to 2022-02-01 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_hospitalisation_rate --skip-existing --output-dir=output/measures
    needs: [study_definition_hospitalisation_rate]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv