version: '3.0'

expectations:
  population_size: 200000

actions:

  generate_study_population_hospitalisation_urti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_urti --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_urti.csv.gz

  generate_study_population_hospitalisation_lrti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_lrti --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_lrti.csv.gz

  generate_study_population_hospitalisation_uti:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_uti --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_uti.csv.gz

  generate_study_population_hospitalisation_sinusitis:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_sinusitis --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_sinusitis.csv.gz

  generate_study_population_hospitalisation_ot_externa:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_ot_externa --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_ot_externa.csv.gz

  generate_study_population_hospitalisation_otmedia:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_otmedia --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_otmedia.csv.gz

  generate_study_population_hospitalisation_pneumonia:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_pneumonia --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_pneumonia.csv.gz

  generate_study_population_hospitalisation_throat:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_throat --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_throat.csv.gz

  generate_study_population_hospitalisation_cough:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_cough --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_cough.csv.gz

  generate_study_population_hospitalisation_cough_cold:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospitalisation_cough_cold --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/hospitalisation_data/input_hospitalisation_cough_cold.csv.gz

  generate_notebook_hospitalisation_prediction_urti:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_urti.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_urti --ExecutePreprocessor.timeout=86400
    # needs: [generate_study_population_hospitalisation_urti,generate_study_population_bmi]
    needs: [generate_study_population_hospitalisation_urti]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_urti/hospitalisation_prediction_urti.html 
        figures: output/hospitalisation_prediction_urti/*

  generate_notebook_hospitalisation_prediction_lrti:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_lrti.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_lrti --ExecutePreprocessor.timeout=86400
    # needs: [generate_study_population_hospitalisation_lrti,generate_study_population_bmi]
    needs: [generate_study_population_hospitalisation_lrti]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_lrti/hospitalisation_prediction_lrti.html 
        figures: output/hospitalisation_prediction_lrti/*

  generate_notebook_hospitalisation_prediction_uti:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_uti.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_uti --ExecutePreprocessor.timeout=86400
    # needs: [generate_study_population_hospitalisation_uti,generate_study_population_bmi]
    needs: [generate_study_population_hospitalisation_uti]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_uti/hospitalisation_prediction_uti.html 
        figures: output/hospitalisation_prediction_uti/*

  generate_notebook_hospitalisation_prediction_sinusitis:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_sinusitis.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_sinusitis --ExecutePreprocessor.timeout=86400
    # needs: [generate_study_population_hospitalisation_sinusitis,generate_study_population_bmi]
    needs: [generate_study_population_hospitalisation_sinusitis]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_sinusitis/hospitalisation_prediction_sinusitis.html 
        figures: output/hospitalisation_prediction_sinusitis/*

  generate_notebook_hospitalisation_prediction_ot_externa:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_ot_externa.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_ot_externa --ExecutePreprocessor.timeout=86400
    # needs: [generate_study_population_hospitalisation_ot_externa,generate_study_population_bmi]
    needs: [generate_study_population_hospitalisation_ot_externa]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_ot_externa/hospitalisation_prediction_ot_externa.html 
        figures: output/hospitalisation_prediction_ot_externa/*

  generate_notebook_hospitalisation_prediction_otmedia:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hospitalisation_prediction_otmedia.ipynb --execute --to html --output-dir=/workspace/output/hospitalisation_prediction_otmedia --ExecutePreprocessor.timeout=86400
    # needs: [generate_study_population_hospitalisation_otmedia,generate_study_population_bmi]
    needs: [generate_study_population_hospitalisation_otmedia]
    outputs:
      moderately_sensitive:
        notebook: output/hospitalisation_prediction_otmedia/hospitalisation_prediction_otmedia.html 
        figures: output/hospitalisation_prediction_otmedia/*

  generate_notebook_hosp_plots:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/hosp_plots.ipynb --execute --to html --output-dir=/workspace/output/hosp_plots --ExecutePreprocessor.timeout=86400
    needs: [generate_notebook_hospitalisation_prediction_urti,generate_notebook_hospitalisation_prediction_lrti,generate_notebook_hospitalisation_prediction_uti,generate_notebook_hospitalisation_prediction_sinusitis,generate_notebook_hospitalisation_prediction_otmedia,generate_notebook_hospitalisation_prediction_ot_externa]
    outputs:
      moderately_sensitive:
        notebook: output/hosp_plots/hosp_plots.html 
        figures: output/hosp_plots/*

  generate_notebook_combining_outputs:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/combining_outputs.ipynb --execute --to html --output-dir=/workspace/output/cox_outputs --ExecutePreprocessor.timeout=86400
    needs: [generate_notebook_hospitalisation_prediction_urti,generate_notebook_hospitalisation_prediction_lrti,generate_notebook_hospitalisation_prediction_uti,generate_notebook_hospitalisation_prediction_sinusitis,generate_notebook_hospitalisation_prediction_otmedia,generate_notebook_hospitalisation_prediction_ot_externa]
    outputs:
      moderately_sensitive:
        notebook: output/cox_outputs/combining_outputs.html 
        figures: output/cox_outputs/*