version: '3.0'

expectations:
  population_size: 30000

actions:

### study cohort ###
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_study_population_ae:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ae --index-date-range "2019-01-01 to 2023-03-31 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_ae_*.csv.gz

  generate_measures_ae:
    run: cohortextractor:latest generate_measures --study-definition study_definition_ae --skip-existing --output-dir=output/measures
    needs: [generate_study_population_ae]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  ae_rate_table:  
    run: r:latest analysis/figure/ae_rate.R
    needs: [generate_measures_ae]
    outputs:
      moderately_sensitive:
        table1: output/ae_rate_table.csv
        table2: output/ae_rate_forplot.csv
        plot1: output/figure_ae_rate.jpeg

  infection_table:  
    run: r:latest analysis/figure/infection_table.R
    needs: [generate_measures_ae]
    outputs:
      moderately_sensitive:
        table1: output/infection_table.csv
        table2: output/infection_forplot.csv
        plot1: output/figure_infection.jpeg

  generate_study_population_2ae:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2ae --index-date-range "2019-01-01 to 2023-03-31 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_2ae_*.csv.gz

  generate_measures_2ae:
    run: cohortextractor:latest generate_measures --study-definition study_definition_2ae --skip-existing --output-dir=output/measures
    needs: [generate_study_population_2ae]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_2ae_*.csv

  ae_rate_42days_table:  
    run: r:latest analysis/figure/ae_rate_42days.R
    needs: [generate_measures_2ae]
    outputs:
      moderately_sensitive:
        table1: output/ae_rate_42days_table.csv
        table2: output/ae_rate_42days_forplot.csv
        plot1: output/figure_ae_42days_rate.jpeg

  ae_rate_42days_nocovid_table:  
    run: r:latest analysis/figure/ae_rate_42days_nocovid.R
    needs: [generate_measures_2ae]
    outputs:
      moderately_sensitive:
        table1: output/ae_rate_42days_nocovid_table.csv
        table2: output/ae_rate_42days_nocovid_forplot.csv
        plot1: output/figure_ae_42days_nocovid_rate.jpeg

###########################################################################
##########                      case control                      #########
###########################################################################
### study cohort ###
  generate_study_population_case:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_case
    outputs:
      highly_sensitive:
        cohort: output/input_case.csv

  generate_study_population_control_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control_1
    outputs:
      highly_sensitive:
        cohort: output/input_control_1.csv

  process_1:  
    run: r:latest analysis/casecontrol/process_1.R
    needs: [generate_study_population_case,generate_study_population_control_1]
    outputs:
      highly_sensitive:
        table1: output/case_1_uti.csv
        table2: output/case_1_lrti.csv
        table3: output/case_1_urti.csv
        table4: output/case_1_sinusitis.csv
        table5: output/case_1_ot_externa.csv
        table6: output/case_1_ot_media.csv
        table7: output/case_1_pneumonia.csv
        table8: output/control_1_uti.csv
        table9: output/control_1_lrti.csv
        table10: output/control_1_urti.csv
        table11: output/control_1_sinusitis.csv
        table12: output/control_1_ot_externa.csv
        table13: output/control_1_ot_media.csv
        table14: output/control_1_pneumonia.csv


  matching_1:
    run: python:latest python analysis/matching_1.py
    needs: [process_1]
    outputs:
      highly_sensitive: 
        table1: output/matched_cases_1_uti.csv
        table2: output/matched_matches_1_uti.csv
        table3: output/matched_combined_1_uti.csv
      moderately_sensitive: 
        report1: output/matching_report_1_uti.txt
