---
title: "ITS - coded antibiotics % "
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = '/workspace')
```

# incident AB prescribing

```{r message=FALSE}
library("ggplot2")
library("data.table")
library("dplyr")
library("tidyverse")
library("MASS")
#library(modelsummary)
#library("gtsummary")
```

```{r message=FALSE}
# Import data
#df=read.csv("/Users/yayang/Documents/GitHub/amr-uom-brit/output/ab_recorded_incident.csv")
df = read.csv(here::here("output","ab_recorded_incident.csv"))

# seasons
df$date=as.Date(df$date)
df$month= format(df$date,"%m")
df=df%>% mutate(season= case_when( month=="03"|month=="04"|month=="05" ~ "spring",
                                   month=="06"|month=="07"|month=="08" ~ "summer",
                                   month=="09"|month=="10"|month=="11" ~ "autumn",
                                   month=="12"|month=="01"|month=="02" ~ "winter"))
df$season=relevel(as.factor(df$season),ref="spring")

# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))

# define covid date
breaks <- c(as.Date("2019-01-01"),as.Date("2019-12-31"),# 1=pre-covid, 2=exclusion
            as.Date("2020-04-01"), as.Date("2021-12-31"),# 3= covid time
            max(df$date)) # NA exclusion

df=df%>%mutate(covid=cut(date,breaks,labels = 1:4))

df=df%>% filter(covid==1 | covid==3)
df$covid= recode(df$covid, '1'="0", '3'="1") # precovid=0, covid=1
df$covid <- factor(df$covid, levels=c("0","1"))

# time sequence after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)

```


```{r}
# split data
df0=df%>%filter(infection=="Uncoded")
df1=df%>%filter(infection=="UTI")
df2=df%>%filter(infection=="URTI")
df3=df%>%filter(infection=="LRTI")
df4=df%>%filter(infection=="Sinusitis")
df5=df%>%filter(infection=="Otitis_externa")
df6=df%>%filter(infection=="Otitis_media")
df7=df%>%filter(infection=="Other_infection")

```


```{r}
# 0. uncoded
m0.1 <- glm.nb(value~  covid + season + times + time.since  , data = df0)

# 1.  UTI
m1.1 <- glm.nb(value~ covid + season + times + time.since  , data = df1)

# 2.  URTI
m2.1 <- glm.nb(value~ covid + season + times + time.since  , data = df2)

# 3.  LRTI
m3.1 <- glm.nb(value~ covid + season + times + time.since  , data = df3)

# 4.  sinusitis
m4.1 <- glm.nb(value~ covid + season + times + time.since  , data = df4)

# 5.  Otitis_externa
m5.1 <- glm.nb(value~ covid + season + times + time.since  , data = df5)

# 6.  Otitis_media
m6.1 <- glm.nb(value~ covid + season + times + time.since  , data = df6)

# 7.  Other_infection
m7.1 <- glm.nb(value~ covid + season + times + time.since  , data = df7)

```

## result- IRR

```{r message=FALSE}
### confidence intervals for the coefficients
(est0.1 <- cbind(Estimate = coef(m0.1), confint(m0.1)))
(est1.1 <- cbind(Estimate = coef(m1.1), confint(m1.1)))
(est2.1 <- cbind(Estimate = coef(m2.1), confint(m2.1)))
(est3.1 <- cbind(Estimate = coef(m3.1), confint(m3.1)))
(est4.1 <- cbind(Estimate = coef(m4.1), confint(m4.1)))
(est5.1 <- cbind(Estimate = coef(m5.1), confint(m5.1)))
(est6.1 <- cbind(Estimate = coef(m6.1), confint(m6.1)))
(est7.1 <- cbind(Estimate = coef(m7.1), confint(m7.1)))
### IRR
exp0.1=exp(est0.1)
exp1.1=exp(est1.1)
exp2.1=exp(est2.1)
exp3.1=exp(est3.1)
exp4.1=exp(est4.1)
exp5.1=exp(est5.1)
exp6.1=exp(est6.1)
exp7.1=exp(est7.1)

```

```{r message=FALSE}
## combine results
# covid
DF=bind_rows(exp0.1[2,],exp1.1[2,],exp2.1[2,],exp3.1[2,],exp4.1[2,],exp5.1[2,],exp6.1[2,],exp7.1[2,])
DF$Infection=c("Uncoded","UTI","URTI","LRTI","Sinusitis","Otitis_externa","Otitis_media","Other_indication")
#reorder
DF$Infection=factor(DF$Infection,levels = c("Uncoded","UTI","URTI","LRTI","Sinusitis","Otitis_externa","Otitis_media","Other_indication"))

names(DF)[1]="IRR"
names(DF)[2]="ci_l"
names(DF)[3]="ci_u"

DF1.exp=DF
DF1.exp
```


## result- ITS Plot

Incident antibiotics prescriptions without infection codes
```{r}

df0 <- cbind(df0, "resp" = predict(m0.1, type = "response", se.fit = TRUE)[1:2])#select fit & se.fit

ggplot(df0, aes(x=date, y=value, group=covid)) + 
 theme_bw()+
  annotate(geom = "rect", xmin = as.Date("2019-12-01"),xmax = as.Date("2020-04-01"),ymin = -Inf, ymax = Inf,fill="grey60", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-04-01"),xmax = as.Date("2021-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_point(shape=4)+
# geom_line(aes(y=fit*1000/population),color="grey")+
# geom_ribbon(aes(ymin=(fit-1.96*se.fit)/population, ymax=(fit+1.96*se.fit)/population),alpha=0.2,fill="black") +
 geom_smooth(color="black",se = FALSE)+
  
 scale_x_date(date_breaks = "1 month",date_labels =  "%Y-%m")+
  theme(axis.text.x = element_text(angle = 60,hjust=1),
        legend.position = "bottom",legend.title =element_blank())+
  labs(
    title = "",

    x = "", 
    y = "Percentage")

```


Incident antibiotics prescriptions with UTI codes
```{r}

df1 <- cbind(df1, "resp" = predict(m1.1, type = "response", se.fit = TRUE)[1:2])#select fit & se.fit

ggplot(df1, aes(x=date, y=value, group=covid)) + 
 theme_bw()+
  annotate(geom = "rect", xmin = as.Date("2019-12-01"),xmax = as.Date("2020-04-01"),ymin = -Inf, ymax = Inf,fill="grey60", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-04-01"),xmax = as.Date("2021-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_point(shape=4)+
# geom_line(aes(y=fit*1000/population),color="grey")+
# geom_ribbon(aes(ymin=(fit-1.96*se.fit)/population, ymax=(fit+1.96*se.fit)/population),alpha=0.2,fill="black") +
 geom_smooth(color="black",se = FALSE)+
  
 scale_x_date(date_breaks = "1 month",date_labels =  "%Y-%m")+
  theme(axis.text.x = element_text(angle = 60,hjust=1),
        legend.position = "bottom",legend.title =element_blank())+
  labs(
    title = "",

    x = "", 
    y = "Percentage")

```
