---
title: "Baseline_table_overall"
author: "Billy Z"
date: "05/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/workspace')
```



```{r include=FALSE}
library("tidyverse") 
library('dplyr')
library('lubridate')
library('stringr')
library("data.table")
library("ggpubr")
library("finalfit")
```

### Import data

#### 01.  extracted variables from "model_variable_broad_2020"

```{r include=FALSE}

df19_1 = read_rds(here::here("output","measures","model_variable_broad_2019_1.rds"))

df19_2 = read_rds(here::here("output","measures","model_variable_broad_2019_2.rds"))
df19_2=df19_2%>% dplyr::select(charlsonGrp,patient_id,date)

df19 <- merge(df19_1,df19_2,by=c('patient_id','date'))
rm(df19_1,df19_2)

df20_1 = read_rds(here::here("output","measures","model_variable_broad_2020_1.rds"))

df20_2 = read_rds(here::here("output","measures","model_variable_broad_2020_2.rds"))
df20_2=df20_2%>% dplyr::select(charlsonGrp,patient_id,date)

df20 <- merge(df20_1,df20_2,by=c('patient_id','date'))
rm(df20_1,df20_2)

df21_1 = read_rds(here::here("output","measures","model_variable_broad_2021_1.rds"))

df21_2 = read_rds(here::here("output","measures","model_variable_broad_2021_2.rds"))
df21_2=df21_2%>% dplyr::select(charlsonGrp,patient_id,date)

df21 <- merge(df21_1,df21_2,by=c('patient_id','date'))
rm(df21_1,df21_2)

df22_1 = read_rds(here::here("output","measures","model_variable_broad_2022_1.rds"))

df22_2 = read_rds(here::here("output","measures","model_variable_broad_2022_2.rds"))
df22_2=df22_2%>% dplyr::select(charlsonGrp,patient_id,date)

df22 <- merge(df22_1,df22_2,by=c('patient_id','date'))
rm(df22_1,df22_2)

last.date=max(df22$date)
df22=df22%>% filter(date!=last.date)

dat=bind_rows(df19,df20,df21,df22)
rm(df19,df20,df21,df22)

```

##Overall count

```{r echo=FALSE}

first_mon <- (format(min(dat$date), "%m-%Y"))
last_mon <- (format(max(dat$date), "%m-%Y"))
num_pats <- length(unique(dat$patient_id))
num_pracs <- length(unique(dat$practice))

overall_counts <- as.data.frame(cbind(first_mon, last_mon, num_pats, num_pracs))
overall_counts
rm(overall_counts) 

```

##Baseline table after randomly select one observation for each patient 

```{r echo=FALSE}

df_one_pat <- dat %>% dplyr::group_by(patient_id) %>%
  dplyr::arrange(date, .group_by=TRUE) %>%
  sample_n(1)

rm(dat)  

# columns for baseline table
colsfortab <- colnames(df_one_pat)
df_one_pat %>% summary_factorlist(explanatory = colsfortab) -> t
t

```


