---
title: "COVID impac on broad_spectrum prescribing proportion_2"
author: "Billy Z"
date: "04/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/workspace')
```


```{r message=FALSE}
library("ggplot2")
library("data.table")
library("dplyr")
library("tidyverse")
```


### Import data

#### 01.  extracted variables from "model_variable_broad_2020"

```{r include=FALSE}
df20_1 = read_rds(here::here("output","measures","model_variable_broad_2020_1.rds"))
df20_1=df20_1%>% dplyr::select( date, patient_id, practice, age_cat,
                            ethnicity_6, flu_vaccine, imd, antibacterial_12mb4, gp_count)

df20_2 = read_rds(here::here("output","measures","model_variable_broad_2020_2.rds"))
df20_2=df20_2%>% dplyr::select(charlson_score,patient_id,date)

df20_ab = read_rds(here::here("output","measures","recorded_ab_broad_2020.rds"))
df20_ab=dplyr::bind_rows(df20_ab)

# recode empty value
df20_ab$infection=ifelse(df20_ab$infection=="","uncoded",df20_ab$infection)
df20_ab$infection=df20_ab$infection %>% replace_na("uncoded")
  
# recode
df20_ab$infection=recode(df20_ab$infection,
                       asthma ="Other_infection",
                       cold="Other_infection",
                       cough="Other_infection",
                       copd="Other_infection",
                       pneumonia="Other_infection",
                       renal="Other_infection",
                       sepsis="Other_infection",
                       throat="Other_infection",
                       uti = "UTI",
                       lrti = "LRTI",
                       urti = "URTI",
                       sinusits = "Sinusitis",
                       otmedia = "Otitis_media",
                       ot_externa = "Otitis_externa",
                       uncoded = "Uncoded")
  
# recode empty value
df20_ab$infection=ifelse(df20_ab$infection=="","uncoded",df20_ab$infection)

df1 <- merge(df20_ab,df20_2,by=c('patient_id','date'))
rm(df20_ab,df20_2)
df1 <- merge(df1,df20_1,by=c('patient_id','date'))
rm(df20_1)

```


#### 02.  extracted variables from "model_variable_broad_2021"

```{r include=FALSE}

df21_1 = read_rds(here::here("output","measures","model_variable_broad_2021_1.rds"))
df21_1=df21_1%>% dplyr::select( date, patient_id, practice, age_cat,
                            ethnicity_6, flu_vaccine, imd, antibacterial_12mb4, gp_count)

df21_2 = read_rds(here::here("output","measures","model_variable_broad_2021_2.rds"))
df21_2=df21_2%>% dplyr::select(charlson_score,patient_id,date)

df21_ab = read_rds(here::here("output","measures","recorded_ab_broad_2021.rds"))
df21_ab=dplyr::bind_rows(df21_ab)

# recode empty value
df21_ab$infection=ifelse(df21_ab$infection=="","uncoded",df21_ab$infection)
df21_ab$infection=df21_ab$infection %>% replace_na("uncoded")
  
# recode
df21_ab$infection=recode(df21_ab$infection,
                       asthma ="Other_infection",
                       cold="Other_infection",
                       cough="Other_infection",
                       copd="Other_infection",
                       pneumonia="Other_infection",
                       renal="Other_infection",
                       sepsis="Other_infection",
                       throat="Other_infection",
                       uti = "UTI",
                       lrti = "LRTI",
                       urti = "URTI",
                       sinusits = "Sinusitis",
                       otmedia = "Otitis_media",
                       ot_externa = "Otitis_externa",
                       uncoded = "Uncoded")
  
# recode empty value
df21_ab$infection=ifelse(df21_ab$infection=="","uncoded",df21_ab$infection)

df2 <- merge(df21_ab,df21_2,by=c('patient_id','date'))
rm(df21_ab,df21_2)
df2 <- merge(df2,df21_1,by=c('patient_id','date'))
rm(df21_1)

```


#### 02.  extracted variables from "model_variable_broad_2022"

```{r include=FALSE}

df22_1 = read_rds(here::here("output","measures","model_variable_broad_2022_1.rds"))
df22_1=df22_1%>% dplyr::select( date, patient_id, practice, age_cat,
                            ethnicity_6, flu_vaccine, imd, antibacterial_12mb4, gp_count)

df22_2 = read_rds(here::here("output","measures","model_variable_broad_2022_2.rds"))
df22_2=df22_2%>% dplyr::select(charlson_score,patient_id,date)

df22_ab = read_rds(here::here("output","measures","recorded_ab_broad_2022.rds"))
df22_ab=dplyr::bind_rows(df22_ab)

# recode empty value
df22_ab$infection=ifelse(df22_ab$infection=="","uncoded",df22_ab$infection)
df22_ab$infection=df22_ab$infection %>% replace_na("uncoded")
  
# recode
df22_ab$infection=recode(df22_ab$infection,
                       asthma ="Other_infection",
                       cold="Other_infection",
                       cough="Other_infection",
                       copd="Other_infection",
                       pneumonia="Other_infection",
                       renal="Other_infection",
                       sepsis="Other_infection",
                       throat="Other_infection",
                       uti = "UTI",
                       lrti = "LRTI",
                       urti = "URTI",
                       sinusits = "Sinusitis",
                       otmedia = "Otitis_media",
                       ot_externa = "Otitis_externa",
                       uncoded = "Uncoded")
  
# recode empty value
df22_ab$infection=ifelse(df22_ab$infection=="","uncoded",df22_ab$infection)

df3 <- merge(df22_ab,df22_2,by=c('patient_id','date'))
rm(df22_ab,df22_2)
df3 <- merge(df3,df22_1,by=c('patient_id','date'))
rm(df22_1)

```



## Link data


```{r include=FALSE}

dat=bind_rows(df1,df2,df3)
rm(df1,df2,df3)

dat$age_cat <- factor(dat$age_cat, levels=c("0-4", "5-14","15-24","25-34","35-44","45-54","55-64","65-74","75+"))
dat$infection <- factor(dat$infection, levels=c("LRTI","Otitis_externa","Otitis_media","Sinusitis","URTI","UTI","Other_infection","Uncoded"))

last.date=max(dat$date)
first.date=min(dat$date)
dat=dat%>% filter(date != last.date)
dat=dat%>% filter(date != first.date)
first.date=min(dat$date)
dat=dat%>% filter(date != first.date)
first.date=min(dat$date)
dat=dat%>% filter(date != first.date)
first.date=min(dat$date)
first_mon=format(min(dat$date),"%m-%Y")
last_mon= format(max(dat$date),"%m-%Y")


```


# Description of data

```{r echo=TRUE}
df_broad <- dat %>% select(patient_id, date, prevalent, infection, broad_spectrum, practice, age_cat, sex)
df_broad_count <- df_broad %>%filter(broad_spectrum==1) %>%  group_by(date,prevalent) %>% summarise(count=n())
df_broad_count$prevalent=recode(df_broad_count$prevalent,
                       "1" ="prevalent",
                       "0" = "incident")
# Plot
df_broad_count %>%
  ggplot( aes(x=date, y=count, group=prevalent, color=prevalent)) +
    geom_line() +
    theme(axis.text.x=element_text(angle=60,hjust=1))+
    scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month")+
    ggtitle("Broad-spectrum antibiotics prescription changes in time") +
    ylab("Broad-spectrum antibiotics prescription")

```


### Logistic regression analysis
model 1
```{r echo=TRUE}
m1 <- glm(broad_spectrum ~ age_cat + sex, family = binomial(link = "logit"),data = df_broad)
summary(m1)
```
### Logistic regression analysis
model 2
```{r echo=TRUE}
dat$month=format(dat$date,"%m")
dat=dat%>% mutate(season= case_when( month=="03"|month=="04"|month=="05" ~ "spring",
                                   month=="06"|month=="07"|month=="08" ~ "summer",
                                   month=="09"|month=="10"|month=="11" ~ "autumn",
                                   month=="12"|month=="01"|month=="02" ~ "winter"))


m2 <- glm (broad_spectrum ~ as.factor(season) + age_cat + sex + as.factor(prevalent) + infection + 
               charlson_score + ethnicity_6 + flu_vaccine + imd + gp_count +antibacterial_12mb4, family = binomial(link = "logit"),data = dat)
summary(m2)
```





























