---
title: "broad_spectrum_ab_freq"
author: "Billy Z"
date: "25/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = '/workspace')
```


```{r echo=TRUE}
library("ggplot2")
library("dplyr")
library("tidyverse")
library('lubridate')
library('knitr')
```



```{r echo=TRUE}
df <- read_csv(
  here::here("output", "measures", "measure_antibiotics_overall_brit_abtype.csv"),  
  col_types = cols_only(
    antibacterial_brit_abtype = col_character(),
    # Outcomes
    antibacterial_brit = col_double(),
    population = col_double(),
    value = col_double(),
    
    # Date
    date = col_date(format="%Y-%m-%d")
    
  ),
  na = character()
  )

df$date <- as.Date(df$date,format="%Y-%m-%d")
df[is.na(df)] <- 0 


# remove last month data
last.date=max(df$date)
df=df%>% filter(date!=last.date)
df$cal_mon <- month(df$date)

df$cal_year <- year(df$date)

first_mon=format(min(df$date),"%m-%Y")
last_mon= format(max(df$date),"%m-%Y")
df$year <- as.factor(df$cal_year)
df$mon <- as.factor(df$cal_mon)

```

## Broad_spectrum antibiotics frequency table--Brit_list

```{r echo=TRUE}

broadtype <- c("Amoxicillin","Ampicillin","Co-amoxiclav","Moxifloxacin","Cefaclor","Cefadroxil","Cefuroxime",     "Cefalexin","Cefazolin","Cefixime","Cefotaxime","Cefoxitin","Cefradine","Cefpirome","Ceftazidime","Ceftriaxone",    "Cefprozil","Ciprofloxacin","Co-fluampicil","Doripenem","Ertapenem", "Cilastatin","Cefamandole","Levofloxacin" , 
"Meropenem" ,"Nalidixic acid","Norfloxacin", "Ofloxacin","Cefpodoxime","Cefepime")


dfb <- df %>% filter(antibacterial_brit_abtype %in% broadtype )
dfb_total <- dfb %>% group_by(antibacterial_brit_abtype) %>% summarise(
  total_count = sum(antibacterial_brit, na.rm = TRUE)
)

dfb_total <- dfb_total %>% arrange(desc(total_count))
kable(dfb_total, caption = 'Broad_spectrum antibiotics frequency table')

```

## broad_spectrum prescription trends by type

```{r}

plot2<- ggplot(dfb, aes(x=date, y=antibacterial_brit ,group=antibacterial_brit_abtype,color=antibacterial_brit_abtype))+
  annotate(geom = "rect", xmin = as.Date("2021-01-01"),xmax = as.Date("2021-04-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-11-01"),xmax = as.Date("2020-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-03-01"),xmax = as.Date("2020-06-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_line()+
  theme(legend.position = "bottom",legend.title =element_blank())+
  labs(
    fill = "Antibiotic type",
    title = "Broad- Spectrum Ab Types Prescribed",
    subtitle = paste(first_mon,"-",last_mon),
    y = "percent",
    x=""
  )+
  theme(axis.text.x=element_text(angle=60,hjust=1))+
  scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month")
plot2


```


## Percentage diagram

```{r echo=TRUE}

df_total <-  df %>% group_by(date) %>% summarise(
  ab_total = sum(antibacterial_brit, na.rm = TRUE)
)
df_b <- dfb %>% group_by(date) %>% summarise(
  b_total = sum(antibacterial_brit, na.rm = TRUE)
)

plot1 <- merge(df_b,df_total, by = 'date')
plot1$cal_mon <- month(plot1$date)
plot1$cal_year <- year(plot1$date)
plot1$year <- as.factor(plot1$cal_year)
plot1$mon <- as.factor(plot1$cal_mon)
plot1 <- plot1 %>% mutate(prop = b_total/ab_total)


p1 <- ggplot(plot1, aes(x=mon, y=prop, group=year)) +
  geom_line(aes(color=year))+
  geom_point(aes(color=year))+
  scale_color_brewer(palette="Paired")+
  theme_minimal()+
  scale_y_continuous(labels = scales::percent,breaks=seq(0, 1, by = 0.005))+
  labs(
    title = "Proportion of broad-spectrum antibiotics prescribed",
    subtitle = paste(first_mon,"-",last_mon),
    x = "Month",
    y = "broad-spectrum antibiotics prescribing %")

p1


```

## Excluding Amoxicillin

```{r}

broadtype2 <- c("Ampicillin","Co-amoxiclav","Moxifloxacin","Cefaclor","Cefadroxil","Cefuroxime",     "Cefalexin","Cefazolin","Cefixime","Cefotaxime","Cefoxitin","Cefradine","Cefpirome","Ceftazidime","Ceftriaxone",    "Cefprozil","Ciprofloxacin","Co-fluampicil","Doripenem","Ertapenem", "Cilastatin","Cefamandole","Levofloxacin" , 
"Meropenem" ,"Nalidixic acid","Norfloxacin", "Ofloxacin","Cefpodoxime","Cefepime")


dfb2 <- df %>% filter(antibacterial_brit_abtype %in% broadtype2 )

df_b2 <- dfb2 %>% group_by(date) %>% summarise(
  b_total = sum(antibacterial_brit, na.rm = TRUE)
)

plot3 <- merge(df_b2,df_total, by = 'date')
plot3$cal_mon <- month(plot3$date)
plot3$cal_year <- year(plot3$date)
plot3$year <- as.factor(plot3$cal_year)
plot3$mon <- as.factor(plot3$cal_mon)
plot3 <- plot3 %>% mutate(prop = b_total/ab_total)


p3 <- ggplot(plot3, aes(x=mon, y=prop, group=year)) +
  geom_line(aes(color=year))+
  geom_point(aes(color=year))+
  scale_color_brewer(palette="Paired")+
  theme_minimal()+
  scale_y_continuous(labels = scales::percent,breaks=seq(0, 1, by = 0.001))+
  labs(
    title = "Proportion of broad-spectrum antibiotics prescribed",
    subtitle = paste(first_mon,"-",last_mon),
    x = "Month",
    y = "broad-spectrum antibiotics prescribing %")

p3


```


## Use antibiotics list and broad_spectrum list on openprescribing.

```{r}
broad_type_op <- c("Co-amoxiclav", "Cefaclor", 
  "Cefadroxil", "Cefixime", "Cefotaxime", "Ceftriaxone", "Ceftazidime", 
  "Cefuroxime", "Cefalexin", "Cefradine", "Moxifloxacin", "Ciprofloxacin", 
  "Nalidixic acid", "Levofloxacin", "Norfloxacin", "Ofloxacin")

overall_type_op <- abtypelist <- c("Amoxicillin", "Ampicillin", "Co-amoxiclav", 
  "Benzylpenicillin", "Co-fluampicil", "Flucloxacillin", "Temocillin", 
  "Phenoxymethylpenicillin", "Piperacillin", "Pivmecillinam", "Ticarcillin", 
  "Cefaclor", "Cefadroxil", "Cefixime", "Cefotaxime", "Ceftriaxone", 
  "Ceftazidime", "Cefuroxime", "Cefalexin", "Cefradine", "Tetracycline", 
  "Minocycline", "Demeclocycline", "Doxycycline", "Lymecycline", 
  "Oxytetracycline", "Tigecycline", "Azithromycin", "Clarithromycin", 
  "Erythromycin", "Telithromycin", "Trimethoprim", "Sulfadiazine", 
  "Sulfamethoxazole", "Sulfapyridine", "Tinidazole", "Metronidazole", 
  "Moxifloxacin", "Ciprofloxacin", "Nalidixic acid", "Levofloxacin", 
  "Norfloxacin", "Ofloxacin", "Fosfomycin", "Nitrofurantoin", "Methenamine")

df_total_op <- df %>% filter(antibacterial_brit_abtype %in% overall_type_op )
df_total_op <-  df_total_op %>% group_by(date) %>% summarise(
  ab_total = sum(antibacterial_brit, na.rm = TRUE)
)


df_broad_op <- df %>% filter(antibacterial_brit_abtype %in% broad_type_op )

df_broad_op <- df_broad_op %>% group_by(date) %>% summarise(
  b_total = sum(antibacterial_brit, na.rm = TRUE)
)

plot4 <- merge(df_broad_op,df_total_op, by = 'date')
plot4$cal_mon <- month(plot4$date)
plot4$cal_year <- year(plot4$date)
plot4$year <- as.factor(plot4$cal_year)
plot4$mon <- as.factor(plot4$cal_mon)
plot4 <- plot4 %>% mutate(prop = b_total/ab_total)


p4 <- ggplot(plot4, aes(x=mon, y=prop, group=year)) +
  geom_line(aes(color=year))+
  geom_point(aes(color=year))+
  scale_color_brewer(palette="Paired")+
  theme_minimal()+
  scale_y_continuous(labels = scales::percent,breaks=seq(0, 1, by = 0.001))+
  labs(
    title = "Proportion of broad-spectrum antibiotics prescribed",
    subtitle = paste(first_mon,"-",last_mon),
    x = "Month",
    y = "broad-spectrum antibiotics prescribing %")

p4

```

## Use broad_spectrum list on openprescribing by Brit overall

```{r}
plot5 <- merge(df_broad_op,df_total, by = 'date')
plot5$cal_mon <- month(plot5$date)
plot5$cal_year <- year(plot5$date)
plot5$year <- as.factor(plot5$cal_year)
plot5$mon <- as.factor(plot5$cal_mon)
plot5 <- plot5 %>% mutate(prop = b_total/ab_total)


p5 <- ggplot(plot5, aes(x=mon, y=prop, group=year)) +
  geom_line(aes(color=year))+
  geom_point(aes(color=year))+
  scale_color_brewer(palette="Paired")+
  theme_minimal()+
  scale_y_continuous(labels = scales::percent,breaks=seq(0, 1, by = 0.001))+
  labs(
    title = "Proportion of broad-spectrum antibiotics prescribed",
    subtitle = paste(first_mon,"-",last_mon),
    x = "Month",
    y = "broad-spectrum antibiotics prescribing %")

p5


```


