---
title: "consultation rate trend - ITS model"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = '/workspace')
```

```{r message=FALSE}
library("ggplot2")
library("data.table")
library("dplyr")
library("tidyverse")
library("MASS")
library("ggpubr")
#library(modelsummary)
#library("gtsummary")
```

# incident

```{r message=FALSE}
### Import data
filelist=c("consult_UTI.rds","consult_URTI.rds","consult_LRTI.rds","consult_sinusitis.rds","consult_ot_externa.rds","consult_otmedia.rds","consult_indications.rds")

#temp <- vector("list", length(filelist))

#for (i in seq_along(filelist)){

df = read_rds(here::here("output","measures",filelist[1]))
# infection counts, population size, covid period
df = df%>% group_by(date, covid)%>% 
  summarise(counts=sum(infection_counts), 
            population=sum(population))
# month for seasonality
df$month= format(df$date,"%m")
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))

# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)
  
#temp[[i]]=df

df1=df
df1$indic="UTI"

rm(df)
#}

df = read_rds(here::here("output","measures",filelist[2]))
# infection counts, population size, covid period
df = df%>% group_by(date, covid)%>% 
  summarise(counts=sum(infection_counts), 
            population=sum(population))
# month for seasonality
df$month= format(df$date,"%m")
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))

# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)
  
#temp[[i]]=df

df2=df
df2$indic="URTI"

rm(df)

df = read_rds(here::here("output","measures",filelist[3]))
# infection counts, population size, covid period
df = df%>% group_by(date, covid)%>% 
  summarise(counts=sum(infection_counts), 
            population=sum(population))
# month for seasonality
df$month= format(df$date,"%m")
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))
# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)
  
#temp[[i]]=df

df3=df
df3$indic="LRTI"

rm(df)

df = read_rds(here::here("output","measures",filelist[4]))
# infection counts, population size, covid period
df = df%>% group_by(date, covid)%>% 
  summarise(counts=sum(infection_counts), 
            population=sum(population))
# month for seasonality
df$month= format(df$date,"%m")
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))
# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)
  
#temp[[i]]=df

df4=df
df4$indic="sinusitis"
rm(df)


df = read_rds(here::here("output","measures",filelist[5]))
# infection counts, population size, covid period
df = df%>% group_by(date, covid)%>% 
  summarise(counts=sum(infection_counts), 
            population=sum(population))
# month for seasonality
df$month= format(df$date,"%m")
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))
# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)
  
#temp[[i]]=df

df5=df
df5$indic="otitis externa"
rm(df)


df = read_rds(here::here("output","measures",filelist[6]))
# infection counts, population size, covid period
df = df%>% group_by(date, covid)%>% 
  summarise(counts=sum(infection_counts), 
            population=sum(population))
# month for seasonality
df$month= format(df$date,"%m")
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))
# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)
  
#temp[[i]]=df

df6=df
df6$indic="otitis media"
rm(df)



# all indications updated
df = read_rds(here::here("output","measures",filelist[7]))
# infection counts, population size, covid period
df = df%>% group_by(date, covid)%>% 
  summarise(counts=sum(infection_counts), 
            population=sum(population))
# month for seasonality
df$month= format(df$date,"%m")
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))
# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)
  
#temp[[i]]=df

df7=df
df7$indic="all infections"

rm(df)

```

```{r message=FALSE}

df1=df1%>%mutate(season= case_when(month=="12"|month=="01"|month=="02" ~ "winter",
                                   month=="03"|month=="04"|month=="05" ~"spring",
                                   month=="06"|month=="07"|month=="08" ~"summer",
                                   month=="09"|month=="10"|month=="11" ~"autumn"))
df1$month=relevel(as.factor(df1$season),ref="spring")
df2=df2%>%mutate(season= case_when(month=="12"|month=="01"|month=="02" ~ "winter",
                                   month=="03"|month=="04"|month=="05" ~"spring",
                                   month=="06"|month=="07"|month=="08" ~"summer",
                                   month=="09"|month=="10"|month=="11" ~"autumn"))
df2$month=relevel(as.factor(df2$season),ref="spring")
df3=df3%>%mutate(season= case_when(month=="12"|month=="01"|month=="02" ~ "winter",
                                   month=="03"|month=="04"|month=="05" ~"spring",
                                   month=="06"|month=="07"|month=="08" ~"summer",
                                   month=="09"|month=="10"|month=="11" ~"autumn"))
df3$month=relevel(as.factor(df3$season),ref="spring")
df4=df4%>%mutate(season= case_when(month=="12"|month=="01"|month=="02" ~ "winter",
                                   month=="03"|month=="04"|month=="05" ~"spring",
                                   month=="06"|month=="07"|month=="08" ~"summer",
                                   month=="09"|month=="10"|month=="11" ~"autumn"))
df4$month=relevel(as.factor(df4$season),ref="spring")
df5=df5%>%mutate(season= case_when(month=="12"|month=="01"|month=="02" ~ "winter",
                                   month=="03"|month=="04"|month=="05" ~"spring",
                                   month=="06"|month=="07"|month=="08" ~"summer",
                                   month=="09"|month=="10"|month=="11" ~"autumn"))
df5$month=relevel(as.factor(df5$season),ref="spring")
df6=df6%>%mutate(season= case_when(month=="12"|month=="01"|month=="02" ~ "winter",
                                   month=="03"|month=="04"|month=="05" ~"spring",
                                   month=="06"|month=="07"|month=="08" ~"summer",
                                   month=="09"|month=="10"|month=="11" ~"autumn"))
df6$month=relevel(as.factor(df6$season),ref="spring")
df7=df7%>%mutate(season= case_when(month=="12"|month=="01"|month=="02" ~ "winter",
                                   month=="03"|month=="04"|month=="05" ~"spring",
                                   month=="06"|month=="07"|month=="08" ~"summer",
                                   month=="09"|month=="10"|month=="11" ~"autumn"))
df7$month=relevel(as.factor(df7$season),ref="spring")
```

1. UTI
```{r}
m1<- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df1)
```

2. URTI
```{r}
m2 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df2)
```

3. LRTI
```{r}
m3 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since , data = df3)
```

4. sinusitis
```{r}
m4 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df4)
```

5. otitis externa
```{r}
m5<-glm.nb(counts~ offset(log(population))+ covid + month + times + time.since , data = df5)
```

6. otitis media
```{r }
m6 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df6)
```

7. all
```{r }
m7 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df7)
```

# prediction
```{r}
df1 <- cbind(df1, "resp" = predict(m1, type = "response", se.fit = TRUE)[1:2])
df2 <- cbind(df2, "resp" = predict(m2, type = "response", se.fit = TRUE)[1:2])
df3 <- cbind(df3, "resp" = predict(m3, type = "response", se.fit = TRUE)[1:2])
df4 <- cbind(df4, "resp" = predict(m4, type = "response", se.fit = TRUE)[1:2])
df5 <- cbind(df5, "resp" = predict(m5, type = "response", se.fit = TRUE)[1:2])
df6 <- cbind(df6, "resp" = predict(m6, type = "response", se.fit = TRUE)[1:2])
df7 <- cbind(df7, "resp" = predict(m7, type = "response", se.fit = TRUE)[1:2])

DF=rbind(df1,df2,df3,df4,df5,df6,df7)

DF$indic=factor(DF$indic,levels=c("all infections","URTI","LRTI","sinusitis","otitis media","otitis externa","UTI"))
```

# prediction -non covid
```{r}

df1_counter <- subset(df1, select=-c(fit,se.fit))
df1_counter$covid<- as.factor(df1_counter$covid)
df1_counter  <- cbind(df1_counter, "resp" = predict(m1, type = "response", se.fit = TRUE, newdata = df1_counter)[1:2])

df2_counter <- subset(df2, select=-c(fit,se.fit))
df2_counter$covid<- as.factor(df2_counter$covid)
df2_counter  <- cbind(df2_counter, "resp" = predict(m2, type = "response", se.fit = TRUE, newdata = df1_counter)[1:2])

df3_counter <- subset(df3, select=-c(fit,se.fit))
df3_counter$covid<- as.factor(df3_counter$covid)
df3_counter  <- cbind(df3_counter, "resp" = predict(m3, type = "response", se.fit = TRUE, newdata = df1_counter)[1:2])

df4_counter <- subset(df4, select=-c(fit,se.fit))
df4_counter$covid<- as.factor(df4_counter$covid)
df4_counter  <- cbind(df4_counter, "resp" = predict(m4, type = "response", se.fit = TRUE, newdata = df1_counter)[1:2])

df5_counter <- subset(df5, select=-c(fit,se.fit))
df5_counter$covid<- as.factor(df5_counter$covid)
df5_counter  <- cbind(df5_counter, "resp" = predict(m5, type = "response", se.fit = TRUE, newdata = df1_counter)[1:2])

df6_counter <- subset(df6, select=-c(fit,se.fit))
df6_counter$covid<- as.factor(df6_counter$covid)
df6_counter  <- cbind(df6_counter, "resp" = predict(m6, type = "response", se.fit = TRUE, newdata = df1_counter)[1:2])

df7_counter <- subset(df7, select=-c(fit,se.fit))
df7_counter$covid<- as.factor(df7_counter$covid)
df7_counter  <- cbind(df7_counter, "resp" = predict(m7, type = "response", se.fit = TRUE, newdata = df1_counter)[1:2])

DF_counter= rbind(df1_counter,df2_counter,df3_counter,df4_counter,df5_counter,df6_counter,df7_counter)
DF_counter$indic=factor(DF_counter$indic,levels=c("all infections","URTI","LRTI","sinusitis","otitis media","otitis externa","UTI"))
```


# plot
```{r}

##add labels etc
plot_ITS<-ggplot(DF, aes(x=date, y=fit*1000/population, group=covid))+ 
  
#actual rage point
    geom_point(shape=4, aes(x=date, y=counts/population*1000))+ 
  
# prediction model  
    geom_line(color="black")+ 
    geom_ribbon(aes(ymin=((fit-1.96*se.fit)*1000)/population, ymax=((fit+1.96*se.fit)*1000)/population),alpha=0.2,fill="black") +

# prediction model: non covid    
    geom_line(aes(y=fit*1000/population,x=date),color="blue",data = DF_counter)+
    geom_ribbon(aes(ymin=((fit-1.96*se.fit)*1000)/population, ymax=((fit+1.96*se.fit)*1000)/population),alpha=0.2,fill="blue",data = DF_counter) +

# group by indication  
  facet_grid(rows = vars(indic),scales="free_y",labeller = label_wrap_gen(width = 2, multi_line = TRUE))+

  # them
    theme_bw()+ 
  annotate(geom = "rect", xmin = as.Date("2019-12-01"),xmax = as.Date("2020-04-01"),ymin = -Inf, ymax = Inf,fill="grey60",alpha=0.5)+   
  
# legend  
    scale_x_date(date_labels = "%m-%Y", 
                 breaks = seq(as.Date("2019-01-01"), as.Date("2021-12-01"), 
                              by = "3 months"))+
      theme(axis.text.x = element_text(angle = 60,hjust=1),
          legend.position = "bottom",legend.title =element_blank())+
    labs(
      title = "",
      x = "", 
      y = "Number of consultations per 1000 patients")

plot_ITS

ggsave(
   plot= plot_ITS,
   filename="plot_ITS.jpeg", path=here::here("output"), dpi = 300
)
```

