---
title: "consultation rate - ITS model2 - combined plots"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = '/workspace')
```

# overall

```{r message=FALSE}
library("ggplot2")
library("data.table")
library("dplyr")
library("tidyverse")
library("MASS")
library(modelsummary)
#library("gtsummary")
```

```{r message=FALSE}
### Import data
filelist=c("consult_UTI.rds","consult_URTI.rds","consult_LRTI.rds","consult_sinusitis.rds","consult_ot_externa.rds","consult_otmedia.rds")

#temp <- vector("list", length(filelist))

#for (i in seq_along(filelist)){

df = read_rds(here::here("output","measures",filelist[1]))
# infection counts, population size, covid period
df = df%>% group_by(date, covid)%>% 
  summarise(counts=sum(infection_counts), 
            population=sum(population))
# month for seasonality
df$month= format(df$date,"%m")
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))

# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)
  
#temp[[i]]=df

df1=df
rm(df)
#}

df = read_rds(here::here("output","measures",filelist[2]))
# infection counts, population size, covid period
df = df%>% group_by(date, covid)%>% 
  summarise(counts=sum(infection_counts), 
            population=sum(population))
# month for seasonality
df$month= format(df$date,"%m")
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))

# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)
  
#temp[[i]]=df

df2=df
rm(df)

df = read_rds(here::here("output","measures",filelist[3]))
# infection counts, population size, covid period
df = df%>% group_by(date, covid)%>% 
  summarise(counts=sum(infection_counts), 
            population=sum(population))
# month for seasonality
df$month= format(df$date,"%m")
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))
# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)
  
#temp[[i]]=df

df3=df
rm(df)

df = read_rds(here::here("output","measures",filelist[4]))
# infection counts, population size, covid period
df = df%>% group_by(date, covid)%>% 
  summarise(counts=sum(infection_counts), 
            population=sum(population))
# month for seasonality
df$month= format(df$date,"%m")
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))
# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)
  
#temp[[i]]=df

df4=df
rm(df)


df = read_rds(here::here("output","measures",filelist[5]))
# infection counts, population size, covid period
df = df%>% group_by(date, covid)%>% 
  summarise(counts=sum(infection_counts), 
            population=sum(population))
# month for seasonality
df$month= format(df$date,"%m")
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))
# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)
  
#temp[[i]]=df

df5=df
rm(df)


df = read_rds(here::here("output","measures",filelist[6]))
# infection counts, population size, covid period
df = df%>% group_by(date, covid)%>% 
  summarise(counts=sum(infection_counts), 
            population=sum(population))
# month for seasonality
df$month= format(df$date,"%m")
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))
# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)
  
#temp[[i]]=df

df6=df
rm(df)

```

```{r message=FALSE}

df1=df1%>%mutate(season= case_when(month=="12"|month=="01"|month=="02" ~ "winter",
                                   month=="03"|month=="04"|month=="05" ~"spring",
                                   month=="06"|month=="07"|month=="08" ~"summer",
                                   month=="09"|month=="10"|month=="11" ~"autumn"))
df1$month=relevel(as.factor(df1$season),ref="spring")
df2=df2%>%mutate(season= case_when(month=="12"|month=="01"|month=="02" ~ "winter",
                                   month=="03"|month=="04"|month=="05" ~"spring",
                                   month=="06"|month=="07"|month=="08" ~"summer",
                                   month=="09"|month=="10"|month=="11" ~"autumn"))
df2$month=relevel(as.factor(df2$season),ref="spring")
df3=df3%>%mutate(season= case_when(month=="12"|month=="01"|month=="02" ~ "winter",
                                   month=="03"|month=="04"|month=="05" ~"spring",
                                   month=="06"|month=="07"|month=="08" ~"summer",
                                   month=="09"|month=="10"|month=="11" ~"autumn"))
df3$month=relevel(as.factor(df3$season),ref="spring")
df4=df4%>%mutate(season= case_when(month=="12"|month=="01"|month=="02" ~ "winter",
                                   month=="03"|month=="04"|month=="05" ~"spring",
                                   month=="06"|month=="07"|month=="08" ~"summer",
                                   month=="09"|month=="10"|month=="11" ~"autumn"))
df4$month=relevel(as.factor(df4$season),ref="spring")
df5=df5%>%mutate(season= case_when(month=="12"|month=="01"|month=="02" ~ "winter",
                                   month=="03"|month=="04"|month=="05" ~"spring",
                                   month=="06"|month=="07"|month=="08" ~"summer",
                                   month=="09"|month=="10"|month=="11" ~"autumn"))
df5$month=relevel(as.factor(df5$season),ref="spring")
df6=df6%>%mutate(season= case_when(month=="12"|month=="01"|month=="02" ~ "winter",
                                   month=="03"|month=="04"|month=="05" ~"spring",
                                   month=="06"|month=="07"|month=="08" ~"summer",
                                   month=="09"|month=="10"|month=="11" ~"autumn"))
df6$month=relevel(as.factor(df6$season),ref="spring")
```


1. UTI
```{r}
m1.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df1)
```

2. URTI
```{r}
m2.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df2)
```

3. LRTI
```{r}
m3.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since , data = df3)
```

4. sinusitis
```{r}
m4.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df4)
```

5. otitis externa
```{r}
m5.1<-glm.nb(counts~ offset(log(population))+ covid + month + times + time.since , data = df5)
```

6. otitis media
```{r }
m6.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df6)
```


```{r message=FALSE}
### confidence intervals for the coefficients
(est1.1 <- cbind(Estimate = coef(m1.1), confint(m1.1)))
(est2.1 <- cbind(Estimate = coef(m2.1), confint(m2.1)))
(est3.1 <- cbind(Estimate = coef(m3.1), confint(m3.1)))
(est4.1 <- cbind(Estimate = coef(m4.1), confint(m4.1)))
(est5.1 <- cbind(Estimate = coef(m5.1), confint(m5.1)))
(est6.1 <- cbind(Estimate = coef(m6.1), confint(m6.1)))

```


```{r message=FALSE}
### calculate IRR & 95%CI
est1.1=exp(est1.1)
est2.1=exp(est2.1)
est3.1=exp(est3.1)
est4.1=exp(est4.1)
est5.1=exp(est5.1)
est6.1=exp(est6.1)
```

### covid
```{r message=FALSE}
## combine results
# covid
DF=bind_rows(est1.1[2,],est2.1[2,],est3.1[2,],est4.1[2,],est5.1[2,],est6.1[2,])
DF$Infection=c("UTI","URTI","LRTI","Sinusitis","Otitis externa","Otitis media")
#reorder
DF=DF%>%arrange(Infection)

names(DF)[1]="IRR"
names(DF)[2]="ci_l"
names(DF)[3]="ci_u"

DF1=DF
DF1
```


# prevalent


```{r message=FALSE}

# import incident cases
df = read_csv(here::here("output","redacted","consultation_rate_prevalent_check.csv"))

# define covid date
breaks <- c(as.Date("2019-01-01"),as.Date("2019-12-31"),# 1=pre-covid, 2=exclusion
            as.Date("2020-04-01"), as.Date("2021-12-31"),# 3= covid time
            max(df$date)) # NA exclusion

df=df%>%mutate(covid=cut(date,breaks,labels = 1:4))

df=df%>% filter(covid==1 | covid==3)
df$covid= recode(df$covid, '1'="0", '3'="1") # precovid=0, covid=1
df$covid <- factor(df$covid, levels=c("0","1"))


# infection counts, population size, covid period
df= df%>% group_by(date, covid,indic)%>% 
  summarise(counts=sum(counts), 
            population=sum(population))

# month for adjust seasonality
df$month=format(df$date,"%m")
df=df%>% mutate(season= case_when( month=="03"|month=="04"|month=="05" ~ "spring",
                                   month=="06"|month=="07"|month=="08" ~ "summer",
                                   month=="09"|month=="10"|month=="11" ~ "autumn",
                                   month=="12"|month=="01"|month=="02" ~ "winter"))
df$month=df$season
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))

# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)


df1=df%>%filter(indic=="UTI")
df2=df%>%filter(indic=="LRTI")
df3=df%>%filter(indic=="URTI") 
df4=df%>%filter(indic=="sinusitis")
df5=df%>%filter(indic=="otitis externa")
df6=df%>%filter(indic=="otitis media")


```


1. UTI
```{r}
m1.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df1)
```

2. URTI
```{r}
m2.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df2)
```

3. LRTI
```{r}
m3.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since , data = df3)
```

4. sinusitis
```{r}
m4.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df4)
```

5. otitis externa
```{r}
m5.1 <-glm.nb(counts~ offset(log(population))+ covid + month + times + time.since , data = df5)
```

6. otitis media
```{r }
m6.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df6)
```


```{r message=FALSE, include=FALSE}
### confidence intervals for the coefficients
(est1.1 <- cbind(Estimate = coef(m1.1), confint(m1.1)))
(est2.1 <- cbind(Estimate = coef(m2.1), confint(m2.1)))
(est3.1 <- cbind(Estimate = coef(m3.1), confint(m3.1)))
(est4.1 <- cbind(Estimate = coef(m4.1), confint(m4.1)))
(est5.1 <- cbind(Estimate = coef(m5.1), confint(m5.1)))
(est6.1 <- cbind(Estimate = coef(m6.1), confint(m6.1)))
```


```{r message=FALSE}
### calculate IRR & 95%CI
est1.1=exp(est1.1)
est2.1=exp(est2.1)
est3.1=exp(est3.1)
est4.1=exp(est4.1)
est5.1=exp(est5.1)
est6.1=exp(est6.1)
```

### covid
```{r message=FALSE}
## combine results
# covid
DF=bind_rows(est1.1[2,],est2.1[2,],est3.1[2,],est4.1[2,],est5.1[2,],est6.1[2,])
DF$Infection=c("UTI","URTI","LRTI","Sinusitis","Otitis externa","Otitis media")
#reorder
DF=DF%>%arrange(Infection)

names(DF)[1]="IRR"
names(DF)[2]="ci_l"
names(DF)[3]="ci_u"

DF2=DF

DF2
```




# incident


```{r message=FALSE}

# import incident cases
df = read_csv(here::here("output","redacted","consultation_rate_incident_check.csv"))

# define covid date
breaks <- c(as.Date("2019-01-01"),as.Date("2019-12-31"),# 1=pre-covid, 2=exclusion
            as.Date("2020-04-01"), as.Date("2021-12-31"),# 3= covid time
            max(df$date)) # NA exclusion

df=df%>%mutate(covid=cut(date,breaks,labels = 1:4))

df=df%>% filter(covid==1 | covid==3)
df$covid= recode(df$covid, '1'="0", '3'="1") # precovid=0, covid=1
df$covid <- factor(df$covid, levels=c("0","1"))


# infection counts, population size, covid period
df= df%>% group_by(date, covid,indic)%>% 
  summarise(counts=sum(counts), 
            population=sum(population))

# month for adjust seasonality
df$month=format(df$date,"%m")
df=df%>% mutate(season= case_when( month=="03"|month=="04"|month=="05" ~ "spring",
                                   month=="06"|month=="07"|month=="08" ~ "summer",
                                   month=="09"|month=="10"|month=="11" ~ "autumn",
                                   month=="12"|month=="01"|month=="02" ~ "winter"))
df$month=df$season
# time elapsed(measurement time point) for linear effect of time to capture long-term behaviour trends
df$times <- as.numeric(as.factor(df$date))

# time sequnece after covid
df=df%>% group_by(covid)%>%mutate(time.since=1:n())
df$time.since <- ifelse(df$covid==0,0,df$time.since)


df1=df%>%filter(indic=="UTI")
df2=df%>%filter(indic=="LRTI")
df3=df%>%filter(indic=="URTI") 
df4=df%>%filter(indic=="sinusitis")
df5=df%>%filter(indic=="otitis externa")
df6=df%>%filter(indic=="otitis media")


```


1. UTI
```{r}
m1.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df1)
```

2. URTI
```{r}
m2.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df2)
```

3. LRTI
```{r}
m3.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since , data = df3)
```

4. sinusitis
```{r}
m4.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df4)
```

5. otitis externa
```{r}
m5.1 <-glm.nb(counts~ offset(log(population))+ covid + month + times + time.since , data = df5)
```

6. otitis media
```{r }
m6.1 <- glm.nb(counts~ offset(log(population))+ covid + month + times + time.since  , data = df6)
```


```{r message=FALSE, include=FALSE}
### confidence intervals for the coefficients
(est1.1 <- cbind(Estimate = coef(m1.1), confint(m1.1)))
(est2.1 <- cbind(Estimate = coef(m2.1), confint(m2.1)))
(est3.1 <- cbind(Estimate = coef(m3.1), confint(m3.1)))
(est4.1 <- cbind(Estimate = coef(m4.1), confint(m4.1)))
(est5.1 <- cbind(Estimate = coef(m5.1), confint(m5.1)))
(est6.1 <- cbind(Estimate = coef(m6.1), confint(m6.1)))
```


```{r message=FALSE}
### calculate IRR & 95%CI
est1.1=exp(est1.1)
est2.1=exp(est2.1)
est3.1=exp(est3.1)
est4.1=exp(est4.1)
est5.1=exp(est5.1)
est6.1=exp(est6.1)
```

### covid
```{r message=FALSE}
## combine results
# covid
DF=bind_rows(est1.1[2,],est2.1[2,],est3.1[2,],est4.1[2,],est5.1[2,],est6.1[2,])
DF$Infection=c("UTI","URTI","LRTI","Sinusitis","Otitis externa","Otitis media")
#reorder
DF=DF%>%arrange(Infection)

names(DF)[1]="IRR"
names(DF)[2]="ci_l"
names(DF)[3]="ci_u"

DF3=DF

DF3
```




# plot
```{r}
DF1$group="overall"
DF2$group="prevalent"
DF3$group="incident"
DF=rbind(DF1,DF2,DF3)
DF$group=factor(DF$group,levels=c("overall","incident","prevalent"))
DF$Infection=factor(DF$Infection, levels=c("URTI","LRTI","Sinusitis","Otitis externa","Otitis media","UTI"))

```


```{r message=FALSE}
### Model2_result
#setting up the basic plot
p2 <- ggplot(data=DF, aes(y=Infection, x=IRR,xmin=ci_l, xmax=ci_u, fill=group))+ 
#this adds the effect sizes to the plot
geom_point()+ 

#adds the CIs
geom_errorbarh(height=.1)+

#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black", linetype="dashed", alpha=.5)+
#thematic stuff
#theme_minimal()+
#theme(text=element_text(family="Times",size=18, color="black"))+
#theme(panel.spacing = unit(1, "lines"))+
labs(
      title = "Consultation Reduction",
    x="IRR (95% CI)",
    y=""
  )+
facet_grid(group~.)
 #theme(axis.title.y =element_blank(),
  #      axis.text.y=element_blank(),
   #     axis.ticks.y=element_blank())
p2
```



```{r message=FALSE}
### Model2_result
#setting up the basic plot
p3 <- ggplot(data=DF, aes(y=Infection, x=IRR,xmin=ci_l, xmax=ci_u))+ 
#this adds the effect sizes to the plot
geom_point()+ 

#adds the CIs
geom_errorbarh(aes(xmin=ci_l, xmax=ci_u))+

#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black", linetype="dashed", alpha=.5)+
#thematic stuff
#theme_minimal()+
#theme(text=element_text(family="Times",size=18, color="black"))+
#theme(panel.spacing = unit(1, "lines"))+
labs(
      title = "Consultation Reduction",
    x="IRR (95% CI)",
    y=""
  )+
facet_grid(group~Infection)+
 theme(axis.title.y =element_blank(),
        axis.text.y=element_blank(),
       axis.ticks.y=element_blank())
p3
```


```{r message=FALSE}
### Model2_result
#setting up the basic plot
p4 <- ggplot(data=DF, aes(y=group, x=IRR,xmin=ci_l, xmax=ci_u,color=group))+ 
#this adds the effect sizes to the plot
geom_point()+ 

#adds the CIs
geom_errorbarh(height=.1)+

#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black", linetype="dashed", alpha=.5)+
#thematic stuff
theme_bw()+
#theme(text=element_text(family="Times",size=18, color="black"))+
#theme(panel.spacing = unit(1, "lines"))+
labs(
      title = "Consultation Reduction",
    x="IRR (95% CI)",
    y=""
  )+
facet_grid(~Infection)+
 theme(axis.title.y =element_blank(),
        axis.text.y=element_blank(),
       axis.ticks.y=element_blank(),
       legend.title=element_blank(),
       legend.position="bottom")
p4
```


```{r message=FALSE}
### Model2_result
#setting up the basic plot
p5 <- ggplot(data=DF, aes(y=group, x=IRR,color=group))+ 
#this adds the effect sizes to the plot
geom_point()+ 

#adds the CIs
geom_errorbarh(aes(xmin=ci_l, xmax=ci_u))+

#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black", linetype="dashed", alpha=.5)+
#tematic stuff
theme_bw()+
#theme(text=element_text(family="Times",size=18, color="black"))+
#theme(panel.spacing = unit(1, "lines"))+
labs(
      title = "Consultation Reduction",
    x="IRR (95% CI)",
    y=""
  )+
facet_grid(Infection~., scales = "free", space = "free")+
 theme(strip.text.y = element_text(angle = 0),
   axis.title.y =element_blank(),
        axis.text.y=element_blank(),
       axis.ticks.y=element_blank(),
       legend.title=element_blank(),
       legend.position="bottom")
p5
```

# table

```{r}
model.all<- list(m1, m1.1)
modelsummary(model.all,
             fmt = 1,
             statistic = 'conf.int', 
             conf_level = .95,
             stars = TRUE,
             exponentiate = TRUE)
```

