---
title: "Descriptive analysis of antibiotic prescribing"
author: "Billy Z"
date: "06/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/workspace')
```



```{r include=FALSE}
library('tidyverse')
library("ggplot2")
library('dplyr')
library('lubridate')
```



###Import data

```{r include=FALSE}
df1 <- read_csv(
  here::here("output", "measures", "measure_STARPU_antibiotics.csv"),
  col_types = cols_only(
    
    # Identifier
    practice = col_integer(),
    
    # Outcomes
    antibacterial_brit  = col_double(),
    population  = col_double(),
    value = col_double(),
    sex = col_character(),
    age_cat = col_character(),
    
    # Date
    date = col_date(format="%Y-%m-%d")
    
  ),
  na = character()
  )


df2 <- read_csv(
  here::here("output", "measures", "measure_STARPU_broad_spectrum.csv"),
  col_types = cols_only(
    
    # Identifier
    practice = col_integer(),
    
    # Outcomes
    broad_spectrum_antibiotics_prescriptions  = col_double(),
    population  = col_double(),
    value = col_double(),
    sex = col_character(),
    age_cat = col_character(),
    
    # Date
    date = col_date(format="%Y-%m-%d")
    
  ),
  na = character()
  )


```

###Overall antibiotics prescribing rate by month per 1000 patients

```{r echo=TRUE}

last.date=max(df1$date)
df1=df1%>% filter(date!=last.date)
first_mon <- (format(min(df1$date), "%m-%Y"))
last_mon <- (format(max(df1$date), "%m-%Y"))

df1$date <- as.Date(df1$date)
df1$cal_mon <- month(df1$date)
df1$cal_year <- year(df1$date)


dat1 <- df1

# mean list size per practice 
num_uniq_prac <- as.numeric(dim(table((df1$practice))))

df1 <- df1 %>% group_by(practice, date) %>%
  mutate(ab_count = sum(antibacterial_brit,na.rm = TRUE),
         pat_count = sum(population,na.rm = TRUE)) 

df_ab <- df1 %>% group_by (practice, date) %>%
  mutate(ab_rate_1000 = ab_count*1000/pat_count,na.rm = TRUE) %>%
  distinct(practice, date,.keep_all = TRUE)

df_ab_mean <- df_ab %>% group_by (date) %>%
  mutate(ab_rate = mean(ab_rate_1000),na.rm = TRUE) %>%
  distinct(date,.keep_all = TRUE)

# x axis treated as continuous variable

df_ab_mean$cal_mon<-as.factor(df_ab_mean$cal_mon)
df_ab_mean$Year<-as.factor(df_ab_mean$cal_year)

p1<-ggplot(df_ab_mean, aes(x=cal_mon, y=ab_rate, group=Year)) +
  geom_line(aes(color=Year))+
  geom_point(aes(color=Year))+ 
  scale_color_brewer(palette="Paired")+
  theme_minimal()+
  labs(
    title = "Overall antibiotics prescribing rate by month per 1000 patients",
    subtitle = paste(first_mon,"-",last_mon),
    caption = paste("Data from approximately", num_uniq_prac,"TPP Practices"),
    x = "Month",
    y = "Antibiotic Prescribing Rate per 1000 registered patients")
p1


```



###percentage of broad spectrum antibiotics


```{r echo=TRUE}

last.date=max(df2$date)
df2=df2%>% filter(date!=last.date)
first_mon <- (format(min(df2$date), "%m-%Y"))
last_mon <- (format(max(df2$date), "%m-%Y"))

df2$date <- as.Date(df2$date)
df2$cal_mon <- month(df2$date)
df2$cal_year <- year(df2$date)

dat2 <- df2

df2 <- df2 %>% group_by(practice, date) %>%
  mutate(broad_count = sum(broad_spectrum_antibiotics_prescriptions,na.rm = TRUE),
         pat_count = sum(population,na.rm = TRUE)) 

df_b <- df2 %>% group_by (practice, date) %>%
  mutate(broad_rate_1000 = broad_count*1000/pat_count,na.rm = TRUE) %>%
  distinct(practice, date,.keep_all = TRUE)

df_broad_mean <- df_b %>% group_by (date) %>%
  mutate(broad_rate = mean(broad_rate_1000),na.rm = TRUE) %>%
  distinct(date,.keep_all = TRUE) 

df <- merge(df_ab_mean,df_broad_mean,by = 'date')
df$prop <- df$broad_rate/df$ab_rate

df$cal_mon <- as.factor(month(df$date))

p2<-ggplot(df, aes(x=cal_mon, y=prop, group=Year)) +
  geom_line(aes(color=Year))+
  geom_point(aes(color=Year))+
  scale_color_brewer(palette="Paired")+
  theme_minimal()+
  scale_y_continuous(labels = scales::percent,breaks=seq(0, 1, by = 0.005))+
  labs(
    title = "Proportion of broad-spectrum antibiotics prescribed",
    subtitle = paste(first_mon,"-",last_mon),
    caption = paste("Data from approximately", num_uniq_prac,"TPP Practices"),
    x = "Month",
    y = "broad-spectrum antibiotics prescribing %")

p2



```



## 65+age group broad-sepctrum antibiotics prescribing percentage

```{r}

dat1 <- dat1 %>% filter(age_cat == '65-74' & age_cat =='75+')

dat1 <- dat1 %>% group_by(practice, date) %>%
  mutate(ab_count = sum(antibacterial_brit,na.rm = TRUE))



dat2 <- dat2 %>% filter(age_cat == '65-74' & age_cat =='75+')

dat2 <- dat2 %>% group_by(practice, date) %>%
  mutate(broad_count = sum(broad_spectrum_antibiotics_prescriptions,na.rm = TRUE))

datplot <- merge(dat1,dat2,by = 'date')
datplot$prop <- datplot$broad_count/datplot$ab_count


datplot$cal_mon<-as.factor(datplot$cal_mon)
datplot$Year<-as.factor(datplot$cal_year)

ggplot(datplot, aes(x=cal_mon, y=prop, group=Year)) +
  geom_line(aes(color=Year))+
  geom_point(aes(color=Year))+
  scale_color_brewer(palette="Paired")+
  theme_minimal()+
  scale_y_continuous(labels = scales::percent,breaks=seq(0, 1, by = 0.005))+
  labs(
    title = "Proportion of broad-spectrum antibiotics prescribed in 65+ age group",
    subtitle = paste(first_mon,"-",last_mon),
    caption = paste("Data from approximately", num_uniq_prac,"TPP Practices"),
    x = "Month",
    y = "broad-spectrum antibiotics prescribing %")


```



