---
title: "conditional logistic regression"
---

```{r setup, include=FALSE}
library("plyr")
library('dplyr')
library('tidyverse')
require("gtsummary")
library("survival")
library(car)
library(finalfit)
```


```{r include=FALSE}
# all data
#setwd("/Users/yayang/Documents/GitHub/amr-uom-brit/output/")
df <- read_rds(here::here("output","all_ranger.rds"))
table(df$decile)
table(df$case)
prop.table(table(df$case,df$decile))

df$case=as.factor(df$case) #1/0

df$decile= relevel(as.factor(df$decile), ref="1")

df$subclass=as.factor(df$subclass)#pair id

df$CCI= relevel(as.factor(df$CCI), ref="Zero")
df$covrx_ever= relevel(as.factor(df$covrx_ever), ref="0")

df$bmi_cat=relevel(as.factor(df$bmi_cat),ref="Healthy weight")
df$care_home=relevel(as.factor(df$care_home),ref = "0")

df$flu_vaccine=relevel(as.factor(df$flu_vaccine),ref= "0")

df$smoking_cat_3=relevel(as.factor(df$smoking_cat_3),ref="Never")
df$imd=relevel(as.factor(df$imd),ref="1")
df$ethnicity_6=relevel(as.factor(df$ethnicity_6),ref = "White")
```


```{r include=FALSE}
# probabilities

table(df$case)
explanatory<- c("prob")
dependent <- "decile"
case=df%>% filter(case==1)%>% summary_factorlist(dependent, explanatory, digits = c(3,3))
case$case=1
case2=df%>% filter(case==1)%>% summary_factorlist(dependent, explanatory,cont = "median", digits = c(3,3))
case2$case=1

contr=df%>% filter(case==0)%>% summary_factorlist(dependent, explanatory, digits = c(3,3))
contr$case=0
contr2=df%>% filter(case==0)%>% summary_factorlist(dependent, explanatory,cont = "median", digits = c(3,3))
contr2$case=0

tbl=rbind(case,contr,case2,contr2)

write.csv(tbl,here::here("output","prob.csv"))
```


```{r include=FALSE}
# decile%  by outcome

# number (%)
explanatory<- c("decile")
dependent <- "case"
tbl=df%>% summary_factorlist(dependent, explanatory)

round_tbl=tbl
#remove percentage
round_tbl[,3]=gsub("\\(.*?\\)","",round_tbl[,3])
round_tbl[,4]=gsub("\\(.*?\\)","",round_tbl[,4])

#round to 5
round_tbl[,3]=as.numeric(round_tbl[,3])
round_tbl[,3]=plyr::round_any(round_tbl[,3], 5, f = round)

round_tbl[,4]=as.numeric(round_tbl[,4])
round_tbl[,4]=plyr::round_any(round_tbl[,4], 5, f = round)

# raw OR calculated
round_tbl$OR="ref" 
for (i in 2:10) {
  round_tbl[i,"OR"]=
    round_tbl[i,4]/round_tbl[i,3]/round_tbl[1,4]*round_tbl[1,3]
}
  
  
write.csv(round_tbl,here::here("output","decile_prop.csv"))

```


#  crude model

```{r echo=FALSE}
df$case=as.numeric(df$case) #1/0
set.seed(123)

model=clogit(case ~ decile+ strata(subclass),df) 

tbl=summary(model)

result=data.frame(tbl$conf.int)
write.csv(result,here::here("output","model.csv"))

```


#  adjusted model
```{r echo=FALSE}

set.seed(123)

model=clogit(case ~ decile + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass),df) 

tbl=summary(model)
result=data.frame(tbl$conf.int)
write.csv(result,here::here("output","model_adj.csv"))

```


