---
title: "conditional logistic regression"
---

```{r setup, include=FALSE}
#library(knitr)
library(dplyr)
#library(skimr)
library('tidyverse')
require("gtsummary")
library("survival")
library(car)
library(finalfit)
```

```{r}
DF1=readRDS(here::here("output","study_1.rds"))


DF2=readRDS(here::here("output","matched_outcome_hosp.rds"))
nrow(DF2)
table(DF2$case)
prop.table(table(DF2$case))
DF2$set=2

table(DF2$level)
summary(DF2[DF2$level==1,"total_ab"])
summary(DF2[DF2$level==2,"total_ab"])
summary(DF2[DF2$level==3,"total_ab"])
summary(DF2[DF2$level==4,"total_ab"])
summary(DF2[DF2$level==5,"total_ab"])

DF3=readRDS(here::here("output","matched_outcome_general.rds"))
nrow(DF3)
table(DF3$case)
prop.table(table(DF3$case))
DF3$set=3

table(DF3$level)
summary(DF3[DF3$level==1,"total_ab"])
summary(DF3[DF3$level==2,"total_ab"])
summary(DF3[DF3$level==3,"total_ab"])
summary(DF3[DF3$level==4,"total_ab"])
summary(DF3[DF3$level==5,"total_ab"])



```





# general
##  crude model
```{r }
data=readRDS(here::here("output","study_1.rds"))

data$quintile=as.factor(data$quintile)
data$subclass=as.factor(data$subclass)#pair id

data$case=as.numeric(data$case) #1/0
model=clogit(case ~ level+ strata(subclass),data) 
summary(model)
```

# hosp
##  crude model
```{r }
data=readRDS(here::here("output","study_2.rds"))

data$quintile=as.factor(data$quintile)
data$subclass=as.factor(data$subclass)#pair id

data$case=as.numeric(data$case) #1/0
model=clogit(case ~ level+ strata(subclass),data) 
summary(model)
```


# death
##  crude model
```{r }
data=readRDS(here::here("output","study_3.rds"))

data$quintile=as.factor(data$quintile)
data$subclass=as.factor(data$subclass)#pair id

data$case=as.numeric(data$case) #1/0
model=clogit(case ~ level+ strata(subclass),data) 
summary(model)
```



