---
title: "complete case"
---

```{r setup, include=FALSE}
library("plyr")
library('dplyr')
library('tidyverse')
require("gtsummary")
library("survival")
library(car)
library(finalfit)
```


```{r include=FALSE}
# all data
#setwd("/Users/yayang/Documents/GitHub/amr-uom-brit/output/")
df <- read_rds(here::here("output","all_ranger.rds"))
table(df$decile)
table(df$case)
prop.table(table(df$case,df$decile))

df$case=as.numeric(df$case) #1/0

df$decile= relevel(as.factor(df$decile), ref="1")

df$subclass=as.factor(df$subclass)#pair id

df$CCI= relevel(as.factor(df$CCI), ref="Zero")
df$covrx_ever= relevel(as.factor(df$covrx_ever), ref="0")

df$bmi_cat=relevel(as.factor(df$bmi_cat),ref="Healthy weight")
df$care_home=relevel(as.factor(df$care_home),ref = "0")

df$flu_vaccine=relevel(as.factor(df$flu_vaccine),ref= "0")

df$smoking_cat_3=relevel(as.factor(df$smoking_cat_3),ref="Never")
df$imd=relevel(as.factor(df$imd),ref="1")
df$ethnicity_6=relevel(as.factor(df$ethnicity_6),ref = "White")
DF=df
```


# ethnicity
```{r}

## ethnicity
# remove control missing
df$exclude.controls=ifelse(df$case==0 & df$ethnicity_6=="Unknown",1,0)

df=df%>%filter(exclude.controls != 1)

# remove whole subclass (case missing)
df$exclude.case=ifelse(df$case==1 & df$ethnicity_6=="Unknown",1,0)
df=df%>%group_by(subclass)%>%mutate(exclude.subclass= max(exclude.case))
df=df%>%filter(exclude.subclass !=1)
df=df%>%ungroup(subclass)

nrow(df)

set.seed(123)

model=clogit(case ~ decile + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass),DF) 

tbl=summary(model)
result=data.frame(tbl$conf.int) 
write.csv(result,here::here("output","model_cas_ethnicity.csv"))

```

# bmi
```{r}


df=DF
## BMI
# remove control missing
df$exclude.controls=ifelse(df$case==0 & df$bmi_cat=="Unknown",1,0)

df=df%>%filter(exclude.controls != 1)

# remove whole subclass (case missing)
df$exclude.case=ifelse(df$case==1 & df$bmi_cat=="Unknown",1,0)
df=df%>%group_by(subclass)%>%mutate(exclude.subclass= max(exclude.case))
df=df%>%filter(exclude.subclass !=1)
df=df%>%ungroup(subclass)

nrow(df)

set.seed(123)

model=clogit(case ~ decile + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass),DF) 

tbl=summary(model)
result=data.frame(tbl$conf.int) 
write.csv(result,here::here("output","model_cas_bmi.csv"))

```

# smoking
```{r}


df=DF
##Smoking
# remove control missing
df$exclude.controls=ifelse(df$case==0 & df$smoking_cat_3=="Unknown",1,0)
df=df%>%filter(exclude.controls != 1)

# remove whole subclass (case missing)
df$exclude.case=ifelse(df$case==1 & df$smoking_cat_3=="Unknown",1,0)
df=df%>%group_by(subclass)%>%mutate(exclude.subclass= max(exclude.case))
df=df%>%filter(exclude.subclass !=1)
df=df%>%ungroup(subclass)
nrow(df)


set.seed(123)

model=clogit(case ~ decile + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass),DF) 

tbl=summary(model)
result=data.frame(tbl$conf.int) 
write.csv(result,here::here("output","model_cas_smoking.csv"))

```

# IMD
```{r}

df=DF

##IMD
# remove control missing
df$exclude.controls=ifelse(df$case==0 & df$imd=="Unknown",1,0)
df=df%>%filter(exclude.controls != 1)

# remove whole subclass (case missing)
df$exclude.case=ifelse(df$case==1 & df$imd=="Unknown",1,0)
df=df%>%group_by(subclass)%>%mutate(exclude.subclass= max(exclude.case))
df=df%>%filter(exclude.subclass !=1)
df=df%>%ungroup(subclass)

nrow(DF)


set.seed(123)

model=clogit(case ~ decile + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass),DF) 

tbl=summary(model)
result=data.frame(tbl$conf.int) 
write.csv(result,here::here("output","model_cas_imd.csv"))

```

# complete case analysis
```{r}

df=DF


###### remove NA
## ethnicity
# remove control missing
df$exclude.controls=ifelse(df$case==0 & df$ethnicity_6=="Unknown",1,0)

df=df%>%filter(exclude.controls != 1)

# remove whole subclass (case missing)
df$exclude.case=ifelse(df$case==1 & df$ethnicity_6=="Unknown",1,0)
df=df%>%group_by(subclass)%>%mutate(exclude.subclass= max(exclude.case))
df=df%>%filter(exclude.subclass !=1)
df=df%>%ungroup(subclass)

## BMI
# remove control missing
df$exclude.controls=ifelse(df$case==0 & df$bmi_cat=="Unknown",1,0)

df=df%>%filter(exclude.controls != 1)

# remove whole subclass (case missing)
df$exclude.case=ifelse(df$case==1 & df$bmi_cat=="Unknown",1,0)
df=df%>%group_by(subclass)%>%mutate(exclude.subclass= max(exclude.case))
df=df%>%filter(exclude.subclass !=1)
df=df%>%ungroup(subclass)


##Smoking
# remove control missing
df$exclude.controls=ifelse(df$case==0 & df$smoking_cat_3=="Unknown",1,0)
df=df%>%filter(exclude.controls != 1)

# remove whole subclass (case missing)
df$exclude.case=ifelse(df$case==1 & df$smoking_cat_3=="Unknown",1,0)
df=df%>%group_by(subclass)%>%mutate(exclude.subclass= max(exclude.case))
df=df%>%filter(exclude.subclass !=1)
df=df%>%ungroup(subclass)


##IMD
# remove control missing
df$exclude.controls=ifelse(df$case==0 & df$imd=="Unknown",1,0)
df=df%>%filter(exclude.controls != 1)

# remove whole subclass (case missing)
df$exclude.case=ifelse(df$case==1 & df$imd=="Unknown",1,0)
df=df%>%group_by(subclass)%>%mutate(exclude.subclass= max(exclude.case))
df=df%>%filter(exclude.subclass !=1)
df=df%>%ungroup(subclass)

set.seed(123)

model=clogit(case ~ decile + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass),DF) 

tbl=summary(model)
result=data.frame(tbl$conf.int) 
write.csv(result,here::here("output","model_cas.csv"))
```

