---
title: "classification_decision tree - category predictor "
---

```{r setup, include=FALSE}
library("survival")
library('tidyverse')
library(pROC) #plyr
library(caret) #dplyr
library(randomForest)
library("rpart.plot")
```


```{r }
# import dataset
train <- read_rds(here::here("output","train_cat_hosp.rds"))
train$case=as.factor(as.character(train$case))

table(train$case)
#table(train$case)
prop.table(table(train$case))

# pick variable
names(train)
col=c("case","total_ab_group","ab_types_group",
      "exposure_period_group","recent_ab_days_group",
      "broad_ab_prescriptions_group",
      "interval_med_group" ,"interval_mean_group","interval_sd_group","interval_CV_group",
      "length_med_group" ,"length_mean_group","length_sd_group","length_CV_group")
#"broad_prop_total"

data=train[col]
str(data)

```

```{r}

prop.table(table(data$total_ab_group))
prop.table(table(data$ab_types_group ))
prop.table(table(data$exposure_period_group ))
prop.table(table(data$recent_ab_days_group ))
prop.table(table(data$broad_ab_prescriptions_group ))
prop.table(table(data$interval_med_group))
prop.table(table(data$interval_mean_group))
prop.table(table(data$interval_sd_group))
prop.table(table(data$interval_CV_group))
prop.table(table(data$length_med_group))
prop.table(table(data$length_mean_group))
prop.table(table(data$length_sd_group))
prop.table(table(data$length_CV_group))
```


## matched 

### overall tree1
```{r  }
set.seed(1024)
model <-train(case ~. , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

summary(predict(model, type = 'prob')[,2])
```

### overall tree 2
```{r  }
set.seed(999)
model <-train(case ~. , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

summary(predict(model, type = 'prob')[,2])
```


### overall tree 3
```{r  }
set.seed(3)
model <-train(case ~. , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

summary(predict(model, type = 'prob')[,2])
```

### total_ab_group 
```{r, fig.width=13, fig.height=20 }
set.seed(1024)
model <-train(case ~total_ab_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

summary(predict(model, type = 'prob')[,2])
```
<br/><br/>

### ab_types_group
```{r }
set.seed(1024)
model <-train(case ~ab_types_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))
summary(predict(model, type = 'prob')[,2])
```

### exposure_period_group
```{r }
set.seed(1024)
model <-train(case ~exposure_period_group , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))
summary(predict(model, type = 'prob')[,2])
```

### recent_ab_days_group
```{r }
set.seed(1024)
model <-train(case ~recent_ab_days_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))
summary(predict(model, type = 'prob')[,2])
```

### broad_ab_prescriptions_group
```{r }
set.seed(1024)
#try(model <-train(case ~broad_ab_prescriptions_group, 
#                  data=data, method="rpart",
 #                 trControl = trainControl("cv", number = 5),
  #                tuneLength=5))
table(data$broad_ab_prescriptions_group)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))
summary(predict(model, type = 'prob')[,2])
```

### interval_med_group
```{r }
set.seed(1024)
model <-train(case ~interval_med_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))
summary(predict(model, type = 'prob')[,2])
```
### interval_mean_group
```{r }
set.seed(1024)
model <-train(case ~interval_mean_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))
summary(predict(model, type = 'prob')[,2])
```
### interval_sd_group
```{r }
set.seed(1024)
model <-train(case ~interval_sd_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))
summary(predict(model, type = 'prob')[,2])
```

### interval_CV_group
```{r }
set.seed(1024)
model <-train(case ~interval_CV_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))
summary(predict(model, type = 'prob')[,2])
```


### length_med_group
```{r }
set.seed(1024)
model <-train(case ~length_med_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))
summary(predict(model, type = 'prob')[,2])
```
### length_mean_group
```{r }
set.seed(1024)
model <-train(case ~length_mean_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))
summary(predict(model, type = 'prob')[,2])
```
### length_sd_group
```{r }
set.seed(1024)
model <-train(case ~length_sd_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))
summary(predict(model, type = 'prob')[,2])
```

### length_CV_group
```{r }
set.seed(1024)
model <-train(case ~length_CV_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))
summary(predict(model, type = 'prob')[,2])
```




### overall tree1
```{r  }
set.seed(1024)
model <-train(case ~. , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

summary(predict(model, type = 'prob')[,2])
```

### overall tree 2
```{r  }
set.seed(999)
model <-train(case ~. , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

summary(predict(model, type = 'prob')[,2])
```


### overall tree 3
```{r  }
set.seed(3)
model <-train(case ~. , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

summary(predict(model, type = 'prob')[,2])
```
