---
title: "divide train/valid dataset"
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(skimr)
library('tidyverse')

library("ggplot2")

library(caret)
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")

```



# import dataset
```{r }
#df <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_ab.rds")
df <- read_rds(here::here("output","matched_ab_hosp.rds"))
table(df$case)
nrow(df)
prop.table(table(df$case))

df=df[!is.na(df$case),]
table(df$case)
nrow(df)
prop.table(table(df$case))

```


```{r eval=FALSE, include=FALSE}
# import antibiotics types

#DF <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/abtype79.rds")
DF<- read_rds(here::here("output","abtype79_hosp.rds"))
table(DF$case)
names(DF)

DF=DF%>% select(-c("case","subclass"))
DF=DF%>% distinct(patient_id,patient_index_date, .keep_all=T)
table(DF$case)

col=c("Rx_Amikacin", "Rx_Amoxicillin", "Rx_Ampicillin", "Rx_Azithromycin", "Rx_Aztreonam", "Rx_Benzylpenicillin", "Rx_Cefaclor", "Rx_Cefadroxil", "Rx_Cefalexin", "Rx_Cefamandole", "Rx_Cefazolin", "Rx_Cefepime", "Rx_Cefixime", "Rx_Cefotaxime", "Rx_Cefoxitin", "Rx_Cefpirome", "Rx_Cefpodoxime", "Rx_Cefprozil", "Rx_Cefradine", "Rx_Ceftazidime", "Rx_Ceftriaxone", "Rx_Cefuroxime", "Rx_Chloramphenicol", "Rx_Cilastatin", "Rx_Ciprofloxacin", "Rx_Clarithromycin", "Rx_Clindamycin", "Rx_Co_amoxiclav", "Rx_Co_fluampicil", "Rx_Colistimethate", "Rx_Dalbavancin", "Rx_Dalfopristin", "Rx_Daptomycin", "Rx_Demeclocycline", "Rx_Doripenem", "Rx_Doxycycline", "Rx_Ertapenem", "Rx_Erythromycin", "Rx_Fidaxomicin", "Rx_Flucloxacillin", "Rx_Fosfomycin", "Rx_Fusidate", "Rx_Gentamicin", "Rx_Levofloxacin", "Rx_Linezolid", "Rx_Lymecycline", "Rx_Meropenem", "Rx_Methenamine", "Rx_Metronidazole", "Rx_Minocycline", "Rx_Moxifloxacin", "Rx_Nalidixic_acid", "Rx_Neomycin", "Rx_Netilmicin", "Rx_Nitazoxanid", "Rx_Nitrofurantoin", "Rx_Norfloxacin", "Rx_Ofloxacin", "Rx_Oxytetracycline", "Rx_Phenoxymethylpenicillin", "Rx_Piperacillin", "Rx_Pivmecillinam", "Rx_Pristinamycin", "Rx_Rifaximin", "Rx_Sulfadiazine", "Rx_Sulfamethoxazole", "Rx_Sulfapyridine", "Rx_Taurolidin", "Rx_Tedizolid", "Rx_Teicoplanin", "Rx_Telithromycin", "Rx_Temocillin", "Rx_Tetracycline", "Rx_Ticarcillin", "Rx_Tigecycline", "Rx_Tinidazole", "Rx_Tobramycin", "Rx_Trimethoprim", "Rx_Vancomycin")


#remove not used AB 

table=data.frame(colSums(DF[col]))
table=table%>% filter(table[,1]>0)
col=rownames(table) # selected columns

length(col) # 55

saveRDS(col,here::here("output","abtype_hosp.rds"))

# merge data
df=merge(df,DF,by=c("patient_id","patient_index_date"), all.x = T)
rm(DF)
table(df$case)
str(df)
```



# random assign subclass to train and valid set
```{r}

subclass=unique(df$subclass)

set.seed(1024)
train_idx <- sample(subclass,  length(subclass)* 0.8)
length(train_idx)

valid_idx <- subclass[!subclass %in% train_idx]
length(valid_idx)

#pred_col=c("patient_id","patient_index_date", "case","subclass","total_ab", "ab_prescriptions","ab_types","prescribe_times","exposure_period","recent_ab_days", "broad_prop" ,"broad_ab_prescriptions","interval_mean","interval_sd","interval_CV","length_mean", "length_sd", "length_CV","prescribe_time_0","prescribe_time_1","prescribe_time_2","prescribe_time_3",col,"AB_1_type","AB_6wk_type" ,"interval_med" ,"length_med" ,"ab_6w_binary" , "AB_6wk")
train_X =df %>% filter(subclass %in% train_idx)
prop.table(table(train_X$case))
table(train_X$case)
nrow(train_X)

valid_X =df %>% filter(subclass %in% valid_idx)
prop.table(table(valid_X$case))
table(valid_X$case)
nrow(valid_X)

```


```{r}
saveRDS(train_X, here::here("output","train_hosp.rds"))
saveRDS(valid_X, here::here("output","valid_hosp.rds"))

```


# categorised ab exposure variables
```{r}
train_X$set=1
valid_X$set=2
df=rbind(train_X, valid_X)
nrow(df)

col=c("case","subclass","set",
  "total_ab","ab_types","prescribe_times",
         "exposure_period","recent_ab_days", 
         "broad_prop","broad_ab_prescriptions",
         "interval_mean","interval_med" ,"interval_sd","interval_CV",
         "length_mean","length_med", "length_sd","length_CV")

df=df %>% mutate_at(col,as.numeric)
df=df[col]
names(df)
```


### group variables
```{r}
for (k in 4:18) {

cut_value=quantile(df[,col[k]],c(0.25,0.5,0.75))
print(cut_value)
  
df[,paste0(col[k],"_group")]=ifelse(
  df[,col[k]] <= cut_value[1],1,NA)  

df[,paste0(col[k],"_group")]=ifelse(
  df[,col[k]] > cut_value[1] & df[,col[k]]<= cut_value[2],2, 
  df[,paste0(col[k],"_group")])  

df[,paste0(col[k],"_group")]=ifelse(
  df[,col[k]] > cut_value[2] & df[,col[k]]<= cut_value[3],3, 
  df[,paste0(col[k],"_group")])  

df[,paste0(col[k],"_group")]=ifelse(
  df[,col[k]] > cut_value[3],4,df[,paste0(col[k],"_group")])  

df[,paste0(col[k],"_group")]=ifelse(
 is.na( df[,col[k]]) ,0 ,df[,paste0(col[k],"_group")])  



}
```


```{r }
df$total_ab_group=relevel(as.factor(df$total_ab_group),ref= "1")
df$ab_types_group=relevel(as.factor(df$ab_types_group),ref= "1")
df$exposure_period_group=relevel(as.factor(df$exposure_period_group),ref= "1")
df$recent_ab_days_group=relevel(as.factor(df$recent_ab_days_group),ref= "1")
df$broad_prop_group=relevel(as.factor(df$broad_prop_group),ref= "1")
df$broad_ab_prescriptions_group=relevel(as.factor(df$broad_ab_prescriptions_group),ref= "1")
df$interval_mean_group=relevel(as.factor(df$interval_mean_group),ref= "1")
df$interval_med_group=relevel(as.factor(df$interval_med_group),ref= "1")
df$interval_CV_group=relevel(as.factor(df$interval_CV_group),ref= "1")
df$interval_sd_group=relevel(as.factor(df$interval_sd_group),ref= "1")
df$length_med_group=relevel(as.factor(df$length_med_group),ref= "1")
df$length_mean_group=relevel(as.factor(df$length_mean_group),ref= "1")
df$length_CV_group=relevel(as.factor(df$length_CV_group),ref= "1")
df$length_sd_group=relevel(as.factor(df$length_sd_group),ref= "1")
```


```{r}
prop.table(table(df$total_ab_group))
prop.table(table(df$ab_types_group))
prop.table(table(df$exposure_period_group))
prop.table(table(df$recent_ab_days_group))
prop.table(table(df$broad_ab_prescriptions_group))
prop.table(table(df$interval_med_group))
prop.table(table(df$interval_sd_group))

```

```{r}

df1=df%>% filter(set==1)
df2=df%>% filter(set==2)
saveRDS(df1,here::here("output","train_cat_hosp.rds"))
saveRDS(df2,here::here("output","valid_cat_hosp.rds"))