---
title: "Random Forest model_hospital admission"
---

```{r setup, include=FALSE}
library(dplyr)
library('tidyverse')
library(pROC)
library(randomForest)

```

# train and valid dataset (matched)
```{r }
train <- read_rds(here::here("output","train_cat.rds"))
train$case=as.factor(train$case)
valid <- read_rds(here::here("output","valid_cat.rds"))
valid$case=as.factor(valid$case)

#names(train)
```

## compare patient number 
```{r}

nrow(train)# train patients (matched)
table(train$case)# total train patients
prop.table(table(train$case))# % train patients

nrow(valid)# valid patients(matched)
table(valid$case)# total valid patients
prop.table(table(valid$case))# % valid patients
```


pick variable
```{r}
names(train)


col=c("case","total_ab_group","ab_types_group",
      "exposure_period_group","recent_ab_days_group",
      "broad_ab_prescriptions_group",
    "interval_mean_group","interval_sd_group")
# abtype
#valid_X=valid[col]

str(train)
```

# random select subclass
```{r}
nrow(train)
train_X=train %>% group_by(case, subclass) %>% sample_n(1)
train_X=train_X%>% ungroup(case, subclass)
nrow(train_X)

train_X=train_X[col]

```

# RF. fraction.sample
```{r}
library(randomForest)

sample_n=as.numeric(table(train_X$case)[2]*0.5)
sample_n
rf.model<- randomForest(formula = case ~ ., data = train_X, 
                           replace = TRUE,
                      #     sampsize=c(sample_n,sample_n), 
                     #      strata=train_X$case,
                           samplsize=0.8,
                           ntree =  2000,
                           nodesize = 100 ,
                           mtry = 3
                          )
# run over 1 wk: 0.6 size 1000 trees
saveRDS(rf.model,here::here("output","RF_model.rds"))
```


```{r}
importance(rf.model)
varImpPlot(rf.model)

```



# development set
## predict probabilities 
```{r }
data=train

prob <- predict(rf.model,data, type = 'prob')[,2]# votes of being case

summary(prob)
hist(prob)
sum(prob==0)/length(prob)# % zero

#exp.class <- predict(rf.model, data, type = 'response')# predicted case/control
#prop.table(summary(exp.class))
```


## create decile group
```{r}

vec=vector()

for (i in 1:10){
  vec[i]=quantile(prob,(i/10),na.rm=T)
}

vec# decile value

decile=vector()
decile=ifelse(prob <=vec[1],1,decile)

for (i in 1:9) {
decile=ifelse(prob >vec[i] & prob <=vec[i+1],i+1,decile )  
}


table(decile)
prop.table(table(decile))*100 

```

## combine columns
```{r}
head(decile)
head(prob)

newdata <- cbind(data,decile,prob)

str(newdata)
```


## check decile distribution
```{r}
for (i in 1:10) {
  
  print(paste0("decile=",i))
  print(summary(newdata[decile==i,]$prob))

}
nrow(newdata)

development=newdata
rm(newdata)
rm(data)
```



# validation set
## predict probabilities 
```{r }
data=valid

prob <- predict(rf.model, data, type = 'prob')[,2]# votes of being case

summary(prob)
hist(prob)
sum(prob==0)/length(prob)# % zero

#exp.class <- predict(rf.model, data, type = 'response')# predicted case/control
#prop.table(summary(exp.class))
```



## create decile group
```{r}

vec=vector()

for (i in 1:10){
  vec[i]=quantile(prob,(i/10),na.rm=T)
}

vec# decile value

decile=vector()
decile=ifelse(prob <=vec[1],1,decile)

for (i in 1:9) {
decile=ifelse(prob >vec[i] & prob <=vec[i+1],i+1,decile )  
}


table(decile)
prop.table(table(decile))*100 # % decile
```

## combine columns
```{r}
head(decile)
head(prob)

newdata <- cbind(data,decile,prob)
str(newdata)
```


## check decile distribution
```{r}
for (i in 1:10) {
  
  print(paste0("decile=",i))
  print(summary(newdata[decile==i,]$prob))

}
nrow(newdata)

validation=newdata
rm(newdata)
rm(data)
```


```{r}
nrow(development)
nrow(validation)
```


```{r}
saveRDS(development,here::here("output","development.rds"))
saveRDS(validation,here::here("output","validation.rds"))

str(development)
```





```{r eval=FALSE, include=FALSE}
# RF_ranger
library(ranger)

#Compute weights to balance the RF
w <- 1/table(train_X$case)
w <- w/sum(w)
w
weights <- rep(0, nrow(train_X))
weights[train$case == 0] <- w['0']
weights[train$case == 1] <- w['1']
table(weights, train_X$case)

set.seed(1024)

    rf.model <- ranger(formula = case ~ ., 
                   data = train_X,
                   num.trees =  3000,
                   min.node.size = 100,
                   importance = "impurity",
                   replace = TRUE,
                   probability = TRUE,
                   case.weights=weights
                   )

  print(rf.model)
  
  
```

```{r eval=FALSE, include=FALSE}
data=train

prob <- predict(rf.model, data=train)$prediction[,2]# probabilities

summary(prob)
hist(prob)
sum(prob==0)/length(prob)# % zero

#exp.class <- predict(rf.model, data, type = 'response')# predicted case/control
#prop.table(summary(exp.class))
```

```{r eval=FALSE, include=FALSE}
data=valid

prob <- predict(rf.model, data=valid)$prediction[,2]# probabiliteis

summary(prob)
hist(prob)
sum(prob==0)/length(prob)# % zero


```