---
title: "Random Forest"
---

```{r setup, include=FALSE}

library("survival")
library('tidyverse')
library(pROC) #plyr
#library(randomForest) #dplyr
library(ranger)
```

# import dataset
```{r }
#data <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_ab.rds")
data <- read_rds(here::here("output","matched_ab.rds"))
table(data$case)
nrow(data)
prop.table(table(data$case))

data=data[!is.na(data$case),]
table(data$case)
nrow(data)
prop.table(table(data$case))

```

# replace outlier
```{r}
range(data$total_ab)
range(data$ab_types)
range(data$exposure_period)
range(data$recent_ab_days)
range(data$broad_ab_prescriptions)
range(data$interval_mean)
range(data$interval_sd)


#90 percentile
N1=quantile(data$total_ab,0.9,na.rm = T)
N2=quantile(data$ab_types,0.9,na.rm = T)
N3=quantile(data$exposure_period,0.9,na.rm = T)
N4=quantile(data$recent_ab_days,0.9,na.rm = T)
N5=quantile(data$broad_ab_prescriptions,0.9,na.rm = T)
N6=quantile(data$interval_mean,0.9,na.rm = T)
N7=quantile(data$interval_sd,0.9,na.rm = T)

N=c(N1,N2,N3,N4,N5,N6,N7)
N

col=c("total_ab","ab_types","exposure_period","recent_ab_days","broad_ab_prescriptions","interval_mean","interval_sd")
```


```{r}
for (i in 1:7) {
  data[,col[i]]=ifelse( data[,col[i]]>=N[i],N[i], data[,col[i]])
}
```




# random assign subclass to train and valid set
```{r}
df=data
subclass=unique(df$subclass)

set.seed(1024)
train_idx <- sample(subclass,  length(subclass)* 0.8)
length(train_idx)

valid_idx <- subclass[!subclass %in% train_idx]
length(valid_idx)

train =df %>% filter(subclass %in% train_idx)
prop.table(table(train$case))
table(train$case)
nrow(train)

valid =df %>% filter(subclass %in% valid_idx)
prop.table(table(valid$case))
table(valid$case)
nrow(valid)

```


# categorised ab exposure variables
```{r eval=FALSE, include=FALSE}

col=c("case","subclass",
  "total_ab","ab_types","prescribe_times",
         "exposure_period","recent_ab_days", 
         "broad_prop","broad_ab_prescriptions",
         "interval_mean","interval_med" ,"interval_sd","interval_CV",
         "length_mean","length_med", "length_sd","length_CV")

data=data %>% mutate_at(col,as.numeric)
names(data)


for (k in 3:17) {

cut_value=quantile(data[,col[k]],c(0.25,0.5,0.75))
print(cut_value)
  
data[,paste0(col[k],"_group")]=ifelse(
  data[,col[k]] <= cut_value[1],1,NA)  

data[,paste0(col[k],"_group")]=ifelse(
  data[,col[k]] > cut_value[1] & data[,col[k]]<= cut_value[2],2, 
  data[,paste0(col[k],"_group")])  

data[,paste0(col[k],"_group")]=ifelse(
  data[,col[k]] > cut_value[2] & data[,col[k]]<= cut_value[3],3, 
  data[,paste0(col[k],"_group")])  

data[,paste0(col[k],"_group")]=ifelse(
  data[,col[k]] > cut_value[3],4,data[,paste0(col[k],"_group")])  

data[,paste0(col[k],"_group")]=ifelse(
 is.na( data[,col[k]]) ,0 ,data[,paste0(col[k],"_group")])  



}

data$total_ab_group=relevel(as.factor(data$total_ab_group),ref= "1")
data$ab_types_group=relevel(as.factor(data$ab_types_group),ref= "1")
data$exposure_period_group=relevel(as.factor(data$exposure_period_group),ref= "1")
data$recent_ab_days_group=relevel(as.factor(data$recent_ab_days_group),ref= "1")
data$broad_prop_group=relevel(as.factor(data$broad_prop_group),ref= "1")
data$broad_ab_prescriptions_group=relevel(as.factor(data$broad_ab_prescriptions_group),ref= "1")
data$interval_mean_group=relevel(as.factor(data$interval_mean_group),ref= "1")
data$interval_med_group=relevel(as.factor(data$interval_med_group),ref= "1")
data$interval_CV_group=relevel(as.factor(data$interval_CV_group),ref= "1")
data$interval_sd_group=relevel(as.factor(data$interval_sd_group),ref= "1")
data$length_med_group=relevel(as.factor(data$length_med_group),ref= "1")
data$length_mean_group=relevel(as.factor(data$length_mean_group),ref= "1")
data$length_CV_group=relevel(as.factor(data$length_CV_group),ref= "1")
data$length_sd_group=relevel(as.factor(data$length_sd_group),ref= "1")

prop.table(table(data$total_ab_group))
prop.table(table(data$ab_types_group))
prop.table(table(data$exposure_period_group))
prop.table(table(data$recent_ab_days_group))
prop.table(table(data$broad_ab_prescriptions_group))
prop.table(table(data$interval_med_group))
prop.table(table(data$interval_sd_group))

```

# RF. ranger probability machine
```{r}
library(ranger)

set.seed(123)

rf.model= ranger(formula = case ~ total_ab+ab_types+exposure_period+recent_ab_days+broad_ab_prescriptions+interval_mean+interval_sd, 
                   data = train,
                   num.trees =   2000,
                   min.node.size = 100,
                   mtry = 3,
                  case.fraction = 0.5,
                   importance = "impurity",
                   replace = TRUE,
                   probability = TRUE
                          )
# run over 1 wk: 0.6 size 1000 trees
saveRDS(rf.model,here::here("output","RF_ranger_contd.rds"))
```

# variable importance
```{r}

# calculate relative importance
imps <- data.frame(var = names(rf.model$variable.importance),
                   imps = rf.model$variable.importance/max(rf.model$variable.importance),
                   imps.score=rf.model$variable.importance)

# rename variable
imps$var
imps$var=c("Total antibiotics","Antibiotic types","Exposure period","Recent exposure", "Broad-spectrum antibiotics","Prescribing intervals (mean)", "Prescribing intervals (SD)")

imps %>% 
  ggplot(aes(imps, x = reorder(var, imps))) +
  geom_point(size = 3, colour = "grey60") +
  coord_flip() +
  labs(x = "", y = "Importance") +
  theme_bw(15)

imps %>% 
  ggplot(aes(imps.score, x = reorder(var, imps.score))) +
  geom_point(size = 3, colour = "grey60", ) +
  coord_flip() +
  labs(x = "", y = "Importance Score") +
  theme_bw(15)
```

# train
## predict probabilities 
```{r }
data=train
set.seed(123)
data$prob <- predict(rf.model,data, type = 'response')$prediction[,2]# votes of being case

summary(data$prob)
hist(data$prob )
sum(data$prob ==0)/length(data$prob)# % zero



#exp.class <- predict(rf.model, data, type = 'response')# predicted case/control
#prop.table(summary(exp.class))
```



```{r}

#  c statistic / AUC
roc_data <- roc(data$case ~data$prob, smoothed = TRUE,
            ci=TRUE, ci.alpha=0.9, stratified=FALSE,
            plot=TRUE, auc.polygon=TRUE, max.auc.polygon=TRUE, grid=TRUE,
            print.auc=TRUE, show.thres=TRUE)
print(roc_data) #AUC


# E/O
O <- prop.table(table(data$case))[2]
E <- mean(data$prob)
E/O
```

## create decile group
```{r }
prob=data$prob
vec=vector()

for (i in 1:10){
  vec[i]=quantile(prob,(i/10),na.rm=T)
}

vec# decile value

decile=vector()
decile=ifelse(prob <=vec[1],1,decile)

for (i in 1:9) {
decile=ifelse(prob>vec[i] & prob <=vec[i+1],i+1,decile )  
}


table(decile)
prop.table(table(decile))*100 
data=cbind(data,decile)
```


```{r}
# calibration 
gpdata=data%>%select(decile, case, prob)

table(gpdata$decile)
summary(gpdata[gpdata$decile==1,])
head(gpdata)

obs=gpdata%>%group_by(decile)%>%dplyr::summarise(mean.obs=mean(as.numeric(as.character(case))))
obs=obs%>% pull(mean.obs)

#obs <- (ddply(gpdata,~groups,summarise,mean=mean(as.numeric(as.character(case))))[,2])
exp=gpdata%>% group_by(decile)%>% dplyr::summarise(mean.exp=mean(as.numeric(prob)))
exp=exp%>%pull(mean.exp)

#exp <- ddply(gpdata,~groups,summarise,mean=mean(pred.y))
obsn <- table(data$case,data$decile)[1,] 

cbind(exp,obs)# expected value vs. observed value
 
# CIs for scatter points
lci = pmax(0,(obs - (1.96*(((obs*(1-obs))/obsn)^.5))))
uci = pmin(1,(obs+ (1.96*(((obs*(1-obs))/obsn)^.5))))

# graph a simple calibration plot over 10 risk groups
par(pty="s")
plot(obs~exp,xlim=c(0,1),ylim=c(0,1),col="red",ylab="Observed",xlab="Expected")
lines(c(0,1),c(0,1),lty=2)

for(i in 1:10){
lines(c(exp[i],exp[i]),c(lci[i],uci[i]),col="green")
}

h <- hist(data$prob, breaks=50, plot=FALSE)
for(i in 1:length(h$mids)){
  lines(c(h$mids[i],h$mids[i]),c(rep(1,length(h$mids))[i],1-((h$counts[i]/max(h$counts))/10)))
}

# Add a loess smoother to the plot
obs_all <- predict(loess(as.numeric(as.character(data$case))~data$prob,span=1))
lines_data <- data.frame(data$prob,obs_all)
lines_data2 <- lines_data[order(data$prob),] 
lines(lines_data2[,1],lines_data2[,2],col="blue")
legend(0.0,0.9,c("Risk groups","Reference line","95% CI","Loess"),col=c("red","black","green","blue"),lty=c(0,2,1,1),pch=c(1,NA,NA,NA),bty="n")

```


```{r}
names(data)
saveRDS(data,here::here("output","all_ranger_contd_train.rds"))
```

# valid
## predict probabilities 
```{r }
data=valid
set.seed(123)
data$prob <- predict(rf.model,data, type = 'response')$prediction[,2]# votes of being case

summary(data$prob)
hist(data$prob )
sum(data$prob ==0)/length(data$prob)# % zero



#exp.class <- predict(rf.model, data, type = 'response')# predicted case/control
#prop.table(summary(exp.class))
```



```{r}

#  c statistic / AUC
roc_data <- roc(data$case ~data$prob, smoothed = TRUE,
            ci=TRUE, ci.alpha=0.9, stratified=FALSE,
            plot=TRUE, auc.polygon=TRUE, max.auc.polygon=TRUE, grid=TRUE,
            print.auc=TRUE, show.thres=TRUE)
print(roc_data) #AUC


# E/O
O <- prop.table(table(data$case))[2]
E <- mean(data$prob)
E/O
```

## create decile group
```{r }
prob=data$prob
vec=vector()

for (i in 1:10){
  vec[i]=quantile(prob,(i/10),na.rm=T)
}

vec# decile value

decile=vector()
decile=ifelse(prob <=vec[1],1,decile)

for (i in 1:9) {
decile=ifelse(prob>vec[i] & prob <=vec[i+1],i+1,decile )  
}


table(decile)
prop.table(table(decile))*100 
data=cbind(data,decile)
```


```{r}
# calibration 
gpdata=data%>%select(decile, case, prob)

table(gpdata$decile)
summary(gpdata[gpdata$decile==1,])
head(gpdata)

obs=gpdata%>%group_by(decile)%>%dplyr::summarise(mean.obs=mean(as.numeric(as.character(case))))
obs=obs%>% pull(mean.obs)

#obs <- (ddply(gpdata,~groups,summarise,mean=mean(as.numeric(as.character(case))))[,2])
exp=gpdata%>% group_by(decile)%>% dplyr::summarise(mean.exp=mean(as.numeric(prob)))
exp=exp%>%pull(mean.exp)

#exp <- ddply(gpdata,~groups,summarise,mean=mean(pred.y))
obsn <- table(data$case,data$decile)[1,] 

cbind(exp,obs)# expected value vs. observed value
 
# CIs for scatter points
lci = pmax(0,(obs - (1.96*(((obs*(1-obs))/obsn)^.5))))
uci = pmin(1,(obs+ (1.96*(((obs*(1-obs))/obsn)^.5))))

# graph a simple calibration plot over 10 risk groups
par(pty="s")
plot(obs~exp,xlim=c(0,1),ylim=c(0,1),col="red",ylab="Observed",xlab="Expected")
lines(c(0,1),c(0,1),lty=2)

for(i in 1:10){
lines(c(exp[i],exp[i]),c(lci[i],uci[i]),col="green")
}

h <- hist(data$prob, breaks=50, plot=FALSE)
for(i in 1:length(h$mids)){
  lines(c(h$mids[i],h$mids[i]),c(rep(1,length(h$mids))[i],1-((h$counts[i]/max(h$counts))/10)))
}

# Add a loess smoother to the plot
obs_all <- predict(loess(as.numeric(as.character(data$case))~data$prob,span=1))
lines_data <- data.frame(data$prob,obs_all)
lines_data2 <- lines_data[order(data$prob),] 
lines(lines_data2[,1],lines_data2[,2],col="blue")
legend(0.0,0.9,c("Risk groups","Reference line","95% CI","Loess"),col=c("red","black","green","blue"),lty=c(0,2,1,1),pch=c(1,NA,NA,NA),bty="n")

```


```{r}
names(data)
saveRDS(data,here::here("output","all_ranger_contd_valid.rds"))
```
