---
title: " Descriptive stat of RF classification: ab types"
---

```{r setup, include=FALSE}
library('tidyverse')
library("ggplot2")
library("plyr")
library('dplyr')
library('lubridate')
library('stringr')
library("data.table")
library("ggpubr")
library("finalfit")
```




# input data

# read table
```{r}
data=read_rds(here::here("output","all_ranger.rds"))
#data=data%>%filter("patient_id","patient_index_date","decile")
nrow(data)
data$decile=as.factor(data$decile)
data$patient_id=as.factor(data$patient_id)
data$patient_index_date=as.factor(data$patient_index_date)
nrow(data)

data=data%>% select(decile, patient_index_date, patient_id)

abtype=read_rds(here::here("output","abtype79.rds"))
nrow(abtype)
abtype$patient_id=as.factor(abtype$patient_id)
abtype$patient_index_date=as.factor(abtype$patient_index_date)
nrow(abtype)
abtype=abtype%>%distinct(patient_id,patient_index_date, .keep_all = TRUE)
nrow(abtype)

DF=merge(data,abtype, by=c("patient_id","patient_index_date"))
nrow(DF)

```



# descriptive stat
## all data
```{r}

explanatory=c("Rx_Amikacin", "Rx_Amoxicillin", "Rx_Ampicillin", "Rx_Azithromycin", "Rx_Aztreonam", "Rx_Benzylpenicillin", "Rx_Cefaclor", "Rx_Cefadroxil", "Rx_Cefalexin", "Rx_Cefamandole", "Rx_Cefazolin", "Rx_Cefepime", "Rx_Cefixime", "Rx_Cefotaxime", "Rx_Cefoxitin", "Rx_Cefpirome", "Rx_Cefpodoxime", "Rx_Cefprozil", "Rx_Cefradine", "Rx_Ceftazidime", "Rx_Ceftriaxone", "Rx_Cefuroxime", "Rx_Chloramphenicol", "Rx_Cilastatin", "Rx_Ciprofloxacin", "Rx_Clarithromycin", "Rx_Clindamycin", "Rx_Co_amoxiclav", "Rx_Co_fluampicil", "Rx_Colistimethate", "Rx_Dalbavancin", "Rx_Dalfopristin", "Rx_Daptomycin", "Rx_Demeclocycline", "Rx_Doripenem", "Rx_Doxycycline", "Rx_Ertapenem", "Rx_Erythromycin", "Rx_Fidaxomicin", "Rx_Flucloxacillin", "Rx_Fosfomycin", "Rx_Fusidate", "Rx_Gentamicin", "Rx_Levofloxacin", "Rx_Linezolid", "Rx_Lymecycline", "Rx_Meropenem", "Rx_Methenamine", "Rx_Metronidazole", "Rx_Minocycline", "Rx_Moxifloxacin", "Rx_Nalidixic_acid", "Rx_Neomycin", "Rx_Netilmicin", "Rx_Nitazoxanid", "Rx_Nitrofurantoin", "Rx_Norfloxacin", "Rx_Ofloxacin", "Rx_Oxytetracycline", "Rx_Phenoxymethylpenicillin", "Rx_Piperacillin", "Rx_Pivmecillinam", "Rx_Pristinamycin", "Rx_Rifaximin", "Rx_Sulfadiazine", "Rx_Sulfamethoxazole", "Rx_Sulfapyridine", "Rx_Taurolidin", "Rx_Tedizolid", "Rx_Teicoplanin", "Rx_Telithromycin", "Rx_Temocillin", "Rx_Tetracycline", "Rx_Ticarcillin", "Rx_Tigecycline", "Rx_Tinidazole", "Rx_Tobramycin", "Rx_Trimethoprim", "Rx_Vancomycin")
dependent <- "decile"


DF=DF%>%mutate_at(explanatory, as.numeric)


```

```{r}

df=DF
df=df%>%mutate_at(explanatory, as.numeric)
table(df$decile)

vec=vector()
temp= data.frame(matrix(nrow = 10, ncol = 79)) 
colnames(temp)= explanatory


for (i in 1:10) {
  sub.dat=df%>%filter(decile==i)
  
  for (j in 1:79) {
    vec[j]= sum(sub.dat[,explanatory[j]])
    
  }
  temp[i,]=vec

}

temp

temp[11,]=colSums(temp)

top=sort(-temp[11,])
ab1=colnames(top)[1:10]

temp1=temp[,ab1]

```


# distinct
```{r}
df=DF
df=df%>%distinct(patient_id,patient_index_date, .keep_all = TRUE)
df=df%>%mutate_at(explanatory, as.numeric)

nrow(df)

```

```{r}
df=df%>%mutate_at(explanatory, as.numeric)
table(df$decile)

vec=vector()
temp= data.frame(matrix(nrow = 10, ncol = 79)) 
colnames(temp)= explanatory


for (i in 1:10) {
  sub.dat=df%>%filter(decile==i)
  
  for (j in 1:79) {
    vec[j]= sum(sub.dat[,explanatory[j]])
    
  }
  temp[i,]=vec

}

temp

temp[11,]=colSums(temp)

top=sort(-temp[11,])
ab2=colnames(top)[1:10]

temp2=temp[,ab2]

```



# random pick 1
```{r}
df=DF
df=df%>%group_by(case,subclass)%>%sample_n(1)

df=df%>%ungroup(case,subclass)

nrow(df)
```


```{r}

df=df%>%mutate_at(explanatory, as.numeric)
table(df$decile)

vec=vector()
temp= data.frame(matrix(nrow = 10, ncol = 79)) 
colnames(temp)= explanatory


for (i in 1:10) {
  sub.dat=df%>%filter(decile==i)
  
  for (j in 1:79) {
    vec[j]= sum(sub.dat[,explanatory[j]])
    
  }
  temp[i,]=vec

}

temp

temp[11,]=colSums(temp)

top=sort(-temp[11,])
ab3=colnames(top)[1:10]

temp3=temp[,ab3]

```


```{r}
temp1


temp$total=rowSums(temp[,ab1])
for (i in 1:10) {
  temp[,i]=temp[,i]/temp$total
}
temp=temp[-11,]
temp=temp[,-11]



temp[,"decile"]=rownames(temp)

temp=temp%>%select(decile, all_of(ab1))

data=gather(temp, key =ab1, value=value, 2:11)
data

data$decile=factor(data$decile, levels = c("1", "2", "3","4","5","6","7","8","9","10"))
  

ggplot(data=data, aes(x=decile, y=value, group=ab1,colour=ab1)) +
  geom_line()+
  geom_point(aes(shape=ab1))+
  scale_y_continuous(labels = scales::percent)+
  xlab("")+
  ylab("")+
  theme_bw()+
   scale_shape_manual(values = c(rep(1:10))) +
  scale_color_manual(values = c("coral2","darkred","goldenrod2","forestgreen","dodgerblue","black","darkcyan","cadetblue3","darkorchid3","deeppink1"))+
   theme(legend.title =element_blank())

```


```{r}
temp2

temp=temp2

temp$total=rowSums(temp[,ab2])
for (i in 1:10) {
  temp[,i]=temp[,i]/temp$total
}
temp=temp[-11,]
temp=temp[,-11]



temp[,"decile"]=rownames(temp)

temp=temp%>%select(decile, ab2)

data=gather(temp, key =ab2, value=value, 2:11)
data

data$decile=factor(data$decile, levels = c("1", "2", "3","4","5","6","7","8","9","10"))
  

ggplot(data=data, aes(x=decile, y=value, group=ab2,colour=ab2)) +
  geom_line()+
  geom_point(aes(shape=ab2))+
  scale_y_continuous(labels = scales::percent)+
  xlab("")+
  ylab("")+
  theme_bw()+
   scale_shape_manual(values = c(rep(1:10))) +
  scale_color_manual(values = c("coral2","darkred","goldenrod2","forestgreen","dodgerblue","black","darkcyan","cadetblue3","darkorchid3","deeppink1"))+
   theme(legend.title =element_blank())
```


```{r}
temp3

temp=temp3

temp$total=rowSums(temp[,ab3])
for (i in 1:10) {
  temp[,i]=temp[,i]/temp$total
}
temp=temp[-11,]
temp=temp[,-11]



temp[,"decile"]=rownames(temp)

temp=temp%>%select(decile, ab3)

data=gather(temp, key =ab3, value=value, 2:11)
data

data$decile=factor(data$decile, levels = c("1", "2", "3","4","5","6","7","8","9","10"))
  

ggplot(data=data, aes(x=decile, y=value, group=ab3,colour=ab3)) +
  geom_line()+
  geom_point(aes(shape=ab3))+
  scale_y_continuous(labels = scales::percent)+
  xlab("")+
  ylab("")+
  theme_bw()+
   scale_shape_manual(values = c(rep(1:10))) +
  scale_color_manual(values = c("coral2","darkred","goldenrod2","forestgreen","dodgerblue","black","darkcyan","cadetblue3","darkorchid3","deeppink1"))+
   theme(legend.title =element_blank())

```

