---
title: "Random Forest"
---

```{r }
#library(knitr)
library(dplyr)
#library(skimr)
library('tidyverse')
library("ggplot2")
#library(caret)
library(pROC)
library(ranger)

knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")

```

# import dataset
```{r }
train <- read_rds(here::here("output","train_cat.rds"))
train$case=as.factor(train$case)
nrow(train)
table(train$case)
prop.table(table(train$case))

```


```{r }

#valid <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/valid.rds")
valid <- read_rds(here::here("output","valid_cat.rds"))
valid$case=as.factor(valid$case)
nrow(valid)
table(valid$case)
prop.table(table(valid$case))

```


pick variable
```{r }
names(train)

#abtype <- read_rds(here::here("output","abtype.rds"))
col=c("case","total_ab_group","ab_types_group",
      "exposure_period_group","recent_ab_days_group",
      "broad_ab_prescriptions_group",
      "interval_med_group" ,"interval_mean_group","interval_sd_group","interval_CV_group",
      "length_med_group" ,"length_mean_group","length_sd_group","length_CV_group")
# abtype
train=train[col]
valid=valid[col]

str(train)
```


train model

## total_ab_group_weighted
```{r }
#Compute weights to balance the RF
w <- 1/table(train$case)
w <- w/sum(w)
w
weights <- rep(0, nrow(train))
weights[train$case == 0] <- w['0']
weights[train$case == 1] <- w['1']
table(weights, train$case)

set.seed(1024)

    rf.model <- ranger(formula = case ~ ., 
                   data = train,
                   num.trees =  1000,
                   min.node.size = 100,
                   importance = "impurity",
                   replace = TRUE,
                   probability = TRUE,
                   case.weights=weights
                   )
  print(rf.model)
  
summary(predictions(rf.model)[,2])
plot(roc(train$case,predictions(rf.model)[,2]))

summary(predict(rf.model, data=train)$prediction[,2])
plot(roc(train$case,predict(rf.model, data=train)$prediction[,2]))

summary(predict(rf.model2, data=valid)$prediction[,2])
plot(roc(train$case,predict(rf.model, data=valid)$prediction[,2]))
```
# total_ab_group
```{r }
library(randomForest)

n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~ total_ab_group, data = train, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.7),
                           nodesize = 100 
              #             mtry = sqrt(ncol(train)-1)
                          )
  print(rf.model)
  
summary(predict(rf.model, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=train, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=valid, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
```

# ab_types_group
```{r eval=FALSE, include=FALSE}


n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~ ab_types_group, data = train, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.7),
                           nodesize = 100 
                          )
  print(rf.model)
  
summary(predict(rf.model, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=train, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=valid, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
```


# exposure_period_group
```{r eval=FALSE, include=FALSE}


n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~exposure_period_group, data = train, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.7),
                           nodesize = 100 
                       #    mtry = sqrt(ncol(train)-1)
                          )
  print(rf.model)
  
summary(predict(rf.model, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=train, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=valid, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
```

# recent_ab_days_group
```{r eval=FALSE, include=FALSE}


n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~recent_ab_days_group, data = train, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.7),
                           nodesize = 100 
                   #        mtry = sqrt(ncol(train)-1)
                          )
  print(rf.model)
  
summary(predict(rf.model, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=train, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=valid, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
```


# broad_ab_prescriptions_group
```{r eval=FALSE, include=FALSE}


n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~broad_ab_prescriptions_group, data = train, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.7),
                           nodesize = 100 
                       #    mtry = sqrt(ncol(train)-1)
                          )
  print(rf.model)
  
summary(predict(rf.model, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=train, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=valid, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
```

# interval_med_group
```{r eval=FALSE, include=FALSE}

n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~interval_med_group, data = train, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.7),
                           nodesize = 100 
                        #   mtry = sqrt(ncol(train)-1)
                          )
  print(rf.model)
summary(predict(rf.model, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=train, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=valid, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
```


# interval_mean_group
```{r eval=FALSE, include=FALSE}

n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~interval_mean_group, data = train, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.7),
                           nodesize = 100 
                  #         mtry = sqrt(ncol(train)-1)
                          )
  print(rf.model)
summary(predict(rf.model, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=train, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=valid, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
```

# interval_sd_group
```{r eval=FALSE, include=FALSE}


n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~interval_sd_group, data = train, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.7),
                           nodesize = 100 
                          )
  print(rf.model)
  
summary(predict(rf.model, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=train, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=valid, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
```


# interval_CV_group
```{r eval=FALSE, include=FALSE}


n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~interval_CV_group, data = train, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.7),
                           nodesize = 100 
                          )
  print(rf.model)
  
summary(predict(rf.model, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=train, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=valid, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
```


# length_med_group
```{r eval=FALSE, include=FALSE}

n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~length_med_group, data = train, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.7),
                           nodesize = 100 
                          )
  print(rf.model)
  
summary(predict(rf.model, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=train, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=valid, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
```


# length_mean_group
```{r eval=FALSE, include=FALSE}

n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~length_mean_group, data = train, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.7),
                           nodesize = 100 
                        #   mtry = sqrt(ncol(train)-1)
                          )
  print(rf.model)
summary(predict(rf.model, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=train, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=valid, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
```

# length_sd_group
```{r eval=FALSE, include=FALSE}


n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~length_sd_group, data = train, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.7),
                           nodesize = 100 
                          )
  print(rf.model)
  
summary(predict(rf.model, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=train, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=valid, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
```


# length_CV_group
```{r eval=FALSE, include=FALSE}


n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~length_CV_group, data = train, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.7),
                           nodesize = 100 
                 #          mtry = sqrt(ncol(train)-1)
                          )
  print(rf.model)
  
summary(predict(rf.model, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=train, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))

summary(predict(rf.model,data=valid, type = 'prob')[,2])
print(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
plot(plot(roc(train$case,predict(rf.model, type = 'prob')[,2])))
```