---
title: " matching result"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(kableExtra)
library('tidyverse')
require("gtsummary")
library("ggplot2")
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")
```



```{r include=FALSE}
# import data

df1 <- read_rds(here::here("output","matched_patients.rds"))
#df1= read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_patients.rds")
df1=df1%>%select("wave","sex","age","age_cat","region") 
df1=subset(df1,case==1)
df1$matched="1"

df2 <- read_rds(here::here("output","unmatched_cases.rds"))
#df2= read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/unmatched_cases.rds.rds")
df2=df2%>%select( "wave","sex","age","age_cat","region" ) 
df2=subset(df2,case==1)
df2$matched="0"

df=rbind(df1,df2)

```


```{r include=FALSE}
num1=count(df[df$matched=="1",])
num2=count(df[df$matched=="0",])
```

#### Matcthed case (1): **count:`r num1`**
#### non-matcthed case (0): **count:`r num2`**

***




```{r}

explanatory<- c("wave","sex","age","age_cat","region")
dependent <- "matched"

tbl=DF%>% summary_factorlist(dependent, explanatory, p=T)

```

# round to nearest5 and redacted <7
```{r}
round_tbl=tbl
#remove percentage
round_tbl[,3]=gsub("\\(.*?\\)","",round_tbl[,3])
round_tbl[,4]=gsub("\\(.*?\\)","",round_tbl[,4])

# redacted
round_tbl[,3]=ifelse(round_tbl[,3]<7,NA,round_tbl[,3])
round_tbl[,4]=ifelse(round_tbl[,4]<7,NA,round_tbl[,4])


#round to 5
round_tbl[,3]=as.numeric(round_tbl[,3])
round_tbl[,3]=plyr::round_any(round_tbl[,3], 5, f = round)

round_tbl[,4]=as.numeric(round_tbl[,4])
round_tbl[,4]=plyr::round_any(round_tbl[,4], 5, f = round)
```

# figure: age difference
```{r  echo=FALSE }
df$matched=as.factor(df$matched)


plot=ggplot(df, aes(x=age, fill=matched, color=matched)) +
 # geom_histogram(aes(y=..density..), position="identity", alpha=0.5,bins=30)+
  geom_density(alpha=0.5)+
  scale_x_continuous(breaks = seq(0, 110, by=10))

table(df$age,df$matched)



df1=df%>%filter(matched==1)
top5=quantile(df1$age, 0.025,na.rm=T)
top95=quantile(df1$age, 0.975,na.rm=T)
df1=df1%>%filter(age>top5 & age<top95)

df0=df%>%filter(matched==0)
top5=quantile(df0$age, 0.025,na.rm=T)
top95=quantile(df0$age, 0.975,na.rm=T)
df0=df0%>%filter(age>top5 & age<top95)

df=rbind(df1,df0)

ggplot(df, aes(x=age, fill=matched, color=matched)) +
 # geom_histogram(aes(y=..density..), position="identity", alpha=0.5,bins=30)+
  geom_density(alpha=0.5)+
  scale_x_continuous(breaks = seq(0, 110, by=10))

table(df$age,df$matched)

```

# output
```{r}
write.csv(round_tbl,here::here("output","unmatched_com.csv"))
ggsave(
   plot= plot,
   filename="unmatched_com.png", path=here::here("output"), dpi = 300,
)          
```


