---
title: "Matching with replacement"
author: "YT Y"
date: "07/04/2022"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
library('tidyverse')
library('MatchIt')
library("ggplot2")
library(knitr)
library(dplyr)
library(kableExtra)
library(data.table)#rbinlist
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")
```

# all case
```{r}
# import
#setwd('/Users/yayang/Documents/GitHub/amr-uom-brit/output')
setwd(here::here("output"))

df=read_csv(here::here("output","control_covid_infection.csv"))
df$case=1
nrow(df)
```

# all control
```{r}
setwd(here::here("output"))
listFiles <- list.files(pattern="general_id_+.*csv")

list=list()

for (i in 1:35) {
  
  list[[i]]=read.csv(here::here("output",listFiles[i]))
}

df0=rbindlist(list)
nrow(df0)


DF=rbind(df1,df0)
nrow(DF)


DF.test=DF%>%distinct(patient_id)
nrow(DF.test)
```




# Matching

## Exact matching
 methods from wjchulme
https://github.com/opensafely/booster-effectiveness/blob/256eae9691d36c0a2c586c9bb307eefb24586c32/analysis/design.R
https://github.com/opensafely/booster-effectiveness/blob/256eae9691d36c0a2c586c9bb307eefb24586c32/analysis/match_seqtrialcox.R

```{r }
# 1:1 NN PS matching w/o replacement

caliper_variables <- c(age = 5,NULL)

exact_variables <- c("sex","stp","cal_YM", NULL)

m.out1 <- matchit(case ~ age + sex + stp + cal_YM , data = df,
                 method = "nearest", distance = "glm", # these two options don't really do anything because we only want exact + caliper matching
                 exact = exact_variables,
                 caliper = caliper_variables, std.caliper=FALSE,
                 replace=TRUE, ratio=6)
m.out1


```




# output
```{r }

m.data1 <- get_matches(m.out1) # repeated id between sets(subclasses)
m.data1=m.data1%>%select("case","subclass","patient_id","patient_index_date","age","sex","stp","cal_YM","age_cat","region") # key variables for merging
write_rds(m.data1, here::here("output", "matched_patients_general.rds"))

m.data2 <- match.data(m.out1) # unique patient ID
m.data2=m.data2%>%select("patient_id","patient_index_date") 
write.csv(m.data2,here::here("output","matched_patients_id_general.csv"))

unmatched=subset(df, !df$patient_id %in% m.data1$patient_id)
unmatched=unmatched%>%filter(case==1)
write_rds(unmatched,here::here("output","unmatched_cases_general.rds"))


```


