### Pneumonia model ###

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/workspace')
```


```{r message=FALSE, warning=FALSE, include=FALSE}
library("dplyr")
library("tidyverse")
library("lubridate")
library("foreign")
library("nnet")
library("ggplot2")
library("VGAM")
library("bayesm")
library("finalfit")
library("here")
library("rms")
library("pROC")
library("predtools")
library("magrittr")

```

```{r message=FALSE, warning=FALSE, include=FALSE}
DF <- read_csv(here::here("output","model_preparation.csv"))
DF <- DF %>% filter(infection== "Pneumonia")
DF$incident_prevalent <- as.factor(DF$incident_prevalent)
DF$outcome <- as.factor(DF$outcome)
DF$ethnicity_6 <- as.factor(DF$ethnicity_6)
DF$imd <- as.factor(DF$imd)
DF$region <- as.factor(DF$region)
DF$charlsonGrp <- as.factor(DF$charlsonGrp)
DF$antibiotics_12mb4 <- as.factor(DF$antibiotics_12mb4)  
DF$incident_prevalent <- relevel(DF$incident_prevalent, ref = "incident")                                          
DF$outcome <- relevel(DF$outcome, ref = "1")
DF$ethnicity_6 <- relevel(DF$ethnicity_6, ref = "White")
DF$imd <- relevel(DF$imd, ref = "1")
DF$region <- relevel(DF$region, ref = "East")
DF$charlsonGrp <- relevel(DF$charlsonGrp, ref = "zero")
DF$antibiotics_12mb4 <- relevel(DF$antibiotics_12mb4, ref = "0")
DF <- DF %>% dplyr::select(outcome,age,sex,ethnicity_6,region,charlsonGrp,imd,incident_prevalent,antibiotics_12mb4,infection)
DF <- DF %>% filter (DF$sex=="M"|DF$sex=="F")
DF <- DF %>% filter (!is.na(outcome))
DF <- DF %>% filter (!is.na(ethnicity_6))
DF <- DF %>% filter (!is.na(imd))
DF <- DF %>% filter (!is.na(region))
DF <- DF %>% filter (!is.na(charlsonGrp))
DF <- DF %>% filter (!is.na(age))
DF <- DF %>% filter (!is.na(sex))
DF <- DF %>% filter (!is.na(antibiotics_12mb4))
DF <- DF %>% filter (!is.na(incident_prevalent))
```

## model summary
```{r echo=FALSE, message=FALSE, warning=FALSE}

# Data Partition 
set.seed(777)
ind <- sample(2,nrow(DF),
              replace = TRUE,
              prob = c(0.75,0.25))

training <- DF[ind==1,]
testing <- DF[ind==2,]

### use training dataset to develop the model
Knots.manual <- rcspline.eval(training$age, nk = 3, knots.only = TRUE)
m1 <- vgam(outcome ~ rcs(age, Knots.manual) + sex + ethnicity_6 + region + charlsonGrp + imd + incident_prevalent + antibiotics_12mb4,  family = multinomial(parallel = FALSE, refLevel = 1), data =training)
summaryvglm(m1)
```


### age plot model[2]/[1] (from age 10 to 90)
```{r echo=FALSE, message=FALSE, warning=FALSE}
rcs1<- rcs(seq(10, 90, 1), Knots.manual)
OR1 <- m1@coefficients["rcs(age, Knots.manual)age:1"]*rcs1[,1] + m1@coefficients["rcs(age, Knots.manual)age':1"]*rcs1[,2] 
OR2 <- m1@coefficients["rcs(age, Knots.manual)age:2"]*rcs1[,1] + m1@coefficients["rcs(age, Knots.manual)age':2"]*rcs1[,2] 

OR1.exp <- exp(OR1)
df.OR1.exp <- as.data.frame(cbind(rcs1[,1],OR1.exp))
names(df.OR1.exp) <- c("Age","expfx")
ggplot(data=df.OR1.exp, aes(x=Age, y=expfx)) +
  geom_line()+
  geom_point()+
  scale_x_continuous(breaks=seq(0, 90 , 10))+
  labs(x="Age", y = "exp(f(X))")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
df.OR1 <- as.data.frame(cbind(rcs1[,1],OR1))
names(df.OR1) <- c("Age","fx")
ggplot(data=df.OR1, aes(x=Age, y=fx)) +
  geom_line()+
  geom_point()+
  scale_x_continuous(breaks=seq(0, 90 , 10))+
  labs(x="Age", y = "f(X)")

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
head(df.OR1,n=90)
```

### age plot model[3]/[1] (from age 10 to 90)
```{r echo=FALSE, message=FALSE, warning=FALSE}
OR2.exp <- exp(OR2)
df.OR2.exp <- as.data.frame(cbind(rcs1[,1],OR2.exp))
names(df.OR2.exp) <- c("Age","expfx")
ggplot(data=df.OR2.exp, aes(x=Age, y=expfx)) +
  geom_line()+
  geom_point()+
  scale_x_continuous(breaks=seq(0, 90 , 10))+
  labs(x="Age", y = "exp(f(X))")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
df.OR2 <- as.data.frame(cbind(rcs1[,1],OR2))
names(df.OR2) <- c("Age","fx")
ggplot(data=df.OR2, aes(x=Age, y=fx)) +
  geom_line()+
  geom_point()+
  scale_x_continuous(breaks=seq(0, 90 , 10))+
  labs(x="Age", y = "f(X)")
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
head(df.OR2,n=90)
```

## Age OR (age = 40 as reference)
```{r echo=FALSE, message=FALSE, warning=FALSE}
title_1 <- c("outcome", "age", "sex", "ethnicity_6", "region", "charlsonGrp", 
             "imd", "incident_prevalent","antibiotics_12mb4")
age_1 <- c("1",10,"F","White","East","zero","1","incident","0")
age_2 <- c("1",20,"F","White","East","zero","1","incident","0")
age_3 <- c("1",30,"F","White","East","zero","1","incident","0")
age_4 <- c("1",40,"F","White","East","zero","1","incident","0")
age_5 <- c("1",50,"F","White","East","zero","1","incident","0")
age_6 <- c("1",60,"F","White","East","zero","1","incident","0")
age_7 <- c("1",70,"F","White","East","zero","1","incident","0")
age_8 <- c("1",80,"F","White","East","zero","1","incident","0")

age_dt <- as.data.frame(rbind(age_1,age_2,age_3,age_4,age_5,age_6,age_7,age_8))
colnames(age_dt) <- title_1

age_dt$outcome <- as.factor(age_dt$outcome)
age_dt$age <- as.numeric(age_dt$age)
age_dt$sex <- as.factor(age_dt$sex)
age_dt$ethnicity_6 <- as.factor(age_dt$ethnicity_6)
age_dt$region <- as.factor(age_dt$region)
age_dt$charlsonGrp <- as.factor(age_dt$charlsonGrp)
age_dt$imd <- as.factor(age_dt$imd)
age_dt$incident_prevalent <- as.factor(age_dt$incident_prevalent)
age_dt$ab12b4 <- as.factor(age_dt$antibiotics_12mb4)

age_LP <- predict(m1, newdata = age_dt,interval = "confidence")
age_LP
```

