---
title: "top 5 antibiotics by infections"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = '/workspace')
```

```{r include=FALSE}
library("tidyverse") 
library('dplyr')#conflict with plyr; load after plyr
library('lubridate')
library(scales)
#setwd(here::here("output", "measures"))
```

# UTI

```{r include=FALSE}
########### UTI
#setwd("/Users/yayang/Documents/GitHub/amr-uom-brit/output/measures")
df=readRDS(here::here("output","measures","abtype_uti.rds"))
df=bind_rows(df)


# remove last month data
last.date=max(df$date)
df=df%>% filter(date!=last.date)
first_mon <- (format(min(df$date), "%m-%Y"))
last_mon <- (format(max(df$date), "%m-%Y"))


# variable types
df$prevalent=as.factor(df$prevalent)
df$date=as.Date(df$date)
df$abtype=as.character(df$abtype)

## filter case with ab
df=df%>%filter(!is.na(abtype))

##select prevalent cases
# calculate ab types
df.1=df%>%filter(prevalent==1)%>%group_by(date)%>%mutate(total=n())
df.1=df.1%>%group_by(date,abtype)%>%summarise(count=n(),total=mean(total))


# top 3 ab
DF.top10.1=df.1%>%
  group_by(abtype)%>%
  summarise(count=sum(count))%>% 
  arrange(desc(count))%>%
  slice(1:5)

# sort ab type
# recode other types
df.1$type=ifelse(df.1$abtype %in% DF.top10.1$abtype | is.na(df.1$abtype), df.1$abtype, "Others")

# recode NA -> no recorded antibiotics
df.1$type=ifelse(is.na(df.1$type),"No_antibiotics", df.1$type)
df.1$type <- factor(df.1$type, levels=c(DF.top10.1$abtype,"Others","No_antibiotics"))# reorder


# consultation with AB 
df.1=df.1%>%group_by(date,type)%>%summarise(count=sum(count),total=mean(total))
##df.1$percentage=df.1$count/df.1$total

##select incident cases
# calculate ab types
df.0=df%>%filter(prevalent==0)%>%group_by(date)%>%mutate(total=n())
df.0=df.0%>%group_by(date,abtype)%>%summarise(count=n(),total=mean(total))


# top 5 ab
DF.top10.0=df.0%>%
  group_by(abtype)%>%
  summarise(count=sum(count))%>% 
  arrange(desc(count))%>%
  slice(1:5)

# sort ab type
# recode other types
df.0$type=ifelse(df.0$abtype %in% DF.top10.0$abtype | is.na(df.0$abtype), df.0$abtype, "Others")

# recode NA -> no recorded antibiotics
df.0$type=ifelse(is.na(df.0$type),"No_antibiotics", df.0$type)
df.0$type <- factor(df.0$type, levels=c(DF.top10.0$abtype,"Others","No_antibiotics"))# reorder


# consultation with AB 
df.0=df.0%>%group_by(date,type)%>%summarise(count=sum(count),total=mean(total))
#df.0$percentage=df.0$count/df.0$total


## csv check for plot
rm(DF.top10.0,DF.top10.1,df)
df.1$prevalent=as.factor(1)
df.0$prevalent=as.factor(0)
df=rbind(df.0,df.1)

# redacted
df$raw_count=df$count
df$raw_total=df$total
df$count=ifelse(df$count<=6,6, df$count)
df=df%>%group_by(date,prevalent)%>%mutate(total=sum(count))
df$percentage=df$count/df$total

df.1=df%>%filter(prevalent==1)
df.0=df%>%filter(prevalent==0)
```


## incident
```{r echo=FALSE}
# incident
lineplot.0.uti<- ggplot(df.0, aes(x=date, y=percentage, group=type,color=type))+
  annotate(geom = "rect", xmin = as.Date("2021-01-01"),xmax = as.Date("2021-04-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-11-01"),xmax = as.Date("2020-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-03-01"),xmax = as.Date("2020-06-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_line(aes(linetype=type))+
  geom_point(aes(shape=type),size=0.5)+
  theme(legend.position = "right",legend.title =element_blank())+
  scale_shape_manual(values = c(rep(1:11))) +
  scale_color_manual(values = c("coral2","deeppink3","darkred","blue","green4","goldenrod2","blue3","green3","forestgreen","dodgerblue","black"))+
  labs(
    y = "" ,
    x="")+
  theme(axis.text.x=element_text(angle=60,hjust=1))+
  scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month", limits = c(as.Date("2019-01-01"),as.Date("2022-06-01")))+
  scale_y_continuous(labels = scales::percent)+
  ggtitle("UTI")+
  theme(text = element_text(size = 10))+
  theme(plot.title = element_text(size = 12))   

lineplot.0.uti
```

## prevalent
```{r echo=FALSE}
### line graph
# prevalent
lineplot.1.uti<- ggplot(df.1, aes(x=date, y=percentage, group=type,color=type))+
  annotate(geom = "rect", xmin = as.Date("2021-01-01"),xmax = as.Date("2021-04-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-11-01"),xmax = as.Date("2020-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-03-01"),xmax = as.Date("2020-06-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_line(aes(linetype=type))+
  geom_point(aes(shape=type),size=0.5)+
  theme(legend.position = "right",legend.title =element_blank())+
  scale_shape_manual(values = c(rep(1:11))) +
  scale_color_manual(values = c("coral2","deeppink3","darkred","blue","green4","goldenrod2","blue3","green3","forestgreen","dodgerblue","black"))+
  labs(
    y = "" ,
    x="")+
  theme(axis.text.x=element_text(angle=60,hjust=1))+
  scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month", limits = c(as.Date("2019-01-01"),as.Date("2022-06-01")))+
  scale_y_continuous(labels = scales::percent)+
  ggtitle("UTI")+
  theme(text = element_text(size = 10))+
  theme(plot.title = element_text(size = 12))   

lineplot.1.uti
```

# URTI

```{r include=FALSE}
rm(list=ls())
#setwd(here::here("output", "measures"))
#setwd("/Users/yayang/Documents/GitHub/amr-uom-brit/output/measures")
df=readRDS(here::here("output","measures","abtype_urti.rds"))
df=bind_rows(df)


# remove last month data
last.date=max(df$date)
df=df%>% filter(date!=last.date)
first_mon <- (format(min(df$date), "%m-%Y"))
last_mon <- (format(max(df$date), "%m-%Y"))


# variable types
df$prevalent=as.factor(df$prevalent)
df$date=as.Date(df$date)
df$abtype=as.character(df$abtype)

## filter case with ab
df=df%>%filter(!is.na(abtype))

##select prevalent cases
# calculate ab types
df.1=df%>%filter(prevalent==1)%>%group_by(date)%>%mutate(total=n())
df.1=df.1%>%group_by(date,abtype)%>%summarise(count=n(),total=mean(total))


# top 3 ab
DF.top10.1=df.1%>%
  group_by(abtype)%>%
  summarise(count=sum(count))%>% 
  arrange(desc(count))%>%
  slice(1:5)

# sort ab type
# recode other types
df.1$type=ifelse(df.1$abtype %in% DF.top10.1$abtype | is.na(df.1$abtype), df.1$abtype, "Others")

# recode NA -> no recorded antibiotics
df.1$type=ifelse(is.na(df.1$type),"No_antibiotics", df.1$type)
df.1$type <- factor(df.1$type, levels=c(DF.top10.1$abtype,"Others","No_antibiotics"))# reorder


# consultation with AB 
df.1=df.1%>%group_by(date,type)%>%summarise(count=sum(count),total=mean(total))
##df.1$percentage=df.1$count/df.1$total

##select incident cases
# calculate ab types
df.0=df%>%filter(prevalent==0)%>%group_by(date)%>%mutate(total=n())
df.0=df.0%>%group_by(date,abtype)%>%summarise(count=n(),total=mean(total))


# top 5 ab
DF.top10.0=df.0%>%
  group_by(abtype)%>%
  summarise(count=sum(count))%>% 
  arrange(desc(count))%>%
  slice(1:5)

# sort ab type
# recode other types
df.0$type=ifelse(df.0$abtype %in% DF.top10.0$abtype | is.na(df.0$abtype), df.0$abtype, "Others")

# recode NA -> no recorded antibiotics
df.0$type=ifelse(is.na(df.0$type),"No_antibiotics", df.0$type)
df.0$type <- factor(df.0$type, levels=c(DF.top10.0$abtype,"Others","No_antibiotics"))# reorder


# consultation with AB 
df.0=df.0%>%group_by(date,type)%>%summarise(count=sum(count),total=mean(total))
#df.0$percentage=df.0$count/df.0$total


## csv check for plot
rm(DF.top10.0,DF.top10.1,df)
df.1$prevalent=as.factor(1)
df.0$prevalent=as.factor(0)
df=rbind(df.0,df.1)

# redacted
df$raw_count=df$count
df$raw_total=df$total
df$count=ifelse(df$count<=6,6, df$count)
df=df%>%group_by(date,prevalent)%>%mutate(total=sum(count))
df$percentage=df$count/df$total

df.1=df%>%filter(prevalent==1)
df.0=df%>%filter(prevalent==0)
```


## incident
```{r echo=FALSE}
# incident
ggplot(df.0, aes(x=date, y=percentage, group=type,color=type))+
  annotate(geom = "rect", xmin = as.Date("2021-01-01"),xmax = as.Date("2021-04-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-11-01"),xmax = as.Date("2020-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-03-01"),xmax = as.Date("2020-06-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_line(aes(linetype=type))+
  geom_point(aes(shape=type),size=0.5)+
  theme(legend.position = "right",legend.title =element_blank())+
  scale_shape_manual(values = c(rep(1:11))) +
  scale_color_manual(values = c("coral2","deeppink3","darkred","blue","green4","goldenrod2","blue3","green3","forestgreen","dodgerblue","black"))+
  labs(
    y = "" ,
    x="")+
  theme(axis.text.x=element_text(angle=60,hjust=1))+
  scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month", limits = c(as.Date("2019-01-01"),as.Date("2022-06-01")))+
  scale_y_continuous(labels = scales::percent)+
  ggtitle("URTI")+
  theme(text = element_text(size = 10))+
  theme(plot.title = element_text(size = 12))   

```

## prevalent
```{r echo=FALSE}
### line graph
# prevalent
ggplot(df.1, aes(x=date, y=percentage, group=type,color=type))+
  annotate(geom = "rect", xmin = as.Date("2021-01-01"),xmax = as.Date("2021-04-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-11-01"),xmax = as.Date("2020-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-03-01"),xmax = as.Date("2020-06-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_line(aes(linetype=type))+
  geom_point(aes(shape=type),size=0.5)+
  theme(legend.position = "right",legend.title =element_blank())+
  scale_shape_manual(values = c(rep(1:11))) +
  scale_color_manual(values = c("coral2","deeppink3","darkred","blue","green4","goldenrod2","blue3","green3","forestgreen","dodgerblue","black"))+
  labs(
    y = "" ,
    x="")+
  theme(axis.text.x=element_text(angle=60,hjust=1))+
  scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month", limits = c(as.Date("2019-01-01"),as.Date("2022-06-01")))+
  scale_y_continuous(labels = scales::percent)+
  ggtitle("URTI")+
  theme(text = element_text(size = 10))+
  theme(plot.title = element_text(size = 12))   


```



# LRTI

```{r include=FALSE}
rm(list=ls())
#setwd(here::here("output", "measures"))
#setwd("/Users/yayang/Documents/GitHub/amr-uom-brit/output/measures")
df=readRDS(here::here("output","measures","abtype_lrti.rds"))
df=bind_rows(df)


# remove last month data
last.date=max(df$date)
df=df%>% filter(date!=last.date)
first_mon <- (format(min(df$date), "%m-%Y"))
last_mon <- (format(max(df$date), "%m-%Y"))


# variable types
df$prevalent=as.factor(df$prevalent)
df$date=as.Date(df$date)
df$abtype=as.character(df$abtype)

## filter case with ab
df=df%>%filter(!is.na(abtype))

##select prevalent cases
# calculate ab types
df.1=df%>%filter(prevalent==1)%>%group_by(date)%>%mutate(total=n())
df.1=df.1%>%group_by(date,abtype)%>%summarise(count=n(),total=mean(total))


# top 3 ab
DF.top10.1=df.1%>%
  group_by(abtype)%>%
  summarise(count=sum(count))%>% 
  arrange(desc(count))%>%
  slice(1:5)

# sort ab type
# recode other types
df.1$type=ifelse(df.1$abtype %in% DF.top10.1$abtype | is.na(df.1$abtype), df.1$abtype, "Others")

# recode NA -> no recorded antibiotics
df.1$type=ifelse(is.na(df.1$type),"No_antibiotics", df.1$type)
df.1$type <- factor(df.1$type, levels=c(DF.top10.1$abtype,"Others","No_antibiotics"))# reorder


# consultation with AB 
df.1=df.1%>%group_by(date,type)%>%summarise(count=sum(count),total=mean(total))
##df.1$percentage=df.1$count/df.1$total

##select incident cases
# calculate ab types
df.0=df%>%filter(prevalent==0)%>%group_by(date)%>%mutate(total=n())
df.0=df.0%>%group_by(date,abtype)%>%summarise(count=n(),total=mean(total))


# top 5 ab
DF.top10.0=df.0%>%
  group_by(abtype)%>%
  summarise(count=sum(count))%>% 
  arrange(desc(count))%>%
  slice(1:5)

# sort ab type
# recode other types
df.0$type=ifelse(df.0$abtype %in% DF.top10.0$abtype | is.na(df.0$abtype), df.0$abtype, "Others")

# recode NA -> no recorded antibiotics
df.0$type=ifelse(is.na(df.0$type),"No_antibiotics", df.0$type)
df.0$type <- factor(df.0$type, levels=c(DF.top10.0$abtype,"Others","No_antibiotics"))# reorder


# consultation with AB 
df.0=df.0%>%group_by(date,type)%>%summarise(count=sum(count),total=mean(total))
#df.0$percentage=df.0$count/df.0$total


## csv check for plot
rm(DF.top10.0,DF.top10.1,df)
df.1$prevalent=as.factor(1)
df.0$prevalent=as.factor(0)
df=rbind(df.0,df.1)

# redacted
df$raw_count=df$count
df$raw_total=df$total
df$count=ifelse(df$count<=6,6, df$count)
df=df%>%group_by(date,prevalent)%>%mutate(total=sum(count))
df$percentage=df$count/df$total

df.1=df%>%filter(prevalent==1)
df.0=df%>%filter(prevalent==0)
```


## incident
```{r echo=FALSE}
# incident
ggplot(df.0, aes(x=date, y=percentage, group=type,color=type))+
  annotate(geom = "rect", xmin = as.Date("2021-01-01"),xmax = as.Date("2021-04-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-11-01"),xmax = as.Date("2020-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-03-01"),xmax = as.Date("2020-06-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_line(aes(linetype=type))+
  geom_point(aes(shape=type),size=0.5)+
  theme(legend.position = "right",legend.title =element_blank())+
  scale_shape_manual(values = c(rep(1:11))) +
  scale_color_manual(values = c("coral2","deeppink3","darkred","blue","green4","goldenrod2","blue3","green3","forestgreen","dodgerblue","black"))+
  labs(
    y = "" ,
    x="")+
  theme(axis.text.x=element_text(angle=60,hjust=1))+
  scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month", limits = c(as.Date("2019-01-01"),as.Date("2022-06-01")))+
  scale_y_continuous(labels = scales::percent)+
  ggtitle("LRTI")+
  theme(text = element_text(size = 10))+
  theme(plot.title = element_text(size = 12))   

```

## prevalent
```{r echo=FALSE}
### line graph
# prevalent
ggplot(df.1, aes(x=date, y=percentage, group=type,color=type))+
  annotate(geom = "rect", xmin = as.Date("2021-01-01"),xmax = as.Date("2021-04-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-11-01"),xmax = as.Date("2020-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-03-01"),xmax = as.Date("2020-06-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_line(aes(linetype=type))+
  geom_point(aes(shape=type),size=0.5)+
  theme(legend.position = "right",legend.title =element_blank())+
  scale_shape_manual(values = c(rep(1:11))) +
  scale_color_manual(values = c("coral2","deeppink3","darkred","blue","green4","goldenrod2","blue3","green3","forestgreen","dodgerblue","black"))+
  labs(
    y = "" ,
    x="")+
  theme(axis.text.x=element_text(angle=60,hjust=1))+
  scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month", limits = c(as.Date("2019-01-01"),as.Date("2022-06-01")))+
  scale_y_continuous(labels = scales::percent)+
  ggtitle("LRTI")+
  theme(text = element_text(size = 10))+
  theme(plot.title = element_text(size = 12))   


```


# Sinusitis

```{r include=FALSE}
rm(list=ls())
#setwd(here::here("output", "measures"))
#setwd("/Users/yayang/Documents/GitHub/amr-uom-brit/output/measures")
df=readRDS(here::here("output","measures","abtype_sinusitis.rds"))
df=bind_rows(df)


# remove last month data
last.date=max(df$date)
df=df%>% filter(date!=last.date)
first_mon <- (format(min(df$date), "%m-%Y"))
last_mon <- (format(max(df$date), "%m-%Y"))


# variable types
df$prevalent=as.factor(df$prevalent)
df$date=as.Date(df$date)
df$abtype=as.character(df$abtype)

## filter case with ab
df=df%>%filter(!is.na(abtype))

##select prevalent cases
# calculate ab types
df.1=df%>%filter(prevalent==1)%>%group_by(date)%>%mutate(total=n())
df.1=df.1%>%group_by(date,abtype)%>%summarise(count=n(),total=mean(total))


# top 3 ab
DF.top10.1=df.1%>%
  group_by(abtype)%>%
  summarise(count=sum(count))%>% 
  arrange(desc(count))%>%
  slice(1:5)

# sort ab type
# recode other types
df.1$type=ifelse(df.1$abtype %in% DF.top10.1$abtype | is.na(df.1$abtype), df.1$abtype, "Others")

# recode NA -> no recorded antibiotics
df.1$type=ifelse(is.na(df.1$type),"No_antibiotics", df.1$type)
df.1$type <- factor(df.1$type, levels=c(DF.top10.1$abtype,"Others","No_antibiotics"))# reorder


# consultation with AB 
df.1=df.1%>%group_by(date,type)%>%summarise(count=sum(count),total=mean(total))
##df.1$percentage=df.1$count/df.1$total

##select incident cases
# calculate ab types
df.0=df%>%filter(prevalent==0)%>%group_by(date)%>%mutate(total=n())
df.0=df.0%>%group_by(date,abtype)%>%summarise(count=n(),total=mean(total))


# top 5 ab
DF.top10.0=df.0%>%
  group_by(abtype)%>%
  summarise(count=sum(count))%>% 
  arrange(desc(count))%>%
  slice(1:5)

# sort ab type
# recode other types
df.0$type=ifelse(df.0$abtype %in% DF.top10.0$abtype | is.na(df.0$abtype), df.0$abtype, "Others")

# recode NA -> no recorded antibiotics
df.0$type=ifelse(is.na(df.0$type),"No_antibiotics", df.0$type)
df.0$type <- factor(df.0$type, levels=c(DF.top10.0$abtype,"Others","No_antibiotics"))# reorder


# consultation with AB 
df.0=df.0%>%group_by(date,type)%>%summarise(count=sum(count),total=mean(total))
#df.0$percentage=df.0$count/df.0$total


## csv check for plot
rm(DF.top10.0,DF.top10.1,df)
df.1$prevalent=as.factor(1)
df.0$prevalent=as.factor(0)
df=rbind(df.0,df.1)

# redacted
df$raw_count=df$count
df$raw_total=df$total
df$count=ifelse(df$count<=6,6, df$count)
df=df%>%group_by(date,prevalent)%>%mutate(total=sum(count))
df$percentage=df$count/df$total

df.1=df%>%filter(prevalent==1)
df.0=df%>%filter(prevalent==0)
```


## incident
```{r echo=FALSE}
# incident
ggplot(df.0, aes(x=date, y=percentage, group=type,color=type))+
  annotate(geom = "rect", xmin = as.Date("2021-01-01"),xmax = as.Date("2021-04-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-11-01"),xmax = as.Date("2020-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-03-01"),xmax = as.Date("2020-06-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_line(aes(linetype=type))+
  geom_point(aes(shape=type),size=0.5)+
  theme(legend.position = "right",legend.title =element_blank())+
  scale_shape_manual(values = c(rep(1:11))) +
  scale_color_manual(values = c("coral2","deeppink3","darkred","blue","green4","goldenrod2","blue3","green3","forestgreen","dodgerblue","black"))+
  labs(
    y = "" ,
    x="")+
  theme(axis.text.x=element_text(angle=60,hjust=1))+
  scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month", limits = c(as.Date("2019-01-01"),as.Date("2022-06-01")))+
  scale_y_continuous(labels = scales::percent)+
  ggtitle("Sinusitis")+
  theme(text = element_text(size = 10))+
  theme(plot.title = element_text(size = 12))   

```

## prevalent
```{r echo=FALSE}
### line graph
# prevalent
ggplot(df.1, aes(x=date, y=percentage, group=type,color=type))+
  annotate(geom = "rect", xmin = as.Date("2021-01-01"),xmax = as.Date("2021-04-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-11-01"),xmax = as.Date("2020-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-03-01"),xmax = as.Date("2020-06-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_line(aes(linetype=type))+
  geom_point(aes(shape=type),size=0.5)+
  theme(legend.position = "right",legend.title =element_blank())+
  scale_shape_manual(values = c(rep(1:11))) +
  scale_color_manual(values = c("coral2","deeppink3","darkred","blue","green4","goldenrod2","blue3","green3","forestgreen","dodgerblue","black"))+
  labs(
    y = "" ,
    x="")+
  theme(axis.text.x=element_text(angle=60,hjust=1))+
  scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month", limits = c(as.Date("2019-01-01"),as.Date("2022-06-01")))+
  scale_y_continuous(labels = scales::percent)+
  ggtitle("Sinusitis")+
  theme(text = element_text(size = 10))+
  theme(plot.title = element_text(size = 12))   


```





# Otitis externa

```{r include=FALSE}
rm(list=ls())
#setwd(here::here("output", "measures"))
#setwd("/Users/yayang/Documents/GitHub/amr-uom-brit/output/measures")
df=readRDS(here::here("output","measures","abtype_ot_externa.rds"))
df=bind_rows(df)


# remove last month data
last.date=max(df$date)
df=df%>% filter(date!=last.date)
first_mon <- (format(min(df$date), "%m-%Y"))
last_mon <- (format(max(df$date), "%m-%Y"))


# variable types
df$prevalent=as.factor(df$prevalent)
df$date=as.Date(df$date)
df$abtype=as.character(df$abtype)

## filter case with ab
df=df%>%filter(!is.na(abtype))

##select prevalent cases
# calculate ab types
df.1=df%>%filter(prevalent==1)%>%group_by(date)%>%mutate(total=n())
df.1=df.1%>%group_by(date,abtype)%>%summarise(count=n(),total=mean(total))


# top 3 ab
DF.top10.1=df.1%>%
  group_by(abtype)%>%
  summarise(count=sum(count))%>% 
  arrange(desc(count))%>%
  slice(1:5)

# sort ab type
# recode other types
df.1$type=ifelse(df.1$abtype %in% DF.top10.1$abtype | is.na(df.1$abtype), df.1$abtype, "Others")

# recode NA -> no recorded antibiotics
df.1$type=ifelse(is.na(df.1$type),"No_antibiotics", df.1$type)
df.1$type <- factor(df.1$type, levels=c(DF.top10.1$abtype,"Others","No_antibiotics"))# reorder


# consultation with AB 
df.1=df.1%>%group_by(date,type)%>%summarise(count=sum(count),total=mean(total))
##df.1$percentage=df.1$count/df.1$total

##select incident cases
# calculate ab types
df.0=df%>%filter(prevalent==0)%>%group_by(date)%>%mutate(total=n())
df.0=df.0%>%group_by(date,abtype)%>%summarise(count=n(),total=mean(total))


# top 5 ab
DF.top10.0=df.0%>%
  group_by(abtype)%>%
  summarise(count=sum(count))%>% 
  arrange(desc(count))%>%
  slice(1:5)

# sort ab type
# recode other types
df.0$type=ifelse(df.0$abtype %in% DF.top10.0$abtype | is.na(df.0$abtype), df.0$abtype, "Others")

# recode NA -> no recorded antibiotics
df.0$type=ifelse(is.na(df.0$type),"No_antibiotics", df.0$type)
df.0$type <- factor(df.0$type, levels=c(DF.top10.0$abtype,"Others","No_antibiotics"))# reorder


# consultation with AB 
df.0=df.0%>%group_by(date,type)%>%summarise(count=sum(count),total=mean(total))
#df.0$percentage=df.0$count/df.0$total


## csv check for plot
rm(DF.top10.0,DF.top10.1,df)
df.1$prevalent=as.factor(1)
df.0$prevalent=as.factor(0)
df=rbind(df.0,df.1)

# redacted
df$raw_count=df$count
df$raw_total=df$total
df$count=ifelse(df$count<=6,6, df$count)
df=df%>%group_by(date,prevalent)%>%mutate(total=sum(count))
df$percentage=df$count/df$total

df.1=df%>%filter(prevalent==1)
df.0=df%>%filter(prevalent==0)
```


## incident
```{r echo=FALSE}
# incident
ggplot(df.0, aes(x=date, y=percentage, group=type,color=type))+
  annotate(geom = "rect", xmin = as.Date("2021-01-01"),xmax = as.Date("2021-04-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-11-01"),xmax = as.Date("2020-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-03-01"),xmax = as.Date("2020-06-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_line(aes(linetype=type))+
  geom_point(aes(shape=type),size=0.5)+
  theme(legend.position = "right",legend.title =element_blank())+
  scale_shape_manual(values = c(rep(1:11))) +
  scale_color_manual(values = c("coral2","deeppink3","darkred","blue","green4","goldenrod2","blue3","green3","forestgreen","dodgerblue","black"))+
  labs(
    y = "" ,
    x="")+
  theme(axis.text.x=element_text(angle=60,hjust=1))+
  scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month", limits = c(as.Date("2019-01-01"),as.Date("2022-06-01")))+
  scale_y_continuous(labels = scales::percent)+
  ggtitle("Otitis externa")+
  theme(text = element_text(size = 10))+
  theme(plot.title = element_text(size = 12))   

```

## prevalent
```{r echo=FALSE}
### line graph
# prevalent
ggplot(df.1, aes(x=date, y=percentage, group=type,color=type))+
  annotate(geom = "rect", xmin = as.Date("2021-01-01"),xmax = as.Date("2021-04-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-11-01"),xmax = as.Date("2020-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-03-01"),xmax = as.Date("2020-06-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_line(aes(linetype=type))+
  geom_point(aes(shape=type),size=0.5)+
  theme(legend.position = "right",legend.title =element_blank())+
  scale_shape_manual(values = c(rep(1:11))) +
  scale_color_manual(values = c("coral2","deeppink3","darkred","blue","green4","goldenrod2","blue3","green3","forestgreen","dodgerblue","black"))+
  labs(
    y = "" ,
    x="")+
  theme(axis.text.x=element_text(angle=60,hjust=1))+
  scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month", limits = c(as.Date("2019-01-01"),as.Date("2022-06-01")))+
  scale_y_continuous(labels = scales::percent)+
  ggtitle("Otitis externa")+
  theme(text = element_text(size = 10))+
  theme(plot.title = element_text(size = 12))   


```





# Otitis media

```{r include=FALSE}
rm(list=ls())
#setwd(here::here("output", "measures"))
#setwd("/Users/yayang/Documents/GitHub/amr-uom-brit/output/measures")
df=readRDS(here::here("output","measures","abtype_otmedia.rds"))
df=bind_rows(df)


# remove last month data
last.date=max(df$date)
df=df%>% filter(date!=last.date)
first_mon <- (format(min(df$date), "%m-%Y"))
last_mon <- (format(max(df$date), "%m-%Y"))


# variable types
df$prevalent=as.factor(df$prevalent)
df$date=as.Date(df$date)
df$abtype=as.character(df$abtype)

## filter case with ab
df=df%>%filter(!is.na(abtype))

##select prevalent cases
# calculate ab types
df.1=df%>%filter(prevalent==1)%>%group_by(date)%>%mutate(total=n())
df.1=df.1%>%group_by(date,abtype)%>%summarise(count=n(),total=mean(total))


# top 3 ab
DF.top10.1=df.1%>%
  group_by(abtype)%>%
  summarise(count=sum(count))%>% 
  arrange(desc(count))%>%
  slice(1:5)

# sort ab type
# recode other types
df.1$type=ifelse(df.1$abtype %in% DF.top10.1$abtype | is.na(df.1$abtype), df.1$abtype, "Others")

# recode NA -> no recorded antibiotics
df.1$type=ifelse(is.na(df.1$type),"No_antibiotics", df.1$type)
df.1$type <- factor(df.1$type, levels=c(DF.top10.1$abtype,"Others","No_antibiotics"))# reorder


# consultation with AB 
df.1=df.1%>%group_by(date,type)%>%summarise(count=sum(count),total=mean(total))
##df.1$percentage=df.1$count/df.1$total

##select incident cases
# calculate ab types
df.0=df%>%filter(prevalent==0)%>%group_by(date)%>%mutate(total=n())
df.0=df.0%>%group_by(date,abtype)%>%summarise(count=n(),total=mean(total))


# top 5 ab
DF.top10.0=df.0%>%
  group_by(abtype)%>%
  summarise(count=sum(count))%>% 
  arrange(desc(count))%>%
  slice(1:5)

# sort ab type
# recode other types
df.0$type=ifelse(df.0$abtype %in% DF.top10.0$abtype | is.na(df.0$abtype), df.0$abtype, "Others")

# recode NA -> no recorded antibiotics
df.0$type=ifelse(is.na(df.0$type),"No_antibiotics", df.0$type)
df.0$type <- factor(df.0$type, levels=c(DF.top10.0$abtype,"Others","No_antibiotics"))# reorder


# consultation with AB 
df.0=df.0%>%group_by(date,type)%>%summarise(count=sum(count),total=mean(total))
#df.0$percentage=df.0$count/df.0$total


## csv check for plot
rm(DF.top10.0,DF.top10.1,df)
df.1$prevalent=as.factor(1)
df.0$prevalent=as.factor(0)
df=rbind(df.0,df.1)

# redacted
df$raw_count=df$count
df$raw_total=df$total
df$count=ifelse(df$count<=6,6, df$count)
df=df%>%group_by(date,prevalent)%>%mutate(total=sum(count))
df$percentage=df$count/df$total

df.1=df%>%filter(prevalent==1)
df.0=df%>%filter(prevalent==0)
```


## incident
```{r echo=FALSE}
# incident
ggplot(df.0, aes(x=date, y=percentage, group=type,color=type))+
  annotate(geom = "rect", xmin = as.Date("2021-01-01"),xmax = as.Date("2021-04-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-11-01"),xmax = as.Date("2020-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-03-01"),xmax = as.Date("2020-06-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_line(aes(linetype=type))+
  geom_point(aes(shape=type),size=0.5)+
  theme(legend.position = "right",legend.title =element_blank())+
  scale_shape_manual(values = c(rep(1:11))) +
  scale_color_manual(values = c("coral2","deeppink3","darkred","blue","green4","goldenrod2","blue3","green3","forestgreen","dodgerblue","black"))+
  labs(
    y = "" ,
    x="")+
  theme(axis.text.x=element_text(angle=60,hjust=1))+
  scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month", limits = c(as.Date("2019-01-01"),as.Date("2022-06-01")))+
  scale_y_continuous(labels = scales::percent)+
  ggtitle("Otitis media")+
  theme(text = element_text(size = 10))+
  theme(plot.title = element_text(size = 12))   

```

## prevalent
```{r echo=FALSE}
### line graph
# prevalent
ggplot(df.1, aes(x=date, y=percentage, group=type,color=type))+
  annotate(geom = "rect", xmin = as.Date("2021-01-01"),xmax = as.Date("2021-04-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-11-01"),xmax = as.Date("2020-12-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  annotate(geom = "rect", xmin = as.Date("2020-03-01"),xmax = as.Date("2020-06-01"),ymin = -Inf, ymax = Inf,fill="grey80", alpha=0.5)+
  geom_line(aes(linetype=type))+
  geom_point(aes(shape=type),size=0.5)+
  theme(legend.position = "right",legend.title =element_blank())+
  scale_shape_manual(values = c(rep(1:11))) +
  scale_color_manual(values = c("coral2","deeppink3","darkred","blue","green4","goldenrod2","blue3","green3","forestgreen","dodgerblue","black"))+
  labs(
    y = "" ,
    x="")+
  theme(axis.text.x=element_text(angle=60,hjust=1))+
  scale_x_date(date_labels = "%m-%Y", date_breaks = "1 month", limits = c(as.Date("2019-01-01"),as.Date("2022-06-01")))+
  scale_y_continuous(labels = scales::percent)+
  ggtitle("Otitis media")+
  theme(text = element_text(size = 10))+
  theme(plot.title = element_text(size = 12))   


```



