---
title: "TPP region"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include=FALSE}
require('tidyverse')
require("gtsummary")
```


# Jan 2019

```{r}
#df1=read_csv("/Users/yayang/Documents/GitHub/amr-uom-brit/output/measures/input_2019-01-01.csv.gz")

df1 <- read_csv(here::here("output","measures","input_2019-01-01.csv.gz"))

df1=df1%>% select("region","age","sex")



```

```{r}
table(df1$sex)
mean(df1$age)
median(df1$age)

median(df1[df1$region=="East",]$age,na.rm = T)
median(df1[df1$region=="East Midlands",]$age,na.rm = T)
median(df1[df1$region=="London",]$age,na.rm = T)
median(df1[df1$region=="North East",]$age,na.rm = T)
median(df1[df1$region=="North West",]$age,na.rm = T)
median(df1[df1$region=="South East",]$age,na.rm = T)
median(df1[df1$region=="South West",]$age,na.rm = T)
median(df1[df1$region=="West Midlands",]$age,na.rm = T)
median(df1[df1$region=="Yorkshire and The Humber",]$age,na.rm = T)


```



# Jan 2020

```{r}
#df1=read_csv("/Users/yayang/Documents/GitHub/amr-uom-brit/output/measures/input_2019-01-01.csv.gz")

df1 <- read_csv(here::here("output","measures","input_2020-01-01.csv.gz"))

df1=df1%>% select("region","age","sex")



```

```{r}

table(df1$sex)
mean(df1$age)
median(df1$age)

median(df1[df1$region=="East",]$age,na.rm = T)
median(df1[df1$region=="East Midlands",]$age,na.rm = T)
median(df1[df1$region=="London",]$age,na.rm = T)
median(df1[df1$region=="North East",]$age,na.rm = T)
median(df1[df1$region=="North West",]$age,na.rm = T)
median(df1[df1$region=="South East",]$age,na.rm = T)
median(df1[df1$region=="South West",]$age,na.rm = T)
median(df1[df1$region=="West Midlands",]$age,na.rm = T)
median(df1[df1$region=="Yorkshire and The Humber",]$age,na.rm = T)

```



# Jan 2021

```{r}
#df1=read_csv("/Users/yayang/Documents/GitHub/amr-uom-brit/output/measures/input_2019-01-01.csv.gz")

df1 <- read_csv(here::here("output","measures","input_2021-01-01.csv.gz"))

df1=df1%>% select("region","age","sex")



```

```{r}
table(df1$sex)
mean(df1$age)
median(df1$age)

median(df1[df1$region=="East",]$age,na.rm = T)
median(df1[df1$region=="East Midlands",]$age,na.rm = T)
median(df1[df1$region=="London",]$age,na.rm = T)
median(df1[df1$region=="North East",]$age,na.rm = T)
median(df1[df1$region=="North West",]$age,na.rm = T)
median(df1[df1$region=="South East",]$age,na.rm = T)
median(df1[df1$region=="South West",]$age,na.rm = T)
median(df1[df1$region=="West Midlands",]$age,na.rm = T)
median(df1[df1$region=="Yorkshire and The Humber",]$age,na.rm = T)

```


