---
title: "check number after rerunning extraction"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include=FALSE}
library('tidyverse')
library("ggplot2")
library('dplyr')
library('lubridate')
```


# <font color=blue>**variable extraction**</font>
```{r include=FALSE}
# extracted dataset after matching
DF1=read_csv(here::here("output","input_outcome.csv"))
#DF1=read.csv("/Users/yayang/Documents/GitHub/amr-uom-brit/output/input_outcome.csv")
names(DF1)
nrow(DF1)



```

# <font color=blue>**matched dataset**</font>
```{r}
## add variables to extracted cohort:"subclass","case", 
DF2 <- read_rds(here::here("output","matched_patients.rds"))
#DF2=readRDS("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_outcome.rds")

names(DF2)
nrow(DF2)

table(DF2$case)

```

# <font color=blue>**merged dataset**</font>
```{r}
#DF2 = subset(DF2,select=c("patient_id","age","sex","set_id","case", "match_counts","stp"))
DF2 = DF2%>%select(c("patient_id","sex","stp","subclass","case","patient_index_date"))

#df=merge(DF1,DF2,by=c("patient_id","age","sex","stp"),all.x=T) can't merge with dummy data
df=merge(DF1,DF2,by=c("patient_id","sex","stp","patient_index_date"),all=T)

names(df)
nrow(df)

table(df$case)
```

