---
title: "AB types"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
##library(kableExtra)
library('tidyverse')
#library("gtsummary")
library("ggplot2")
library(scales)
library(survival)
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")
```

```{r}

#df <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/abtype79.rds")
df <- read_rds(here::here("output","abtype79.rds"))
col=c("Rx_Amikacin", "Rx_Amoxicillin", "Rx_Ampicillin", "Rx_Azithromycin", "Rx_Aztreonam", "Rx_Benzylpenicillin", "Rx_Cefaclor", "Rx_Cefadroxil", "Rx_Cefalexin", "Rx_Cefamandole", "Rx_Cefazolin", "Rx_Cefepime", "Rx_Cefixime", "Rx_Cefotaxime", "Rx_Cefoxitin", "Rx_Cefpirome", "Rx_Cefpodoxime", "Rx_Cefprozil", "Rx_Cefradine", "Rx_Ceftazidime", "Rx_Ceftriaxone", "Rx_Cefuroxime", "Rx_Chloramphenicol", "Rx_Cilastatin", "Rx_Ciprofloxacin", "Rx_Clarithromycin", "Rx_Clindamycin", "Rx_Co_amoxiclav", "Rx_Co_fluampicil", "Rx_Colistimethate", "Rx_Dalbavancin", "Rx_Dalfopristin", "Rx_Daptomycin", "Rx_Demeclocycline", "Rx_Doripenem", "Rx_Doxycycline", "Rx_Ertapenem", "Rx_Erythromycin", "Rx_Fidaxomicin", "Rx_Flucloxacillin", "Rx_Fosfomycin", "Rx_Fusidate", "Rx_Gentamicin", "Rx_Levofloxacin", "Rx_Linezolid", "Rx_Lymecycline", "Rx_Meropenem", "Rx_Methenamine", "Rx_Metronidazole", "Rx_Minocycline", "Rx_Moxifloxacin", "Rx_Nalidixic_acid", "Rx_Neomycin", "Rx_Netilmicin", "Rx_Nitazoxanid", "Rx_Nitrofurantoin", "Rx_Norfloxacin", "Rx_Ofloxacin", "Rx_Oxytetracycline", "Rx_Phenoxymethylpenicillin", "Rx_Piperacillin", "Rx_Pivmecillinam", "Rx_Pristinamycin", "Rx_Rifaximin", "Rx_Sulfadiazine", "Rx_Sulfamethoxazole", "Rx_Sulfapyridine", "Rx_Taurolidin", "Rx_Tedizolid", "Rx_Teicoplanin", "Rx_Telithromycin", "Rx_Temocillin", "Rx_Tetracycline", "Rx_Ticarcillin", "Rx_Tigecycline", "Rx_Tinidazole", "Rx_Tobramycin", "Rx_Trimethoprim", "Rx_Vancomycin")


df1=df%>% filter(case==1)
df0=df%>% filter(case==0) %>% group_by(subclass) %>% sample_n(1)
DF=rbind(df1,df0)

DF$sum=rowSums(DF[1:79])
outlier=quantile(DF$sum, 0.9)
DF=DF%>%filter(sum<=outlier)
```



```{r}
# univariate regression
#clogit(case ~ Rx_Amoxicillin + strata(subclass), data=DF)
#clogit(case ~ Rx_Doxycycline + strata(subclass), data=DF)
#clogit(case ~ Rx_Flucloxacillin + strata(subclass), data=DF)
#clogit(case ~ Rx_Nitrofurantoin + strata(subclass), data=DF)

```

# scatter plot
```{r}
# Scatter plot
#DF=DF%>% select(-"subclass")

DF$case=as.factor(DF$case)

DF_1=DF%>% filter(case==1)%>% select(subclass,Rx_Nitrofurantoin, Rx_Trimethoprim, Rx_Amoxicillin, Rx_Flucloxacillin, Rx_Doxycycline) 
names(DF_1)[2]<-"N.case"
names(DF_1)[3]<-"T.case"
names(DF_1)[4]<-"A.case"
names(DF_1)[5]<-"F.case"
names(DF_1)[6]<-"D.case"

DF_0=DF%>% filter(case==0)%>% select(subclass,Rx_Nitrofurantoin, Rx_Trimethoprim, Rx_Amoxicillin, Rx_Flucloxacillin, Rx_Doxycycline) 
names(DF_0)[2]<-"N.con"
names(DF_0)[3]<-"T.con"
names(DF_0)[4]<-"A.con"
names(DF_0)[5]<-"F.con"
names(DF_0)[6]<-"D.con"

df=merge(DF_1,DF_0, by="subclass")

df$diff_N=df$N.case-df$N.con
df$diff_T=df$T.case-df$T.con
df$diff_A=df$A.case-df$A.con
df$diff_F=df$F.case-df$F.con
df$diff_D=df$D.case-df$D.con

```

```{r}
hist(df$diff_N)
hist(df$diff_T)
hist(df$diff_A)
hist(df$diff_F)
hist(df$diff_D)

```


```{r}
p<- ggplot(df, aes(N.case, N.con))
p +   geom_point(alpha=1/10) + geom_smooth(method=lm)


p<- ggplot(df, aes(T.case, T.con))
p +   geom_point(alpha=1/10) + geom_smooth(method=lm)
p<- ggplot(df, aes(A.case, A.con))
p +   geom_point(alpha=1/10) + geom_smooth(method=lm)
p<- ggplot(df, aes(F.case, F.con))
p +   geom_point(alpha=1/10) + geom_smooth(method=lm)
p<- ggplot(df, aes(D.case, D.con))
p +   geom_point(alpha=1/10) + geom_smooth(method=lm)
```

```{r}
# Quick display of two cabapilities of GGally, to assess the distribution and correlation of variables 
library(GGally)
 
# From the help page:

ggpairs(df, columns = 2:10) 
```



# frequency table
## case
```{r}
DF1=data.frame(colSums(Filter(is.numeric, df1[col])))
names(DF1)[1] <- "sum.case"

total=sum(DF1[,1])
DF1$percent.case=DF1[,1]/total

DF1%>% arrange(desc(sum.case))%>% top_n(10)

```


## control
```{r}
DF0=data.frame(colSums(Filter(is.numeric, df0[col])))
names(DF0)[1] <- "sum.control"


total=sum(DF0[,1])
DF0$percent.case=DF0[,1]/total

DF0%>% arrange(desc(sum.control))%>% top_n(10)

```

## difference
```{r}
DF=cbind(DF1,DF0)
DF$diff=DF[,1]-DF[,3]
DF$diff.percent=DF[,2]-DF[,4]

DF[,2]=label_percent()(DF[,2])
DF[,4]=label_percent()(DF[,4])
DF[,6]=label_percent()(DF[,6])

DF
```

