---
title: "AB in recent 1 year vs. 3 year"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
library('tidyverse')
library("ggplot2")
library('dplyr')
library('lubridate')

knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")
```

# AB year1
```{r}

setwd(here::here("output"))
#setwd("/Users/yayang/Documents/GitHub/amr-uom-brit/output")
# read variables and add "case"
df_ab_extraction=read.csv("input_ab_yr1.csv")

count(df_ab_extraction)

## add variables to extracted cohort:"subclass","case", 
df_matched <- read_rds("matched_patients.rds")
df_matched= df_matched%>%select(c("patient_id","sex","stp","subclass","case","patient_index_date"))

count(df_matched)
#df=merge(DF1,DF2,by=c("patient_id","age","sex","stp"),all.x=T) can't merge with dummy data
df=merge(df_matched,df_ab_extraction,by=c("patient_id","sex","stp","patient_index_date"),all=T)
rm(df_matched,df_ab_extraction)

count(df)
```

```{r}
df1=df%>%filter(case==1)
df0=df%>%filter(case==0)
# random 1 control
df0=df%>% group_by(subclass)%>%sample_n(1)
df0=ungroup(df0)

df=rbind(df1,df0)
count(df1)
count(df0)
count(df)
```


```{r}
AB_name=c("Amoxicillin","Azithromycin","Cefalexin","Ciprofloxacin","Clarithromycin","Co_amoxiclav","Doxycycline","Flucloxacillin","Nitrofurantoin","Phenoxymethylpenicillin","Trimethoprim")

DF_case=data_frame()
for (i in 1:12){
 for (j in 1:11){
   DF_case[i,j]=sum(df1[paste0("Rx_",i,"_",AB_name[j])],na.rm = T)
  }
}
colnames(DF_case)=AB_name

DF_case
```

```{r}

DF_control=data_frame()
for (i in 1:12){
  for (j in 1:11){
    DF_control[i,j]=sum(df0[paste0("Rx_",i,"_",AB_name[j])] ,na.rm = T)
  }
}
colnames(DF_control)=AB_name
DF_control
```

```{r}

DF_case=DF_case%>% gather()
DF_case$month=rep(1:12,11)

DF_control=gather(DF_control)
DF_control$month=rep(1:12,11)

DF_case$case=1
DF_control$case=0

DF=rbind(DF_case,DF_control)

DF$case=as.factor(DF$case)
DF$month=as.factor(DF$month)




```

```{r}
for (i in 1:11){

DF_ab=DF%>%filter(key==AB_name[i])

DF_ab$case=as.factor(DF_ab$case)
DF_ab$month=as.factor(DF_ab$month)

print(
ggplot(data=DF_ab, aes(x=month, y=value, fill=case)) +
  geom_col(position="dodge", stat="identity")
)
}

```

```{r}
# yearly sum

DF.yr1=DF%>%group_by(case,key)%>% summarise(total=sum(value))
DF.yr1$group="1"

rm(df,DF,DF_ab,DF_case,DF_control,df0,df1,AB_name,i,j)
```



# AB year3

```{r}
setwd(here::here("output"))
#setwd("/Users/yayang/Documents/GitHub/amr-uom-brit/output")
df <- read_rds("abtype79.rds")
count(df)

```

```{r}

df1=df%>%filter(case==1)
df0=df%>%filter(case==0)
# random 1 control
df0=df%>% group_by(subclass)%>%sample_n(1)
df0=ungroup(df0)

df=rbind(df1,df0)
count(df1)
count(df0)
count(df)
```


```{r}
keep.var=c("Rx_Amoxicillin","Rx_Azithromycin","Rx_Cefalexin","Rx_Ciprofloxacin","Rx_Clarithromycin","Rx_Co_amoxiclav","Rx_Doxycycline","Rx_Flucloxacillin","Rx_Nitrofurantoin","Rx_Phenoxymethylpenicillin","Rx_Trimethoprim","case")

DF=df[colnames(df) %in% keep.var]

df1=DF%>% filter(case==1)

DF_case=vector()
for (i in 1:11){
   DF_case[i]=sum(df1[keep.var[i]])
  }
DF_case=data.frame(DF_case)

DF_case$AB=keep.var[1:11]

DF_case
```

```{r}

df0=DF%>% filter(case==0)

DF_control=vector()
for (i in 1:11){
   DF_control[i]=sum(df0[keep.var[i]])
  }
DF_control=data.frame(DF_control)

DF_control$AB=keep.var[1:11]

DF_control
```

```{r}
DF_case$case=1
colnames(DF_case)[1]="total"
DF_control$case=0
colnames(DF_control)[1]="total"
DF.yr3=rbind(DF_case,DF_control)
DF.yr3$group=3
rm(df,DF,DF_case,DF_control,df0,df1,keep.var,i)

DF.yr3$AB=gsub("Rx_","",DF.yr3$AB)

```



```{r}
colnames(DF.yr1)[2]="AB"
DF.yr1=DF.yr1%>%select("AB","group","case","total")
DF.yr1=data.frame(DF.yr1)
DF.yr3=DF.yr3%>%select("AB","group","case","total")

DF=rbind(DF.yr1,DF.yr3)

```


```{r}


DF$case=as.factor(DF$case)

p=ggplot(data=DF, aes(x=AB, y=total, fill=group)) +
  geom_col(position="dodge", stat="identity")+
 theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
p  +  facet_grid(vars(case), scales = "free")

```


```{r}
p=ggplot(data=DF, aes(x=AB, y=total, fill=case)) +
  geom_col(position="dodge", stat="identity")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

p  +  facet_grid(vars(group), scales = "free")

```

