---
title: "ab time - 45 extraction"
author: "YT Y"
date: "07/04/2022"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
library('tidyverse')
library("ggplot2")
library(knitr)
library(dplyr)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")
```


```{r}
#setwd(here::here("output"))
setwd('/Users/yayang/Documents/GitHub/amr-uom-brit/output')
df_time=read.csv("input_ab_time.csv")
#head(df_time)
#tail(df_time)
# import matched patients dataset
df=read_rds("matched_outcome.rds")
df=df%>% select("patient_id","patient_index_date","total_ab")
# filter only 1 ID
df=df %>% distinct(patient_id, .keep_all=T)
DF=merge(df,df_time,by=c("patient_id","patient_index_date"), all.x = TRUE)

count(df_time)
count(df)
count(DF)

#head(DF)
#tail(DF)
```

total ab check
```{r }
for (i in 3:129) {
 DF[,i]=ifelse(DF[,i]=="",NA,DF[,i])
 
}

for (i in 54:129) {
 DF[,i]=ifelse(is.na(DF[,i]),0,DF[,i])
 
}


DF$total_check=rowSums(DF[,71:130])

#head(DF)
#tail(DF)
#for (i in 1:45) {
 #  DF$total_check=  DF$total_check + DF[,paste0("AB_",i)]
#}

DF$cover=DF$total_check/DF$total_ab

head(DF)
#plot(DF$cover)

```

# disconcordance
```{r}
plot(DF$total_ab,DF$total_check)
abline(lm(DF$total_check ~ total_ab, data =DF), col = "blue")
```


percentile check coverage
```{r}
quantile(DF$cover,0.99, na.rm=T)
quantile(DF$cover,0.95, na.rm=T)
quantile(DF$cover,0.90, na.rm=T)

quantile(DF$cover,0.75, na.rm=T)
quantile(DF$cover,0.5, na.rm=T)
quantile(DF$cover,0.25, na.rm=T)

```

