---
title: "Input Data Check"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r , include=FALSE}
require('tidyverse')
require("gtsummary")
require("ggplot2")
```

## cohort extractor

#### 1.1 study_population_covid_primary_care 
###### patient_index_date range
```{r}
dat=read_csv(here::here("output","input_covid_primarycare.csv"),
             col_types=cols_only(
               age=col_double(),
               sex=col_character(),
               patient_index_date=col_date()
             ))

range(dat$patient_index_date, na.rm=T)

dat$patient_index_date=ifelse(is.na(dat$patient_index_date),NA,1)

dat %>%
  tbl_summary(
    statistic = list(
      all_continuous() ~ "{min}, {max}",
      all_categorical() ~ "{n} ({p}%)"))
rm(dat)
```

#### 1.2 study_population_covid_SGSS
###### patient_index_date range
```{r}
dat=read_csv(here::here("output","input_covid_SGSS.csv"),
             col_types=cols_only(
               age=col_double(),
               sex=col_character(),
               patient_index_date=col_date()
             ))

range(dat$patient_index_date, na.rm=T)

dat$patient_index_date=ifelse(is.na(dat$patient_index_date),NA,1)

dat %>%
  tbl_summary(
    statistic = list(
      all_continuous() ~ "{min}, {max}",
      all_categorical() ~ "{n} ({p}%)"))
rm(list=ls())

```



##  define case and control
#### 1. covid infection without any covid record later
###### patient_index_date range
```{r}
dat=read_csv(here::here("output","control_covid_infection.csv"),
             col_types=cols_only(
               age=col_double(),
               sex=col_character(),
               patient_index_date=col_date()
             ))

range(dat$patient_index_date, na.rm=T)

dat$patient_index_date=ifelse(is.na(dat$patient_index_date),NA,1)

dat %>%
  tbl_summary(
    statistic = list(
      all_continuous() ~ "{min}, {max}",
      all_categorical() ~ "{n} ({p}%)"))
rm(list=ls())
```


#### 2. covid infection with hospital admission
###### patient_index_date range
```{r}
dat=read_csv(here::here("output","case_covid_hosp.csv"),
             col_types=cols_only(
               age=col_double(),
               sex=col_character(),
               patient_index_date=col_date()
             ))

range(dat$patient_index_date, na.rm=T)

dat$patient_index_date=ifelse(is.na(dat$patient_index_date),NA,1)

dat %>%
  tbl_summary(
    statistic = list(
      all_continuous() ~ "{min}, {max}",
      all_categorical() ~ "{n} ({p}%)"))
rm(list=ls())
```
