---
title: "AB types"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)

library('tidyverse')

library("ggplot2")

library(caret)
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")
```

```{r}

setwd(here::here("output"))
#setwd("/Users/yayang/Documents/GitHub/amr-uom-brit/output")
# read variables and add "case"
df_ab_extraction=read.csv("input_ab_yr1.csv")

## add variables to extracted cohort:"subclass","case", 
df_matched <- read_rds("matched_patients.rds")
df_matched= df_matched%>%select(c("patient_id","sex","stp","subclass","case","patient_index_date"))

count(df_matched)
#df=merge(DF1,DF2,by=c("patient_id","age","sex","stp"),all.x=T) can't merge with dummy data
df=merge(df_matched,df_ab_extraction,by=c("patient_id","sex","stp","patient_index_date"),all=T)
rm(df_matched,df_ab_extraction)

df=df%>%select(-c("patient_id","patient_index_date","sex","stp","subclass","age","ab_first_date","ab_last_date"))
count(df)
```

```{r}


df=df[!is.na(df$case),]
count(df)

col=colnames(df)[2:135]
sum(is.na(df[,col]))

df=df%>%na.omit()
count(df)


```


```{r}
# divide data
set.seed(1024)
all_idx <- 1:nrow(df)

train_idx <- sample(all_idx, nrow(df) * 0.8)
test_idx <- all_idx[!all_idx %in% train_idx]

df.train=df[train_idx,]
df.test=df[test_idx,]

length(all_idx)
length(train_idx)
length(test_idx)
```


```{r echo=TRUE}
# develop model
df.train=sample_n(df.train,1000)

set.seed(123) 
train.control <- trainControl(method = "repeatedcv",
                              number = 5,
                              search="random", repeats=3, savePredictions = T)
# Train the model
model <- train(case ~., data = df.train, method = "rf",
               trControl = train.control, tuneLength= 10, ntree=1000)
# Summarize the results
print(model)
plot(model)

model$bestTune# mtry: Number of variable is randomly collected to be sampled at each split time.

plot(varImp(model,scale = F), main="var imp: RF 5 fold cv")

sub_rf1=subset(model$pred, model$pred$mtry== model$bestTune$mtry)
#caret::confusionMatrix((table(sub_rf1$pred,sub_rf1$obs)))
```

