---
title: "classification_decision tree - category predictor - per predictor"
---

```{r setup, include=FALSE}
library("survival")
library('tidyverse')
library(pROC) #plyr
library(caret) #dplyr
library(randomForest)
library("rpart.plot")
```


```{r }
# import dataset
train <- read_rds(here::here("output","train_cat.rds"))
train$case=as.factor(train$case)

table(train$case)
prop.table(table(train$case))
train=train%>% group_by(subclass)%>% dplyr::mutate(rep.no=n()-1)#count control no. in subclass
train=train%>% ungroup(subclass)

train.1=train%>%filter(case==1)# filter case
train.1 <- as.data.frame(lapply(train.1, rep, train.1$rep.no-1))# duplicate case (6case:6control)
train=rbind(train.1,train) #merge

#table(train$case)
prop.table(table(train$case))
# pick variable
names(train)
col=c("case","total_ab_group","ab_types_group",
      "exposure_period_group","recent_ab_days_group",
      "broad_ab_prescriptions_group",
      "interval_med_group" ,"interval_sd_group")
#"broad_prop_total"

data=train[col]
str(data)
```

```{r}

prop.table(table(data$total_ab_group))
prop.table(table(data$ab_types_group ))
prop.table(table(data$exposure_period_group ))
prop.table(table(data$recent_ab_days_group ))
prop.table(table(data$broad_ab_prescriptions_group ))
prop.table(table(data$interval_med_group))
prop.table(table(data$interval_sd_group))
```


## matched 

### overall tree1
```{r  }
set.seed(1024)
model <-train(case ~. , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

summary(predict(model, type = 'prob')[,2])
```

### overall tree 2
```{r  }
set.seed(999)
model <-train(case ~. , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

summary(predict(model, type = 'prob')[,2])
```


### overall tree 3
```{r  }
set.seed(3)
model <-train(case ~. , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

summary(predict(model, type = 'prob')[,2])
```

## filter ab users (unmatched)
```{r}
data=train%>% distinct(patient_id,.keep_all = TRUE) %>%filter(total_ab>0)
data=data[col]
table(data$case)
prop.table(table(data$case))

```

```{r}
prop.table(table(data$total_ab_group))
prop.table(table(data$ab_types_group ))
prop.table(table(data$exposure_period_group ))
prop.table(table(data$recent_ab_days_group ))
prop.table(table(data$broad_ab_prescriptions_group ))
prop.table(table(data$interval_med_group))
prop.table(table(data$interval_sd_group))
```

### overall tree1
```{r  }
set.seed(1024)
model <-train(case ~. , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

summary(predict(model, type = 'prob')[,2])
```

### overall tree2
```{r  }
set.seed(999)
model <-train(case ~. , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

summary(predict(model, type = 'prob')[,2])
```

### overall tree3
```{r  }
set.seed(3)
model <-train(case ~. , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

summary(predict(model, type = 'prob')[,2])
```

