---
title: "classification_decision tree - category predictor - uni&multi predictor- 1:6 vs 1:1"
---

```{r setup, include=FALSE}
library("survival")
library('tidyverse')
library(pROC) #plyr
library(caret) #dplyr
library(randomForest)
library("rpart.plot")
```


```{r }
# import dataset
train <- read_rds(here::here("output","train_cat.rds"))
train$case=as.factor(train$case)

table(train$case)
prop.table(table(train$case))
```



# 1:1 
```{r }
train=train%>% group_by(subclass)%>% dplyr::mutate(rep.no=n()-1)#count control no. in subclass
train=train%>% ungroup(subclass)

train.1=train%>%filter(case==1)# filter case
train.1 <- as.data.frame(lapply(train.1, rep, train.1$rep.no-1))# duplicate case (6case:6control)
train=rbind(train.1,train) #merge

#table(train$case)
prop.table(table(train$case))
# pick variable
names(train)
col=c("case","total_ab_group","ab_types_group",
      "exposure_period_group","recent_ab_days_group",
      "broad_ab_prescriptions_group",
      "interval_med_group" ,"interval_sd_group")
#"broad_prop_total"

data=train[col]
str(data)
```



### overall tree1
```{r  }
set.seed(1024)

tree.model_list <- list()

for (i in 1:100){
tree.model_list[[i]] <-train(case ~. , 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
}

final_pred <- 0

for (i in 1:length(tree.model_list)) {
  
  prob_list <- predict(tree.model_list[[i]], type = 'prob')
  prob_y <- do.call('rbind', prob_list)[,1]
  final_pred <- final_pred + prob_y / length(tree.model_list)
  
}
summary(final_pred)
```

