---
title: "classification_decision tree - category predictor - per predictor"
---

```{r setup, include=FALSE}
library("survival")
library('tidyverse')
library(pROC) #plyr
library(caret) #dplyr
library(randomForest)
library(rpart)
library("rpart.plot")

```


```{r }
# import dataset
train <- read_rds(here::here("output","train_cat.rds"))
train$case=as.factor(train$case)

#valid <- read_rds(here::here("output","valid_cat.rds"))
#valid$case=as.factor(valid$case)

table(train$case)
# pick variable
names(train)
col=c("case","total_ab_group","ab_types_group",
      "exposure_period_group","recent_ab_days_group",
      "broad_ab_prescriptions_group",
      "interval_med_group" ,"interval_sd_group","age.x")
#"broad_prop_total"

data=train[col]
str(data)
```

```{r}

prop.table(table(data$total_ab_group))
prop.table(table(data$ab_types_group))
prop.table(table(data$exposure_period_group))
prop.table(table(data$recent_ab_days_group))
prop.table(table(data$broad_ab_prescriptions_group))
prop.table(table(data$interval_med_group))
prop.table(table(data$interval_sd_group))
```


## matched 
### total_ab_group
```{r, fig.width=13, fig.height=20 }
set.seed(324)
model<- rpart(
  case ~ total_ab_group, 
  data = data, 
  method = "class"
 # minsplit = 2,  minbucket = 1
  )

print(model)

try(rpart.plot(model))

```
<br/><br/>

### ab_types_group
```{r }
set.seed(324)
model<- rpart(
  case ~ ab_types_group, 
  data = data, 
  method = "class",
 control=rpart.control(minsplit=2, minbucket=1, cp=0.001)
  )

  
print(model)

try(rpart.plot(model))

```

### exposure_period_group
```{r }
set.seed(324)

model<- rpart(
  case ~ exposure_period_group, 
  data = data, 
  method = "class",
 control=rpart.control(minsplit=2, minbucket=1, cp=0.001)  )
  
print(model)

try(rpart.plot(model))

```

### recent_ab_days_group
```{r }
set.seed(324)
model<- rpart(
  case ~ recent_ab_days_group, 
  data = data, 
  method = "class",
 control=rpart.control(minsplit=2, minbucket=1, cp=0.001)  )
  
print(model)

try(rpart.plot(model))

```

### broad_ab_prescriptions_group
```{r }
set.seed(324)
model<- rpart(
  case ~ broad_ab_prescriptions_group, 
  data = data, 
  method = "class",
 control=rpart.control(minsplit=2, minbucket=1, cp=0.001)  )
print(model)

try(rpart.plot(model))

```

### interval_med_group
```{r }
set.seed(324)

model<- rpart(
  case ~interval_med_group, 
  data = data, 
  method = "class",
 control=rpart.control(minsplit=2, minbucket=1, cp=0.001)  )
  
print(model)

try(rpart.plot(model))

```

### interval_sd_group
```{r }
set.seed(324)

model<- rpart(
  case ~interval_sd_group, 
  data = data, 
  method = "class",
 control=rpart.control(minsplit=2, minbucket=1, cp=0.001)  )
  
  
print(model)

try(rpart.plot(model))

```




## filter ab users (unmatched)
```{r}
data=train%>% distinct(patient_id,.keep_all = TRUE) %>%filter(total_ab>0)
data=data[col]
table(data$case)
prop.table(table(data$case))

```

```{r}

prop.table(table(data$total_ab_group))
prop.table(table(data$ab_types_group))
prop.table(table(data$exposure_period_group))
prop.table(table(data$recent_ab_days_group))
prop.table(table(data$broad_ab_prescriptions_group))
prop.table(table(data$interval_med_group))
prop.table(table(data$interval_sd_group))
```

### total_ab_group
```{r, fig.width=13, fig.height=20 }
set.seed(324)
model<- rpart(
  case ~ total_ab_group, 
  data = data, 
  method = "class",
 control=rpart.control(minsplit=2, minbucket=1, cp=0.001)  )

print(model)

try(rpart.plot(model))

```
<br/><br/>

### ab_types_group
```{r }
set.seed(324)
model<- rpart(
  case ~ ab_types_group, 
  data = data, 
  method = "class",
 control=rpart.control(minsplit=2, minbucket=1, cp=0.001)  )

  
print(model)

try(rpart.plot(model))

```

### exposure_period_group
```{r }
set.seed(324)

model<- rpart(
  case ~ exposure_period_group, 
  data = data, 
  method = "class",
 control=rpart.control(minsplit=2, minbucket=1, cp=0.001)  )
  
print(model)

try(rpart.plot(model))

```

### recent_ab_days_group
```{r }
set.seed(324)
model<- rpart(
  case ~ recent_ab_days_group, 
  data = data, 
  method = "class",
 control=rpart.control(minsplit=2, minbucket=1, cp=0.001)  )
  
print(model)

try(rpart.plot(model))

```

### broad_ab_prescriptions_group
```{r }
set.seed(324)
model<- rpart(
  case ~ broad_ab_prescriptions_group, 
  data = data, 
  method = "class",
 control=rpart.control(minsplit=2, minbucket=1, cp=0.001)  )
print(model)

try(rpart.plot(model))

```

### interval_med_group
```{r }
set.seed(324)

model<- rpart(
  case ~interval_med_group, 
  data = data, 
  method = "class",
 control=rpart.control(minsplit=2, minbucket=1, cp=0.001)  )
  
print(model)

try(rpart.plot(model))

```

### interval_sd_group
```{r }
set.seed(324)

model<- rpart(
  case ~interval_sd_group, 
  data = data, 
  method = "class",
 control=rpart.control(minsplit=2, minbucket=1, cp=0.001)  )
  
  
print(model)

try(rpart.plot(model))

```