---
title: "classification_decision tree - category predictor - per predictor"
---

```{r setup, include=FALSE}
library("survival")
library('tidyverse')
library(pROC) #plyr
library(caret) #dplyr
library(randomForest)
library("rpart.plot")
```


```{r }
# import dataset
train <- read_rds(here::here("output","train_cat.rds"))
train$case=as.factor(train$case)

#valid <- read_rds(here::here("output","valid_cat.rds"))
#valid$case=as.factor(valid$case)

table(train$case)
# pick variable
names(train)
col=c("case","total_ab_group","ab_types_group",
      "exposure_period_group","recent_ab_days_group",
      "broad_ab_prescriptions_group",
      "interval_med_group" ,"interval_sd_group")
#"broad_prop_total"

data=train[col]
str(data)
```

```{r}

prop.table(table(data$total_ab_group))
prop.table(table(data$ab_types_group))
prop.table(table(data$exposure_period_group))
prop.table(table(data$recent_ab_days_group))
prop.table(table(data$broad_ab_prescriptions_group))
prop.table(table(data$interval_med_group))
prop.table(table(data$interval_sd_group))
```


## matched 
### total_ab_group
```{r }
set.seed(124)
model <-train(case ~total_ab_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

```

### ab_types_group
```{r }
set.seed(124)
model <-train(case ~ab_types_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))

```

### exposure_period_group
```{r }
set.seed(124)
model <-train(case ~exposure_period_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))

```

### recent_ab_days_group
```{r }
set.seed(124)
model <-train(case ~recent_ab_days_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))

```

### broad_ab_prescriptions_group
```{r }
set.seed(124)
model <-train(case ~broad_ab_prescriptions_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))

```

### interval_med_group
```{r }
set.seed(124)
model <-train(case ~interval_med_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))

```

### interval_sd_group
```{r }
set.seed(124)
model <-train(case ~interval_sd_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))

```

```{r eval=FALSE, include=FALSE}
library(rpart)
rf.model<- rpart(
  case ~ ., 
  data = data, 
  method = "class"
 # minsplit = 2,  minbucket = 1
  )

print(rf.model)
par(xpd = NA)
plot(rf.model)
text(rf.model,  digits = 3)
```


```{r eval=FALSE, include=FALSE}
rf.model <- randomForest(formula = case ~ ., data = data, 
                           replace = TRUE,
                           ntree =  1,
                           sampsize = round(nrow(data)*0.6),
                           nodesize = 1 ,
                           mtry = sqrt(ncol(data)-1)
                          )
  print(rf.model)
  getTree(rf.model, k=1, labelVar=TRUE)

```


## filter ab users (unmatched)
```{r}
data=train%>% distinct(patient_id,.keep_all = TRUE) %>%filter(total_ab>0)
data=data[col]
table(data$case)
prop.table(table(data$case))

```

```{r}

prop.table(table(data$total_ab_group))
prop.table(table(data$ab_types_group))
prop.table(table(data$exposure_period_group))
prop.table(table(data$recent_ab_days_group))
prop.table(table(data$broad_ab_prescriptions_group))
prop.table(table(data$interval_med_group))
prop.table(table(data$interval_sd_group))
```

### total_ab_group
```{r }
set.seed(124)
model <-train(case ~total_ab_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model
#try(par(xpd = NA)) # Avoid clipping the text in some device
#try(plot(model$finalModel))
#try(text(model$finalModel,  digits = 3,cex=0.7))

try(rpart.plot(model$finalModel))

```

### ab_types_group
```{r }
set.seed(124)
model <-train(case ~ab_types_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))

```

### exposure_period_group
```{r }
set.seed(124)
model <-train(case ~exposure_period_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))

```

### recent_ab_days_group
```{r }
set.seed(124)
model <-train(case ~recent_ab_days_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))

```

### broad_ab_prescriptions_group
```{r }
set.seed(124)
model <-train(case ~broad_ab_prescriptions_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))

```

### interval_med_group
```{r }
set.seed(124)
model <-train(case ~interval_med_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))

```

### interval_sd_group
```{r }
set.seed(124)
model <-train(case ~interval_sd_group, 
                  data=data, method="rpart",
                  trControl = trainControl("cv", number = 5),
                  tuneLength=5)
  
print(model)
model$finalModel
# Plot the final tree model

try(rpart.plot(model$finalModel))

```
