---
title: "classification comparison: RF vs logistic"
---

```{r setup, include=FALSE}
library("survival")
library('tidyverse')
library(pROC)
library(randomForest)
library(plyr)
```

# import dataset
```{r }
train <- read_rds(here::here("output","train_X.rds"))
train$case=as.factor(train$case)

valid <- read_rds(here::here("output","valid_X.rds"))
valid$case=as.factor(valid$case)

table(train$case)
table(valid$case)
```

# separate dataset: random one control
```{r }

set.seed(123)
train=train%>%group_by(case, subclass)%>%sample_n(1)
valid=valid%>%group_by(case, subclass)%>%sample_n(1)

table(train$case)
table(valid$case)

train=train%>%ungroup(case,subclass)
valid=valid%>%ungroup(case,subclass)

```


# pick variable
```{r}
names(train)
col=c("case","total_ab","ab_types","subclass",
      "prescribe_time_0","prescribe_time_1","prescribe_time_2","prescribe_time_3",
      "exposure_period","recent_ab_days",
      "broad_ab_prescriptions","broad_prop_total","broad_prop",
      "interval_med" ,"interval_mean","interval_CV","interval_sd",
      "length_med","length_mean","length_CV","length_sd")


train=train[col]

str(train)
```

# Randomforest
```{r}
n=nrow(train)
data=train[col[c(1,2)]] # select predicotr
```


```{r}
set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~ ., data = data, 
                           replace = TRUE,
                           ntree =  3000,
                           sampsize = round(n*0.7),
                           nodesize = 50 ,
                           mtry = sqrt(ncol(train)-1)
                          )
  print(rf.model)
```


## model performance

### train
```{r}
# probabilities of cases
pred.y <- predict(rf.model, train, type = 'prob')[,2]

#  c statistic / AUC
roc_train <- roc(train$case ~ pred.y, smoothed = TRUE,
            ci=TRUE, ci.alpha=0.9, stratified=FALSE,
            plot=TRUE, auc.polygon=TRUE, max.auc.polygon=TRUE, grid=TRUE,
            print.auc=TRUE, show.thres=TRUE)
print(roc_train) #AUC


# E/O
O <- prop.table(table(train$case))[2]
E <- mean(pred.y)
E/O
```


```{r}
library(dplyr)
# calibration 
# create 10 risk groups
groups <- cut(pred_prob,breaks=quantile(pred_prob, prob = c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0)),labels=c(1:10),include.lowest=TRUE)

# average the observed and expected probabilities of patients in each risk group 
gpdata <- cbind(train,groups,pred.y)
obs <- (ddply(gpdata,~groups,summarise,mean=mean(as.numeric(as.character(case))))[,2])
exp <- ddply(gpdata,~groups,summarise,mean=mean(pred.y))
obsn <- table(train$case,groups)[1,] 

cbind(exp,obs)# expected value vs. observed value
 
# CIs for scatter points
lci = pmax(0,(obs - (1.96*(((obs*(1-obs))/obsn)^.5))))
uci = pmin(1,(obs + (1.96*(((obs*(1-obs))/obsn)^.5))))

# graph a simple calibration plot over 10 risk groups
par(pty="s")
plot(obs~exp[,2],xlim=c(0,1),ylim=c(0,1),col="red",ylab="Observed",xlab="Expected")
lines(c(0,1),c(0,1),lty=2)

for(i in 1:10){
lines(c(exp[i,2],exp[i,2]),c(lci[i],uci[i]),col="green")
}

h <- hist(pred.y, breaks=50, plot=FALSE)
for(i in 1:length(h$mids)){
  lines(c(h$mids[i],h$mids[i]),c(rep(1,length(h$mids))[i],1-((h$counts[i]/max(h$counts))/10)))
}

# Add a loess smoother to the plot
obs_all <- predict(loess(as.numeric(as.character(train$case))~pred.y,span=1))
lines_data <- data.frame(pred.y,obs_all)
lines_data2 <- lines_data[order(pred.y),] 
lines(lines_data2[,1],lines_data2[,2],col="blue")
legend(0.0,0.9,c("Risk groups","Reference line","95% CI","Loess"),col=c("red","black","green","blue"),lty=c(0,2,1,1),pch=c(1,NA,NA,NA),bty="n")

```



### valid
```{r}
# probabilities of cases
pred.y <- predict(rf.model, valid, type = 'prob')[,2]

#  c statistic / AUC
roc_valid <- roc(valid$case ~ pred.y, smoothed = TRUE,
            ci=TRUE, ci.alpha=0.9, stratified=FALSE,
            plot=TRUE, auc.polygon=TRUE, max.auc.polygon=TRUE, grid=TRUE,
            print.auc=TRUE, show.thres=TRUE)
print(roc_valid) #AUC


# E/O
O <- prop.table(table(valid$case))[2]
E <- mean(pred.y)
E/O
```


```{r}
library(dplyr)
# calibration 
# create 10 risk groups
groups <- cut(pred_prob,breaks=quantile(pred_prob, prob = c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0)),labels=c(1:10),include.lowest=TRUE)

# average the observed and expected probabilities of patients in each risk group 
gpdata <- cbind(valid,groups,pred.y)
obs <- (ddply(gpdata,~groups,summarise,mean=mean(as.numeric(as.character(case))))[,2])
exp <- ddply(gpdata,~groups,summarise,mean=mean(pred.y))
obsn <- table(valid$case,groups)[1,] 

cbind(exp,obs)# expected value vs. observed value
 
# CIs for scatter points
lci = pmax(0,(obs - (1.96*(((obs*(1-obs))/obsn)^.5))))
uci = pmin(1,(obs + (1.96*(((obs*(1-obs))/obsn)^.5))))

# graph a simple calibration plot over 10 risk groups
par(pty="s")
plot(obs~exp[,2],xlim=c(0,1),ylim=c(0,1),col="red",ylab="Observed",xlab="Expected")
lines(c(0,1),c(0,1),lty=2)

for(i in 1:10){
lines(c(exp[i,2],exp[i,2]),c(lci[i],uci[i]),col="green")
}

h <- hist(pred.y, breaks=50, plot=FALSE)
for(i in 1:length(h$mids)){
  lines(c(h$mids[i],h$mids[i]),c(rep(1,length(h$mids))[i],1-((h$counts[i]/max(h$counts))/10)))
}

# Add a loess smoother to the plot
obs_all <- predict(loess(as.numeric(as.character(valid$case))~pred.y,span=1))
lines_data <- data.frame(pred.y,obs_all)
lines_data2 <- lines_data[order(pred.y),] 
lines(lines_data2[,1],lines_data2[,2],col="blue")
legend(0.0,0.9,c("Risk groups","Reference line","95% CI","Loess"),col=c("red","black","green","blue"),lty=c(0,2,1,1),pch=c(1,NA,NA,NA),bty="n")

```








# logistic regression
```{r}
rf.model=clogit(case ~ total_ab + strata(subclass),data) 
print(rf.model)
```

# model performance
## train
```{r}
# probabilities of cases
pred.y <- predict(rf.model, train, type = 'expected')

#  c statistic / AUC
roc_train <- roc(train$case ~ pred.y, smoothed = TRUE,
            ci=TRUE, ci.alpha=0.9, stratified=FALSE,
            plot=TRUE, auc.polygon=TRUE, max.auc.polygon=TRUE, grid=TRUE,
            print.auc=TRUE, show.thres=TRUE)
print(roc_train) #AUC


# E/O
O <- prop.table(table(train$case))[2]
E <- mean(pred.y)
E/O
```

## create decile group of risk probability
```{r}

vec=vector()

for (i in 1:10){
  vec[i]=quantile(prob,(i/10),na.rm=T)
}

vec# decile value

groups=prob
groups=ifelse(prob <=vec[1],1,groups)

for (i in 1:9) {
groups=ifelse(groups >vec[i] & groups <=vec[i+1],i,groups)  
}

groups=ifelse(prob > vec[10],10,decile)

table(groups)
prop.table(table(groups))*100 # % decile

```

```{r}
library(dplyr)
# calibration 

# average the observed and expected probabilities of patients in each risk group 
gpdata <- cbind(train,groups,pred.y)
obs <- (ddply(gpdata,~groups,summarise,mean=mean(as.numeric(as.character(case))))[,2])
exp <- ddply(gpdata,~groups,summarise,mean=mean(pred.y))
obsn <- table(train$case,groups)[1,] 

cbind(exp,obs)# expected value vs. observed value
 
# CIs for scatter points
lci = pmax(0,(obs - (1.96*(((obs*(1-obs))/obsn)^.5))))
uci = pmin(1,(obs + (1.96*(((obs*(1-obs))/obsn)^.5))))

# graph a simple calibration plot over 10 risk groups
par(pty="s")
plot(obs~exp[,2],xlim=c(0,1),ylim=c(0,1),col="red",ylab="Observed",xlab="Expected")
lines(c(0,1),c(0,1),lty=2)

for(i in 1:10){
lines(c(exp[i,2],exp[i,2]),c(lci[i],uci[i]),col="green")
}

h <- hist(pred.y, breaks=50, plot=FALSE)
for(i in 1:length(h$mids)){
  lines(c(h$mids[i],h$mids[i]),c(rep(1,length(h$mids))[i],1-((h$counts[i]/max(h$counts))/10)))
}

# Add a loess smoother to the plot
obs_all <- predict(loess(as.numeric(as.character(train$case))~pred.y,span=1))
lines_data <- data.frame(pred.y,obs_all)
lines_data2 <- lines_data[order(pred.y),] 
lines(lines_data2[,1],lines_data2[,2],col="blue")
legend(0.0,0.9,c("Risk groups","Reference line","95% CI","Loess"),col=c("red","black","green","blue"),lty=c(0,2,1,1),pch=c(1,NA,NA,NA),bty="n")

```



### valid
```{r}
# probabilities of cases
pred.y <- predict(rf.model, valid, type = 'expected')

#  c statistic / AUC
roc_valid <- roc(valid$case ~ pred.y, smoothed = TRUE,
            ci=TRUE, ci.alpha=0.9, stratified=FALSE,
            plot=TRUE, auc.polygon=TRUE, max.auc.polygon=TRUE, grid=TRUE,
            print.auc=TRUE, show.thres=TRUE)
print(roc_valid) #AUC


# E/O
O <- prop.table(table(valid$case))[2]
E <- mean(pred.y)
E/O
```

## create decile group of risk probability
```{r}

vec=vector()

for (i in 1:10){
  vec[i]=quantile(prob,(i/10),na.rm=T)
}

vec# decile value

groups=prob
groups=ifelse(prob <=vec[1],1,groups)

for (i in 1:9) {
groups=ifelse(groups >vec[i] & groups <=vec[i+1],i,groups)  
}

groups=ifelse(prob > vec[10],10,decile)

table(groups)
prop.table(table(groups))*100 # % decile

```

```{r}
library(dplyr)
# calibration 
# average the observed and expected probabilities of patients in each risk group 
gpdata <- cbind(valid,groups,pred.y)
obs <- (ddply(gpdata,~groups,summarise,mean=mean(as.numeric(as.character(case))))[,2])
exp <- ddply(gpdata,~groups,summarise,mean=mean(pred.y))
obsn <- table(valid$case,groups)[1,] 

cbind(exp,obs)# expected value vs. observed value
 
# CIs for scatter points
lci = pmax(0,(obs - (1.96*(((obs*(1-obs))/obsn)^.5))))
uci = pmin(1,(obs + (1.96*(((obs*(1-obs))/obsn)^.5))))

# graph a simple calibration plot over 10 risk groups
par(pty="s")
plot(obs~exp[,2],xlim=c(0,1),ylim=c(0,1),col="red",ylab="Observed",xlab="Expected")
lines(c(0,1),c(0,1),lty=2)

for(i in 1:10){
lines(c(exp[i,2],exp[i,2]),c(lci[i],uci[i]),col="green")
}

h <- hist(pred.y, breaks=50, plot=FALSE)
for(i in 1:length(h$mids)){
  lines(c(h$mids[i],h$mids[i]),c(rep(1,length(h$mids))[i],1-((h$counts[i]/max(h$counts))/10)))
}

# Add a loess smoother to the plot
obs_all <- predict(loess(as.numeric(as.character(valid$case))~pred.y,span=1))
lines_data <- data.frame(pred.y,obs_all)
lines_data2 <- lines_data[order(pred.y),] 
lines(lines_data2[,1],lines_data2[,2],col="blue")
legend(0.0,0.9,c("Risk groups","Reference line","95% CI","Loess"),col=c("red","black","green","blue"),lty=c(0,2,1,1),pch=c(1,NA,NA,NA),bty="n")

```
