---
title: "subgroup analysis"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include=FALSE}
require('tidyverse')
require("gtsummary")
require("ggplot2")
library("survival")
library(car)
```


# <font color=blue>**Outcome 2**</font>
```{r include=FALSE}
# import data
rm(list=ls())
#df=read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_outcome.rds")
df <- read_rds(here::here("output","matched_outcome.rds"))

```

```{r}

# outcome
df$case=as.numeric(df$case) #1/0

df$subclass=as.factor(df$subclass)#pair id

# matched variables
df$ab_qn=as.character(df$ab_qn) #category
df$ab_types=as.integer(df$ab_types)

df$br_ab_qn=as.character(df$br_ab_qn)




```

```{r}
# dummy data
#df[1:15,5]<-1
 #df[16:29,5]<-0
#df[1:15,4]<-seq(1:15)
 #df[16:29,4]<-seq(1:14)
```


# abtypes

## continuous variable
```{r}

ggplot(df, aes(x=ab_types)) +
  geom_bar(aes(y = ..prop..))+
  facet_grid(ab_qn~case)

table(df$ab_qn,df$ab_types)
prop.table(table(df$ab_qn,df$ab_types),margin=1)*100
```

## categorical variable
```{r}
#df=df%>%mutate(abtype_3=ntile(ab_types,3))

df=df%>%mutate(abtype_3=case_when( ab_types==0 ~ "0",
               ab_types>0 & ab_types<=3 ~"1",
               ab_types>3 & ab_types<=6 ~"2",
               ab_types>6 & ab_types<=9 ~"3"))

summary(df[df$abtype_3=="1",]$ab_types)
summary(df[df$abtype_3=="2",]$ab_types)
summary(df[df$abtype_3=="3",]$ab_types)


table(df$ab_qn,df$abtype_3)
prop.table(table(df$ab_qn,df$abtype_3),margin=1)*100

ggplot(df, aes(x=abtype_3)) +
  geom_bar()+
  facet_grid(ab_qn~case)


```

# broad ab
```{r}

ggplot(df, aes(x=br_ab_qn)) +
  geom_bar()+
  facet_grid(ab_qn~case)
table(df$ab_qn,df$br_ab_qn)
prop.table(table(df$ab_qn,df$br_ab_qn),margin=1)*100
```



# model
## abtype_3

```{r}
#df$ab_qn_type=ifelse(ab_qn==0, 0
 #                    ifelse(ab_qn==1))

```

```{r}

#mod=clogit(case ~ ab_qn + ab_types + ab_qn*ab_types + CCI + covrx_ever + strata(subclass), df)
#summary(mod)
#vif(mod)
```

## br_ab
```{r}
#mod=clogit(case ~ ab_qn +br_ab_qn + ab_qn*br_ab_qn + CCI + covrx_ever + strata(subclass), df)
#summary(mod)
#vif(mod)
```


