---
title: "covidimd_model"
author: "Billy"
date: "26/01/2023"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/workspace')
```

```{r packages, include=FALSE}
require('tidyverse')
require("gtsummary")
require("ggplot2")
library("survival")
library(car)
library(data.table)
library(gridExtra)
```

```{r include=FALSE}
# import data
col_spec <-cols_only(patient_index_date = col_date(format = ""),
                        age = col_number(),
                        sex = col_character(),
                        region = col_character(),
                        imd = col_integer(),
                        set_id = col_number(),
                        sepsis_type = col_number(),
                        case = col_number(),
                        patient_id = col_number()
)

col_spec1 <-cols_only(patient_index_date = col_date(format = ""),
                        age = col_number(),
                        sex = col_character(),
                        region = col_character(),
                        imd = col_integer(),
                        set_id = col_number(),
                        case = col_number(),
                        patient_id = col_number()
)

df1.1<- read_csv(here::here("output", "matched_cases_191.csv"), col_types = col_spec)
df2.1<- read_csv(here::here("output", "matched_cases_192.csv"), col_types = col_spec)
df1.2<- read_csv(here::here("output", "matched_cases_201.csv"), col_types = col_spec)
df2.2<- read_csv(here::here("output", "matched_cases_202.csv"), col_types = col_spec)
df1.3<- read_csv(here::here("output", "matched_cases_211.csv"), col_types = col_spec)
df2.3<- read_csv(here::here("output", "matched_cases_212.csv"), col_types = col_spec)
df3.1<- read_csv(here::here("output", "matched_cases_221.csv"), col_types = col_spec)
case<-bind_rows(df1.1,df2.1,df1.2,df2.2,df1.3,df2.3,df3.1)

df1.1<- read_csv(here::here("output", "matched_matches_191.csv"), col_types = col_spec1)
df2.1<- read_csv(here::here("output", "matched_matches_192.csv"), col_types = col_spec1)
df1.2<- read_csv(here::here("output", "matched_matches_201.csv"), col_types = col_spec1)
df2.2<- read_csv(here::here("output", "matched_matches_202.csv"), col_types = col_spec1)
df1.3<- read_csv(here::here("output", "matched_matches_211.csv"), col_types = col_spec1)
df2.3<- read_csv(here::here("output", "matched_matches_212.csv"), col_types = col_spec1)
df3.1<- read_csv(here::here("output", "matched_matches_221.csv"), col_types = col_spec1)

control<-bind_rows(df1.1,df2.1,df1.2,df2.2,df1.3,df2.3,df3.1)
control <- control[,-6]
case_date <-select(case,set_id,patient_index_date,sepsis_type)
control <- merge(control,case_date,by = "set_id")
df <- bind_rows(case,control)

control_var <- readRDS("output/processed/input_control_data.rds")
case_var <- readRDS("output/processed/input_case_data.rds")
control_var <-control_var[,-(3:7)]
case_var <-case_var[,-(3:7)]

case <-merge(case,case_var,by=c("patient_id","patient_index_date"))
control <-merge(control,control_var,by=c("patient_id","patient_index_date"))
df <- bind_rows(case,control)
```

```{r include=FALSE}
# outcome
df$case=as.numeric(df$case) #1/0
df$set_id=as.factor(df$set_id)#pair id
df$imd= relevel(as.factor(df$imd), ref="5")
df$smoking_status= relevel(as.factor(df$smoking_status), ref="Never")
df <- df %>% mutate(covid = case_when(patient_index_date < as.Date("2020-03-26") ~ "1",
                                      patient_index_date >=as.Date("2020-03-26")&patient_index_date < as.Date("2021-03-08") ~ "2",
                                      patient_index_date >= as.Date("2021-03-08") ~ "3"))
df$covid=relevel(as.factor(df$covid), ref="1")

```


```{r include=FALSE}
mod=clogit(case ~ region + ethnicity + bmi + smoking_status + hypertension + chronic_respiratory_disease +
             asthma + chronic_cardiac_disease + diabetes_controlled + cancer + haem_cancer + chronic_liver_disease +
             stroke + dementia + other_neuro + organ_kidney_transplant + asplenia + ra_sle_psoriasis + immunosuppression +
             learning_disability + sev_mental_ill + alcohol_problems + care_home_type + ckd_rrt + strata(set_id), df)
sum.mod=summary(mod)
sum.mod
```

```{r echo=TRUE}
result=data.frame(sum.mod$conf.int)
DF=result[,-2]
names(DF)[1]="OR"
names(DF)[2]="CI_L"
names(DF)[3]="CI_U"
setDT(DF, keep.rownames = TRUE)[]
names(DF)[1]="type"
Region <- DF[1:8,]
Ethnicity <- DF[9:13,]
BMI <- DF[14:16,]
Smoking <- DF[17:19,]
CKD <- DF[45:50,]
CHT <- DF[42:44,]
Other1 <- DF[20:27,]
Other2 <- DF[28:41,]

```

```{r echo=TRUE}
p <- ggplot(data=Region, aes(y= type,x=OR))+ 
#xlim(c(0,2.2))+
scale_x_continuous(limits = c(0.6,2.2),breaks = c(1.0,1.5,2.0))+
geom_point(color="black")+ 
#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+
#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+
#thematic stuff
theme_classic()+ 
theme(text=element_text(size=14, color="black"),
      plot.title=element_text(size=12, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  
labs(
    title = "",
    x="",
    y=""
  )
p
```

```{r echo=TRUE}
p <- ggplot(data=Ethnicity, aes(y= type,x=OR))+ 
#xlim(c(0,2.2))+
scale_x_continuous(limits = c(0.6,2.2),breaks = c(1.0,1.5,2.0))+
geom_point(color="black")+ 
#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+
#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+
#thematic stuff
theme_classic()+ 
theme(text=element_text(size=14, color="black"),
      plot.title=element_text(size=12, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  
labs(
    title = "",
    x="",
    y=""
  )
p
```

```{r echo=TRUE}
p <- ggplot(data=BMI, aes(y= type,x=OR))+ 
#xlim(c(0,2.2))+
scale_x_continuous(limits = c(0.6,2.2),breaks = c(1.0,1.5,2.0))+
geom_point(color="black")+ 
#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+
#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+
#thematic stuff
theme_classic()+ 
theme(text=element_text(size=14, color="black"),
      plot.title=element_text(size=12, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  
labs(
    title = "",
    x="",
    y=""
  )
p
```

```{r echo=TRUE}
p <- ggplot(data=Smoking, aes(y= type,x=OR))+ 
#xlim(c(0,2.2))+
scale_x_continuous(limits = c(0.6,2.2),breaks = c(1.0,1.5,2.0))+
geom_point(color="black")+ 
#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+
#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+
#thematic stuff
theme_classic()+ 
theme(text=element_text(size=14, color="black"),
      plot.title=element_text(size=12, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  
labs(
    title = "",
    x="",
    y=""
  )
p
```

```{r echo=TRUE}
p <- ggplot(data=CKD, aes(y= type,x=OR))+ 
#xlim(c(0,2.2))+
scale_x_continuous(limits = c(0.6,2.2),breaks = c(1.0,1.5,2.0))+
geom_point(color="black")+ 
#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+
#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+
#thematic stuff
theme_classic()+ 
theme(text=element_text(size=14, color="black"),
      plot.title=element_text(size=12, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  
labs(
    title = "",
    x="",
    y=""
  )
p
```

```{r echo=TRUE}
p <- ggplot(data=CHT, aes(y= type,x=OR))+ 
#xlim(c(0,2.2))+
scale_x_continuous(limits = c(0.6,2.2),breaks = c(1.0,1.5,2.0))+
geom_point(color="black")+ 
#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+
#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+
#thematic stuff
theme_classic()+ 
theme(text=element_text(size=14, color="black"),
      plot.title=element_text(size=12, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  
labs(
    title = "",
    x="",
    y=""
  )
p
```

```{r echo=TRUE}
p <- ggplot(data=Other1, aes(y= type,x=OR))+ 
#xlim(c(0,2.2))+
scale_x_continuous(limits = c(0.6,2.2),breaks = c(1.0,1.5,2.0))+
geom_point(color="black")+ 
#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+
#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+
#thematic stuff
theme_classic()+ 
theme(text=element_text(size=14, color="black"),
      plot.title=element_text(size=12, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  
labs(
    title = "",
    x="",
    y=""
  )
p
```


```{r echo=TRUE}
p <- ggplot(data=Other2, aes(y= type,x=OR))+ 
#xlim(c(0,2.2))+
scale_x_continuous(limits = c(0.6,2.2),breaks = c(1.0,1.5,2.0))+
geom_point(color="black")+ 
#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+
#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+
#thematic stuff
theme_classic()+ 
theme(text=element_text(size=14, color="black"),
      plot.title=element_text(size=12, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  
labs(
    title = "",
    x="",
    y=""
  )
p
```

