---
title: "Random Forest"
---

```{r setup, include=FALSE}
library("caret")
library("survival")
library('tidyverse')
library(pROC) #plyr
library(randomForest) #dplyr
```

# import dataset
```{r }
df<- read.csv(here::here("output","hospitalisation_prediction_lrti","prob_pred_lr_rf_lrti_incdt_deciles_r_analysis.csv"))
df$ab_binary=as.factor(df$ab_binary)

names(df)

```


# split data
```{r}

df$idx=seq(nrow(df))
idx=df$idx

set.seed(1024)
train_idx <- sample(idx,  length(idx)* 0.8)
length(train_idx)

valid_idx <- idx[!idx %in% train_idx]
length(valid_idx)

train =df %>% filter(idx %in% train_idx)
nrow(train)

valid =df %>% filter(idx %in% valid_idx)
nrow(valid)

```

# logistic model
## train
```{r }
model <- glm(ab_binary ~bins , data = train, family = binomial,x=TRUE, y=TRUE)

print(model)
```

### ROC
```{r}
data=train
# Obtain the predicted probabilities for each patient
data$prob <- predict(model,type="response")

#  c statistic / AUC
roc_data <- roc(data$ab_binary ~data$prob, smoothed = TRUE,
            ci=TRUE, ci.alpha=0.9, stratified=FALSE,
            plot=TRUE, auc.polygon=TRUE, max.auc.polygon=TRUE, grid=TRUE,
            print.auc=TRUE, show.thres=TRUE)
print(roc_data) #AUC


# E/O
O <- prop.table(table(data$ab_binary))[2]
E <- mean(data$prob)
E/O
```

### calibration 
```{r}
prob=data$prob
vec=vector()

for (i in 1:10){
  vec[i]=quantile(prob,(i/10),na.rm=T)
}

vec# decile value

decile=vector()
decile=ifelse(prob <=vec[1],1,decile)

for (i in 1:9) {
decile=ifelse(prob>vec[i] & prob <=vec[i+1],i+1,decile )  
}


table(decile)
prop.table(table(decile))*100 
data=cbind(data,decile)
```

```{r}

gpdata=data%>%select(decile, ab_binary, prob)

table(gpdata$decile)
summary(gpdata[gpdata$decile==1,])
head(gpdata)

obs=gpdata%>%group_by(decile)%>%dplyr::summarise(mean.obs=mean(as.numeric(as.character(ab_binary))))
obs=obs%>% pull(mean.obs)

#obs <- (ddply(gpdata,~groups,summarise,mean=mean(as.numeric(as.character(ab_binary))))[,2])
exp=gpdata%>% group_by(decile)%>% dplyr::summarise(mean.exp=mean(as.numeric(prob)))
exp=exp%>%pull(mean.exp)

#exp <- ddply(gpdata,~groups,summarise,mean=mean(pred.y))
obsn <- table(data$ab_binary,data$decile)[1,] 

cbind(exp,obs)# expected value vs. observed value
 
# CIs for scatter points
lci = pmax(0,(obs - (1.96*(((obs*(1-obs))/obsn)^.5))))
uci = pmin(1,(obs+ (1.96*(((obs*(1-obs))/obsn)^.5))))

# graph a simple calibration plot over 10 risk groups
par(pty="s")
plot(obs~exp,xlim=c(0,1),ylim=c(0,1),col="red",ylab="Observed",xlab="Expected")
lines(c(0,1),c(0,1),lty=2)

for(i in 1:10){
lines(c(exp[i],exp[i]),c(lci[i],uci[i]),col="green")
}

h <- hist(data$prob, breaks=50, plot=FALSE)
for(i in 1:length(h$mids)){
  lines(c(h$mids[i],h$mids[i]),c(rep(1,length(h$mids))[i],1-((h$counts[i]/max(h$counts))/10)))
}

# Add a loess smoother to the plot
obs_all <- predict(loess(as.numeric(as.character(data$ab_binary))~data$prob,span=1))
lines_data <- data.frame(data$prob,obs_all)
lines_data2 <- lines_data[order(data$prob),] 
lines(lines_data2[,1],lines_data2[,2],col="blue")
legend(0.0,0.9,c("Risk groups","Reference line","95% CI","Loess"),col=c("red","black","green","blue"),lty=c(0,2,1,1),pch=c(1,NA,NA,NA),bty="n")

```


## valid
# logistic model
```{r }
model <- glm(ab_binary ~bins , data = valid, family = binomial)

print(model)
```

### ROC
```{r}
data=valid
# Obtain the predicted probabilities for each patient
data$prob <- predict(model,type="response")

#  c statistic / AUC
roc_data <- roc(data$ab_binary ~data$prob, smoothed = TRUE,
            ci=TRUE, ci.alpha=0.9, stratified=FALSE,
            plot=TRUE, auc.polygon=TRUE, max.auc.polygon=TRUE, grid=TRUE,
            print.auc=TRUE, show.thres=TRUE)
print(roc_data) #AUC


# E/O
O <- prop.table(table(data$ab_binary))[2]
E <- mean(data$prob)
E/O
```

### calibration 
```{r}
prob=data$prob
vec=vector()

for (i in 1:10){
  vec[i]=quantile(prob,(i/10),na.rm=T)
}

vec# decile value

decile=vector()
decile=ifelse(prob <=vec[1],1,decile)

for (i in 1:9) {
decile=ifelse(prob>vec[i] & prob <=vec[i+1],i+1,decile )  
}


table(decile)
prop.table(table(decile))*100 
data=cbind(data,decile)
```

```{r}

gpdata=data%>%select(decile, ab_binary, prob)

table(gpdata$decile)
summary(gpdata[gpdata$decile==1,])
head(gpdata)

obs=gpdata%>%group_by(decile)%>%dplyr::summarise(mean.obs=mean(as.numeric(as.character(ab_binary))))
obs=obs%>% pull(mean.obs)

#obs <- (ddply(gpdata,~groups,summarise,mean=mean(as.numeric(as.character(ab_binary))))[,2])
exp=gpdata%>% group_by(decile)%>% dplyr::summarise(mean.exp=mean(as.numeric(prob)))
exp=exp%>%pull(mean.exp)

#exp <- ddply(gpdata,~groups,summarise,mean=mean(pred.y))
obsn <- table(data$ab_binary,data$decile)[1,] 

cbind(exp,obs)# expected value vs. observed value
 
# CIs for scatter points
lci = pmax(0,(obs - (1.96*(((obs*(1-obs))/obsn)^.5))))
uci = pmin(1,(obs+ (1.96*(((obs*(1-obs))/obsn)^.5))))

# graph a simple calibration plot over 10 risk groups
par(pty="s")
plot(obs~exp,xlim=c(0,1),ylim=c(0,1),col="red",ylab="Observed",xlab="Expected")
lines(c(0,1),c(0,1),lty=2)

for(i in 1:10){
lines(c(exp[i],exp[i]),c(lci[i],uci[i]),col="green")
}

h <- hist(data$prob, breaks=50, plot=FALSE)
for(i in 1:length(h$mids)){
  lines(c(h$mids[i],h$mids[i]),c(rep(1,length(h$mids))[i],1-((h$counts[i]/max(h$counts))/10)))
}

# Add a loess smoother to the plot
obs_all <- predict(loess(as.numeric(as.character(data$ab_binary))~data$prob,span=1))
lines_data <- data.frame(data$prob,obs_all)
lines_data2 <- lines_data[order(data$prob),] 
lines(lines_data2[,1],lines_data2[,2],col="blue")
legend(0.0,0.9,c("Risk groups","Reference line","95% CI","Loess"),col=c("red","black","green","blue"),lty=c(0,2,1,1),pch=c(1,NA,NA,NA),bty="n")

```