---
title: "model2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include=FALSE}
require('tidyverse')
require("gtsummary")
require("ggplot2")
library("survival")
library(car)
```


# <font color=blue>**Outcome 3**</font>
```{r include=FALSE}
# import data
rm(list=ls())
#df=read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_outcome.rds")
df <- read_rds(here::here("output","matched_outcome.rds"))

```

```{r}

# outcome
df$case=as.numeric(df$case) #1/0

df$subclass=as.factor(df$subclass)#pair id

# replace ab prescription with total ab
df$ab_qn=as.character(df$total_ab_qn) #category
df$ab_qn_5=as.character(df$total_ab_qn_5) #category

df$ab_prescriptions=as.numeric(df$total_ab)

df$CCI= relevel(as.factor(df$CCI), ref="Very low")
df$covrx_ever= relevel(as.factor(df$covrx_ever), ref="0")


df$cancer=as.factor(df$cancer)
df$cvd=as.factor(df$cvd)
df$copd=as.factor(df$copd)
df$heart_failure=as.factor(df$heart_failure)
df$connective_tissue=as.factor(df$connective_tissue)
df$dementia=as.factor(df$dementia)
df$diabetes=as.factor(df$diabetes)
df$diabetes_complications=as.factor(df$diabetes_complications)
df$hemiplegia=as.factor(df$hemiplegia)
df$hiv=as.factor(df$hiv)
df$metastatic_cancer=as.factor(df$metastatic_cancer)
df$mild_liver=as.factor(df$mild_liver)
df$mod_severe_liver=as.factor(df$mod_severe_liver)
df$mod_severe_renal=as.factor(df$mod_severe_renal)
df$mi=as.factor(df$mi)
df$peptic_ulcer=as.factor(df$peptic_ulcer)
df$peripheral_vascular=as.factor(df$peripheral_vascular)
```

```{r}
# dummy data
 #df[1:15,5]<-1
 #df[16:29,5]<-0
#df[1:15,4]<-seq(1:15)
# df[16:29,4]<-seq(1:14)
```


# models_CCI
```{r}
 
mod=clogit(case ~ ab_qn + CCI + covrx_ever + strata(subclass), df)
summary(mod)
vif(mod)


mod=clogit(case ~ ab_qn_5 + CCI + covrx_ever + strata(subclass), df)
summary(mod)
vif(mod)
```


# models_individual comorbidity
```{r}
 
mod=clogit(case ~ ab_qn_5  + covrx_ever + cancer + cvd + copd + heart_failure + connective_tissue + dementia + diabetes + diabetes_complications + hemiplegia + hiv + metastatic_cancer + mild_liver + mod_severe_liver + mod_severe_renal + mi + peptic_ulcer + peripheral_vascular + strata(subclass), df)
summary(mod)
vif(mod)

```

