---
title: "univariable analysis"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r packages, include=FALSE}
require('tidyverse')
require("gtsummary")
require("ggplot2")
library("survival")
library(car)
library(data.table)
library(gridExtra)
library(finalfit)

```

```{r}
df <- read_rds(here::here("output","matched_outcome.rds"))


## define variables
df$case=as.numeric(df$case) #1/0

df$subclass=as.factor(df$subclass)#pair id

df$level=as.character(df$level) #category

df$CCI= relevel(as.factor(df$CCI), ref="Zero")
df$covrx_ever= relevel(as.factor(df$covrx_ever), ref="0")

df$bmi_cat=relevel(as.factor(df$bmi_cat),ref="Healthy weight")
df$care_home=relevel(as.factor(df$care_home),ref = "0")

df$flu_vaccine=relevel(as.factor(df$flu_vaccine),ref= "0")

df$smoking_cat_3=relevel(as.factor(df$smoking_cat_3),ref="Never")
df$imd=relevel(as.factor(df$imd),ref="1")
df$ethnicity_6=relevel(as.factor(df$ethnicity_6),ref = "White")
```


```{r}
#### crude model

df%>%
  summary_factorlist("case", c("CCI"), fit_id = TRUE) %>% 
  ff_merge(
    survival::clogit(case ~ level + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass),df) %>% 
      fit2df(estimate_name = "OR (95% CI; case-control)"),
    last_merge = TRUE
  )%>% select(-c("unit","value"))


```


```{r}

#### crude model

df%>%
  summary_factorlist("case", c("covrx_ever"), fit_id = TRUE) %>% 
  ff_merge(
    survival::clogit(case ~ level + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass),df) %>% 
      fit2df(estimate_name = "OR (95% CI; case-control)"),
    last_merge = TRUE
  )%>% select(-c("unit","value"))

```


