---
title: "model 5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include=FALSE}
require('tidyverse')
require("gtsummary")
require("ggplot2")
library("survival")
library(car)
library(data.table)
```


```{r include=FALSE}
# import data
rm(list=ls())
#df=read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_outcome.rds")
df <- read_rds(here::here("output","matched_outcome.rds"))

```

```{r}

# outcome
df$case=as.numeric(df$case) #1/0

df$subclass=as.factor(df$subclass)#pair id

# replace ab prescription with total ab
#df$ab_qn=as.character(df$total_ab_qn) #category
df$total_ab_qn_5=as.factor(df$total_ab_qn_5) #category
df$total_ab=as.numeric(df$total_ab)
df$br_total_ab_qn_5=as.factor(df$br_total_ab_qn_5)
df$broad_ab_prescriptions=as.numeric(df$broad_ab_prescriptions)

df$CCI= relevel(as.factor(df$CCI), ref="Very low")
df$covrx_ever= relevel(as.factor(df$covrx_ever), ref="0")

df$bmi_cat=relevel(as.factor(df$bmi_cat),ref="Healthy weight")
df$care_home=relevel(as.factor(df$care_home),ref = "0")

df$flu_vaccine=relevel(as.factor(df$flu_vaccine),ref= "0")

df$smoking_cat_3=relevel(as.factor(df$smoking_cat_3),ref="Never")
df$imd=relevel(as.factor(df$imd),ref="1")
df$ethnicity_6=relevel(as.factor(df$ethnicity_6),ref = "White")




```

```{r}
# dummy data
#df[1:15,5]<-1
 #df[16:29,5]<-0
#df[1:15,4]<-seq(1:15)
# df[16:29,4]<-seq(1:14)
```

```{r}

df$br_total_ab_qn_5=factor(df$br_total_ab_qn_5,levels=c("br_total_ab_qn_5without any ab","br_total_ab_qn_5without broad ab","br_total_ab_qn_51","br_total_ab_qn_52","br_total_ab_qn_53","br_total_ab_qn_54","br_total_ab_qn_55"))
summary(df[df$br_total_ab_qn_5=="without any ab",]$broad_ab_prescriptions)
summary(df[df$br_total_ab_qn_5=="without broad ab",]$broad_ab_prescriptions)
summary(df[df$br_total_ab_qn_5=="1",]$broad_ab_prescriptions)
summary(df[df$br_total_ab_qn_5=="2",]$broad_ab_prescriptions)
summary(df[df$br_total_ab_qn_5=="3",]$broad_ab_prescriptions)
summary(df[df$br_total_ab_qn_5=="4",]$broad_ab_prescriptions)
summary(df[df$br_total_ab_qn_5=="5",]$broad_ab_prescriptions)


```


# models


```{r}
 
mod=clogit(case ~ br_total_ab_qn_5 + CCI + covrx_ever + strata(subclass), df)
           #+ bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 
sum.mod=summary(mod)
sum.mod
vif(mod)

```


```{r}
result=data.frame(sum.mod$conf.int)

result

result=result[1:6,-2]
```


```{r}
DF=result

setDT(DF, keep.rownames = TRUE)[]
names(DF)[1]="broad_AB_exposure"



names(DF)[2]="OR"
names(DF)[3]="CI_L"
names(DF)[4]="CI_U"

DF
```


```{r}
p <- ggplot(data=DF, aes(y=broad_AB_exposure, x=OR))+ 

#this adds the effect sizes to the plot
geom_point(color="blue")+ 

#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U))+
  

#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black", linetype="dashed")+
  
#thematic stuff
theme_classic()+ 
  xlim(0, 5)+
theme(text=element_text(family="Times",size=18, color="black"))+
theme(panel.spacing = unit(1, "lines"))+

labs(
      title = "",
    x="OR (95% CI)",
    y=""
  )
p
```

