---
title: "Random Forest model_ decile groups of probabilities"
---

```{r setup, include=FALSE}
library(dplyr)
library('tidyverse')
library(pROC)
library(randomForest)

```

# import dataset
```{r }
# original dataset
#DF <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_outcome.rds")
DF<- read_rds(here::here("output","matched_outcome.rds"))
col1=c("wave","patient_index_date","patient_id","subclass","case","sex","age","age_cat","stp","region","ethnicity_6","bmi","bmi_cat","CCI","Charlson","smoking_cat_3","imd","care_home","covrx_ever","flu_vaccine","cancer_comor","cerebrovascular_disease_comor", "chronic_obstructive_pulmonary_comor", "heart_failure_comor", "connective_tissue_comor", "dementia_comor", "diabetes_comor", "diabetes_complications_comor", "hemiplegia_comor", "hiv_comor", "metastatic_cancer_comor", "mild_liver_comor", "mod_severe_liver_comor", "mod_severe_renal_comor", "mi_comor", "peptic_ulcer_comor", "peripheral_vascular_comor",
"care_home_type","hospital_counts")
DF=subset(DF,select=col1)

nrow(DF)
table(DF$case)

#df <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_ab.rds")
#df <- read_rds(here::here("output","matched_ab.rds"))
#table(df$case)
#col2=c("patient_index_date","patient_id","AB_6wk_type","ab_6w_binary" , "AB_6wk")
#df=subset(df,select=col2)
#df=df%>% distinct(patient_id,patient_index_date, .keep_all=T)
#nrow(df)

#DF=merge(DF,df,by=c("patient_id","patient_index_date"), all.x = T)
#table(DF$case)
#nrow(DF)
```


```{r }




#train_X <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/train_X.rds")
train_X <- read_rds(here::here("output","train_X.rds"))
train_X$case=as.factor(train_X$case)


#valid_X <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/valid_X.rds")
valid_X <- read_rds(here::here("output","valid_X.rds"))
valid_X$case=as.factor(valid_X$case)

table(train_X$case)
table(valid_X$case)


abtype <- read_rds(here::here("output","abtype.rds"))
col=c("patient_id","patient_index_date","total_ab","ab_types","prescribe_times","exposure_period","recent_ab_days", "broad_prop","interval_med" ,"interval_mean","interval_sd","interval_CV",
           "length_mean","length_med", "length_sd", "length_CV" , "AB_6wk",abtype)

train_X=train_X%>% select(all_of(col))
valid_X=valid_X%>% select(all_of(col))

table(train_X$case)
table(valid_X$case)


rf.model=readRDS(here::here("output","model_RandomForest.rds"))
print(rf.model)
```



development set
```{r}
# probabilities of being case
prob <- predict(rf.model, train_X, type = 'prob')[,2]
summary(prob)
hist(prob)

sum(prob==0)
length(prob)

exp.class <- predict(rf.model, train_X, type = 'response')
summary(exp.class)
# create 10 risk groups

prob=ifelse(prob==0,NA,prob)


decile <- ntile(prob,10)
summary(decile)

prob=ifelse(is.na(prob),0,prob)
decile=ifelse(is.na(decile),0,decile)


# combined
#train_X=train_X[,c("patient_id","patient_index_date")]
devel <- cbind(train_X,decile,prob,exp.class)


for (i in 1:10) {
  
  print(paste0("decile=",i))
  print(summary(devel[decile==i,]$prob))

}


head(devel)

devel$set=0

head(prob)

```

development set
```{r eval=FALSE, include=FALSE}
# probabilities of being case
prob <- predict(rf.model, type = 'prob')[,2]
summary(prob)
hist(prob)

sum(prob==0)
length(prob)

exp.class <- predict(rf.model, type = 'response')
summary(exp.class)

# create 10 risk groups
decile <- ntile(prob,10)
table(decile)




# combined
#train_X=train_X[,c("patient_id","patient_index_date")]
devel <- cbind(train_X,decile,prob,exp.class)

head(devel)

devel$set=0

head(prob)

```


validation set
```{r}
rm(prob)
# probabilities of being case
prob <- predict(rf.model, valid_X, type = 'prob')[,2]
summary(prob)
hist(prob)

sum(prob==0)
length(prob)

exp.class <- predict(rf.model, valid_X, type = 'response')
summary(exp.class)

prob=ifelse(prob==0,NA,prob)


decile <- ntile(prob,10)
summary(decile)

prob=ifelse(is.na(prob),0,prob)
decile=ifelse(is.na(decile),0,decile)


#valid_X=valid_X[,c("patient_id","patient_index_date")]

# combined
valid<- cbind(valid_X,decile,prob,exp.class)

for (i in 1:10) {
  
  print(paste0("decile=",i))
  print(summary(valid[decile==i,]$prob))

}

head(valid)

valid$set=1
```

```{r}
nrow(devel)
nrow(valid)

data=rbind(devel,valid)
nrow(data)
```


```{r}

nrow(data)
nrow(DF)

DF=merge(DF,data,by=c("patient_id","patient_index_date"), all.x = T)
table(DF$case)
nrow(DF)

names(DF)
```



```{r}

development=DF%>%filter(set==0)
saveRDS(development,here::here("output","development.rds"))
validation=DF%>%filter(set==1)
saveRDS(validation,here::here("output","validation.rds"))

table(development$case)
nrow(development)
table(validation$case)
nrow(validation)
```
