---
title: "Model_antibiotic types"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE)
```


```{r packages}
library('tidyverse')
library("gtsummary")
library("ggplot2")
library("survival")
library(car)
library(data.table)
library(gridExtra)

```


```{r }
# import data
rm(list=ls())
#df=read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_outcome.rds")
df <- read_rds(here::here("output","all_ranger.rds"))

```

```{r }
# outcome
df$case=as.numeric(df$case) #1/0

df$subclass=as.factor(df$subclass)#pair id

df$total_ab_group= relevel(as.factor(df$total_ab_group), ref="1")
df$recent_ab_days_group= relevel(as.factor(df$recent_ab_days_group), ref="1")
df$ab_types_group= relevel(as.factor(df$ab_types_group), ref="1")
df$exposure_period_group= relevel(as.factor(df$exposure_period_group), ref="1")
df$broad_ab_prescriptions_group= relevel(as.factor(df$broad_ab_prescriptions_group), ref="1")
df$interval_mean_group= relevel(as.factor(df$interval_mean_group), ref="1")
df$interval_sd_group= relevel(as.factor(df$interval_sd_group), ref="1")

df$CCI= relevel(as.factor(df$CCI), ref="Zero")
df$covrx_ever= relevel(as.factor(df$covrx_ever), ref="0")

df$bmi_cat=relevel(as.factor(df$bmi_cat),ref="Healthy weight")
df$care_home=relevel(as.factor(df$care_home),ref = "0")

df$flu_vaccine=relevel(as.factor(df$flu_vaccine),ref= "0")

df$smoking_cat_3=relevel(as.factor(df$smoking_cat_3),ref="Never")
df$imd=relevel(as.factor(df$imd),ref="1")
df$ethnicity_6=relevel(as.factor(df$ethnicity_6),ref = "White")

contd<- c("exposure_period","recent_ab_days","interval_mean","interval_sd","ab_types","broad_ab_prescriptions")
explanatory<- c("exposure_period_group","interval_mean_group","interval_sd_group","recent_ab_days_group","ab_types_group","broad_ab_prescriptions_group")

```

## create quartiles by total_ab_group
```{r }
i=1
Q1=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.25)
Q2=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.5)
Q3=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.75)

Q1#total ab_1; total_ab 2; total ab 3; total ab 4
Q2
Q3
```


```{r }

df[explanatory[i]]=""

# total ab level 1

df1=df%>%filter(total_ab_group==1)
df1[explanatory[i]]=ifelse(df1[contd[i]]<= Q1[1], 1,ifelse(
  df1[contd[i]] > Q1[1] &  df1[contd[i]] <= Q2[1], 2,ifelse(
    df1[contd[i]] > Q2[1] & df1[contd[i]] <= Q3[1], 3, ifelse(
      df1[contd[i]] > Q3[1],4, NA)
    )
  )
)

# total ab level 2
df2=df%>%filter(total_ab_group==2)
df2[explanatory[i]]=ifelse(df2[contd[i]]<= Q1[2], 1,ifelse(
  df2[contd[i]] > Q1[2] &  df2[contd[i]] <= Q2[2], 2,ifelse(
    df2[contd[i]] > Q2[2] & df2[contd[i]] <= Q3[2], 3, ifelse(
      df2[contd[i]] > Q3[2],4, NA)
    )
  )
)
 

# total ab level3
df3=df%>%filter(total_ab_group==3)
df3[explanatory[i]]=ifelse(df3[contd[i]]<= Q1[3], 1,ifelse(
  df3[contd[i]] > Q1[3] &  df3[contd[i]] <= Q2[3], 2,ifelse(
    df3[contd[i]] > Q2[3] & df3[contd[i]] <= Q3[3], 3, ifelse(
      df3[contd[i]] > Q3[3],4, NA)
    )
  )
)
 


# total ab level4
df4=df%>%filter(total_ab_group==4)
df4[explanatory[i]]=ifelse(df4[contd[i]]<= Q1[4], 1,ifelse(
  df4[contd[i]] > Q1[4] &  df4[contd[i]] <= Q2[4], 2,ifelse(
    df4[contd[i]] > Q2[4] & df4[contd[i]] <= Q3[4], 3, ifelse(
      df4[contd[i]] > Q3[4],4, NA)
    )
  )
)
 

df=rbind(df1,df2,df3,df4)

```


# Exposure period

```{r }
df=df%>%mutate(ab_Level_type= 
                 case_when(
                           total_ab_group=="1" & exposure_period_group==1 ~ 1,
                           total_ab_group=="1" & exposure_period_group==2 ~ 2,
                           total_ab_group=="1" & exposure_period_group==3 ~ 3,
                           total_ab_group=="1" & exposure_period_group==4 ~ 4,
                           total_ab_group=="2" & exposure_period_group==1 ~ 5,
                           total_ab_group=="2" & exposure_period_group==2 ~ 6,
                           total_ab_group=="2" & exposure_period_group==3 ~ 7,
                           total_ab_group=="2" & exposure_period_group==4 ~ 8,
                           total_ab_group=="3" & exposure_period_group==1 ~ 9,
                           total_ab_group=="3" & exposure_period_group==2 ~ 10,
                           total_ab_group=="3" & exposure_period_group==3 ~ 11,
                           total_ab_group=="3" & exposure_period_group==4 ~ 12,
                           total_ab_group=="4" & exposure_period_group==1 ~ 13,
                           total_ab_group=="4" & exposure_period_group==2 ~ 14,
                           total_ab_group=="4" & exposure_period_group==3 ~ 15,
                           total_ab_group=="4" & exposure_period_group==4 ~ 16


                          ))

table(df$ab_Level_type)
```

```{r }
# median of each group
Q2=tapply(df[,"exposure_period"],df[,"ab_Level_type"],quantile,p=0.5 )
Q2

```



```{r }
## model summary
df$ab_Level_type= relevel(as.factor(df$ab_Level_type), ref="1")
mod=clogit(case ~ ab_Level_type + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass), df)
sum.mod=summary(mod)
#sum.mod
#vif(mod)

```


```{r }
result=data.frame(sum.mod$conf.int)
DF=result[1:15,-2]
```


```{r }

setDT(DF, keep.rownames = TRUE)[]
names(DF)[1]="AB_exposure"
DF$AB_exposure=factor(DF$AB_exposure,levels=c("ab_Level_type2","ab_Level_type3","ab_Level_type4","ab_Level_type5","ab_Level_type6","ab_Level_type7","ab_Level_type8","ab_Level_type9","ab_Level_type10","ab_Level_type11","ab_Level_type12","ab_Level_type13","ab_Level_type14","ab_Level_type15","ab_Level_type16"))

DF=DF%>%arrange(AB_exposure)
DF
DF[1,1]="1"
DF[2,1]="2"
DF[3,1]="3"
DF[4,1]="4"
DF[5,1]="5"
DF[6,1]="6"
DF[7,1]="7"
DF[8,1]="8"
DF[9,1]="9"
DF[10,1]="10"
DF[11,1]="11"
DF[12,1]="12"
DF[13,1]="13"
DF[14,1]="14"
DF[15,1]="15"
#DF[16,1]="16"


 Index = rep(1:15) ## This provides an order to the data
  label = as.factor(rep(1:15))


names(DF)[2]="OR"
names(DF)[3]="CI_L"
names(DF)[4]="CI_U"

DF$CI_L=round(DF$CI_L,digits = 2)
DF$CI_U=round(DF$CI_U, digits = 2)

DF$CI=paste0(DF$CI_L,",",DF$CI_U)

```



```{r }
p <- ggplot(data=DF, aes(y=AB_exposure, x=OR))+ 
xlim(c(0,2.5))+
#scale_x_continuous(limits = c(0.6,2.2),breaks = c(1.0,1.5,2.0))+
#scale_y_discrete(labels=c("level1, type1"="n= 1 ","level2, type1"="n= 1 ", "level2, type2"="n= 2 ","level3, type1"="n= 1 ","level3, type2"="n= 2 ","level3, type3"="n>= 3 ","level4, type1"="n= 1 ","level4, type2"="n= 2 ","level4, type3"="n>= 3 ","level5, type1"="n= 1 ","level5, type2"="n= 2 ","level5, type3"="n>= 3 ")) +

#this adds the effect sizes to the plot
geom_point(color="black")+
#thematic stuff
theme_classic()+ 

annotate(geom = "rect", xmin = -Inf,xmax = Inf,ymin = 0, ymax = 3.5,fill="grey80", alpha=0.5)+
annotate(geom = "rect", xmin = -Inf,xmax = Inf,ymin = 7.5, ymax = 11.5,fill="grey80", alpha=0.5)+

  annotate("text", x = 0.1, y =2, label = "Very Low",size=3)+
  annotate("text", x = 0.1, y =5.5, label = "Low",size=3)+
  annotate("text", x = 0.1, y =9.5, label = "High",size=3)+
  annotate("text", x = 0.1, y =13.5, label = "Very High",size=3)+

   geom_text( size=3,aes(y = 1:15, x = 0.7,
               label = c("1"=paste0("Level2 (",Q2[2],")"),
                        "2"= paste0("Level3 (",Q2[3],")"),
                        "3"= paste0("Level4 (",Q2[4],")"),
                        "4"= paste0("Level1 (",Q2[5],")"),
                        "5"= paste0("Level2 (",Q2[6],")"),
                        "6"= paste0("Level3 (",Q2[7],")"),
                        "7"= paste0("Level4 (",Q2[8],")"),
                        "8"= paste0("Level1 (",Q2[9],")"),
                        "9"= paste0("Level2 (",Q2[10],")"),
                        "10"= paste0("Level3 (",Q2[11],")"),
                        "11"= paste0("Level4 (",Q2[12],")"),
                        "12"= paste0("Level1 (",Q2[13],")"),
                        "13"= paste0("Level2 (",Q2[14],")"),
                        "14"= paste0("Level3 (",Q2[15],")"),
                        "15"= paste0("Level4 (",Q2[16],")"))),
           hjust = "right",
           nudge_y = -.1)+


#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+

#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+


theme(text=element_text(size=10, color="black"),
      plot.title=element_text(size=10, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  

labs(
    title = "Total antibiotics*Exposure period levels",
    x="",
    y="",
    caption = paste0("Reference group: Total antibiotics(very low) * Exposure period level1(median=",Q2[1],")")
  )
p
```

```{r eval=FALSE, include=FALSE}
table_base <- ggplot(DF, aes(y=label)) +
  ylab(NULL) + xlab("  ") + 
  theme(plot.title = element_text(hjust = 0.5, size=10), 
        axis.text.x = element_text(color="white", hjust = -3, size = 25), ## This is used to help with alignment
        axis.line = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks = element_blank(),
        axis.title.y = element_blank(), 
        legend.position = "none",
        panel.background = element_blank(), 
        panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        plot.background = element_blank())
tab1 <- table_base + 
  labs(title = "space") +
  geom_text(aes(y = Index, x = 1, label = sprintf("%0.2f", round(OR, digits = 2))), size = 2) + ## decimal places
  ggtitle("OR")

## 95% CI table
tab2 <- table_base+
  geom_text(aes(y = Index, x = 1, label = CI), size = 2) + 
  ggtitle("95% CI")


```


```{r eval=FALSE, include=FALSE}
## forest plot
## Merge tables with plot
lay <-  matrix(c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,3,3,3.3), nrow = 1)
grid.arrange(p, tab1, tab2, layout_matrix = lay)
```




# Recent antibiotics
## create quartiles by total_ab_group
```{r }
i=2
df[explanatory[i]]=""

Q1=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.25)
Q2=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.5)
Q3=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.75)

Q1
Q2
Q3

# total ab level 1
df1=df%>%filter(total_ab_group==1)
df1[explanatory[i]]=ifelse(df1[contd[i]]<= Q1[1], 1,ifelse(
  df1[contd[i]] > Q1[1] &  df1[contd[i]] <= Q2[1], 2,ifelse(
    df1[contd[i]] > Q2[1] & df1[contd[i]] <= Q3[1], 3, ifelse(
      df1[contd[i]] > Q3[1],4, NA)
    )
  )
)
 

# total ab level 2
df2=df%>%filter(total_ab_group==2)
df2[explanatory[i]]=ifelse(df2[contd[i]]<= Q1[2], 1,ifelse(
  df2[contd[i]] > Q1[2] &  df2[contd[i]] <= Q2[2], 2,ifelse(
    df2[contd[i]] > Q2[2] & df2[contd[i]] <= Q3[2], 3, ifelse(
      df2[contd[i]] > Q3[2],4, NA)
    )
  )
)
 

# total ab level3
df3=df%>%filter(total_ab_group==3)
df3[explanatory[i]]=ifelse(df3[contd[i]]<= Q1[3], 1,ifelse(
  df3[contd[i]] > Q1[3] &  df3[contd[i]] <= Q2[3], 2,ifelse(
    df3[contd[i]] > Q2[3] & df3[contd[i]] <= Q3[3], 3, ifelse(
      df3[contd[i]] > Q3[3],4, NA)
    )
  )
)
 


# total ab level4
df4=df%>%filter(total_ab_group==4)
df4[explanatory[i]]=ifelse(df4[contd[i]]<= Q1[4], 1,ifelse(
  df4[contd[i]] > Q1[4] &  df4[contd[i]] <= Q2[4], 2,ifelse(
    df4[contd[i]] > Q2[4] & df4[contd[i]] <= Q3[4], 3, ifelse(
      df4[contd[i]] > Q3[4],4, NA)
    )
  )
)
 

df=rbind(df1,df2,df3,df4)

```



```{r}

df=df%>%mutate(ab_Level_type= 
                 case_when(
                           total_ab_group=="1" & recent_ab_days_group==1 ~ 1,
                           total_ab_group=="1" & recent_ab_days_group==2 ~ 2,
                           total_ab_group=="1" & recent_ab_days_group==3 ~ 3,
                           total_ab_group=="1" & recent_ab_days_group==4 ~ 4,
                           total_ab_group=="2" & recent_ab_days_group==1 ~ 5,
                           total_ab_group=="2" & recent_ab_days_group==2 ~ 6,
                           total_ab_group=="2" & recent_ab_days_group==3 ~ 7,
                           total_ab_group=="2" & recent_ab_days_group==4 ~ 8,
                           total_ab_group=="3" & recent_ab_days_group==1 ~ 9,
                           total_ab_group=="3" & recent_ab_days_group==2 ~ 10,
                           total_ab_group=="3" & recent_ab_days_group==3 ~ 11,
                           total_ab_group=="3" & recent_ab_days_group==4 ~ 12,
                           total_ab_group=="4" & recent_ab_days_group==1 ~ 13,
                           total_ab_group=="4" & recent_ab_days_group==2 ~ 14,
                           total_ab_group=="4" & recent_ab_days_group==3 ~ 15,
                           total_ab_group=="4" & recent_ab_days_group==4 ~ 16


                          ))


table(df$ab_Level_type)
```

```{r }
# median of each group

Q2=tapply(df[,"recent_ab_days"],df[,"ab_Level_type"],quantile,p=0.5)
Q2

```

```{r }
df$ab_Level_type= relevel(as.factor(df$ab_Level_type), ref="1")
mod=clogit(case ~ ab_Level_type + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass), df)
sum.mod=summary(mod)

```


```{r}
result=data.frame(sum.mod$conf.int)
DF=result[1:15,-2]
```


```{r }

setDT(DF, keep.rownames = TRUE)[]
names(DF)[1]="AB_exposure"
DF$AB_exposure=factor(DF$AB_exposure,levels=c("ab_Level_type1","ab_Level_type2","ab_Level_type3","ab_Level_type4","ab_Level_type5","ab_Level_type6","ab_Level_type7","ab_Level_type8","ab_Level_type9","ab_Level_type10","ab_Level_type11","ab_Level_type12","ab_Level_type13","ab_Level_type14","ab_Level_type15"))

DF=DF%>%arrange(AB_exposure)
DF[1,1]="1"
DF[2,1]="2"
DF[3,1]="3"
DF[4,1]="4"
DF[5,1]="5"
DF[6,1]="6"
DF[7,1]="7"
DF[8,1]="8"
DF[9,1]="9"
DF[10,1]="10"
DF[11,1]="11"
DF[12,1]="12"
DF[13,1]="13"
DF[14,1]="14"
DF[15,1]="15"
#DF[16,1]="16"


 Index = rep(1:15) ## This provides an order to the data
  label = as.factor(rep(1:15))


names(DF)[2]="OR"
names(DF)[3]="CI_L"
names(DF)[4]="CI_U"

DF$CI_L=round(DF$CI_L,digits = 2)
DF$CI_U=round(DF$CI_U, digits = 2)

DF$CI=paste0(DF$CI_L,",",DF$CI_U)

DF
```



```{r }
p <- ggplot(data=DF, aes(y=AB_exposure, x=OR))+ 
xlim(c(0,2.5))+
#scale_x_continuous(limits = c(0.6,2.2),breaks = c(1.0,1.5,2.0))+
#scale_y_discrete(labels=c("level1, type1"="n= 1 ","level2, type1"="n= 1 ", "level2, type2"="n= 2 ","level3, type1"="n= 1 ","level3, type2"="n= 2 ","level3, type3"="n>= 3 ","level4, type1"="n= 1 ","level4, type2"="n= 2 ","level4, type3"="n>= 3 ","level5, type1"="n= 1 ","level5, type2"="n= 2 ","level5, type3"="n>= 3 ")) +

#this adds the effect sizes to the plot
geom_point(color="black")+
#thematic stuff
theme_classic()+ 

annotate(geom = "rect", xmin = -Inf,xmax = Inf,ymin = 0, ymax = 3.5,fill="grey80", alpha=0.5)+
annotate(geom = "rect", xmin = -Inf,xmax = Inf,ymin = 7.5, ymax = 11.5,fill="grey80", alpha=0.5)+

  annotate("text", x = 0.1, y =2, label = "Very Low",size=3)+
  annotate("text", x = 0.1, y =5.5, label = "Low",size=3)+
  annotate("text", x = 0.1, y =9.5, label = "High",size=3)+
  annotate("text", x = 0.1, y =13.5, label = "Very High",size=3)+

   geom_text( size=3,aes(y = 1:15, x = 0.7,
               label = c("1"=paste0("Level2 (",Q2[2],")"),
                        "2"= paste0("Level3 (",Q2[3],")"),
                        "3"= paste0("Level4 (",Q2[4],")"),
                        "4"= paste0("Level1 (",Q2[5],")"),
                        "5"= paste0("Level2 (",Q2[6],")"),
                        "6"= paste0("Level3 (",Q2[7],")"),
                        "7"= paste0("Level4 (",Q2[8],")"),
                        "8"= paste0("Level1 (",Q2[9],")"),
                        "9"= paste0("Level2 (",Q2[10],")"),
                        "10"= paste0("Level3 (",Q2[11],")"),
                        "11"= paste0("Level4 (",Q2[12],")"),
                        "12"= paste0("Level1 (",Q2[13],")"),
                        "13"= paste0("Level2 (",Q2[14],")"),
                        "14"= paste0("Level3 (",Q2[15],")"),
                        "15"= paste0("Level4 (",Q2[16],")"))),
           hjust = "right",
           nudge_y = -.1)+


#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+

#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+


theme(text=element_text(size=10, color="black"),
      plot.title=element_text(size=10, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  

labs(
    title = "Total antibiotics*Recent antibiotics levels",
    x="",
    y="",
    caption = paste0("Reference group: Total antibiotics(very low) * Recent antibiotics level1(median=",Q2[1],")")
  )
p
```











# prescribing intervals (mean)

## create quartiles by total_ab_group
```{r }
i=3
df[explanatory[i]]=""
df[contd[i]]=round(df[contd[i]],digits = 1)

Q1=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.25)
Q2=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.5)
Q3=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.75)

Q1=round(Q1,digits = 1) 
Q2=round(Q2,digits = 1)
Q3=round(Q3,digits = 1)
Q1
Q2
Q3
# total ab level 1
df1=df%>%filter(total_ab_group==1)
df1[explanatory[i]]=ifelse(df1[contd[i]]<= Q1[1], 1,ifelse(
  df1[contd[i]] > Q1[1] &  df1[contd[i]] <= Q2[1], 2,ifelse(
    df1[contd[i]] > Q2[1] & df1[contd[i]] <= Q3[1], 3, ifelse(
      df1[contd[i]] > Q3[1],4, NA)
    )
  )
)

quantile(df1$interval_mean_group,p=0.25) 
quantile(df1$interval_mean_group,p=0.5) 
quantile(df1$interval_mean_group,p=0.75) 

# total ab level 2
df2=df%>%filter(total_ab_group==2)
df2[explanatory[i]]=ifelse(df2[contd[i]]<= Q1[2], 1,ifelse(
  df2[contd[i]] > Q1[2] &  df2[contd[i]] <= Q2[2], 2,ifelse(
    df2[contd[i]] > Q2[2] & df2[contd[i]] <= Q3[2], 3, ifelse(
      df2[contd[i]] > Q3[2],4, NA)
    )
  )
)
 
quantile(df2$interval_mean_group,p=0.25) 
quantile(df2$interval_mean_group,p=0.5) 
quantile(df2$interval_mean_group,p=0.75) 

# total ab level3
df3=df%>%filter(total_ab_group==3)
df3[explanatory[i]]=ifelse(df3[contd[i]]<= Q1[3], 1,ifelse(
  df3[contd[i]] > Q1[3] &  df3[contd[i]] <= Q2[3], 2,ifelse(
    df3[contd[i]] > Q2[3] & df3[contd[i]] <= Q3[3], 3, ifelse(
      df3[contd[i]] > Q3[3],4, NA)
    )
  )
)
 
quantile(df3$interval_mean_group,p=0.25) 
quantile(df3$interval_mean_group,p=0.5) 
quantile(df3$interval_mean_group,p=0.75) 

# total ab level4
df4=df%>%filter(total_ab_group==4)
df4[explanatory[i]]=ifelse(df4[contd[i]]<= Q1[4], 1,ifelse(
  df4[contd[i]] > Q1[4] &  df4[contd[i]] <= Q2[4], 2,ifelse(
    df4[contd[i]] > Q2[4] & df4[contd[i]] <= Q3[4], 3, ifelse(
      df4[contd[i]] > Q3[4],4, NA)
    )
  )
)
 
quantile(df4$interval_mean_group,p=0.25) 
quantile(df4$interval_mean_group,p=0.5) 
quantile(df4$interval_mean_group,p=0.75) 
df=rbind(df1,df2,df3,df4)

```

```{r }

df=df%>%mutate(ab_Level_type= 
                 case_when(
                           total_ab_group=="1" & interval_mean_group==1 ~ 1,
                           total_ab_group=="1" & interval_mean_group==2 ~ 2,
                           total_ab_group=="1" & interval_mean_group==3 ~ 3,
                           total_ab_group=="1" & interval_mean_group==4 ~ 4,
                           total_ab_group=="2" & interval_mean_group==1 ~ 5,
                           total_ab_group=="2" & interval_mean_group==2 ~ 6,
                           total_ab_group=="2" & interval_mean_group==3 ~ 7,
                           total_ab_group=="2" & interval_mean_group==4 ~ 8,
                           total_ab_group=="3" & interval_mean_group==1 ~ 9,
                           total_ab_group=="3" & interval_mean_group==2 ~ 10,
                           total_ab_group=="3" & interval_mean_group==3 ~ 11,
                           total_ab_group=="3" & interval_mean_group==4 ~ 12,
                           total_ab_group=="4" & interval_mean_group==1 ~ 13,
                           total_ab_group=="4" & interval_mean_group==2 ~ 14,
                           total_ab_group=="4" & interval_mean_group==3 ~ 15,
                           total_ab_group=="4" & interval_mean_group==4 ~ 16


                          ))


table(df$ab_Level_type)
```

```{r }
# median of each group

Q2=tapply(df[,"interval_mean"],df[,"ab_Level_type"],quantile,p=0.5)
Q2=round(Q2,digits = 1)
Q2
```

```{r }
df$ab_Level_type= relevel(as.factor(df$ab_Level_type), ref="1")
mod=clogit(case ~ ab_Level_type + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass), df)
sum.mod=summary(mod)

```


```{r }
result=data.frame(sum.mod$conf.int)
DF=result[1:15,-2]
```


```{r }
setDT(DF, keep.rownames = TRUE)[]
names(DF)[1]="AB_exposure"
DF$AB_exposure=factor(DF$AB_exposure,levels=c("ab_Level_type1","ab_Level_type2","ab_Level_type3","ab_Level_type4","ab_Level_type5","ab_Level_type6","ab_Level_type7","ab_Level_type8","ab_Level_type9","ab_Level_type10","ab_Level_type11","ab_Level_type12","ab_Level_type13","ab_Level_type14","ab_Level_type15"))

DF=DF%>%arrange(AB_exposure)
DF[1,1]="1"
DF[2,1]="2"
DF[3,1]="3"
DF[4,1]="4"
DF[5,1]="5"
DF[6,1]="6"
DF[7,1]="7"
DF[8,1]="8"
DF[9,1]="9"
DF[10,1]="10"
DF[11,1]="11"
DF[12,1]="12"
DF[13,1]="13"
DF[14,1]="14"
DF[15,1]="15"
#DF[16,1]="16"


 Index = rep(1:15) ## This provides an order to the data
  label = as.factor(rep(1:15))


names(DF)[2]="OR"
names(DF)[3]="CI_L"
names(DF)[4]="CI_U"

DF$CI_L=round(DF$CI_L,digits = 2)
DF$CI_U=round(DF$CI_U, digits = 2)

DF$CI=paste0(DF$CI_L,",",DF$CI_U)

DF
```


```{r }
p <- ggplot(data=DF, aes(y=AB_exposure, x=OR))+ 
xlim(c(0,2.5))+

#this adds the effect sizes to the plot
geom_point(color="black")+
#thematic stuff
theme_classic()+ 

annotate(geom = "rect", xmin = -Inf,xmax = Inf,ymin = 0, ymax = 3.5,fill="grey80", alpha=0.5)+
annotate(geom = "rect", xmin = -Inf,xmax = Inf,ymin = 7.5, ymax = 11.5,fill="grey80", alpha=0.5)+

  annotate("text", x = 0.1, y =2, label = "Very Low",size=3)+
  annotate("text", x = 0.1, y =5.5, label = "Low",size=3)+
  annotate("text", x = 0.1, y =9.5, label = "High",size=3)+
  annotate("text", x = 0.1, y =13.5, label = "Very High",size=3)+

   geom_text( size=3,aes(y = 1:15, x = 0.7,
               label = c("1"=paste0("Level2 (",Q2[2],")"),
                        "2"= paste0("Level3 (",Q2[3],")"),
                        "3"= paste0("Level4 (",Q2[4],")"),
                        "4"= paste0("Level1 (",Q2[5],")"),
                        "5"= paste0("Level2 (",Q2[6],")"),
                        "6"= paste0("Level3 (",Q2[7],")"),
                        "7"= paste0("Level4 (",Q2[8],")"),
                        "8"= paste0("Level1 (",Q2[9],")"),
                        "9"= paste0("Level2 (",Q2[10],")"),
                        "10"= paste0("Level3 (",Q2[11],")"),
                        "11"= paste0("Level4 (",Q2[12],")"),
                        "12"= paste0("Level1 (",Q2[13],")"),
                        "13"= paste0("Level2 (",Q2[14],")"),
                        "14"= paste0("Level3 (",Q2[15],")"),
                        "15"= paste0("Level4 (",Q2[16],")"))),
           hjust = "right",
           nudge_y = -.1)+


#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+

#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+


theme(text=element_text(size=10, color="black"),
      plot.title=element_text(size=10, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  

labs(
    title = "Total antibiotics*Prescribing intervals average",
    x="",
    y="",
    caption = paste0("Reference group: Total antibiotics(very low) * Prescribing intervals average level1(median=",Q2[1],")")
  )
p
```







# prescribing intervals (sd)
## create quartiles by total_ab_group
```{r }
i=4
df[explanatory[i]]=""

df[contd[i]]=round(df[contd[i]],digits = 1)

Q1=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.25)
Q2=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.5)
Q3=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.75)

Q1=round(Q1,digits = 1) 
Q2=round(Q2,digits = 1)
Q3=round(Q3,digits = 1)
Q1
Q2
Q3


# total ab level 1
df1=df%>%filter(total_ab_group==1)
df1[explanatory[i]]=ifelse(df1[contd[i]]<= Q1[1], 1,ifelse(
  df1[contd[i]] > Q1[1] &  df1[contd[i]] <= Q2[1], 2,ifelse(
    df1[contd[i]] > Q2[1] & df1[contd[i]] <= Q3[1], 3, ifelse(
      df1[contd[i]] > Q3[1],4, NA)
    )
  )
)
 
quantile(df1$interval_sd_group,p=0.25) 
quantile(df1$interval_sd_group,p=0.5) 
quantile(df1$interval_sd_group,p=0.75) 
# total ab level 2
df2=df%>%filter(total_ab_group==2)
df2[explanatory[i]]=ifelse(df2[contd[i]]<= Q1[2], 1,ifelse(
  df2[contd[i]] > Q1[2] &  df2[contd[i]] <= Q2[2], 2,ifelse(
    df2[contd[i]] > Q2[2] & df2[contd[i]] <= Q3[2], 3, ifelse(
      df2[contd[i]] > Q3[2],4, NA)
    )
  )
)
 quantile(df2$interval_sd_group,p=0.25) 
quantile(df2$interval_sd_group,p=0.5) 
quantile(df2$interval_sd_group,p=0.75) 

# total ab level3
df3=df%>%filter(total_ab_group==3)
df3[explanatory[i]]=ifelse(df3[contd[i]]<= Q1[3], 1,ifelse(
  df3[contd[i]] > Q1[3] &  df3[contd[i]] <= Q2[3], 2,ifelse(
    df3[contd[i]] > Q2[3] & df3[contd[i]] <= Q3[3], 3, ifelse(
      df3[contd[i]] > Q3[3],4, NA)
    )
  )
)
 
quantile(df3$interval_sd_group,p=0.25) 
quantile(df3$interval_sd_group,p=0.5) 
quantile(df3$interval_sd_group,p=0.75) 

# total ab level4
df4=df%>%filter(total_ab_group==4)
df4[explanatory[i]]=ifelse(df4[contd[i]]<= Q1[4], 1,ifelse(
  df4[contd[i]] > Q1[4] &  df4[contd[i]] <= Q2[4], 2,ifelse(
    df4[contd[i]] > Q2[4] & df4[contd[i]] <= Q3[4], 3, ifelse(
      df4[contd[i]] > Q3[4],4, NA)
    )
  )
)
 quantile(df4$interval_sd_group,p=0.25) 
quantile(df4$interval_sd_group,p=0.5) 
quantile(df4$interval_sd_group,p=0.75) 

df=rbind(df1,df2,df3,df4)

```

```{r }

df=df%>%mutate(ab_Level_type= 
                 case_when(
                           total_ab_group=="1" & interval_sd_group==1 ~ 1,
                           total_ab_group=="1" & interval_sd_group==2 ~ 2,
                           total_ab_group=="1" & interval_sd_group==3 ~ 3,
                           total_ab_group=="1" & interval_sd_group==4 ~ 4,
                           total_ab_group=="2" & interval_sd_group==1 ~ 5,
                           total_ab_group=="2" & interval_sd_group==2 ~ 6,
                           total_ab_group=="2" & interval_sd_group==3 ~ 7,
                           total_ab_group=="2" & interval_sd_group==4 ~ 8,
                           total_ab_group=="3" & interval_sd_group==1 ~ 9,
                           total_ab_group=="3" & interval_sd_group==2 ~ 10,
                           total_ab_group=="3" & interval_sd_group==3 ~ 11,
                           total_ab_group=="3" & interval_sd_group==4 ~ 12,
                           total_ab_group=="4" & interval_sd_group==1 ~ 13,
                           total_ab_group=="4" & interval_sd_group==2 ~ 14,
                           total_ab_group=="4" & interval_sd_group==3 ~ 15,
                           total_ab_group=="4" & interval_sd_group==4 ~ 16


                          ))


table(df$ab_Level_type)
```

```{r }
# median of each group

Q2=tapply(df[,"interval_sd"],df[,"ab_Level_type"],quantile,p=0.5)
Q2=round(Q2,digits = 1)
Q2

```


```{r }
df$ab_Level_type= relevel(as.factor(df$ab_Level_type), ref="1")
mod=clogit(case ~ ab_Level_type + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass), df)
sum.mod=summary(mod)

```


```{r }
result=data.frame(sum.mod$conf.int)
DF=result[1:15,-2]
```


```{r }
setDT(DF, keep.rownames = TRUE)[]
names(DF)[1]="AB_exposure"
DF$AB_exposure=factor(DF$AB_exposure,levels=c("ab_Level_type1","ab_Level_type2","ab_Level_type3","ab_Level_type4","ab_Level_type5","ab_Level_type6","ab_Level_type7","ab_Level_type8","ab_Level_type9","ab_Level_type10","ab_Level_type11","ab_Level_type12","ab_Level_type13","ab_Level_type14","ab_Level_type15"))

DF=DF%>%arrange(AB_exposure)
DF[1,1]="1"
DF[2,1]="2"
DF[3,1]="3"
DF[4,1]="4"
DF[5,1]="5"
DF[6,1]="6"
DF[7,1]="7"
DF[8,1]="8"
DF[9,1]="9"
DF[10,1]="10"
DF[11,1]="11"
DF[12,1]="12"
DF[13,1]="13"
DF[14,1]="14"
DF[15,1]="15"
#DF[16,1]="16"


 Index = rep(1:15) ## This provides an order to the data
  label = as.factor(rep(1:15))


names(DF)[2]="OR"
names(DF)[3]="CI_L"
names(DF)[4]="CI_U"

DF$CI_L=round(DF$CI_L,digits = 2)
DF$CI_U=round(DF$CI_U, digits = 2)

DF$CI=paste0(DF$CI_L,",",DF$CI_U)

DF
```


```{r }
p <- ggplot(data=DF, aes(y=AB_exposure, x=OR))+ 
xlim(c(0,2.5))+

#this adds the effect sizes to the plot
geom_point(color="black")+
#thematic stuff
theme_classic()+ 

annotate(geom = "rect", xmin = -Inf,xmax = Inf,ymin = 0, ymax = 3.5,fill="grey80", alpha=0.5)+
annotate(geom = "rect", xmin = -Inf,xmax = Inf,ymin = 7.5, ymax = 11.5,fill="grey80", alpha=0.5)+

  annotate("text", x = 0.1, y =2, label = "Very Low",size=3)+
  annotate("text", x = 0.1, y =5.5, label = "Low",size=3)+
  annotate("text", x = 0.1, y =9.5, label = "High",size=3)+
  annotate("text", x = 0.1, y =13.5, label = "Very High",size=3)+

   geom_text( size=3,aes(y = 1:15, x = 0.7,
               label = c("1"=paste0("Level2 (",Q2[2],")"),
                        "2"= paste0("Level3 (",Q2[3],")"),
                        "3"= paste0("Level4 (",Q2[4],")"),
                        "4"= paste0("Level1 (",Q2[5],")"),
                        "5"= paste0("Level2 (",Q2[6],")"),
                        "6"= paste0("Level3 (",Q2[7],")"),
                        "7"= paste0("Level4 (",Q2[8],")"),
                        "8"= paste0("Level1 (",Q2[9],")"),
                        "9"= paste0("Level2 (",Q2[10],")"),
                        "10"= paste0("Level3 (",Q2[11],")"),
                        "11"= paste0("Level4 (",Q2[12],")"),
                        "12"= paste0("Level1 (",Q2[13],")"),
                        "13"= paste0("Level2 (",Q2[14],")"),
                        "14"= paste0("Level3 (",Q2[15],")"),
                        "15"= paste0("Level4 (",Q2[16],")"))),
           hjust = "right",
           nudge_y = -.1)+


#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+

#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+


theme(text=element_text(size=10, color="black"),
      plot.title=element_text(size=10, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  

labs(
    title = "Total antibiotics*Prescribing intervals deviation",
    x="",
    y="",
    caption = paste0("Reference group: Total antibiotics(very low)*Prescribing intervals deviation level1(median=",Q2[1],")")
  )
p
```







# Antibiotics types

## create quartiles by total_ab_group
```{r }
i=5
df[explanatory[i]]=""

Q1=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.25)
Q2=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.5)
Q3=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.75)

Q1
Q2
Q3

# total ab level 1
df1=df%>%filter(total_ab_group==1)
df1[explanatory[i]]=ifelse(df1[contd[i]]<= Q1[1], 1,ifelse(
  df1[contd[i]] > Q1[1] &  df1[contd[i]] <= Q2[1], 2,ifelse(
    df1[contd[i]] > Q2[1] & df1[contd[i]] <= Q3[1], 3, ifelse(
      df1[contd[i]] > Q3[1],4, NA)
    )
  )
)

# total ab level 2
df2=df%>%filter(total_ab_group==2)
df2[explanatory[i]]=ifelse(df2[contd[i]]<= Q1[2], 1,ifelse(
  df2[contd[i]] > Q1[2] &  df2[contd[i]] <= Q2[2], 2,ifelse(
    df2[contd[i]] > Q2[2] & df2[contd[i]] <= Q3[2], 3, ifelse(
      df2[contd[i]] > Q3[2],4, NA)
    )
  )
)
 

# total ab level3
df3=df%>%filter(total_ab_group==3)
df3[explanatory[i]]=ifelse(df3[contd[i]]<= Q1[3], 1,ifelse(
  df3[contd[i]] > Q1[3] &  df3[contd[i]] <= Q2[3], 2,ifelse(
    df3[contd[i]] > Q2[3] & df3[contd[i]] <= Q3[3], 3, ifelse(
      df3[contd[i]] > Q3[3],4, NA)
    )
  )
)
 


# total ab level4
df4=df%>%filter(total_ab_group==4)
df4[explanatory[i]]=ifelse(df4[contd[i]]<= Q1[4], 1,ifelse(
  df4[contd[i]] > Q1[4] &  df4[contd[i]] <= Q2[4], 2,ifelse(
    df4[contd[i]] > Q2[4] & df4[contd[i]] <= Q3[4], 3, ifelse(
      df4[contd[i]] > Q3[4],4, NA)
    )
  )
)
 

df=rbind(df1,df2,df3,df4)

```


```{r }

df=df%>%mutate(ab_Level_type= 
                 case_when(
                           total_ab_group=="1" & ab_types_group==1 ~ 1,
                           total_ab_group=="1" & ab_types_group==2 ~ 2,
                         #  total_ab_group=="1" & ab_types_group==3 ~ 3,
                        #   total_ab_group=="1" & ab_types_group==4 ~ 4,
                           total_ab_group=="2" & ab_types_group==1 ~ 5,
                        #   total_ab_group=="2" & ab_types_group==2 ~ 6,
                           total_ab_group=="2" & ab_types_group==3 ~ 7,
                           total_ab_group=="2" & ab_types_group==4 ~ 8,
                           total_ab_group=="3" & ab_types_group==1 ~ 9,
                           total_ab_group=="3" & ab_types_group==2 ~ 10,
                           total_ab_group=="3" & ab_types_group==3 ~ 11,
                           total_ab_group=="3" & ab_types_group==4 ~ 12,
                           total_ab_group=="4" & ab_types_group==1 ~ 13,
                           total_ab_group=="4" & ab_types_group==2 ~ 14,
                           total_ab_group=="4" & ab_types_group==3 ~ 15,
                           total_ab_group=="4" & ab_types_group==4 ~ 16


                          ))


table(df$ab_Level_type)
```

```{r }
# median of each group

Q2=tapply(df[,"ab_types"],df[,"ab_Level_type"],quantile,p=0.5)
Q2

```



```{r }
df$ab_Level_type= relevel(as.factor(df$ab_Level_type), ref="1")
mod=clogit(case ~ ab_Level_type + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass), df)
sum.mod=summary(mod)

```


```{r }
result=data.frame(sum.mod$conf.int)
DF=result[1:12,-2]
```


```{r }
setDT(DF, keep.rownames = TRUE)[]
names(DF)[1]="AB_exposure"
DF$AB_exposure=factor(DF$AB_exposure,levels=c("ab_Level_type2","ab_Level_type5","ab_Level_type7","ab_Level_type8","ab_Level_type9","ab_Level_type10","ab_Level_type11","ab_Level_type12","ab_Level_type13","ab_Level_type14","ab_Level_type15","ab_Level_type16")) # remove 3,4,6

DF=DF%>%arrange(AB_exposure)
DF[1,1]="1"
DF[2,1]="2"
DF[3,1]="3"
DF[4,1]="4"
DF[5,1]="5"
DF[6,1]="6"
DF[7,1]="7"
DF[8,1]="8"
DF[9,1]="9"
DF[10,1]="10"
DF[11,1]="11"
DF[12,1]="12"
#DF[13,1]="13"
#DF[14,1]="14"
#DF[15,1]="15"
#DF[16,1]="16"


 Index = rep(1:12) ## This provides an order to the data
  label = as.factor(rep(1:12))


names(DF)[2]="OR"
names(DF)[3]="CI_L"
names(DF)[4]="CI_U"

DF$CI_L=round(DF$CI_L,digits = 2)
DF$CI_U=round(DF$CI_U, digits = 2)

DF$CI=paste0(DF$CI_L,",",DF$CI_U)

DF
```


```{r }
p <- ggplot(data=DF, aes(y=AB_exposure, x=OR))+ 
xlim(c(0,2.5))+

#this adds the effect sizes to the plot
geom_point(color="black")+
#thematic stuff
theme_classic()+ 

annotate(geom = "rect", xmin = -Inf,xmax = Inf,ymin = 0, ymax = 1.5,fill="grey80", alpha=0.5)+
annotate(geom = "rect", xmin = -Inf,xmax = Inf,ymin = 4.5, ymax = 8.5,fill="grey80", alpha=0.5)+

  annotate("text", x = 0.1, y =1, label = "Very Low",size=3)+
  annotate("text", x = 0.1, y =3, label = "Low",size=3)+
  annotate("text", x = 0.1, y =6.5, label = "High",size=3)+
  annotate("text", x = 0.1, y =10.5, label = "Very High",size=3)+

   geom_text( size=3,aes(y = 1:12, x = 0.7,
               label = c("1"=paste0("Level2 (",Q2[2],")"),
                        "2"= paste0("Level1 (",Q2[3],")"),
                        "3"= paste0("Level2 (",Q2[4],")"),
                        "4"= paste0("Level3 (",Q2[5],")"),
                        "5"= paste0("Level1 (",Q2[6],")"),
                        "6"= paste0("Level2 (",Q2[7],")"),
                        "7"= paste0("Level3 (",Q2[8],")"),
                        "8"= paste0("Level4 (",Q2[9],")"),
                        "9"= paste0("Level1 (",Q2[10],")"),
                        "10"= paste0("Level2 (",Q2[11],")"),
                        "11"= paste0("Level3 (",Q2[12],")"),
                        "12"= paste0("Level4 (",Q2[13],")"))),
           hjust = "right",
           nudge_y = -.1)+


#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+

#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+


theme(text=element_text(size=10, color="black"),
      plot.title=element_text(size=10, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  

labs(
    title = "Total antibiotics*Antibiotic types levels",
    x="",
    y="",
    caption = paste0("Reference group: Total antibiotics(very low)*Antibiotic types level1(median=",Q2[1],")")
  )
p
```






# Broad AB

## create quartiles by total_ab_group
```{r }
i=6
df[explanatory[i]]=""

Q1=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.25)
Q2=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.5)
Q3=tapply(df[,contd[i]],df[,"total_ab_group"],quantile,p=0.75)

Q1
Q2
Q3

# total ab level 1
df1=df%>%filter(total_ab_group==1)
df1[explanatory[i]]=ifelse(df1[contd[i]]<= Q1[1], 1,ifelse(
  df1[contd[i]] > Q1[1] &  df1[contd[i]] <= Q2[1], 2,ifelse(
    df1[contd[i]] > Q2[1] & df1[contd[i]] <= Q3[1], 3, ifelse(
      df1[contd[i]] > Q3[1],4, NA)
    )
  )
) 

# total ab level 2
df2=df%>%filter(total_ab_group==2)
df2[explanatory[i]]=ifelse(df2[contd[i]]<= Q1[2], 1,ifelse(
  df2[contd[i]] > Q1[2] &  df2[contd[i]] <= Q2[2], 2,ifelse(
    df2[contd[i]] > Q2[2] & df2[contd[i]] <= Q3[2], 3, ifelse(
      df2[contd[i]] > Q3[2],4, NA)
    )
  )
)
 

# total ab level3
df3=df%>%filter(total_ab_group==3)
df3[explanatory[i]]=ifelse(df3[contd[i]]<= Q1[3], 1,ifelse(
  df3[contd[i]] > Q1[3] &  df3[contd[i]] <= Q2[3], 2,ifelse(
    df3[contd[i]] > Q2[3] & df3[contd[i]] <= Q3[3], 3, ifelse(
      df3[contd[i]] > Q3[3],4, NA)
    )
  )
)
 


# total ab level4
df4=df%>%filter(total_ab_group==4)
df4[explanatory[i]]=ifelse(df4[contd[i]]<= Q1[4], 1,ifelse(
  df4[contd[i]] > Q1[4] &  df4[contd[i]] <= Q2[4], 2,ifelse(
    df4[contd[i]] > Q2[4] & df4[contd[i]] <= Q3[4], 3, ifelse(
      df4[contd[i]] > Q3[4],4, NA)
    )
  )
)
 

df=rbind(df1,df2,df3,df4)

```


```{r }

df=df%>%mutate(ab_Level_type= 
                 case_when(
                           total_ab_group=="1" & broad_ab_prescriptions_group==1 ~ 1,
                         #  total_ab_group=="1" & broad_ab_prescriptions_group==2 ~ 2,
                         #  total_ab_group=="1" & broad_ab_prescriptions_group==3 ~ 3,
                           total_ab_group=="1" & broad_ab_prescriptions_group==4 ~ 4,
                           total_ab_group=="2" & broad_ab_prescriptions_group==1 ~ 5,
                           #total_ab_group=="2" & broad_ab_prescriptions_group==2 ~ 6,
                          # total_ab_group=="2" & broad_ab_prescriptions_group==3 ~ 7,
                           total_ab_group=="2" & broad_ab_prescriptions_group==4 ~ 8,
                           total_ab_group=="3" & broad_ab_prescriptions_group==1 ~ 9,
                          # total_ab_group=="3" & broad_ab_prescriptions_group==2 ~ 10,
                           total_ab_group=="3" & broad_ab_prescriptions_group==3 ~ 11,
                           total_ab_group=="3" & broad_ab_prescriptions_group==4 ~ 12,
                           total_ab_group=="4" & broad_ab_prescriptions_group==1 ~ 13,
                          # total_ab_group=="4" & broad_ab_prescriptions_group==2 ~ 14,
                           total_ab_group=="4" & broad_ab_prescriptions_group==3 ~ 15,
                           total_ab_group=="4" & broad_ab_prescriptions_group==4 ~ 16


                          ))


table(df$ab_Level_type)
```

```{r }
# median of each group

Q2=tapply(df[,"broad_ab_prescriptions"],df[,"ab_Level_type"],quantile,p=0.5)
Q2

```



```{r }
df$ab_Level_type= relevel(as.factor(df$ab_Level_type), ref="1")
mod=clogit(case ~ ab_Level_type + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass), df)
sum.mod=summary(mod)

```


```{r }
result=data.frame(sum.mod$conf.int)
DF=result[1:9,-2]
```


```{r }
setDT(DF, keep.rownames = TRUE)[]
names(DF)[1]="AB_exposure"
DF$AB_exposure=factor(DF$AB_exposure,levels=c("ab_Level_type4","ab_Level_type5","ab_Level_type8","ab_Level_type9","ab_Level_type11","ab_Level_type12","ab_Level_type13","ab_Level_type15","ab_Level_type16"))

DF=DF%>%arrange(AB_exposure)
DF[1,1]="1"
DF[2,1]="2"
DF[3,1]="3"
DF[4,1]="4"
DF[5,1]="5"
DF[6,1]="6"
DF[7,1]="7"
DF[8,1]="8"
DF[9,1]="9"
#DF[10,1]="10"
#DF[11,1]="11"
#DF[12,1]="12"
#DF[13,1]="13"
#DF[14,1]="14"
#DF[15,1]="15"
#DF[16,1]="16"


 Index = rep(1:9) ## This provides an order to the data
  label = as.factor(rep(1:9))


names(DF)[2]="OR"
names(DF)[3]="CI_L"
names(DF)[4]="CI_U"

DF$CI_L=round(DF$CI_L,digits = 2)
DF$CI_U=round(DF$CI_U, digits = 2)

DF$CI=paste0(DF$CI_L,",",DF$CI_U)

DF
```


```{r }
p <- ggplot(data=DF, aes(y=AB_exposure, x=OR))+ 
xlim(c(0,2.5))+

#this adds the effect sizes to the plot
geom_point(color="black")+
#thematic stuff
theme_classic()+ 

annotate(geom = "rect", xmin = -Inf,xmax = Inf,ymin = 0, ymax = 1.5,fill="grey80", alpha=0.5)+
annotate(geom = "rect", xmin = -Inf,xmax = Inf,ymin = 3.5, ymax = 6.5,fill="grey80", alpha=0.5)+

  annotate("text", x = 0.1, y =1, label = "Very Low",size=3)+
  annotate("text", x = 0.1, y =2.5, label = "Low",size=3)+
  annotate("text", x = 0.1, y =5, label = "High",size=3)+
  annotate("text", x = 0.1, y =8, label = "Very High",size=3)+

   geom_text( size=3,aes(y = 1:9, x = 0.7,
               label = c(#"1"=paste0("Level2 (",Q2[1],")"),
                        "1"= paste0("Level2 (",Q2[2],")"),
                        "2"= paste0("Level1 (",Q2[3],")"),
                        "3"= paste0("Level2 (",Q2[4],")"),
                        "4"= paste0("Level1(",Q2[5],")"),
                        "5"= paste0("Level2 (",Q2[6],")"),
                        "6"= paste0("Level3 (",Q2[7],")"),
                        "7"= paste0("Level1 (",Q2[8],")"),
                        "8"= paste0("Level2 (",Q2[9],")"),
                         "9"= paste0("Level3 (",Q2[10],")"))),
           hjust = "right",
           nudge_y = -.1)+


#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U, height = .2))+

#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black")+


theme(text=element_text(size=10, color="black"),
      plot.title=element_text(size=10, vjust = 0.5),
      panel.spacing = unit(1, "lines"))+
  #    plot.title.position = "plot")+
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank()) +   
  
    theme(axis.ticks.x = element_blank()) +  

labs(
    title = "Total antibiotics*Broad-spectrum antibiotics levels",
    x="",
    y="",
    caption = paste0("Reference group: Total antibiotics(very low)*Boad-spectrum antibiotics level1(median=",Q2[1],")")
  )
p
```