---
title: "Random Forest"
---

```{r setup, include=FALSE}
#library(knitr)
library(dplyr)
#library(skimr)
library('tidyverse')
library("ggplot2")
#library(caret)

knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")

```

# import dataset
```{r }

#train_X <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/train_X.rds")
train_X <- read_rds(here::here("output","train_cat.rds"))
train_X$case=as.factor(train_X$case)
#col=c("patient_id","patient_index_date")
#train_X = subset(train_X, select = -c(patient_id, patient_index_date))
table(train_X$case)
prop.table(table(train_X$case))

valid_X <- read_rds(here::here("output","valid_cat.rds"))
valid_X$case=as.factor(valid_X$case)

table(valid_X$case)
prop.table(table(valid_X$case))

```


pick variable
```{r}
names(train_X)

#pred_col=c("patient_id","patient_index_date", "case","total_ab", "ab_prescriptions","ab_types","prescribe_times","exposure_period","recent_ab_days", "broad_prop" ,"broad_ab_prescriptions","interval_mean","interval_sd","interval_CV","length_mean", "length_sd", "length_CV","prescribe_time_0","prescribe_time_1","prescribe_time_2","prescribe_time_3",col,"AB_1_type","AB_6wk_type" ,"interval_med" ,"length_med" ,"ab_6w_binary" , "AB_6wk")

#abtype <- read_rds(here::here("output","abtype.rds"))
col=c("case","total_ab_group","ab_types_group",
      "exposure_period_group","recent_ab_days_group",
      "broad_ab_prescriptions_group",
      "interval_med_group" ,"interval_sd_group")
# abtype
train_X=train_X[col]
valid_X=valid_X[col]

str(train_X)
```


train model
```{r}
library(randomForest)

sample_n=as.numeric(table(train_X$case)[2]*0.8)
sample_n

set.seed(1024)
#for (i in 1:nrow(result)) {
  
rf1<- randomForest(formula = case ~ ., data = train_X, 
                           replace = TRUE,
                           sampsize=round(nrow(train_X)*0.8),
                           ntree =  1000,
                           nodesize = 100 ,
                           mtry = 3
                          )

# 1:1
rf2<- randomForest(formula = case ~ ., data = train_X, 
                           replace = TRUE,
                           sampsize=c(sample_n,sample_n),
                           strata=train_X$case,
                           ntree =  1000,
                           nodesize = 100 ,
                           mtry = 3
                          )
# 1:2
rf3<- randomForest(formula = case ~ ., data = train_X, 
                           replace = TRUE,
                           sampsize=c(sample_n*2,sample_n),
                           strata=train_X$case,
                           ntree =  1000,
                           nodesize = 100 ,
                           mtry = 3
                          )
# 1:6
rf4<- randomForest(formula = case ~ ., data = train_X, 
                           replace = TRUE,
                           sampsize=c(sample_n*6,sample_n),
                           strata=train_X$case,
                           ntree =  1000,
                           nodesize = 100 ,
                           mtry = 3
                          )
```

```{r}
varImpPlot(rf1)
varImpPlot(rf2)
varImpPlot(rf3)
varImpPlot(rf4)
saveRDS(rf2,here::here("output","model_RandomForest_cat.rds"))
```


```{r}
library(pROC)

set.seed(1024)
pred.y.1 <- predict(rf1, type = 'prob')[,2]
pred.y.2 <- predict(rf2, type = 'prob')[,2]
pred.y.3 <- predict(rf3, type = 'prob')[,2]
pred.y.4 <- predict(rf4, type = 'prob')[,2]

plot(roc <- roc(train_X$case~ pred.y.1),main="ROC curves for four models predicting case")#black
plot(roc <- roc(train_X$case~ pred.y.2),col=2,add=T)#red
plot(roc <- roc(train_X$case~ pred.y.3),col=3,add=T)#green
plot(roc <- roc(train_X$case~ pred.y.4),col=4,add=T)#blue
   #result[i,'valid_auc'] <- roc_valid[['auc']]

#result
```

```{r}
set.seed(1024)
pred.y.1 <- predict(rf1, train_X,type = 'prob')[,2]
pred.y.2 <- predict(rf2, train_X,type = 'prob')[,2]
pred.y.3 <- predict(rf3, train_X,type = 'prob')[,2]
pred.y.4 <- predict(rf4, train_X,type = 'prob')[,2]

plot(roc <- roc(train_X$case~ pred.y.1),main="ROC curves for four models predicting case")
plot(roc <- roc(train_X$case~ pred.y.2),col=2,add=T)#red
plot(roc <- roc(train_X$case~ pred.y.3),col=3,add=T)#green
plot(roc <- roc(train_X$case~ pred.y.4),col=4,add=T)#blue
```


```{r}
#names(train_X)
#used_count <- varUsed(rf.model)
#train_X=train_X[,-train_X$case]
#names(used_count) <- colnames(train_X)
#sort(used_count, decreasing = TRUE)
#used_count
```


```{r}
#count_table <- varUsed(rf.model, by.tree = TRUE)
#rownames(count_table) <- colnames(train_X)
#write.csv(count_table,here::here("output","var_tree.csv"))

```



```{r}
set.seed(1024)

pred.y.1 <- predict(rf1, valid_X,type = 'prob')[,2]
pred.y.2 <- predict(rf2, valid_X,type = 'prob')[,2]
pred.y.3 <- predict(rf3, valid_X,type = 'prob')[,2]
pred.y.4 <- predict(rf4, valid_X,type = 'prob')[,2]

plot(roc <- roc(valid_X$case~ pred.y.1),main="ROC curves for four models predicting case")
plot(roc <- roc(valid_X$case~ pred.y.2),col=2,add=T)#red
plot(roc <- roc(valid_X$case~ pred.y.3),col=3,add=T)#green
plot(roc <- roc(valid_X$case~ pred.y.4),col=4,add=T)#blue
```


