---
title: "model by age & sex"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include=FALSE}
require('tidyverse')
require("gtsummary")
require("ggplot2")
library("survival")
library(car)
```

```{r include=FALSE}
# import data
rm(list=ls())
#df=read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_outcome.rds")
df <- read_rds(here::here("output","matched_outcome.rds"))

```

```{r}

# outcome
df$case=as.numeric(df$case) #1/0

df$subclass=as.factor(df$subclass)#pair id

df$level=as.character(df$level) #category
df$level=ifelse(df$level=="3","2",
                ifelse(df$level=="4","3",
                       ifelse(df$level=="5","4",df$level)))

df$CCI= relevel(as.factor(df$CCI), ref="Zero")
df$covrx_ever= relevel(as.factor(df$covrx_ever), ref="0")

df$bmi_cat=relevel(as.factor(df$bmi_cat),ref="Healthy weight")
df$care_home=relevel(as.factor(df$care_home),ref = "0")

df$flu_vaccine=relevel(as.factor(df$flu_vaccine),ref= "0")

df$smoking_cat_3=relevel(as.factor(df$smoking_cat_3),ref="Never")
df$imd=relevel(as.factor(df$imd),ref="1")
df$ethnicity_6=relevel(as.factor(df$ethnicity_6),ref = "White")


# stratified by age & sex

## age grp
df=df%>%mutate(age_group=case_when(case==1 & age<40 ~1,
                                 case==1 & age>=40 & age<60 ~2,
                                 case==1 & age>=60 & age<80 ~3,
                                 case==1 & age>=80 ~4))
df=df%>% group_by(subclass)%>%mutate(age_grp=sum(age_group,na.rm = T))

# dummy data
df$case[1:7]=1
df$case[8:14]=0
df$subclass[1:7]=rep(1:7)
df$subclass[8:14]=rep(1:7)
DF=df
rm(df)

```



# male
```{r}
df=DF%>%filter(sex=="M")
```

## ab level
```{r}
summary(df[df$level==0,]$total_ab)
summary(df[df$level==1,]$total_ab)
summary(df[df$level==2,]$total_ab)
summary(df[df$level==3,]$total_ab)
summary(df[df$level==4,]$total_ab)

```

## crude model

```{r}
mod1=clogit(case ~ level + strata(subclass), df)
summary(mod1)
vif(mod1)
```

## adjust model

```{r}
 
mod1=clogit(case ~ level + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass), df)
summary(mod1)
vif(mod1)

```

# female
```{r}
df=DF%>%filter(sex=="F")
```

## ab level
```{r}
summary(df[df$level==0,]$total_ab)
summary(df[df$level==1,]$total_ab)
summary(df[df$level==2,]$total_ab)
summary(df[df$level==3,]$total_ab)
summary(df[df$level==4,]$total_ab)

```

## crude model

```{r}
mod1=clogit(case ~ level + strata(subclass), df)
summary(mod1)
vif(mod1)
```

## adjust model

```{r}
 
mod1=clogit(case ~ level + CCI + covrx_ever + bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 + strata(subclass), df)
summary(mod1)
vif(mod1)
```


# age group 18-39
```{r}
df=DF%>%filter(age_grp==1)
count(df)
```

## crude model

```{r}
mod1=clogit(case ~ level + strata(subclass), df)
summary(mod1)
vif(mod1)
```

## adjust model

```{r}
 
mod1=clogit(case ~ level + CCI + covrx_ever + strata(subclass), df)
summary(mod1)
vif(mod1)
```

