---
title: "Random Forest"
---

```{r setup, include=FALSE}
#library(knitr)
library(plyr)
#library(skimr)
library('tidyverse')
#library("ggplot2")
#library(caret)
library(pROC)
library(randomForest)
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")

```

# import dataset
```{r }
#train_Y <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/train_Y.rds")
train <- read_rds(here::here("output","train_Y.rds"))
train=as.factor(train)
#train_X <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/train_X.rds")
train <- read_rds(here::here("output","train_X.rds"))
train$case=as.factor(train$case)
#col=c("patient_id","patient_index_date")
#train_X = subset(train_X, select = -c(patient_id, patient_index_date))

#valid_Y <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/valid_Y.rds")
valid <- read_rds(here::here("output","valid_Y.rds"))
valid=as.factor(valid)
#valid_X <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/valid_X.rds")
valid <- read_rds(here::here("output","valid_X.rds"))
valid$case=as.factor(valid$case)




```

# pick variable
```{r}
names(train)

abtype <- read_rds(here::here("output","abtype.rds"))
col=c("case","length_CV")
      
      #"total_ab","ab_types",
      # "prescribe_time_0","prescribe_time_1","prescribe_time_2","prescribe_time_3",
      # "exposure_period","recent_ab_days",
      # "broad_ab_prescriptions","broad_prop_total","broad_prop",
      # "interval_med" ,"interval_mean","interval_CV","interval_sd",
      # "length_med","length_mean","length_CV","length_sd", abtype)
# abtype
train=train[col]

str(train)
```


# train model
```{r}


#result = expand.grid(
 #  ntree=c(1000,2000),
#  sampsize = c(round(n*0.6), round(n*0.8), round(n*0.9)),
 #  nodesize = c( 5,50),
 # mtry=1:round(sqrt(ncol(train_X)-1)),
 # valid_auc = NA)
n=nrow(train)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~ ., data = train, 
                           replace = TRUE,
                           ntree =  3000,
                           sampsize = round(n*0.8),
                           nodesize = 25 ,
                           mtry = sqrt(ncol(train)-1)
                          )
  print(rf.model)
  varImpPlot(rf.model)
```

# model performance

## train_ all
```{r}

# probabilities of cases
pred.y <- predict(rf.model, train, type = 'prob')[,2]

#  c statistic / AUC
roc_train <- roc(train$case ~ pred.y)
  
plot(roc_train)# ROC
print(roc_train) #AUC


  
# E/O
O <- prop.table(table(train$case))[2]
E <- mean(pred.y)
E/O


library(dplyr)
# calibration 
# create 10 risk groups
groups <- ntile(pred.y,10)
# average the observed and expected probabilities of patients in each risk group 
gpdata <- cbind(train,groups,pred.y)
obs <- (ddply(gpdata,~groups,summarise,mean=mean(as.numeric(as.character(case))))[,2])
exp <- ddply(gpdata,~groups,summarise,mean=mean(pred.y))
obsn <- table(train$case,groups)[1,] 

obs 
exp
 
# CIs for scatter points
lci = pmax(0,(obs - (1.96*(((obs*(1-obs))/obsn)^.5))))
uci = pmin(1,(obs + (1.96*(((obs*(1-obs))/obsn)^.5))))

# graph a simple calibration plot over 10 risk groups
par(pty="s")
plot(obs~exp[,2],xlim=c(0,1),ylim=c(0,1),col="red",ylab="Observed",xlab="Expected")
lines(c(0,1),c(0,1),lty=2)

for(i in 1:10){
lines(c(exp[i,2],exp[i,2]),c(lci[i],uci[i]),col="green")
}

h <- hist(pred.y, breaks=50, plot=FALSE)
for(i in 1:length(h$mids)){
  lines(c(h$mids[i],h$mids[i]),c(rep(1,length(h$mids))[i],1-((h$counts[i]/max(h$counts))/10)))
}

# Add a loess smoother to the plot
obs_all <- predict(loess(as.numeric(as.character(train$case))~pred.y,span=1))
lines_data <- data.frame(pred.y,obs_all)
lines_data2 <- lines_data[order(pred.y),] 
lines(lines_data2[,1],lines_data2[,2],col="blue")
legend(0.0,0.9,c("Risk groups","Reference line","95% CI","Loess"),col=c("red","black","green","blue"),lty=c(0,2,1,1),pch=c(1,NA,NA,NA),bty="n")

```

## valid_all
```{r}
rm(pred.y,train)
pred.y <- predict(rf.model, valid, type = 'prob')[,2]
roc_valid <- roc(valid$case ~ pred.y)
  
plot(roc_valid)#ROC curve
print(roc_valid)#AUC


# E/O
O <- prop.table(table(valid$case))[2]
E <- mean(pred.y)
E/O



# calibration 
# create 10 risk groups
groups <- ntile(pred.y,10)
# average the observed and expected probabilities of patients in each risk group 
gpdata <- cbind(valid,groups,pred.y)
obs <- (ddply(gpdata,~groups,summarise,mean=mean(as.numeric(as.character(case))))[,2])
exp <- ddply(gpdata,~groups,summarise,mean=mean(pred.y))
obsn <- table(valid$case,groups)[1,] 
obs 
exp
 
# CIs for scatter points
lci = pmax(0,(obs - (1.96*(((obs*(1-obs))/obsn)^.5))))
uci = pmin(1,(obs + (1.96*(((obs*(1-obs))/obsn)^.5))))

# graph a simple calibration plot over 10 risk groups
par(pty="s")
plot(obs~exp[,2],xlim=c(0,1),ylim=c(0,1),col="red",ylab="Observed",xlab="Expected")
lines(c(0,1),c(0,1),lty=2)

for(i in 1:10){
lines(c(exp[i,2],exp[i,2]),c(lci[i],uci[i]),col="green")
}

h <- hist(pred.y, breaks=50, plot=FALSE)
for(i in 1:length(h$mids)){
  lines(c(h$mids[i],h$mids[i]),c(rep(1,length(h$mids))[i],1-((h$counts[i]/max(h$counts))/10)))
}

# Add a loess smoother to the plot
obs_all <- predict(loess(as.numeric(as.character(valid$case))~pred.y,span=1))
lines_data <- data.frame(pred.y,obs_all)
lines_data2 <- lines_data[order(pred.y),] 
lines(lines_data2[,1],lines_data2[,2],col="blue")
legend(0.0,0.9,c("Risk groups","Reference line","95% CI","Loess"),col=c("red","black","green","blue"),lty=c(0,2,1,1),pch=c(1,NA,NA,NA),bty="n")

```
