---
title: "Random Forest model_ decile groups of probabilities"
---

```{r setup, include=FALSE}
library(dplyr)
library('tidyverse')
library(pROC)
library(randomForest)

```

# train and valid dataset (matched)
```{r }
train_X <- read_rds(here::here("output","train_X.rds"))
train_X$case=as.factor(train_X$case)
valid_X <- read_rds(here::here("output","valid_X.rds"))
valid_X$case=as.factor(valid_X$case)

names(train_X)
```

## compare patient number (matched)
```{r}

nrow(train_X)# train patients (matched)
table(train_X$case)# total train patients
prop.table(table(train_X$case))# % train patients

nrow(valid_X)# valid patients(matched)
table(valid_X$case)# total valid patients
prop.table(table(valid_X$case))# % valid patients
```




# import RF model
```{r }
rf.model=readRDS(here::here("output","model_RF_ab.rds"))
print(rf.model)
input=rownames(data.frame(rf.model$importance))
input
```

# select columns
```{r }
col=c("patient_id","patient_index_date","case","subclass",input,
       "ethnicity_6","bmi","bmi_cat","CCI","Charlson","smoking_cat_3","imd","care_home","covrx_ever","flu_vaccine","care_home_type","hospital_counts")

train_X=train_X[col]
valid_X=valid_X[col]


str(train_X)
```



# development set
## predict probabilities 
```{r}
data=train_X

prob <- predict(rf.model, data, type = 'prob')[,2]# votes of being case

summary(prob)
hist(prob)
sum(prob==0)/length(prob)# % zero

exp.class <- predict(rf.model, data, type = 'response')# predicted case/control
prop.table(summary(exp.class))
```

## create decile group
```{r}

vec=vector()

for (i in 1:10){
  vec[i]=quantile(prob,(i/10),na.rm=T)
}

vec# decile value

decile=prob
decile=ifelse(prob <=vec[1],1,decile)

for (i in 1:9) {
decile=ifelse(decile >vec[i] & decile <=vec[i+1],i+1,decile )  
}

table(decile)
prop.table(table(decile))*100 # % decile

#prob=ifelse(prob==0,NA,prob) # 0 as one group
#summary(prob)
#decile <- ntile(prob,10)
#prob=ifelse(is.na(prob),0,prob)
#decile=ifelse(is.na(decile),0,decile)
```

## combine columns
```{r}
head(decile)
head(prob)
head(exp.class)

newdata <- cbind(data,decile,prob,exp.class)

str(newdata)
```

## check decile distribution
```{r}
for (i in 1:10) {
  
  print(paste0("decile=",i))
  print(summary(newdata[decile==i,]$prob))

}
nrow(newdata)
```



```{r}
development=newdata
rm(newdata)
rm(data)
```






# validation set
## predict probabilities 
```{r}
data=valid_X

prob <- predict(rf.model, data, type = 'prob')[,2]# votes of being case

summary(prob)
hist(prob)
sum(prob==0)/length(prob)# % zero

exp.class <- predict(rf.model, data, type = 'response')# predicted case/control
prop.table(summary(exp.class))
```

## create decile group
```{r}

vec=vector()

for (i in 1:10){
  vec[i]=quantile(prob,(i/10),na.rm=T)
}

vec# decile value

decile=prob
decile=ifelse(prob <=vec[1],1,decile)

for (i in 1:9) {
decile=ifelse(decile >vec[i] & decile <=vec[i+1],i+1,decile )  
}


table(decile)
prop.table(table(decile))*100 # % decile

#prob=ifelse(prob==0,NA,prob) # 0 as one group
#summary(prob)
#decile <- ntile(prob,10)
#prob=ifelse(is.na(prob),0,prob)
#decile=ifelse(is.na(decile),0,decile)
```

## combine columns
```{r}
head(decile)
head(prob)
head(exp.class)

newdata <- cbind(data,decile,prob,exp.class)
str(newdata)
```

## check decile distribution
```{r}
for (i in 1:10) {
  
  print(paste0("decile=",i))
  print(summary(newdata[decile==i,]$prob))

}
nrow(newdata)

validation=newdata
rm(newdata)
rm(data)
```



## identify ab users, make decile==0
```{r}
development$decile=ifelse(development$total_ab>0,development$decile,0)
validation$decile=ifelse(validation$total_ab>0,validation$decile,0)

prop.table(table(development$decile,development$case))
prop.table(table(validation$decile,validation$case))
```


```{r}

nrow(development)
nrow(validation)

saveRDS(development,here::here("output","development_ab.rds"))
saveRDS(validation,here::here("output","validation_ab.rds"))

str(development)
```



```{r}
# Libraries
library(ggplot2)
library(dplyr)
library(tidyr)
library(viridis)


development$decile=as.factor(development$decile)
validation$decile=as.factor(validation$decile)
# Without transparency (left)
 ggplot(data=development, aes(x=prob, group=decile, fill=decile)) +
    geom_density(adjust=1.5, alpha=.4) 
#p1

# With transparency (right)
 ggplot(data=validation, aes(x=prob, group=decile, fill=decile)) +
    geom_density(adjust=1.5, alpha=.4)
```


```{r}
development=development%>%filter(decile>0)
validation=validation%>% filter(decile>0)

  ggplot(data=development, aes(x=prob, group=decile, fill=decile)) +
    geom_density(adjust=1.5, alpha=.4) 
#p1

# With transparency (right)
 ggplot(data=validation, aes(x=prob, group=decile, fill=decile)) +
    geom_density(adjust=1.5, alpha=.4) 
```

