---
title: "model 4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include=FALSE}
require('tidyverse')
require("gtsummary")
require("ggplot2")
library("survival")
library(car)
library(data.table)
library(gridExtra)

```


```{r include=FALSE}
# import data
rm(list=ls())
#df=read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_outcome.rds")
df <- read_rds(here::here("output","matched_outcome.rds"))

```

```{r}

# outcome
df$case=as.numeric(df$case) #1/0

df$subclass=as.factor(df$subclass)#pair id

# replace ab prescription with total ab
#df$ab_qn=as.character(df$total_ab_qn) #category
df$total_ab_qn_5=as.factor(df$total_ab_qn_5) #category
df$total_ab=as.numeric(df$total_ab)
df$ab_types=as.numeric(df$ab_types)

df$CCI= relevel(as.factor(df$CCI), ref="Very low")
df$covrx_ever= relevel(as.factor(df$covrx_ever), ref="0")

df$bmi_cat=relevel(as.factor(df$bmi_cat),ref="Healthy weight")
df$care_home=relevel(as.factor(df$care_home),ref = "0")

df$flu_vaccine=relevel(as.factor(df$flu_vaccine),ref= "0")

df$smoking_cat_3=relevel(as.factor(df$smoking_cat_3),ref="Never")
df$imd=relevel(as.factor(df$imd),ref="1")
df$ethnicity_6=relevel(as.factor(df$ethnicity_6),ref = "White")




```

```{r}
# dummy data
#df[1:15,5]<-1
#df[16:29,5]<-0
#df[1:15,4]<-seq(1:15)
# df[16:29,4]<-seq(1:14)
```

```{r}
df=df%>%mutate(abtype_3= case_when(ab_types==0 ~ "0",
               ab_types>=1 & ab_types<=2 ~"1",
               ab_types>=3 & ab_types<=4 ~"2",
               ab_types>=5  ~"3"))

summary(df[df$abtype_3=="0",]$ab_types)
summary(df[df$abtype_3=="1",]$ab_types)
summary(df[df$abtype_3=="2",]$ab_types)
summary(df[df$abtype_3=="3",]$ab_types)


```

```{r}


summary(df[df$total_ab_qn_5=="0",]$total_ab)
summary(df[df$total_ab_qn_5=="1",]$total_ab)
summary(df[df$total_ab_qn_5=="2",]$total_ab)
summary(df[df$total_ab_qn_5=="3",]$total_ab)
summary(df[df$total_ab_qn_5=="4",]$total_ab)
summary(df[df$total_ab_qn_5=="5",]$total_ab)


```


```{r}

#df=df%>%mutate(ab_qn_type= 
 #                case_when(total_ab_qn_5==0 & abtype_3==0 ~ "0",
  #                         total_ab_qn_5==1 & abtype_3==1 ~ "1",
   #                        total_ab_qn_5==1 & abtype_3==2 ~ "2",
    #                       total_ab_qn_5==1 & abtype_3==3 ~ "3",
     #                      total_ab_qn_5==2 & abtype_3==1 ~ "4",
      #                     total_ab_qn_5==2 & abtype_3==2 ~ "5",
       #                    total_ab_qn_5==2 & abtype_3==3 ~ "6",
        #                   total_ab_qn_5==3 & abtype_3==1 ~ "7",
         #                  total_ab_qn_5==3 & abtype_3>=2 ~ "8",
          #                # total_ab_qn_5==3 & abtype_3==3 ~ "9",                           
           #                total_ab_qn_5==4 & abtype_3==1 ~ "10",
            #               total_ab_qn_5==4 & abtype_3>=2 ~ "11",
             #              #total_ab_qn_5==4 & abtype_3==3 ~ "12",                           
              #             total_ab_qn_5==5 & abtype_3==1 ~ "13",
               #            total_ab_qn_5==5 & abtype_3>=2 ~ "14"
                #         #  total_ab_qn_5==5 & abtype_3==3 ~ "15" 
                 #         ))


#df=df%>%mutate(ab_qn_type= 
#                 case_when(total_ab_qn_5==0 & ab_types==0 ~ "0",
 #                          total_ab_qn_5==1 & ab_types==1 ~ "1",
  #                         total_ab_qn_5==1 &  ab_types==2 ~ "2",
   #                        total_ab_qn_5==1 &  ab_types>=3 ~ "3",
    #                       total_ab_qn_5==2 &  ab_types<=2 ~ "4",
     #                      total_ab_qn_5==2 &  ab_types==3 ~ "5",
      #                     total_ab_qn_5==2 &  ab_types>=4 ~ "6",
       #                    total_ab_qn_5==3 &  ab_types<=2 ~ "7",
        #                   total_ab_qn_5==3 &  ab_types>=3 ~ "8",
         #                  total_ab_qn_5==4 &  ab_types<=2 ~ "9",
          #                 total_ab_qn_5==4 &  ab_types>=3 ~ "10",
           #                 total_ab_qn_5==5 &  ab_types<=2 ~ "11",
            #               total_ab_qn_5==5 &  ab_types>=3 ~ "12"                          
             #             ))

df=df%>%mutate(ab_qn_type= 
                 case_when(total_ab_qn_5==0 & ab_types==0 ~ "0",
                           total_ab_qn_5==1 & ab_types==1 ~ "1",
                           total_ab_qn_5==1 &  ab_types==2 ~ "2",
                           total_ab_qn_5==1 &  ab_types>=3 ~ "3",
                           total_ab_qn_5==2 &  ab_types==1 ~ "4",
                           total_ab_qn_5==2 &  ab_types==2 ~ "5",
                           total_ab_qn_5==2 &  ab_types>=3 ~ "6",
                           total_ab_qn_5==3 &  ab_types==1 ~ "7",
                           total_ab_qn_5==3 &  ab_types==2 ~ "8",
                           total_ab_qn_5==3 &  ab_types>=3 ~ "9",
                           total_ab_qn_5==4 &  ab_types==1 ~ "10",
                           total_ab_qn_5==4 &  ab_types==2 ~ "11",
                           total_ab_qn_5==4 &  ab_types>=3 ~ "12",
                           total_ab_qn_5==5 &  ab_types==1 ~ "13",
                           total_ab_qn_5==5 &  ab_types==2 ~ "14", 
                           total_ab_qn_5==5 &  ab_types>=3 ~ "15"
                          ))

summary(df[df$ab_qn_type=="0",]$total_ab)
summary(df[df$ab_qn_type=="1",]$total_ab)
summary(df[df$ab_qn_type=="2",]$total_ab)
summary(df[df$ab_qn_type=="3",]$total_ab)
summary(df[df$ab_qn_type=="4",]$total_ab)
summary(df[df$ab_qn_type=="5",]$total_ab)
summary(df[df$ab_qn_type=="6",]$total_ab)
summary(df[df$ab_qn_type=="7",]$total_ab)
summary(df[df$ab_qn_type=="8",]$total_ab)
summary(df[df$ab_qn_type=="9",]$total_ab)
summary(df[df$ab_qn_type=="10",]$total_ab)
summary(df[df$ab_qn_type=="11",]$total_ab)
summary(df[df$ab_qn_type=="12",]$total_ab)
summary(df[df$ab_qn_type=="13",]$total_ab)
summary(df[df$ab_qn_type=="14",]$total_ab)
summary(df[df$ab_qn_type=="15",]$total_ab)

df$ab_qn_type=as.factor(df$ab_qn_type)
#df$ab_qn_type=factor(df$ab_qn_type,levels=c(seq(1:15)))


table(df$ab_qn_type)
```


# models


```{r}

mod=clogit(case ~ ab_qn_type + CCI + covrx_ever + strata(subclass), df)
           #+ bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 
sum.mod=summary(mod)
sum.mod
vif(mod)

```


```{r}
result=data.frame(sum.mod$conf.int)

result

result=result[1:15,-2]
```


```{r}
DF=result

setDT(DF, keep.rownames = TRUE)[]
names(DF)[1]="AB_exposure"
DF$AB_exposure=factor(DF$AB_exposure,levels=c("ab_qn_type1","ab_qn_type2","ab_qn_type3","ab_qn_type4","ab_qn_type5","ab_qn_type6","ab_qn_type7","ab_qn_type8","ab_qn_type9","ab_qn_type10","ab_qn_type11","ab_qn_type12","ab_qn_type13","ab_qn_type14","ab_qn_type15"))

DF=DF%>%arrange(AB_exposure)
DF[1,1]="level1, type=1"
DF[2,1]="level1, type=2"
DF[3,1]="level1, type≥3"
DF[4,1]="level2, type=1"
DF[5,1]="level2, type=2"
DF[6,1]="level2, type≥3"
DF[7,1]="level3, type=1"
DF[8,1]="level3, type=2"
DF[9,1]="level3, type≥3"
DF[10,1]="level4, type=1"
DF[11,1]="level4, type=2"
DF[12,1]="level4, type≥3"
DF[13,1]="level5, type=1"
DF[14,1]="level5, type=2"
DF[15,1]="level5, type≥3"

 Index = rep(1:15) ## This provides an order to the data
  label = c("level1, type=1","level1, type=2","level1, type≥3","level2, type=1","level2, type=2","level2, type≥3","level3, type=1","level3, type=2","level3, type≥3","level4, type=1","level4, type=2","level4, type≥3","level5, type=1","level5, type=2","level5, type≥3")

names(DF)[2]="OR"
names(DF)[3]="CI_L"
names(DF)[4]="CI_U"

DF$CI_L=round(DF$CI_L,digits = 2)
DF$CI_U=round(DF$CI_U, digits = 2)

DF$CI=paste0(DF$CI_L,",",DF$CI_U)

DF
```



```{r}
p <- ggplot(data=DF, aes(y=AB_exposure, x=OR))+ 

#this adds the effect sizes to the plot
geom_point(color="blue")+ 

#adds the CIs
geom_errorbarh(aes(xmin=CI_L, xmax=CI_U))+
  

#adding a vertical line at the effect = 0 mark
geom_vline(xintercept=1, color="black", linetype="dashed")+
  
#thematic stuff
theme_classic()+ 
  xlim(0, 15)+
theme(text=element_text(family="Times",size=18, color="black"))+
theme(panel.spacing = unit(1, "lines"))+

labs(
      title = "",
    x="OR (95% CI)",
    y=""
  )
p
```
```{r}
table_base <- ggplot(DF, aes(y=label)) +
  ylab(NULL) + xlab("  ") + 
  theme(plot.title = element_text(hjust = 0.5, size=12), 
        axis.text.x = element_text(color="white", hjust = -3, size = 25), ## This is used to help with alignment
        axis.line = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks = element_blank(),
        axis.title.y = element_blank(), 
        legend.position = "none",
        panel.background = element_blank(), 
        panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        plot.background = element_blank())
tab1 <- table_base + 
  labs(title = "space") +
  geom_text(aes(y = rev(Index), x = 1, label = sprintf("%0.1f", round(OR, digits = 1))), size = 4) + ## decimal places
  ggtitle("OR")

## 95% CI table
tab2 <- table_base+
  geom_text(aes(y = rev(Index), x = 1, label = CI), size = 4) + 
  ggtitle("95% CI")
```


```{r}
## Merge tables with plot
lay <-  matrix(c(1,1,1,1,1,1,1,1,1,1,2,3,3), nrow = 1)
grid.arrange(p, tab1, tab2, layout_matrix = lay)
```








## merge high qn group



```{r}

#df=df%>%mutate(ab_qn_type= 
 #                case_when(total_ab_qn_5==0 & abtype_3==0 ~ "0",
  #                         total_ab_qn_5==1 & abtype_3==1 ~ "1",
   #                        total_ab_qn_5==1 & abtype_3==2 ~ "2",
    #                       total_ab_qn_5==1 & abtype_3==3 ~ "3",
     #                      total_ab_qn_5==2 & abtype_3==1 ~ "4",
      #                     total_ab_qn_5==2 & abtype_3==2 ~ "5",
       #                    total_ab_qn_5==2 & abtype_3==3 ~ "6",
        #                   total_ab_qn_5==3 & abtype_3==1 ~ "7",
         #                  total_ab_qn_5==3 & abtype_3>=2 ~ "8",
          #                # total_ab_qn_5==3 & abtype_3==3 ~ "9",                           
           #                total_ab_qn_5==4 & abtype_3==1 ~ "10",
            #               total_ab_qn_5==4 & abtype_3>=2 ~ "11",
             #              #total_ab_qn_5==4 & abtype_3==3 ~ "12",                           
              #             total_ab_qn_5==5 & abtype_3==1 ~ "13",
               #            total_ab_qn_5==5 & abtype_3>=2 ~ "14"
                #         #  total_ab_qn_5==5 & abtype_3==3 ~ "15" 
                 #         ))


#df=df%>%mutate(ab_qn_type= 
#                 case_when(total_ab_qn_5==0 & ab_types==0 ~ "0",
 #                          total_ab_qn_5==1 & ab_types==1 ~ "1",
  #                         total_ab_qn_5==1 &  ab_types==2 ~ "2",
   #                        total_ab_qn_5==1 &  ab_types>=3 ~ "3",
    #                       total_ab_qn_5==2 &  ab_types<=2 ~ "4",
     #                      total_ab_qn_5==2 &  ab_types==3 ~ "5",
      #                     total_ab_qn_5==2 &  ab_types>=4 ~ "6",
       #                    total_ab_qn_5==3 &  ab_types<=2 ~ "7",
        #                   total_ab_qn_5==3 &  ab_types>=3 ~ "8",
         #                  total_ab_qn_5==4 &  ab_types<=2 ~ "9",
          #                 total_ab_qn_5==4 &  ab_types>=3 ~ "10",
           #                 total_ab_qn_5==5 &  ab_types<=2 ~ "11",
            #               total_ab_qn_5==5 &  ab_types>=3 ~ "12"                          
             #             ))

df=df%>%mutate(ab_qn_type= 
                 case_when(total_ab_qn_5==0 & ab_types==0 ~ "0",
                           total_ab_qn_5==1 & ab_types==1 ~ "1",
                           total_ab_qn_5==1 &  ab_types==2 ~ "2",
                           total_ab_qn_5==1 &  ab_types>=3 ~ "3",
                           total_ab_qn_5==2 &  ab_types==1 ~ "4",
                           total_ab_qn_5==2 &  ab_types==2 ~ "5",
                           total_ab_qn_5==2 &  ab_types>=3 ~ "6",
                          # total_ab_qn_5==3 &  ab_types==1 ~ "7",
                           total_ab_qn_5==3 &  ab_types<=2 ~ "8",
                           total_ab_qn_5==3 &  ab_types>=3 ~ "9",
                          # total_ab_qn_5==4 &  ab_types==1 ~ "10",
                           total_ab_qn_5==4 &  ab_types<=2 ~ "11",
                           total_ab_qn_5==4 &  ab_types>=3 ~ "12",
                         #   total_ab_qn_5==5 &  ab_types==1 ~ "13",
                           total_ab_qn_5==5 &  ab_types<=2 ~ "14", 
                           total_ab_qn_5==5 &  ab_types>=3 ~ "15"
                          ))

summary(df[df$ab_qn_type=="0",]$total_ab)
summary(df[df$ab_qn_type=="1",]$total_ab)
summary(df[df$ab_qn_type=="2",]$total_ab)
summary(df[df$ab_qn_type=="3",]$total_ab)
summary(df[df$ab_qn_type=="4",]$total_ab)
summary(df[df$ab_qn_type=="5",]$total_ab)
summary(df[df$ab_qn_type=="6",]$total_ab)
#summary(df[df$ab_qn_type=="7",]$total_ab)
summary(df[df$ab_qn_type=="8",]$total_ab)
summary(df[df$ab_qn_type=="9",]$total_ab)
#summary(df[df$ab_qn_type=="10",]$total_ab)
summary(df[df$ab_qn_type=="11",]$total_ab)
summary(df[df$ab_qn_type=="12",]$total_ab)
#summary(df[df$ab_qn_type=="13",]$total_ab)
summary(df[df$ab_qn_type=="14",]$total_ab)
summary(df[df$ab_qn_type=="15",]$total_ab)

df$ab_qn_type=as.factor(df$ab_qn_type)
#df$ab_qn_type=factor(df$ab_qn_type,levels=c("ab_qn_type1","ab_qn_type2","ab_qn_type3","ab_qn_type4","ab_qn_type5","ab_qn_type6","ab_qn_type8","ab_qn_type9","ab_qn_type11","ab_qn_type12","ab_qn_type14","ab_qn_type15"))


table(df$ab_qn_type)
```


# models


```{r}
 
mod=clogit(case ~ ab_qn_type + CCI + covrx_ever + strata(subclass), df)
           #+ bmi_cat + care_home + flu_vaccine + smoking_cat_3 + imd+ ethnicity_6 
sum.mod=summary(mod)
sum.mod
vif(mod)

```


```{r}
result=data.frame(sum.mod$conf.int)

result

result=result[1:12,-2]
```


```{r}
DF=result

setDT(DF, keep.rownames = TRUE)[]
names(DF)[1]="AB_exposure"
#DF$AB_exposure=factor(DF$AB_exposure,levels=c("ab_qn_type1","ab_qn_type2","ab_qn_type3","ab_qn_type4","ab_qn_type5","ab_qn_type6","ab_qn_type7","ab_qn_type8","ab_qn_type9","ab_qn_type10","ab_qn_type11","ab_qn_type12","ab_qn_type13","ab_qn_type14","ab_qn_type15"))


names(DF)[2]="OR"
names(DF)[3]="CI_L"
names(DF)[4]="CI_U"

DF
```

