---
title: "data preparation: measure antibiotics exposure"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
library('tidyverse')
library("ggplot2")
library('dplyr')
library('lubridate')
```

input ab_time
```{r}
setwd(here::here("output"))
#setwd('/Users/yayang/Documents/GitHub/amr-uom-brit/output')
df <- read_rds("matched_outcome.rds")
df=df%>% select("patient_id","patient_index_date","case","subclass","total_ab","ab_prescriptions","broad_ab_prescriptions","ab_types")



DF=read.csv("input_ab_time.csv")
names(DF)

ab_date=colnames(DF[,9:68])
ab_date
ab_conut=colnames(DF[,70:129])
ab_conut
count(DF)

```


```{r }
#replace NA
# all date+ab variables 
for (i in 7:129) {
 DF[,i]=ifelse(DF[,i]=="",NA,DF[,i])
 
}
# all 60 ab counts+AB_0
for (i in 69:129) {
 DF[,i]=ifelse(is.na(DF[,i]),0,DF[,i])
 
}
```

all ab: sum of total 60 extractions
```{r }
DF$all_ab=rowSums(DF[,ab_conut])
```

filter ab users (from all matched patient cohort)
```{r}
DF=DF%>% filter(all_ab>0)
count(DF)
```

exposure period
```{r}
#DF$last_date= apply(DF[ab_date], 1, max, na.rm=TRUE)
DF[,"last_date"]=do.call(pmin, c(DF[,ab_date], na.rm = TRUE)) # earliest date of ab exposure

```



```{r}
library(lubridate)
DF$last_date=ifelse(is.na(DF$last_date),NA, DF$last_date)
DF$AB_date_1=ifelse(is.na(DF$AB_date_1),NA,DF$AB_date_1) # most recent ab date

DF$last_date=ymd(DF$last_date)
DF$AB_date_1=ymd(DF$AB_date_1)

#DF$exposure_period=DF$last_date-DF$AB_date_1
DF$exposure_period=difftime(DF$AB_date_1,DF$last_date, units = "day")
DF$exposure_period=as.numeric(DF$exposure_period)
summary(DF$exposure_period)
```

```{r eval=FALSE, include=FALSE}

DF[ab_date]=lapply(DF[ab_date], as.Date, origin="1970-01-01")

DF$last_time= apply(DF[ab_date], 1, max, na.rm=TRUE)

DF$exposure_period=difftime(DF$last_time,DF$AB_date_1, units = "day")

DF$exposure_period=as.numeric(DF$exposure_period)
summary(DF$exposure_period)
```

most recent exp days
```{r}
DF$recent_ab_days=difftime(DF$patient_index_date,DF$AB_date_1, units = "day")
DF$recent_ab_days=as.numeric(DF$recent_ab_days)
summary(DF$recent_ab_days)
```

ab in 6 weeks
```{r}
summary(DF$AB_6wk)
DF$ab_6w_binary=ifelse(DF$AB_6wk>0,1,0)

```

recent ab type
```{r}
table(DF$AB_6wk_type)
table(DF$AB_1_type)
```


prescribing times
```{r}
DF$prescribe_times=60-rowSums(is.na(DF[,ab_date]))
```



calculate time interval between prescriptions

```{r}

for (i in 2:60) {
  DF[,ab_date[i]]=ifelse(
    is.na(DF[,ab_date[i]]), NA,
    DF[,ab_date[i]])
  
  
}

```

```{r}
for (i in 1:59){


DF[,137+i]=difftime( DF[,ab_date[i]],DF[,ab_date[i+1]],units = "day" )
  colnames(DF)[137+i]=paste0("interval_",i)


}


DF[,138:196]=lapply(DF[,138:196], as.numeric)


names(DF)


DF$interval_mean= apply(DF[,138:196], 1, mean, na.rm=TRUE)
DF$interval_med= apply(DF[,138:196], 1, median, na.rm=TRUE)
DF$interval_sd= apply(DF[,138:196], 1, sd, na.rm=TRUE)
DF$interval_CV=DF$interval_sd/DF$interval_mean

head(DF)
```


calculate time interval from index date
```{r}
sum(is.na(DF$patient_index_date))
DF[,"patient_index_date"]=ifelse(
  is.na(DF[,"patient_index_date"]), NA, 
  DF[,"patient_index_date"])
sum(is.na(DF$patient_index_date))
DF[,"patient_index_date"]=ymd(DF[,"patient_index_date"])


```


```{r}
for (i in 1:59){


DF[,200+i]=difftime(DF[,"patient_index_date"], DF[,ab_date[i]], units = "day" )
  colnames(DF)[200+i]=paste0("length_",i)


}


DF[,201:259]=lapply(DF[,201:259], as.numeric)


names(DF)


DF$length_mean= apply(DF[,201:259], 1, mean, na.rm=TRUE)
DF$length_med= apply(DF[,201:259], 1, median, na.rm=TRUE)
DF$length_sd= apply(DF[,201:259], 1, sd, na.rm=TRUE)
DF$length_CV=DF$length_sd/DF$length_mean

head(DF)
```

filter column
```{r}


DF=DF%>% select(patient_id,patient_index_date,interval_med,interval_mean,interval_sd,interval_CV,prescribe_times,AB_6wk_type,AB_6wk,ab_6w_binary,AB_1_type,recent_ab_days,exposure_period,length_mean,length_med,length_sd,length_CV)


str(DF)
```



```{r}
#setwd(here::here("output"))
#setwd('/Users/yayang/Documents/GitHub/amr-uom-brit/output')
# import matched patients dataset

# filter only 1 ID
#df=df %>% distinct(patient_id, .keep_all=T)
data=merge(df,DF,by=c("patient_id","patient_index_date"), all.x = TRUE)

head(data)

rm(df,DF)
```

broad %
```{r}
#data$broad_prop=data$broad_ab_prescriptions/data$total_ab
data$broad_prop=data$broad_ab_prescriptions/data$ab_prescriptions

```

```{r}
write_rds(data, here::here("output", "matched_ab.rds"))
```

