---
title: "filter id with ab use"
author: "YT Y"
date: "07/04/2022"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
library('tidyverse')
library("ggplot2")
library(knitr)
library(dplyr)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")
```


```{r}
# import
#setwd('/Users/yayang/Documents/GitHub/amr-uom-brit/output')
setwd(here::here("output"))
df=read_rds(here::here("output","matched_outcome.rds"))
#df=read_rds("matched_outcome.rds")
df=df%>% select("case","patient_id","patient_index_date","total_ab")
count(df)
```

ab users in case
```{r}

df1=df%>%filter(case==1 & total_ab>0)
count(df1)
length(unique(df1$patient_id))
```

ab users in control
```{r}

df0=df%>%filter(case==0 & total_ab>0)
count(df0)
length(unique(df0$patient_id))
```

# output
```{r}
DF=rbind(df1,df0)

DF=DF%>% select("patient_id","patient_index_date")
DF=DF%>% distinct(patient_id, .keep_all = TRUE)

count(DF)

write.csv(DF,here::here("output","matched_patients_id_ab.csv"))



```


