---
title: "merge monthly ab var"
author: "YT Y"
date: "07/04/2022"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
library('tidyverse')
library("ggplot2")
library(knitr)
library(dplyr)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")


```


```{r}
setwd(here::here("output"))
#setwd('/Users/yayang/Documents/GitHub/amr-uom-brit/output')

# import matched patients dataset
df=read_rds("matched_outcome.rds")
df=df%>% select("patient_id","patient_index_date","age","sex","stp","case","subclass","total_ab")
count(df)

# year1 ab variables
#df1=read.csv(here::here("output","input_ab_yr1.csv"))
df1=read.csv("input_ab_yr1.csv")
str(df1)

#AB=colnames(df1[,8:139])
df1[,6:137]=df1[,6:137]%>%mutate_all(~replace(., is.na(.), 0)) # recode NA -> 0
df1[,6:137]<- sapply(df1[6:137],as.numeric)
df1$total_ab_yr1=rowSums(df1[,6:137])

str(df1)

df1=df1%>% select(-c("ab_prescriptions"))
names(df1)[138]<-"broad_ab_yr1"
count(df1)

df1=df1%>% select(-c("age","sex","stp"))
# merge
#DF=merge(df,df1,by=c("patient_id","patient_index_date","age","sex","stp"))
DF=merge(df,df1,by=c("patient_id","patient_index_date"), all.x = TRUE)
count(DF)

```

```{r}
# import ab var2
setwd(here::here("output"))
#setwd('/Users/yayang/Documents/GitHub/amr-uom-brit/output')

#df2=read.csv(here::here("output","input_ab_yr2.csv"))
df2=read.csv("input_ab_yr2.csv")

df2[,6:137]=df2[,6:137]%>%mutate_all(~replace(., is.na(.), 0)) # recode NA -> 0
df2[,6:137]<- sapply(df2[,6:137],as.numeric)
df2$total_ab_yr2=rowSums(df2[,6:137])

names(df2)[138]<-"broad_ab_yr2"
count(df2)

df2=df2%>% select(-c("age","sex","stp"))

# merge
DF2=merge(DF,df2,by=c("patient_id","patient_index_date"), all.x = TRUE)
count(DF2)

```

```{r}
# import ab var3
setwd(here::here("output"))
#setwd('/Users/yayang/Documents/GitHub/amr-uom-brit/output')

#df3=read.csv(here::here("output","input_ab_yr3.csv"))
df3=read.csv("input_ab_yr3.csv")

df3[,6:137]=df3[,6:137]%>%mutate_all(~replace(., is.na(.), 0)) # recode NA -> 0
df3[,6:137]<- sapply(df3[,6:137],as.numeric)
df3$total_ab_yr3=rowSums(df3[,6:137])

names(df3)[138]<-"broad_ab_yr3"
count(df3)

df3=df3%>% select(-c("age","sex","stp"))

# merge
DF3=merge(DF2,df3,by=c("patient_id","patient_index_date"), all.x = TRUE)
count(DF3)


```


```{r}
# import ab var3
setwd(here::here("output"))
#setwd('/Users/yayang/Documents/GitHub/amr-uom-brit/output')

#df3=read.csv(here::here("output","input_ab_yr3.csv"))
df3_15d=read.csv("input_ab_yr3_15d.csv")

df3_15d[,6:16]=df3_15d[,6:16]%>%mutate_all(~replace(., is.na(.), 0)) # recode NA -> 0
df3_15d[,6:16]<- sapply(df3_15d[,6:16],as.numeric)
df3_15d$total_ab_yr3_15d=rowSums(df3_15d[,6:16])

names(df3_15d)[17]<-"broad_ab_yr3"
count(df3_15d)

df3_15d=df3_15d%>% select(-c("age","sex","stp"))

# merge
DF3_all=merge(DF3,df3_15d,by=c("patient_id","patient_index_date"), all.x = TRUE)
count(DF3_all)

DF3_all[,8:423]=DF3_all[,8:423]%>%mutate_all(~replace(., is.na(.), 0)) # recode NA -> 0


write_rds(DF3_all,"matched_patients_monthly_ab.rds")
```




```{r}
 # overall check

DF3=DF3_all

DF3$total_check=DF3$total_ab_yr1+DF3$total_ab_yr2+DF3$total_ab_yr3+total_ab_yr3_15d
DF3=DF3%>% select("total_ab","total_check","patient_id","patient_index_date")

# discrepancy
count(DF3[DF3$total_check==0 & DF3$total_ab != 0,])
count(DF3[DF3$total_check!=0 & DF3$total_ab == 0,])

#DF3=DF3%>% filter(total_ab>0)
count(DF3[DF3$total_check> DF3$total_ab,])
count(DF3[DF3$total_check< DF3$total_ab,])

```

```{r}

DF3=DF3%>% filter(total_ab>0)
DF3$diff= DF3$total_check - DF3$total_ab

DF3$diff=as.factor(DF3$diff)
counts=table(DF3$diff)

barplot(counts, main="difference distribution",
   xlab="total check - total ab")
```

