---
title: "TPP region"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include=FALSE}
require('tidyverse')
require("gtsummary")
```


# Jan 2019

```{r}
#df1=read_csv("/Users/yayang/Documents/GitHub/amr-uom-brit/output/measures/input_2019-01-01.csv.gz")

df1 <- read_csv(here::here("output","measures","input_2019-01-01.csv.gz"))

df1=df1%>% select("region","age_cat","age","sex")



```

```{r}

#df0=df0%>%select("stp")

table1 <- 
  tbl_summary(
    df1,
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{n}  ({p}%)"),
    digits = all_continuous() ~ 2,
  ) %>%
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 

table1
```


# Jan 2020

```{r}
#df1=read_csv("/Users/yayang/Documents/GitHub/amr-uom-brit/output/measures/input_2019-01-01.csv.gz")

df1 <- read_csv(here::here("output","measures","input_2020-01-01.csv.gz"))

df1=df1%>% select("region","age_cat","age","sex")



```

```{r}

#df0=df0%>%select("stp")

table1 <- 
  tbl_summary(
    df1,
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{n}  ({p}%)"),
    digits = all_continuous() ~ 2,
  ) %>%
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 

table1
```



# Jan 2021

```{r}
#df1=read_csv("/Users/yayang/Documents/GitHub/amr-uom-brit/output/measures/input_2019-01-01.csv.gz")

df1 <- read_csv(here::here("output","measures","input_2021-01-01.csv.gz"))

df1=df1%>% select("region","age_cat","age","sex")



```

```{r}

#df0=df0%>%select("stp")

table1 <- 
  tbl_summary(
    df1,
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{n}  ({p}%)"),
    digits = all_continuous() ~ 2,
  ) %>%
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 

table1
```


