---
title: "Random Forest"
---

```{r setup, include=FALSE}
#library(knitr)
library(dplyr)
#library(skimr)
library('tidyverse')
library("ggplot2")
#library(caret)
library(pROC)
library(randomForest)
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format="html")

```

# import dataset
```{r }
#train_X <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/train_X.rds")
train_X <- read_rds(here::here("output","train_X.rds"))
train_X$case=as.factor(train_X$case)
#valid_X <- read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/valid_X.rds")
valid_X <- read_rds(here::here("output","valid_X.rds"))
valid_X$case=as.factor(valid_X$case)

data=rbind(train_X, valid_X)
nrow(data)
rm(train_X,valid_X)

data=data%>%filter(total_ab>0)
data=data%>%distinct(patient_id, .keep_all = TRUE)
nrow(data)

```


pick variable
```{r}
names(train_X)

col=c("case","total_ab","ab_types","exposure_period" ,"recent_ab_days","broad_ab_prescriptions" ,"interval_med" , "interval_sd")
# abtype
data=data[col]
```


RF model
```{r}

n=nrow(train_X)

set.seed(1024)
#for (i in 1:nrow(result)) {
  
  rf.model <- randomForest(formula = case ~ ., data = data, 
                           replace = TRUE,
                           ntree =  1000,
                           sampsize = round(n*0.6),
                           nodesize = 25 ,
                           mtry = sqrt(ncol(data)-1)
                          )
  print(rf.model)
```

```{r}
importance(rf.model)
varImpPlot(rf.model)

saveRDS(rf.model,here::here("output","model_RandomForest.rds"))
```




```{r}
set.seed(1024)
pred.y <- predict(rf.model, type = 'prob')[,2]
  roc_valid <- roc(data$case~ pred.y)
  
   #result[i,'valid_auc'] <- roc_valid[['auc']]
  
  plot(roc_valid)
  print(roc_valid)
#}

#result
```



