
from cohortextractor import (
    StudyDefinition,
    patients,
    #codelist_from_csv,
    codelist,
    filter_codes_by_category,
    #combine_codelists,
    Measure
)

###### import matched cohort
COHORT = "output/matched_patients_id_ab.csv"

###### Code lists
from codelists import *

###### Define study time variables
from datetime import datetime
start_date = "2020-02-01"
end_date = "2021-12-31"

####### Import variables

# ## infection before patient_index_date
# from variables_infection import generate_infection_variables
# infection_variables = generate_infection_variables(index_date_variable="patient_index_date")



study = StudyDefinition(

    # Configure the expectations framework
    default_expectations={
        "date": {"earliest": start_date, "latest": end_date},
        "rate": "uniform",
        "incidence": 0.1,
    },

    # Set index date to start date
    index_date=start_date,
   
    # study population
    population=patients.which_exist_in_file(COHORT),

    ### patient index date  
    # case_infection_date
    patient_index_date=patients.with_value_from_file(
        COHORT,
        returning="patient_index_date",
        returning_type="date",
    ),

    ## Age
    age=patients.age_as_of(
        "patient_index_date",
        return_expectations={
            "rate": "universal",
            "int": {"distribution": "population_ages"},
            "incidence": 0.001
        },
    ),

    # ## Age categories
    # ## 0-4; 5-14; 15-24; 25-34; 35-44; 45-54; 55-64; 65-74; 75+
    # age_cat=patients.categorised_as(
    #     {
    #         "0":"DEFAULT",
    #         "0-4": """ age >= 0 AND age < 5""",
    #         "5-14": """ age >= 5 AND age < 15""",
    #         "15-24": """ age >= 15 AND age < 25""",
    #         "25-34": """ age >= 25 AND age < 35""",
    #         "35-44": """ age >= 35 AND age < 45""",
    #         "45-54": """ age >= 45 AND age < 55""",
    #         "55-64": """ age >= 55 AND age < 65""",
    #         "65-74": """ age >= 65 AND age < 75""",
    #         "75+": """ age >= 75 AND age < 120""",
    #     },
    #     return_expectations={
    #         "rate": "universal",
    #         "category": {
    #             "ratios": {
    #                 "0": 0,
    #                 "0-4": 0.12, 
    #                 "5-14": 0.11,
    #                 "15-24": 0.11,
    #                 "25-34": 0.11,
    #                 "35-44": 0.11,
    #                 "45-54": 0.11,
    #                 "55-64": 0.11,
    #                 "65-74": 0.11,
    #                 "75+": 0.11,
    #             }
    #         },
    #     },
    # ),

    
    ## Sex
    sex=patients.sex(
        return_expectations={
            "rate": "universal",
            "category": {"ratios": {"M": 0.49, "F": 0.51}},
        }
    ),

## region
    stp=patients.registered_practice_as_of(
             "patient_index_date",
            returning="stp_code",
            return_expectations={
                "rate": "universal",
                "category": {
                    "ratios": {
                        "STP1": 0.1,
                        "STP2": 0.1,
                        "STP3": 0.1,
                        "STP4": 0.1,
                        "STP5": 0.1,
                        "STP6": 0.1,
                        "STP7": 0.1,
                        "STP8": 0.1,
                        "STP9": 0.1,
                        "STP10": 0.1,
                    }
                },
            },
    ),

    
# # data check	
#     ## de-register after start date	
#     dereg_date=patients.date_deregistered_from_all_supported_practices(	
#         on_or_before="patient_index_date - 1 day",	
#         date_format="YYYY-MM-DD",	
#         return_expectations={	
#         "date": {"earliest": "2020-02-01"},	
#         "incidence": 0.05	
#         }	
#     ),	
#     ## died after patient index date	
#     ons_died_date_after=patients.died_from_any_cause(	
#         between=["patient_index_date" , "patient_index_date + 1 month"],        	
#         returning="date_of_death",	
#         date_format="YYYY-MM-DD",	
#         return_expectations={"date": {"earliest": "2020-03-01"},"incidence": 0.1},	
#     ),

#     ## died before patient index date	
#     ons_died_date_before=patients.died_from_any_cause(	
#         on_or_before="patient_index_date - 1 day",        	
#         returning="date_of_death",	
#         date_format="YYYY-MM-DD",	
#         return_expectations={"date": {"earliest": "2020-02-01"},"incidence": 0.1},	
#     ),

    AB_6wk=patients.with_these_medications(
        antibacterials_codes_brit,
        returning="number_of_matches_in_period",
        between=["patient_index_date - 42 days", "patient_index_date"],
        return_last_date_in_period=True,
        include_date_of_match= True,
        date_format="YYYY-MM-DD",
        return_expectations={
            "int" : {"distribution": "normal", "mean": 5, "stddev": 1},"incidence":0.2}
    ),  


AB_1=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_0_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_2=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_1_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_3=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_2_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_4=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_3_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_5=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_4_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_6=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_5_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_7=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_6_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_8=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_7_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_9=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_8_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_10=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_9_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_11=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_10_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_12=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_11_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_13=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_12_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_14=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_13_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_15=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_14_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_16=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_15_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_17=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_16_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_18=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_17_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_19=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_18_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_20=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_19_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_21=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_20_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_22=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_21_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_23=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_22_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_24=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_23_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_25=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_24_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_26=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_25_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_27=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_26_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_28=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_27_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_29=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_28_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_30=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_29_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_31=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_30_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_32=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_31_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_33=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_32_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_34=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_33_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_35=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_34_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_36=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_35_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_37=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_36_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_38=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_37_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_39=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_38_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_40=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_39_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_41=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_40_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_42=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_41_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_43=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_42_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_44=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_43_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_45=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_44_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_46=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_45_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_47=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_46_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_48=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_47_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_49=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_48_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_50=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_49_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_51=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_50_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_52=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_51_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_53=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_52_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_54=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_53_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_55=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_54_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_56=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_55_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_57=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_56_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_58=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_57_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_59=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_58_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_60=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_59_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_61=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_60_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_62=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_61_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_63=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_62_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_64=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_63_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_65=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_64_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_66=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_65_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_67=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_66_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_68=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_67_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_69=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_68_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_70=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_69_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_71=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_70_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_72=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_71_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_73=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_72_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_74=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_73_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_75=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_74_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_76=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_75_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_77=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_76_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_78=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_77_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_79=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_78_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_80=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_79_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_81=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_80_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_82=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_81_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_83=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_82_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_84=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_83_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_85=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_84_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_86=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_85_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_87=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_86_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_88=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_87_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_89=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_88_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_90=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_89_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_91=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_90_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_92=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_91_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_93=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_92_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_94=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_93_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_95=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_94_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_96=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_95_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_97=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_96_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_98=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_97_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_99=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_98_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_100=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_99_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_101=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_100_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_102=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_101_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_103=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_102_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_104=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_103_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_105=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_104_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_106=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_105_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_107=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_106_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_108=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_107_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_109=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_108_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_110=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_109_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_111=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_110_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_112=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_111_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_113=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_112_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_114=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_113_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_115=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_114_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_116=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_115_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_117=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_116_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_118=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_117_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_119=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_118_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_120=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_119_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_121=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_120_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_122=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_121_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_123=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_122_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_124=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_123_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_125=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_124_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_126=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_125_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_127=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_126_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_128=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_127_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_129=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_128_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_130=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_129_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_131=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_130_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_132=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_131_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_133=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_132_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_134=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_133_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_135=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_134_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_136=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_135_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_137=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_136_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_138=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_137_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_139=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_138_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_140=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_139_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_141=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_140_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_142=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_141_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_143=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_142_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_144=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_143_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_145=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_144_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_146=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_145_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_147=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_146_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_148=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_147_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_149=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_148_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_150=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_149_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_151=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_150_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_152=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_151_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_153=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_152_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_154=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_153_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_155=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_154_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_156=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_155_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_157=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_156_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_158=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_157_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_159=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_158_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_160=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_159_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_161=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_160_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_162=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_161_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_163=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_162_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_164=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_163_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_165=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_164_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_166=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_165_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_167=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_166_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_168=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_167_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_169=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_168_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_170=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_169_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_171=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_170_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_172=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_171_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_173=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_172_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_174=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_173_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_175=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_174_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_176=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_175_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_177=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_176_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_178=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_177_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_179=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_178_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_180=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_179_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_181=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_180_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_182=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_181_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_183=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_182_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_184=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_183_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_185=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_184_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_186=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_185_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_187=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_186_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_188=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_187_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_189=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_188_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_190=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_189_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_191=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_190_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_192=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_191_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_193=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_192_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_194=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_193_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_195=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_194_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_196=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_195_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_197=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_196_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_198=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_197_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_199=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_198_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_200=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_199_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_201=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_200_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_202=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_201_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_203=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_202_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_204=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_203_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_205=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_204_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_206=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_205_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_207=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_206_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_208=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_207_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_209=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_208_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_210=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_209_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_211=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_210_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
AB_212=patients.with_these_medications(antibacterials_codes_brit,returning='number_of_matches_in_period',between=['patient_index_date - 1137 daysAB_211_date'],return_last_date_in_period=True,include_date_of_match= True,date_format='YYYY-MM-DD',return_expectations={'int' : {'distributio': 'normal', 'mean': 5, 'stddev': 1},'incidence':0.2}),
    )
