---
title: "table 1"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include=FALSE}
require('tidyverse')
require("gtsummary")
```


 compare study cohort before and after matching


```{r}

#df1=read.csv("/Users/yayang/Documents/GitHub/amr-uom-brit/output/case_covid_icu_death.csv")
#df2=read.csv("/Users/yayang/Documents/GitHub/amr-uom-brit/output/control_covid_hosp.csv")
df1 <- read.csv(here::here("output","case_covid_hosp.csv"))
df1$case=1
df2 <- read.csv(here::here("output","control_covid_infection.csv"))
df2$case=0

df0=rbind(df1,df2)
df0$wave=ifelse(df0$patient_index_date >= as.Date("2021-05-01"),"3", 
               ifelse(df0$patient_index_date >= as.Date("2020-09-01"),"2", 
                      ifelse(df0$patient_index_date >= as.Date("2020-02-01"),"1","0")))

df0=df0%>% select("case","wave","age","region")


df0$age_cat=ifelse(df0$age<30,"18-29",
                   ifelse(df0$age<40,"30-39",
                          ifelse(df0$age<50,"40-49",
                                 ifelse(df0$age<60,"50-59",
                                        ifelse(df0$age<70,"60-69",
                                               ifelse(df0$age<80,"70-79","80+"))))))
df0$age_cat <- factor(df0$age_cat, levels=c("18-29","30-39","40-49","50-59","60-69","70-79","80+"))


```


# unmatched
```{r}

#df0=df0%>%select("stp")

table <- 
  tbl_summary(
    df0,
    by = case, 
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{n}  ({p}%)"),
    digits = all_continuous() ~ 2,
  ) %>%
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 

table
```


# matched
## all patinets
```{r}
#df1=read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_outcome.rds")

df1 <- read_rds(here::here("output","matched_outcome.rds"))
df1=df1%>% select("case","wave","age","age_cat","region")


```

```{r}

#df0=df0%>%select("stp")

table1 <- 
  tbl_summary(
    df1,
    by = case, 
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{n}  ({p}%)"),
      digits = all_continuous() ~ 2,
  ) %>%
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 

table1
```


## randomly pick 1 control in subclass

```{r}
#df1=read_rds("/Users/yayang/Documents/GitHub/amr-uom-brit/output/matched_outcome.rds")

df1 <- read_rds(here::here("output","matched_outcome.rds"))
df1=df1%>% group_by(case,subclass)%>% sample_n(1)

df1$subclass=NULL

df1=df1%>% select("case","wave","age","age_cat","region")


```

```{r}

#df0=df0%>%select("stp")

table1 <- 
  tbl_summary(
    df1,
    by = case, 
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{n}  ({p}%)"),
      digits = all_continuous() ~ 2,
  ) %>%
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 

table1
```
