---
title: "baseline table confounders"
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float:
     collapsed: false
     smooth_scorll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include=FALSE}
library('tidyverse')
#library("plyr")
library('dplyr')
library('stringr')
library("data.table")
library("ggpubr")
library("finalfit")
```

```{r include=FALSE}
data=readRDS(here::here("output","matched_ab.rds"))

col=c("total_ab","ab_types","exposure_period","recent_ab_days", "broad_ab_prescriptions","interval_mean","interval_sd")

data$case=as.factor(data$case)
data=data %>% mutate_at(col,as.numeric)
names(data)
```

# categorised ab exposure variables
```{r }
for (k in 1:7) {

cut_value=quantile(data[,col[k]],c(0.25,0.5,0.75))
print(cut_value)
  
data[,paste0(col[k],"_group")]=ifelse(
  data[,col[k]] <= cut_value[1],1,NA)  

data[,paste0(col[k],"_group")]=ifelse(
  data[,col[k]] > cut_value[1] & data[,col[k]]<= cut_value[2],2, 
  data[,paste0(col[k],"_group")])  

data[,paste0(col[k],"_group")]=ifelse(
  data[,col[k]] > cut_value[2] & data[,col[k]]<= cut_value[3],3, 
  data[,paste0(col[k],"_group")])  

data[,paste0(col[k],"_group")]=ifelse(
  data[,col[k]] > cut_value[3],4,data[,paste0(col[k],"_group")])  

data[,paste0(col[k],"_group")]=ifelse(
 is.na( data[,col[k]]) ,0 ,data[,paste0(col[k],"_group")])  



}

data$total_ab_group=relevel(as.factor(data$total_ab_group),ref= "1")
data$ab_types_group=relevel(as.factor(data$ab_types_group),ref= "1")
data$exposure_period_group=relevel(as.factor(data$exposure_period_group),ref= "1")
data$recent_ab_days_group=relevel(as.factor(data$recent_ab_days_group),ref= "1")
data$broad_ab_prescriptions_group=relevel(as.factor(data$broad_ab_prescriptions_group),ref= "1")
data$interval_mean_group=relevel(as.factor(data$interval_mean_group),ref= "1")
data$interval_sd_group=relevel(as.factor(data$interval_sd_group),ref= "1")

prop.table(table(data$total_ab_group))
prop.table(table(data$ab_types_group))
prop.table(table(data$exposure_period_group))
prop.table(table(data$recent_ab_days_group))
prop.table(table(data$broad_ab_prescriptions_group))
prop.table(table(data$interval_mean_group))
prop.table(table(data$interval_sd_group))

df=data
```

# original
```{r}
dependent <- "case"
explanatory<- c("total_ab_group","exposure_period_group","interval_mean_group","interval_sd_group","recent_ab_days_group","ab_types_group","broad_ab_prescriptions_group")
contd<- c("total_ab", "exposure_period","recent_ab_days","interval_mean","interval_sd","ab_types","broad_ab_prescriptions")
```

```{r}
range(data$total_ab)
range(data$ab_types)
range(data$exposure_period)
range(data$recent_ab_days)
range(data$broad_ab_prescriptions)
range(data$interval_mean)
range(data$interval_sd)
```


```{r}
data%>% summary_factorlist(dependent, explanatory)
```


```{r}
data%>% summary_factorlist(dependent, contd)
```


# median (IQR)
```{r}
# median (IQR)

explanatory<- c("total_ab", "exposure_period","recent_ab_days","interval_mean","interval_sd","ab_types","broad_ab_prescriptions")
dependent <- "case"
tbl2=DF%>% summary_factorlist(dependent, explanatory, p=T, cont = "median")

round_tbl=rbind(round_tbl,tbl2)

#write.csv(tbl1,"table3_group.csv")
write.csv(round_tbl,here::here("output","table3.csv"))
```


```{r}
# median (IQR) per levels
col<- c("total_ab_group","exposure_period_group","interval_mean_group","interval_sd_group","recent_ab_days_group","ab_types_group","broad_ab_prescriptions_group")
                

i=1
L1=quantile(DF[col[i]==1,col[i]],c(0.25,0.5,0.75))
L2=quantile(DF[col[i]==2,col[i]],c(0.25,0.5,0.75))
L3=quantile(DF[col[i]==3,col[i]],c(0.25,0.5,0.75))
L4=quantile(DF[col[i]==4,col[i]],c(0.25,0.5,0.75)) 

table=data.frame(rbind(L1,L2,L3,L4))
row.names(tbl)=c(paste0(col[i],"_L1"),paste0(col[i],"_L2"),paste0(col[i],"_L3"),paste0(col[i],"_L4"))

for (i in 2:5) {
  
  L1=quantile(DF[col[i]==1,col[i]],c(0.25,0.5,0.75))
  L2=quantile(DF[col[i]==2,col[i]],c(0.25,0.5,0.75))
  L3=quantile(DF[col[i]==3,col[i]],c(0.25,0.5,0.75))
  L4=quantile(DF[col[i]==4,col[i]],c(0.25,0.5,0.75)) 

  tbl=data.frame(rbind(L1,L2,L3,L4))
  row.names(tbl)=c(paste0(col[i],"_L1"),paste0(col[i],"_L2"),paste0(col[i],"_L3"),paste0(col[i],"_L4"))
  table=rbind(table,tbl)
}

for (i in 6:7) {
  
  L1=quantile(DF[col[i]==1,col[i]],c(0.25,0.5,0.75))
  L2=quantile(DF[col[i]==2,col[i]],c(0.25,0.5,0.75))
  L3=quantile(DF[col[i]==3,col[i]],c(0.25,0.5,0.75))
  L4=c(NA,NA,NA)

  tbl=data.frame(rbind(L1,L2,L3,L4))
  row.names(tbl)=c(paste0(col[i],"_L1"),paste0(col[i],"_L2"),paste0(col[i],"_L3"),paste0(col[i],"_L4"))
  table=rbind(table,tbl)
}
```


# outliers replaced 0.9999
```{r }
data=df

N1=quantile(data$total_ab,0.9999,na.rm = T)
N2=quantile(data$ab_types,0.9999,na.rm = T)
N3=quantile(data$exposure_period,0.9999,na.rm = T)
N4=quantile(data$recent_ab_days,0.9999,na.rm = T)
N5=quantile(data$broad_ab_prescriptions,0.9999,na.rm = T)
N6=quantile(data$interval_mean,0.9999,na.rm = T)
N7=quantile(data$interval_sd,0.9999,na.rm = T)

N=c(N1,N2,N3,N4,N5,N6,N7)
N

col=c("total_ab","ab_types","exposure_period","recent_ab_days","broad_ab_prescriptions","interval_mean","interval_sd")
```


```{r}

for (i in 1:7) {# just replace total ab
  data[,col[i]]=ifelse( data[,col[i]]>=N[i],N[i], data[,col[i]])
}

range(data$total_ab)
range(data$ab_types)
range(data$exposure_period)
range(data$recent_ab_days)
range(data$broad_ab_prescriptions)
range(data$interval_mean)
range(data$interval_sd)

```

```{r}
data%>% summary_factorlist(dependent, explanatory)
```


```{r}
data%>% summary_factorlist(dependent, contd)
```



# outliers replaced 0.999
```{r }
data=df
N1=quantile(data$total_ab,0.999,na.rm = T)
N2=quantile(data$ab_types,0.999,na.rm = T)
N3=quantile(data$exposure_period,0.999,na.rm = T)
N4=quantile(data$recent_ab_days,0.999,na.rm = T)
N5=quantile(data$broad_ab_prescriptions,0.999,na.rm = T)
N6=quantile(data$interval_mean,0.999,na.rm = T)
N7=quantile(data$interval_sd,0.999,na.rm = T)

N=c(N1,N2,N3,N4,N5,N6,N7)
N

col=c("total_ab","ab_types","exposure_period","recent_ab_days","broad_ab_prescriptions","interval_mean","interval_sd")
```


```{r}
data=df

for (i in 1:7) {# just replace total ab
  data[,col[i]]=ifelse( data[,col[i]]>=N[i],N[i], data[,col[i]])
}

range(data$total_ab)
range(data$ab_types)
range(data$exposure_period)
range(data$recent_ab_days)
range(data$broad_ab_prescriptions)
range(data$interval_mean)
range(data$interval_sd)

```

```{r}
data%>% summary_factorlist(dependent, explanatory)
```


```{r}
data%>% summary_factorlist(dependent, contd)
```



# outliers replaced 0.99
```{r }
data=df
N1=quantile(data$total_ab,0.99,na.rm = T)
N2=quantile(data$ab_types,0.99,na.rm = T)
N3=quantile(data$exposure_period,0.99,na.rm = T)
N4=quantile(data$recent_ab_days,0.99,na.rm = T)
N5=quantile(data$broad_ab_prescriptions,0.99,na.rm = T)
N6=quantile(data$interval_mean,0.99,na.rm = T)
N7=quantile(data$interval_sd,0.99,na.rm = T)

N=c(N1,N2,N3,N4,N5,N6,N7)
N

col=c("total_ab","ab_types","exposure_period","recent_ab_days","broad_ab_prescriptions","interval_mean","interval_sd")
```


```{r}
data=df

for (i in 1:7) {# just replace total ab
  data[,col[i]]=ifelse( data[,col[i]]>=N[i],N[i], data[,col[i]])
}

range(data$total_ab)
range(data$ab_types)
range(data$exposure_period)
range(data$recent_ab_days)
range(data$broad_ab_prescriptions)
range(data$interval_mean)
range(data$interval_sd)

```

```{r}
data%>% summary_factorlist(dependent, explanatory)
```


```{r}
data%>% summary_factorlist(dependent, contd)
```



# outliers replaced 0.9
```{r }
data=df

N1=quantile(data$total_ab,0.9,na.rm = T)
N2=quantile(data$ab_types,0.9,na.rm = T)
N3=quantile(data$exposure_period,0.9,na.rm = T)
N4=quantile(data$recent_ab_days,0.9,na.rm = T)
N5=quantile(data$broad_ab_prescriptions,0.9,na.rm = T)
N6=quantile(data$interval_mean,0.9,na.rm = T)
N7=quantile(data$interval_sd,0.9,na.rm = T)

N=c(N1,N2,N3,N4,N5,N6,N7)
N

col=c("total_ab","ab_types","exposure_period","recent_ab_days","broad_ab_prescriptions","interval_mean","interval_sd")
```


```{r}

for (i in 1:7) {# just replace total ab
  data[,col[i]]=ifelse( data[,col[i]]>=N[i],N[i], data[,col[i]])
}

range(data$total_ab)
range(data$ab_types)
range(data$exposure_period)
range(data$recent_ab_days)
range(data$broad_ab_prescriptions)
range(data$interval_mean)
range(data$interval_sd)

```

```{r}
data%>% summary_factorlist(dependent, explanatory)
```


```{r}
data%>% summary_factorlist(dependent, contd)
```
