from cohortextractor import filter_codes_by_category, patients, combine_codelists
from codelists import *
from datetime import datetime, timedelta

def generate_ab_variables(index_date_variable):
    ab_variables  = dict(
         ## ab types:79
  Rx_Amikacin=patients.with_these_medications(codes_ab_type_Amikacin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Amoxicillin=patients.with_these_medications(codes_ab_type_Amoxicillin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Ampicillin=patients.with_these_medications(codes_ab_type_Ampicillin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Azithromycin=patients.with_these_medications(codes_ab_type_Azithromycin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Aztreonam=patients.with_these_medications(codes_ab_type_Aztreonam,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Benzylpenicillin=patients.with_these_medications(codes_ab_type_Benzylpenicillin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefaclor=patients.with_these_medications(codes_ab_type_Cefaclor,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefadroxil=patients.with_these_medications(codes_ab_type_Cefadroxil,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefalexin=patients.with_these_medications(codes_ab_type_Cefalexin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefamandole=patients.with_these_medications(codes_ab_type_Cefamandole,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefazolin=patients.with_these_medications(codes_ab_type_Cefazolin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefepime=patients.with_these_medications(codes_ab_type_Cefepime,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefixime=patients.with_these_medications(codes_ab_type_Cefixime,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefotaxime=patients.with_these_medications(codes_ab_type_Cefotaxime,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefoxitin=patients.with_these_medications(codes_ab_type_Cefoxitin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefpirome=patients.with_these_medications(codes_ab_type_Cefpirome,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefpodoxime=patients.with_these_medications(codes_ab_type_Cefpodoxime,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefprozil=patients.with_these_medications(codes_ab_type_Cefprozil,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefradine=patients.with_these_medications(codes_ab_type_Cefradine,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Ceftazidime=patients.with_these_medications(codes_ab_type_Ceftazidime,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Ceftriaxone=patients.with_these_medications(codes_ab_type_Ceftriaxone,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cefuroxime=patients.with_these_medications(codes_ab_type_Cefuroxime,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Chloramphenicol=patients.with_these_medications(codes_ab_type_Chloramphenicol,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Cilastatin=patients.with_these_medications(codes_ab_type_Cilastatin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Ciprofloxacin=patients.with_these_medications(codes_ab_type_Ciprofloxacin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Clarithromycin=patients.with_these_medications(codes_ab_type_Clarithromycin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Clindamycin=patients.with_these_medications(codes_ab_type_Clindamycin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Co_amoxiclav=patients.with_these_medications(codes_ab_type_Co_amoxiclav,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Co_fluampicil=patients.with_these_medications(codes_ab_type_Co_fluampicil,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Colistimethate=patients.with_these_medications(codes_ab_type_Colistimethate,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Dalbavancin=patients.with_these_medications(codes_ab_type_Dalbavancin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Dalfopristin=patients.with_these_medications(codes_ab_type_Dalfopristin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Daptomycin=patients.with_these_medications(codes_ab_type_Daptomycin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Demeclocycline=patients.with_these_medications(codes_ab_type_Demeclocycline,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Doripenem=patients.with_these_medications(codes_ab_type_Doripenem,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Doxycycline=patients.with_these_medications(codes_ab_type_Doxycycline,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Ertapenem=patients.with_these_medications(codes_ab_type_Ertapenem,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Erythromycin=patients.with_these_medications(codes_ab_type_Erythromycin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Fidaxomicin=patients.with_these_medications(codes_ab_type_Fidaxomicin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Flucloxacillin=patients.with_these_medications(codes_ab_type_Flucloxacillin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Fosfomycin=patients.with_these_medications(codes_ab_type_Fosfomycin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Fusidate=patients.with_these_medications(codes_ab_type_Fusidate,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Gentamicin=patients.with_these_medications(codes_ab_type_Gentamicin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Levofloxacin=patients.with_these_medications(codes_ab_type_Levofloxacin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Linezolid=patients.with_these_medications(codes_ab_type_Linezolid,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Lymecycline=patients.with_these_medications(codes_ab_type_Lymecycline,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Meropenem=patients.with_these_medications(codes_ab_type_Meropenem,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Methenamine=patients.with_these_medications(codes_ab_type_Methenamine,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Metronidazole=patients.with_these_medications(codes_ab_type_Metronidazole,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Minocycline=patients.with_these_medications(codes_ab_type_Minocycline,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Moxifloxacin=patients.with_these_medications(codes_ab_type_Moxifloxacin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Nalidixic_acid=patients.with_these_medications(codes_ab_type_Nalidixic_acid,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Neomycin=patients.with_these_medications(codes_ab_type_Neomycin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Netilmicin=patients.with_these_medications(codes_ab_type_Netilmicin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Nitazoxanid=patients.with_these_medications(codes_ab_type_Nitazoxanid,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Nitrofurantoin=patients.with_these_medications(codes_ab_type_Nitrofurantoin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Norfloxacin=patients.with_these_medications(codes_ab_type_Norfloxacin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Ofloxacin=patients.with_these_medications(codes_ab_type_Ofloxacin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Oxytetracycline=patients.with_these_medications(codes_ab_type_Oxytetracycline,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Phenoxymethylpenicillin=patients.with_these_medications(codes_ab_type_Phenoxymethylpenicillin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Piperacillin=patients.with_these_medications(codes_ab_type_Piperacillin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Pivmecillinam=patients.with_these_medications(codes_ab_type_Pivmecillinam,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Pristinamycin=patients.with_these_medications(codes_ab_type_Pristinamycin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Rifaximin=patients.with_these_medications(codes_ab_type_Rifaximin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Sulfadiazine=patients.with_these_medications(codes_ab_type_Sulfadiazine,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Sulfamethoxazole=patients.with_these_medications(codes_ab_type_Sulfamethoxazole,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Sulfapyridine=patients.with_these_medications(codes_ab_type_Sulfapyridine,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Taurolidin=patients.with_these_medications(codes_ab_type_Taurolidin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Tedizolid=patients.with_these_medications(codes_ab_type_Tedizolid,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Teicoplanin=patients.with_these_medications(codes_ab_type_Teicoplanin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Telithromycin=patients.with_these_medications(codes_ab_type_Telithromycin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Temocillin=patients.with_these_medications(codes_ab_type_Temocillin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Tetracycline=patients.with_these_medications(codes_ab_type_Tetracycline,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Ticarcillin=patients.with_these_medications(codes_ab_type_Ticarcillin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Tigecycline=patients.with_these_medications(codes_ab_type_Tigecycline,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Tinidazole=patients.with_these_medications(codes_ab_type_Tinidazole,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Tobramycin=patients.with_these_medications(codes_ab_type_Tobramycin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Trimethoprim=patients.with_these_medications(codes_ab_type_Trimethoprim,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),
    Rx_Vancomycin=patients.with_these_medications(codes_ab_type_Vancomycin,between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],returning='number_of_matches_in_period',
  return_expectations={'int': {'distribution': 'normal', 'mean': 3, 'stddev': 1},'incidence': 0.5,}),

        
    ## number of total prescriptions 
    ab_prescriptions=patients.with_these_medications(
        antibacterials_codes_brit,
        between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],
        returning="number_of_matches_in_period",
        return_expectations={
            "int": {"distribution": "normal", "mean": 3, "stddev": 1},
            "incidence": 0.5,
        },
    ),
    
    ## time period ab prescriptions 
    ab_first_date=patients.with_these_medications(
        antibacterials_codes_brit,
        between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],
        returning="date",
        find_first_match_in_period=True,  
        date_format="YYYY-MM-DD",  
        return_expectations={"date": {"earliest": "2020-03-01"}, "incidence" : 0.5},
    ),

    ab_last_date=patients.with_these_medications(
        antibacterials_codes_brit,
        between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],
        returning="date",
        find_last_match_in_period=True,  
        date_format="YYYY-MM-DD",  
        return_expectations={"date": {"earliest": "2020-03-01"}, "incidence" : 0.5},
    ),


    ## number of broad-spectrum ab prescriptions
   
    broad_ab_prescriptions=patients.with_these_medications(
        broad_spectrum_antibiotics_codes,
        between=[f'{index_date_variable}- 1137 days', f'{index_date_variable}- 42 days'],
        returning="number_of_matches_in_period",
        return_expectations={
            "int": {"distribution": "normal", "mean": 3, "stddev": 1},
            "incidence": 0.5,
        },
    ),

    ## time difference

  )
    return ab_variables